Repository OCA/stock-logistics-workflow, pull requests merged in 2018-11, with the labels that each got.

#467 [11.0][MIG] stock_picking_filter_lot
  stock_picking_filter_lot/README.rst
  stock_picking_filter_lot/__init__.py
  stock_picking_filter_lot/__manifest__.py
  stock_picking_filter_lot/models/__init__.py
  stock_picking_filter_lot/models/stock_pack_operation.py
  stock_picking_filter_lot/models/stock_production_lot.py
  stock_picking_filter_lot/readme/CONTRIBUTORS.rst
  stock_picking_filter_lot/readme/DESCRIPTION.rst
  stock_picking_filter_lot/readme/USAGE.rst
  stock_picking_filter_lot/views/stock_move_line_view.xml
  stock_picking_filter_lot/views/stock_pack_operation.xml
  stock_picking_filter_lot/views/stock_picking_view.xml
Labels: needs review

#363 [10.0][FIX]stock_ownership_availability_rules: in case of return, virtual location id does not have any company
  stock_ownership_availability_rules/__manifest__.py
  stock_ownership_availability_rules/model/quant.py
Labels: approved

#437 [11.0][MIG] stock_batch_picking: Migration to 11.0 (WIP)
  stock_batch_picking/README.rst
  stock_batch_picking/__init__.py
  stock_batch_picking/__manifest__.py
  stock_batch_picking/data/batch_picking_actions_server.xml
  stock_batch_picking/data/stock_batch_picking_sequence.xml
  stock_batch_picking/i18n/de.po
  stock_batch_picking/i18n/es.po
  stock_batch_picking/i18n/fr.po
  stock_batch_picking/i18n/it.po
  stock_batch_picking/i18n/pt_BR.po
  stock_batch_picking/i18n/sl.po
  stock_batch_picking/models/__init__.py
  stock_batch_picking/models/product_product.py
  stock_batch_picking/models/stock_batch_picking.py
  stock_batch_picking/models/stock_picking.py
  stock_batch_picking/models/stock_warehouse.py
  stock_batch_picking/readme/CONTRIBUTORS.rst
  stock_batch_picking/readme/DESCRIPTION.rst
  stock_batch_picking/report/__init__.py
  stock_batch_picking/report/batch_report.py
  stock_batch_picking/security/ir.model.access.csv
  stock_batch_picking/static/batch_form.png
  stock_batch_picking/static/batch_form_operation.png
  stock_batch_picking/static/batch_wizard.png
  stock_batch_picking/static/description/index.html
  stock_batch_picking/static/stock_picking_list.png
  stock_batch_picking/tests/__init__.py
  stock_batch_picking/tests/test_batch.py
  stock_batch_picking/views/product_product.xml
  stock_batch_picking/views/report_batch_picking.xml
  stock_batch_picking/views/stock_batch_picking.xml
  stock_batch_picking/views/stock_picking.xml
  stock_batch_picking/views/stock_warehouse.xml
  stock_batch_picking/wizard/__init__.py
  stock_batch_picking/wizard/batch_picking_creator.py
  stock_batch_picking/wizard/batch_picking_creator_view.xml
Labels: approved, needs review

#472 [FIX] stock_picking_package_preparation_line: Do not delete lines when the picking is not removed
  stock_picking_package_preparation_line/__manifest__.py
  stock_picking_package_preparation_line/models/stock_picking_package_preparation.py
  stock_picking_package_preparation_line/tests/test_package_preparation_line.py
Labels: approved

#478 [11.0][FIX] stock_picking_package_preparation_line: Do not delete lines when the picking is not removed
  stock_picking_package_preparation_line/__manifest__.py
  stock_picking_package_preparation_line/models/stock_picking_package_preparation.py
  stock_picking_package_preparation_line/tests/test_package_preparation_line.py
Labels: approved, enhancement, needs review

#479 [FIX] stock_picking_invoice_link: typo in readme
  stock_picking_invoice_link/README.rst
  stock_picking_invoice_link/__manifest__.py
  stock_picking_invoice_link/readme/CONTRIBUTORS.rst
  stock_picking_invoice_link/readme/DESCRIPTION.rst
  stock_picking_invoice_link/readme/USAGE.rst
  stock_picking_invoice_link/static/description/index.html
Labels: approved, enhancement, needs review
