Repository OCA/stock-logistics-workflow, pull requests merged in 2019-02, with the labels that each got.

#477 [MIG]Migrate stock_picking_show_return from v11 to v12
  stock_picking_show_return/README.rst
  stock_picking_show_return/__init__.py
  stock_picking_show_return/__manifest__.py
  stock_picking_show_return/i18n/de.po
  stock_picking_show_return/i18n/es.po
  stock_picking_show_return/i18n/fr.po
  stock_picking_show_return/i18n/it.po
  stock_picking_show_return/i18n/nl_NL.po
  stock_picking_show_return/i18n/pt.po
  stock_picking_show_return/i18n/pt_BR.po
  stock_picking_show_return/i18n/sl.po
  stock_picking_show_return/i18n/stock_picking_show_return.pot
  stock_picking_show_return/models/__init__.py
  stock_picking_show_return/models/stock_picking.py
  stock_picking_show_return/readme/CONTRIBUTORS.rst
  stock_picking_show_return/readme/DESCRIPTION.rst
  stock_picking_show_return/readme/USAGE.rst
  stock_picking_show_return/static/description/index.html
  stock_picking_show_return/tests/__init__.py
  stock_picking_show_return/tests/test_stock_picking_show_return.py
  stock_picking_show_return/views/stock_picking_view.xml
Labels: approved, needs review

#476 [MIG]Migrate stock_picking_customer_ref
  stock_picking_customer_ref/README.rst
  stock_picking_customer_ref/__init__.py
  stock_picking_customer_ref/__manifest__.py
  stock_picking_customer_ref/i18n/de.po
  stock_picking_customer_ref/i18n/es.po
  stock_picking_customer_ref/i18n/fr.po
  stock_picking_customer_ref/i18n/hr.po
  stock_picking_customer_ref/i18n/it.po
  stock_picking_customer_ref/i18n/nl.po
  stock_picking_customer_ref/i18n/pt.po
  stock_picking_customer_ref/i18n/pt_BR.po
  stock_picking_customer_ref/i18n/sl_SI.po
  stock_picking_customer_ref/i18n/stock_picking_customer_ref.pot
  stock_picking_customer_ref/models/__init__.py
  stock_picking_customer_ref/models/stock_picking.py
  stock_picking_customer_ref/readme/CONTRIBUTORS.rst
  stock_picking_customer_ref/readme/CREDITS.rst
  stock_picking_customer_ref/readme/DESCRIPTION.rst
  stock_picking_customer_ref/readme/USAGE.rst
  stock_picking_customer_ref/static/description/index.html
  stock_picking_customer_ref/tests/__init__.py
  stock_picking_customer_ref/tests/test_stock_picking_customer_ref.py
  stock_picking_customer_ref/views/stock_picking_view.xml
Labels: approved, needs review, ready to merge

#497 [11.0][FIX] stock_picking_backorder_strategy - Issue #495
  stock_picking_backorder_strategy/__manifest__.py
  stock_picking_backorder_strategy/models/stock_picking.py
Labels: bug

#496 [10.0][FIX] stock_picking_backorder_strategy: Return value
  stock_picking_backorder_strategy/__manifest__.py
  stock_picking_backorder_strategy/models/stock_picking.py
Labels: enhancement

#489 [12.0] mig stock_picking_package_preparation_line
  stock_picking_package_preparation_line/README.rst
  stock_picking_package_preparation_line/__init__.py
  stock_picking_package_preparation_line/__manifest__.py
  stock_picking_package_preparation_line/i18n/ca.po
  stock_picking_package_preparation_line/i18n/de.po
  stock_picking_package_preparation_line/i18n/en.po
  stock_picking_package_preparation_line/i18n/es.po
  stock_picking_package_preparation_line/i18n/es_MX.po
  stock_picking_package_preparation_line/i18n/fi.po
  stock_picking_package_preparation_line/i18n/fr.po
  stock_picking_package_preparation_line/i18n/hr.po
  stock_picking_package_preparation_line/i18n/it.po
  stock_picking_package_preparation_line/i18n/nl_NL.po
  stock_picking_package_preparation_line/i18n/pt.po
  stock_picking_package_preparation_line/i18n/pt_BR.po
  stock_picking_package_preparation_line/i18n/sl.po
  stock_picking_package_preparation_line/i18n/stock_picking_package_preparation_line.pot
  stock_picking_package_preparation_line/i18n/tr.po
  stock_picking_package_preparation_line/i18n/tr_TR.po
  stock_picking_package_preparation_line/models/__init__.py
  stock_picking_package_preparation_line/models/ir_config.py
  stock_picking_package_preparation_line/models/res_company.py
  stock_picking_package_preparation_line/models/stock_move.py
  stock_picking_package_preparation_line/models/stock_picking_package_preparation.py
  stock_picking_package_preparation_line/models/stock_picking_package_preparation_line.py
  stock_picking_package_preparation_line/readme/CONTRIBUTORS.rst
  stock_picking_package_preparation_line/readme/DESCRIPTION.rst
  stock_picking_package_preparation_line/security/ir.model.access.csv
  stock_picking_package_preparation_line/security/package_preparation_line_security.xml
  stock_picking_package_preparation_line/static/description/index.html
  stock_picking_package_preparation_line/tests/__init__.py
  stock_picking_package_preparation_line/tests/test_package_preparation_line.py
  stock_picking_package_preparation_line/views/ir_config_view.xml
  stock_picking_package_preparation_line/views/stock_picking_package_preparation_line.xml
Labels: approved, needs review, ready to merge

#411 [8.0][FIX] not show an error if picking is already assigned, it is a …
  stock_picking_package_preparation/__openerp__.py
  stock_picking_package_preparation/model/stock_picking_package_preparation.py
  stock_picking_package_preparation_line/__openerp__.py
  stock_picking_package_preparation_line/models/stock_picking_package_preparation_line.py
Labels: approved, needs review, ready to merge

#501 [12.0] FIX stock_picking_package_preparation_line: crash opening inventory settings
  stock_picking_package_preparation_line/__manifest__.py
  stock_picking_package_preparation_line/models/ir_config.py
  stock_picking_package_preparation_line/views/ir_config_view.xml
Labels: approved, enhancement, ready to merge

#470 [12.0][MIG] stock_picking_sale_order_link: Migration to 12.0
  stock_picking_sale_order_link/README.rst
  stock_picking_sale_order_link/__init__.py
  stock_picking_sale_order_link/__manifest__.py
  stock_picking_sale_order_link/i18n/de.po
  stock_picking_sale_order_link/i18n/es.po
  stock_picking_sale_order_link/i18n/fr.po
  stock_picking_sale_order_link/i18n/it.po
  stock_picking_sale_order_link/i18n/pt_BR.po
  stock_picking_sale_order_link/i18n/stock_picking_sale_order_link.pot
  stock_picking_sale_order_link/models/__init__.py
  stock_picking_sale_order_link/models/stock_picking.py
  stock_picking_sale_order_link/readme/CONTRIBUTORS.rst
  stock_picking_sale_order_link/readme/DESCRIPTION.rst
  stock_picking_sale_order_link/readme/USAGE.rst
  stock_picking_sale_order_link/static/description/icon.png
  stock_picking_sale_order_link/static/description/index.html
  stock_picking_sale_order_link/tests/__init__.py
  stock_picking_sale_order_link/tests/test_stock_picking_sale_order_link.py
  stock_picking_sale_order_link/views/stock_picking_view.xml
Labels: approved, needs review, ready to merge

#505 [11.0][FIX] stock_picking_auto_create_lot: Not create lot if lot_name is stored in move_line
  stock_picking_auto_create_lot/models/stock_picking.py
Labels: approved

#508 [12.0][MIG] Migration of stock_no_negative
  stock_no_negative/README.rst
  stock_no_negative/__init__.py
  stock_no_negative/__manifest__.py
  stock_no_negative/i18n/ar.po
  stock_no_negative/i18n/es.po
  stock_no_negative/i18n/fr.po
  stock_no_negative/i18n/stock_no_negative.pot
  stock_no_negative/models/__init__.py
  stock_no_negative/models/product.py
  stock_no_negative/models/stock_location.py
  stock_no_negative/models/stock_quant.py
  stock_no_negative/readme/CONFIGURE.rst
  stock_no_negative/readme/CONTRIBUTORS.rst
  stock_no_negative/readme/DESCRIPTION.rst
  stock_no_negative/readme/HISTORY.rst
  stock_no_negative/readme/USAGE.rst
  stock_no_negative/static/description/index.html
  stock_no_negative/tests/__init__.py
  stock_no_negative/tests/test_stock_no_negative.py
  stock_no_negative/views/product_product_views.xml
  stock_no_negative/views/stock_location_views.xml
Labels: approved
