Repository OCA/stock-logistics-workflow, pull requests merged in 2019-04, with the labels that each got.

#513 [12.0][MIG] stock_picking_invoice_link
  stock_picking_invoice_link/README.rst
  stock_picking_invoice_link/__init__.py
  stock_picking_invoice_link/__manifest__.py
  stock_picking_invoice_link/i18n/ca.po
  stock_picking_invoice_link/i18n/de.po
  stock_picking_invoice_link/i18n/es.po
  stock_picking_invoice_link/i18n/es_MX.po
  stock_picking_invoice_link/i18n/fi.po
  stock_picking_invoice_link/i18n/fr.po
  stock_picking_invoice_link/i18n/hr.po
  stock_picking_invoice_link/i18n/it.po
  stock_picking_invoice_link/i18n/nl_NL.po
  stock_picking_invoice_link/i18n/pt.po
  stock_picking_invoice_link/i18n/pt_BR.po
  stock_picking_invoice_link/i18n/sl.po
  stock_picking_invoice_link/i18n/stock_picking_invoice_link.pot
  stock_picking_invoice_link/i18n/tr.po
  stock_picking_invoice_link/i18n/tr_TR.po
  stock_picking_invoice_link/models/__init__.py
  stock_picking_invoice_link/models/account_invoice.py
  stock_picking_invoice_link/models/sale_order.py
  stock_picking_invoice_link/models/stock_move.py
  stock_picking_invoice_link/models/stock_picking.py
  stock_picking_invoice_link/readme/CONTRIBUTORS.rst
  stock_picking_invoice_link/readme/DESCRIPTION.rst
  stock_picking_invoice_link/readme/USAGE.rst
  stock_picking_invoice_link/static/description/icon.png
  stock_picking_invoice_link/static/description/index.html
  stock_picking_invoice_link/tests/__init__.py
  stock_picking_invoice_link/tests/test_stock_picking_invoice_link.py
  stock_picking_invoice_link/views/account_invoice_view.xml
  stock_picking_invoice_link/views/stock_view.xml
Labels: approved

#515 [12.0][MIG] stock_picking_restrict_cancel_with_orig_move
  stock_picking_restrict_cancel_with_orig_move/README.rst
  stock_picking_restrict_cancel_with_orig_move/__init__.py
  stock_picking_restrict_cancel_with_orig_move/__manifest__.py
  stock_picking_restrict_cancel_with_orig_move/i18n/stock_picking_restrict_cancel_with_orig_move.pot
  stock_picking_restrict_cancel_with_orig_move/models/__init__.py
  stock_picking_restrict_cancel_with_orig_move/models/stock_move.py
  stock_picking_restrict_cancel_with_orig_move/readme/CONTRIBUTORS.rst
  stock_picking_restrict_cancel_with_orig_move/readme/DESCRIPTION.rst
  stock_picking_restrict_cancel_with_orig_move/readme/USAGE.rst
  stock_picking_restrict_cancel_with_orig_move/static/description/icon.png
  stock_picking_restrict_cancel_with_orig_move/static/description/index.html
  stock_picking_restrict_cancel_with_orig_move/tests/__init__.py
  stock_picking_restrict_cancel_with_orig_move/tests/test_restrict_cancel.py
Labels: approved

#521 [10.0][FIX] stock_picking_line_sequence
  stock_picking_line_sequence/__manifest__.py
  stock_picking_line_sequence/models/__init__.py
  stock_picking_line_sequence/models/procurement.py
  stock_picking_line_sequence/models/stock.py
Labels: approved, enhancement

#492 [8.0][MIG] stock_picking_send_by_mail: Backport from 9.0
  stock_picking_send_by_mail/README.rst
  stock_picking_send_by_mail/__init__.py
  stock_picking_send_by_mail/__openerp__.py
  stock_picking_send_by_mail/data/stock_picking_mail.xml
  stock_picking_send_by_mail/i18n/de.po
  stock_picking_send_by_mail/i18n/es.po
  stock_picking_send_by_mail/i18n/fr.po
  stock_picking_send_by_mail/i18n/it.po
  stock_picking_send_by_mail/i18n/pt_BR.po
  stock_picking_send_by_mail/i18n/stock_picking_send_by_mail.pot
  stock_picking_send_by_mail/models/__init__.py
  stock_picking_send_by_mail/models/stock_picking.py
  stock_picking_send_by_mail/static/description/icon.png
  stock_picking_send_by_mail/tests/__init__.py
  stock_picking_send_by_mail/tests/test_stock_picking_send_by_mail.py
  stock_picking_send_by_mail/views/stock_picking_view.xml
Labels: needs review

#494 [10.0][ADD] stock_exclude_to_remove_lot
  setup/stock_exclude_to_remove_lot/odoo/__init__.py
  setup/stock_exclude_to_remove_lot/odoo/addons/__init__.py
  setup/stock_exclude_to_remove_lot/odoo/addons/stock_exclude_to_remove_lot
  setup/stock_exclude_to_remove_lot/setup.py
  stock_exclude_to_remove_lot/README.rst
  stock_exclude_to_remove_lot/__init__.py
  stock_exclude_to_remove_lot/__manifest__.py
  stock_exclude_to_remove_lot/models/__init__.py
  stock_exclude_to_remove_lot/models/stock_picking_type.py
  stock_exclude_to_remove_lot/models/stock_production_lot.py
  stock_exclude_to_remove_lot/readme/CONTRIBUTORS.rst
  stock_exclude_to_remove_lot/readme/DESCRIPTION.rst
  stock_exclude_to_remove_lot/readme/USAGE.rst
  stock_exclude_to_remove_lot/static/description/icon.png
  stock_exclude_to_remove_lot/static/description/index.html
  stock_exclude_to_remove_lot/tests/__init__.py
  stock_exclude_to_remove_lot/tests/test_remove_lots.py
  stock_exclude_to_remove_lot/views/stock_picking_type.xml
Labels: approved, needs review, ready to merge
