Repository OCA/stock-logistics-workflow, pull requests merged in 2019-07, with the labels that each got.

#549 [FIX] product_espiry_simple: Not use unlink records on action_done
  product_expiry_simple/models/stock_move_line.py
Labels: approved, enhancement, needs review

#552 [11.0][ADD] stock_picking_purchase_order_link
  stock_picking_purchase_order_link/README.rst
  stock_picking_purchase_order_link/__init__.py
  stock_picking_purchase_order_link/__manifest__.py
  stock_picking_purchase_order_link/models/__init__.py
  stock_picking_purchase_order_link/models/stock_picking.py
  stock_picking_purchase_order_link/readme/CONTRIBUTORS.rst
  stock_picking_purchase_order_link/readme/DESCRIPTION.rst
  stock_picking_purchase_order_link/readme/USAGE.rst
  stock_picking_purchase_order_link/static/description/icon.png
  stock_picking_purchase_order_link/static/description/index.html
  stock_picking_purchase_order_link/tests/__init__.py
  stock_picking_purchase_order_link/tests/test_stock_picking_purchase_order_link.py
  stock_picking_purchase_order_link/views/stock_picking_view.xml
Labels: approved

#553 [11.0][ADD] expiry date in view_production_lot_form_simple
  product_expiry_simple/views/stock.xml
Labels: approved, enhancement
