Repository OCA/stock-logistics-workflow, pull requests merged in 2019-01, with the labels that each got.

#462 [10.0][ADD] stock_change_price_at_date
  setup/stock_change_price_at_date/odoo/__init__.py
  setup/stock_change_price_at_date/odoo/addons/__init__.py
  setup/stock_change_price_at_date/odoo/addons/stock_change_price_at_date
  setup/stock_change_price_at_date/setup.py
  stock_change_price_at_date/README.rst
  stock_change_price_at_date/__init__.py
  stock_change_price_at_date/__manifest__.py
  stock_change_price_at_date/models/__init__.py
  stock_change_price_at_date/models/account_move.py
  stock_change_price_at_date/models/product_product.py
  stock_change_price_at_date/readme/CONTRIBUTORS.rst
  stock_change_price_at_date/readme/DESCRIPTION.rst
  stock_change_price_at_date/readme/USAGE.rst
  stock_change_price_at_date/static/description/icon.png
  stock_change_price_at_date/static/description/index.html
  stock_change_price_at_date/tests/__init__.py
  stock_change_price_at_date/tests/test_change_price_at_date.py
  stock_change_price_at_date/wizards/__init__.py
  stock_change_price_at_date/wizards/stock_change_standard_price.py
  stock_change_price_at_date/wizards/stock_change_standard_price.xml
Labels: approved, needs review

#487 [stock_picking_deactivate_immediate_transfer] missing act.window
  stock_picking_deactivate_immediate_transfer/views/stock_picking_views.xml
Labels: approved, enhancement, needs review

#493 [11.0][stock_no_negative] fix in incorrect view
  stock_no_negative/__manifest__.py
  stock_no_negative/views/stock_location_views.xml
Labels: approved
