Repository OCA/stock-logistics-workflow, pull requests merged in 2019-05, with the labels that each got.

#519 [12.0][MIG] stock_move_quick_lot
  stock_move_quick_lot/README.rst
  stock_move_quick_lot/__init__.py
  stock_move_quick_lot/__manifest__.py
  stock_move_quick_lot/i18n/es.po
  stock_move_quick_lot/i18n/stock_move_quick_lot.pot
  stock_move_quick_lot/i18n/stock_pack_operation_quick_lot.pot
  stock_move_quick_lot/models/__init__.py
  stock_move_quick_lot/models/stock_move.py
  stock_move_quick_lot/readme/CONFIGURE.rst
  stock_move_quick_lot/readme/CONTRIBUTORS.rst
  stock_move_quick_lot/readme/DESCRIPTION.rst
  stock_move_quick_lot/readme/USAGE.rst
  stock_move_quick_lot/static/description/icon.png
  stock_move_quick_lot/static/description/icon.svg
  stock_move_quick_lot/static/description/index.html
  stock_move_quick_lot/tests/__init__.py
  stock_move_quick_lot/tests/test_stock_move_quick_lot.py
  stock_move_quick_lot/views/stock_view.xml
Labels: approved, ready to merge

#277 [10.0] Add module stock_cost_method_last
  stock_cost_method_last/README.rst
  stock_cost_method_last/__init__.py
  stock_cost_method_last/__manifest__.py
  stock_cost_method_last/models/__init__.py
  stock_cost_method_last/models/product.py
  stock_cost_method_last/models/stock_move.py
  stock_cost_method_last/views/product.xml
Labels: approved, needs review

#516 [12.0][MIG] purchase_stock_picking_restrict_cancel
  purchase_stock_picking_restrict_cancel/README.rst
  purchase_stock_picking_restrict_cancel/__init__.py
  purchase_stock_picking_restrict_cancel/__manifest__.py
  purchase_stock_picking_restrict_cancel/i18n/purchase_stock_picking_restrict_cancel.pot
  purchase_stock_picking_restrict_cancel/models/__init__.py
  purchase_stock_picking_restrict_cancel/models/stock_move.py
  purchase_stock_picking_restrict_cancel/readme/CONTRIBUTORS.rst
  purchase_stock_picking_restrict_cancel/readme/DESCRIPTION.rst
  purchase_stock_picking_restrict_cancel/static/description/icon.png
  purchase_stock_picking_restrict_cancel/static/description/index.html
  purchase_stock_picking_restrict_cancel/tests/__init__.py
  purchase_stock_picking_restrict_cancel/tests/test_purchase_picking_restrict_cancel.py
Labels: approved, needs review, ready to merge

#526 [12.0][MIG] stock_picking_send_by_email
  stock_picking_send_by_mail/README.rst
  stock_picking_send_by_mail/__init__.py
  stock_picking_send_by_mail/__manifest__.py
  stock_picking_send_by_mail/data/stock_picking_mail.xml
  stock_picking_send_by_mail/i18n/de.po
  stock_picking_send_by_mail/i18n/es.po
  stock_picking_send_by_mail/i18n/fr.po
  stock_picking_send_by_mail/i18n/it.po
  stock_picking_send_by_mail/i18n/pt_BR.po
  stock_picking_send_by_mail/i18n/stock_picking_send_by_mail.pot
  stock_picking_send_by_mail/models/__init__.py
  stock_picking_send_by_mail/models/stock_picking.py
  stock_picking_send_by_mail/readme/CONTRIBUTORS.rst
  stock_picking_send_by_mail/readme/DESCRIPTION.rst
  stock_picking_send_by_mail/readme/USAGE.rst
  stock_picking_send_by_mail/static/description/icon.png
  stock_picking_send_by_mail/static/description/index.html
  stock_picking_send_by_mail/tests/__init__.py
  stock_picking_send_by_mail/tests/test_stock_picking_send_by_mail.py
  stock_picking_send_by_mail/views/stock_picking_view.xml
Labels: approved, needs review, ready to merge

#511 [12.0][ADD] New module stock_landed_costs_currency
  stock_landed_costs_currency/README.rst
  stock_landed_costs_currency/__init__.py
  stock_landed_costs_currency/__manifest__.py
  stock_landed_costs_currency/models/__init__.py
  stock_landed_costs_currency/models/stock_landed_cost.py
  stock_landed_costs_currency/models/stock_landed_cost_lines.py
  stock_landed_costs_currency/readme/CONFIGURE.rst
  stock_landed_costs_currency/readme/CONTRIBUTORS.rst
  stock_landed_costs_currency/readme/DESCRIPTION.rst
  stock_landed_costs_currency/readme/USAGE.rst
  stock_landed_costs_currency/tests/__init__.py
  stock_landed_costs_currency/tests/test_stock_landed_costs_currency.py
  stock_landed_costs_currency/views/stock_landed_cost_views.xml
Labels: approved, needs review, ready to merge

#356 [9.0][ADD] delivery_weight_uom_not_required
  delivery_weight_uom_not_required/README.rst
  delivery_weight_uom_not_required/__init__.py
  delivery_weight_uom_not_required/__openerp__.py
  delivery_weight_uom_not_required/models/__init__.py
  delivery_weight_uom_not_required/models/stock_move.py
  delivery_weight_uom_not_required/models/stock_picking.py
  delivery_weight_uom_not_required/static/description/icon.png
Labels: approved, question, ready to merge

#527 [IMP] stock_picking_mass_action: Fix and improve transfer method
  stock_picking_mass_action/README.rst
  stock_picking_mass_action/__manifest__.py
  stock_picking_mass_action/models/stock_picking.py
  stock_picking_mass_action/readme/CONTRIBUTORS.rst
  stock_picking_mass_action/tests/test_mass_action.py
  stock_picking_mass_action/wizard/mass_action.py
Labels: approved, bug, enhancement, ready to merge

#379 [8.0][FIX] stock_split_picking: do not write date_done when splitting closes
  stock_split_picking/__openerp__.py
  stock_split_picking/model/stock.py
  stock_split_picking/test/test_assigned_picking_split.yml
  stock_split_picking/test/test_picking_split.yml
  stock_split_picking/test/test_picking_split_two_move_lines.yml
Labels: needs review

#510 [ADD] module stock_picking_quick
  oca_dependencies.txt
  stock_picking_quick/README.rst
  stock_picking_quick/__init__.py
  stock_picking_quick/__manifest__.py
  stock_picking_quick/models/__init__.py
  stock_picking_quick/models/product_product.py
  stock_picking_quick/models/stock_picking.py
  stock_picking_quick/readme/CONTRIBUTORS.rst
  stock_picking_quick/readme/DESCRIPTION.rst
  stock_picking_quick/readme/USAGE.rst
  stock_picking_quick/static/description/filter.png
  stock_picking_quick/static/description/index.html
  stock_picking_quick/static/description/po-product.png
  stock_picking_quick/static/description/po.png
  stock_picking_quick/tests/__init__.py
  stock_picking_quick/tests/test_stock_picking_quick.py
  stock_picking_quick/views/picking_view.xml
  stock_picking_quick/views/product_view.xml
Labels: approved, needs review

#490 [10.0][FIX] stock_ownership_availability_rules: Wrong owner in multi …
  stock_ownership_availability_rules/__manifest__.py
  stock_ownership_availability_rules/model/quant.py
  stock_ownership_availability_rules/tests/__init__.py
  stock_ownership_availability_rules/tests/test_multicompany.py
Labels: approved, enhancement, needs review

#523 [IMP] stock_split_picking: rewrite
  stock_split_picking/README.rst
  stock_split_picking/__init__.py
  stock_split_picking/__manifest__.py
  stock_split_picking/models/__init__.py
  stock_split_picking/models/stock_picking.py
  stock_split_picking/tests/test_stock_split_picking.py
  stock_split_picking/views/stock_partial_picking.xml
  stock_split_picking/wizards/__init__.py
  stock_split_picking/wizards/stock_picking_split.py
  stock_split_picking/wizards/stock_picking_split.xml
Labels: approved, enhancement, ready to merge

#474 [12.0] [MIG] stock_picking_line_sequence
  stock_picking_line_sequence/README.rst
  stock_picking_line_sequence/__init__.py
  stock_picking_line_sequence/__manifest__.py
  stock_picking_line_sequence/i18n/ca.po
  stock_picking_line_sequence/i18n/de.po
  stock_picking_line_sequence/i18n/es.po
  stock_picking_line_sequence/i18n/es_MX.po
  stock_picking_line_sequence/i18n/fi.po
  stock_picking_line_sequence/i18n/fr.po
  stock_picking_line_sequence/i18n/hr.po
  stock_picking_line_sequence/i18n/it.po
  stock_picking_line_sequence/i18n/nl_NL.po
  stock_picking_line_sequence/i18n/pt.po
  stock_picking_line_sequence/i18n/pt_BR.po
  stock_picking_line_sequence/i18n/sl.po
  stock_picking_line_sequence/i18n/stock_picking_line_sequence.pot
  stock_picking_line_sequence/i18n/tr.po
  stock_picking_line_sequence/i18n/tr_TR.po
  stock_picking_line_sequence/init_hooks.py
  stock_picking_line_sequence/models/__init__.py
  stock_picking_line_sequence/models/stock.py
  stock_picking_line_sequence/readme/CONTRIBUTORS.rst
  stock_picking_line_sequence/readme/DESCRIPTION.rst
  stock_picking_line_sequence/readme/USAGE.rst
  stock_picking_line_sequence/static/description/index.html
  stock_picking_line_sequence/tests/__init__.py
  stock_picking_line_sequence/tests/test_move_lines_sequence.py
  stock_picking_line_sequence/views/stock_view.xml
Labels: approved, needs review, ready to merge

#509 [10.0] product_expiry_simple: Replace stored display_name by name_get()
  product_expiry_simple/__manifest__.py
  product_expiry_simple/models/stock_production_lot.py
Labels: approved, ready to merge
