Repository OCA/stock-logistics-workflow, pull requests merged in 2020-08, with the labels that each got.

#690 [FIX] stock_putaway_by_route: AttributeError: 'stock.move.line' object has no attribute 'rule_id'
  stock_putaway_by_route/models/stock_move_line.py
Labels: approved, bot is merging ⏳

#681 [11.0][FIX] stock_batch_picking: statusbar_visible attribute has an undefined state
  stock_batch_picking/readme/CONTRIBUTORS.rst
  stock_batch_picking/views/stock_batch_picking.xml
Labels: bot is merging ⏳

#686 [13.0][IMP] stock_picking_group_by_partner_by_carrier
  stock_picking_group_by_partner_by_carrier/models/sale_order.py
  stock_picking_group_by_partner_by_carrier/models/stock_picking.py
Labels: approved, bot is merging ⏳, ready to merge

#694 [12.0][IMP] .travis.yml: Update to latest template
  .travis.yml
Labels: bot is merging ⏳, enhancement

#662 [12.0][FIX] stock_request: CI random fails
  stock_return_request/tests/test_stock_return_request_common.py
Labels: approved, bot is merging ⏳, ready to merge

#697 [12.0][IMP] README.md: Show Weblate status
  README.md
Labels: approved, bot is merging ⏳

#695 [13.0] stock_picking_group_by_partner_by_carrier: Display carrier on PG
  stock_picking_group_by_partner_by_carrier/__manifest__.py
  stock_picking_group_by_partner_by_carrier/views/procurement_group.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#693 [13.0] Create module sale_stock_mto_as_mts_orderpoint - alpha
  oca_dependencies.txt
  sale_stock_mto_as_mts_orderpoint/__init__.py
  sale_stock_mto_as_mts_orderpoint/__manifest__.py
  sale_stock_mto_as_mts_orderpoint/models/__init__.py
  sale_stock_mto_as_mts_orderpoint/models/product.py
  sale_stock_mto_as_mts_orderpoint/models/sale_order.py
  sale_stock_mto_as_mts_orderpoint/models/stock_move.py
  sale_stock_mto_as_mts_orderpoint/models/stock_warehouse.py
  sale_stock_mto_as_mts_orderpoint/readme/CONFIGURATION.rst
  sale_stock_mto_as_mts_orderpoint/readme/CONTRIBUTORS.rst
  sale_stock_mto_as_mts_orderpoint/readme/DESCRIPTION.rst
  sale_stock_mto_as_mts_orderpoint/readme/ROADMAP.rst
  sale_stock_mto_as_mts_orderpoint/tests/__init__.py
  sale_stock_mto_as_mts_orderpoint/tests/test_sale_stock_mto_as_mts_orderpoint.py
  setup/sale_stock_mto_as_mts_orderpoint/odoo/addons/sale_stock_mto_as_mts_orderpoint
  setup/sale_stock_mto_as_mts_orderpoint/setup.py
Labels: approved, bot is merging ⏳

#692 [13.0] Add match by product's route in putaway by routes
  stock_putaway_by_route/models/stock_move.py
  stock_putaway_by_route/models/stock_move_line.py
  stock_putaway_by_route/readme/DESCRIPTION.rst
  stock_putaway_by_route/tests/test_route_putaway.py
  stock_putaway_hook/models/stock_location.py
  stock_putaway_hook/readme/USAGE.rst
Labels: approved, bot is merging ⏳

#688 [13.0][MIG] stock_picking_restrict_cancel_with_orig_move
  stock_picking_restrict_cancel_with_orig_move/README.rst
  stock_picking_restrict_cancel_with_orig_move/__init__.py
  stock_picking_restrict_cancel_with_orig_move/__manifest__.py
  stock_picking_restrict_cancel_with_orig_move/i18n/stock_picking_restrict_cancel_with_orig_move.pot
  stock_picking_restrict_cancel_with_orig_move/models/__init__.py
  stock_picking_restrict_cancel_with_orig_move/models/stock_move.py
  stock_picking_restrict_cancel_with_orig_move/readme/CONTRIBUTORS.rst
  stock_picking_restrict_cancel_with_orig_move/readme/DESCRIPTION.rst
  stock_picking_restrict_cancel_with_orig_move/readme/USAGE.rst
  stock_picking_restrict_cancel_with_orig_move/static/description/icon.png
  stock_picking_restrict_cancel_with_orig_move/static/description/index.html
  stock_picking_restrict_cancel_with_orig_move/tests/__init__.py
  stock_picking_restrict_cancel_with_orig_move/tests/test_restrict_cancel.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#689 [13.0] Create module delivery_package_default_shipping_weight
  delivery_package_default_shipping_weight/__init__.py
  delivery_package_default_shipping_weight/__manifest__.py
  delivery_package_default_shipping_weight/models/__init__.py
  delivery_package_default_shipping_weight/models/product_packaging.py
  delivery_package_default_shipping_weight/models/stock_quant_package.py
  delivery_package_default_shipping_weight/readme/CONTRIBUTORS.rst
  delivery_package_default_shipping_weight/readme/DESCRIPTION.rst
  delivery_package_default_shipping_weight/tests/__init__.py
  delivery_package_default_shipping_weight/tests/test_delivery_package_default_shipping_weight.py
  delivery_package_default_shipping_weight/views/product_packaging.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge
