Repository OCA/stock-logistics-workflow, pull requests merged in 2020-04, with the labels that each got.

#644 [IMP] product_cost_price_avco_sync: Fix test. Aleatory error
  product_cost_price_avco_sync/tests/test_product_cost_price_avco_sync.py
Labels: bot is merging ⏳

#635 [13.0][ADD] stock_picking_return_restricted_qty:New module
  stock_picking_return_restricted_qty/README.rst
  stock_picking_return_restricted_qty/__init__.py
  stock_picking_return_restricted_qty/__manifest__.py
  stock_picking_return_restricted_qty/i18n/es.po
  stock_picking_return_restricted_qty/i18n/stock_picking_return_restricted_qty.pot
  stock_picking_return_restricted_qty/readme/CONTRIBUTORS.rst
  stock_picking_return_restricted_qty/readme/DESCRIPTION.rst
  stock_picking_return_restricted_qty/readme/USAGE.rst
  stock_picking_return_restricted_qty/static/description/index.html
  stock_picking_return_restricted_qty/tests/__init__.py
  stock_picking_return_restricted_qty/tests/test_stock_picking_return_restricted_qty.py
  stock_picking_return_restricted_qty/wizard/__init__.py
  stock_picking_return_restricted_qty/wizard/stock_picking_return.py
Labels: bot is merging ⏳

#636 [12.0][ADD] stock_picking_return_restricted_qty: Don't allows you to return more quantity than delivered
  stock_picking_return_restricted_qty/README.rst
  stock_picking_return_restricted_qty/__init__.py
  stock_picking_return_restricted_qty/__manifest__.py
  stock_picking_return_restricted_qty/i18n/es.po
  stock_picking_return_restricted_qty/i18n/stock_picking_return_restricted_qty.pot
  stock_picking_return_restricted_qty/readme/CONTRIBUTORS.rst
  stock_picking_return_restricted_qty/readme/DESCRIPTION.rst
  stock_picking_return_restricted_qty/readme/USAGE.rst
  stock_picking_return_restricted_qty/static/description/index.html
  stock_picking_return_restricted_qty/tests/__init__.py
  stock_picking_return_restricted_qty/tests/test_stock_picking_return_restricted_qty.py
  stock_picking_return_restricted_qty/wizard/__init__.py
  stock_picking_return_restricted_qty/wizard/stock_picking_return.py
Labels: approved, bot is merging ⏳

#653 [12.0][IMP] stock_return_request: Get sub locations. Get quant location for quants if possible
  stock_return_request/models/stock_return_request.py
  stock_return_request/tests/test_stock_return_request.py
  stock_return_request/tests/test_stock_return_request_common.py
Labels: bot is merging ⏳

#651 [FIX] 12.0 picking_quick search view
  stock_picking_quick/__manifest__.py
  stock_picking_quick/models/stock_picking.py
  stock_picking_quick/views/product_view.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge
