Repository OCA/stock-logistics-workflow, pull requests merged in 2020-02, with the labels that each got.

#615 [12.0][ADD] stock_picking_filter_lot: add logic to filter by lots in stock scrap
  stock_picking_filter_lot/__manifest__.py
  stock_picking_filter_lot/readme/CONTRIBUTORS.rst
  stock_picking_filter_lot/readme/DESCRIPTION.rst
  stock_picking_filter_lot/readme/USAGE.rst
  stock_picking_filter_lot/views/stock_scrap_view.xml
Labels: approved, enhancement, needs review, ready to merge

#626 [12.0][FIX] stock_picking_mass_action: Error mass picking transfer mixing
  stock_picking_mass_action/models/stock_picking.py
  stock_picking_mass_action/tests/test_mass_action.py
Labels: approved, enhancement, needs review, ready to merge, work in progress

#620 [IMP] stock_return_request: lot suggestions
  stock_return_request/__init__.py
  stock_return_request/__manifest__.py
  stock_return_request/models/stock_move.py
  stock_return_request/models/stock_return_request.py
  stock_return_request/views/stock_return_request_views.xml
  stock_return_request/wizard/__init__.py
  stock_return_request/wizard/suggest_return_request.xml
  stock_return_request/wizard/suggest_return_request_lot.py
Labels: enhancement, needs review

#621 [MIG][13.0] stock_picking_sale_order_link: Migration to v13.0
  stock_picking_sale_order_link/README.rst
  stock_picking_sale_order_link/__init__.py
  stock_picking_sale_order_link/__manifest__.py
  stock_picking_sale_order_link/i18n/de.po
  stock_picking_sale_order_link/i18n/es.po
  stock_picking_sale_order_link/i18n/fr.po
  stock_picking_sale_order_link/i18n/it.po
  stock_picking_sale_order_link/i18n/pt_BR.po
  stock_picking_sale_order_link/i18n/stock_picking_sale_order_link.pot
  stock_picking_sale_order_link/models/__init__.py
  stock_picking_sale_order_link/models/stock_picking.py
  stock_picking_sale_order_link/readme/CONTRIBUTORS.rst
  stock_picking_sale_order_link/readme/DESCRIPTION.rst
  stock_picking_sale_order_link/readme/USAGE.rst
  stock_picking_sale_order_link/static/description/icon.png
  stock_picking_sale_order_link/static/description/index.html
  stock_picking_sale_order_link/tests/__init__.py
  stock_picking_sale_order_link/tests/test_stock_picking_sale_order_link.py
  stock_picking_sale_order_link/views/stock_picking_view.xml
Labels: approved
