Repository OCA/stock-logistics-workflow, pull requests merged in 2020-10, with the labels that each got.

#706 [13.0][UPD] Eficent -> ForgeFlow
  stock_no_negative/README.rst
  stock_no_negative/models/stock_location.py
  stock_no_negative/readme/CONTRIBUTORS.rst
  stock_no_negative/static/description/index.html
  stock_no_negative/tests/__init__.py
  stock_no_negative/tests/test_stock_no_negative.py
  stock_picking_filter_lot/README.rst
  stock_picking_filter_lot/readme/CONTRIBUTORS.rst
  stock_picking_filter_lot/static/description/index.html
  stock_picking_filter_lot/views/stock_move_line_view.xml
Labels: approved, bot is merging ⏳

#710 [12.0][IMP] stock_picking_batch_extended: Request confirmation to cancel pickings
  stock_picking_batch_extended/i18n/es.po
  stock_picking_batch_extended/i18n/stock_picking_batch_extended.pot
  stock_picking_batch_extended/views/stock_batch_picking.xml
Labels: approved, bot is merging ⏳

#711 [13.0][FIX] stock_picking_sale_order_link: New sale line added to done picking
  stock_picking_sale_order_link/models/stock_picking.py
Labels: bot is merging ⏳

#712 Revert "[FIX] stock: When a transfer is packaged and unpacked, it creates a"
  stock_no_negative/models/stock_quant.py
Labels: bot is merging ⏳

#704 [13.0][FIX] stock_move_line_auto_fill: Qty done not fully updated in case of update stock move line
  stock_move_line_auto_fill/models/stock_move.py
  stock_move_line_auto_fill/tests/test_stock_picking_auto_fill.py
Labels: approved, bot is merging ⏳

#715 [12.0][FIX] stock_move_line_auto_fill: Qty done not fully updated in case of update stock move line
  stock_move_line_auto_fill/models/stock_move.py
  stock_move_line_auto_fill/tests/test_stock_picking_auto_fill.py
Labels: bot is merging ⏳

#646 [13.0][ADD] stock_picking_warn_message
  setup/stock_picking_warn_message/odoo/addons/stock_picking_warn_message
  setup/stock_picking_warn_message/setup.py
  stock_picking_warn_message/README.rst
  stock_picking_warn_message/__init__.py
  stock_picking_warn_message/__manifest__.py
  stock_picking_warn_message/models/__init__.py
  stock_picking_warn_message/models/stock_picking.py
  stock_picking_warn_message/readme/CONTRIBUTORS.rst
  stock_picking_warn_message/readme/DESCRIPTION.rst
  stock_picking_warn_message/static/description/icon.png
  stock_picking_warn_message/static/description/index.html
  stock_picking_warn_message/tests/__init__.py
  stock_picking_warn_message/tests/test_stock_picking_warn_message.py
  stock_picking_warn_message/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#717 [13.0][IMP] stock_picking_warn_message: disable tracking test suite wise
  stock_picking_warn_message/tests/test_stock_picking_warn_message.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge
