Repository OCA/stock-logistics-workflow, pull requests merged in 2020-09, with the labels that each got.

#699 [12.0][ADD] stock_picking_late_activity: new module
  stock_picking_late_activity/README.rst
  stock_picking_late_activity/__init__.py
  stock_picking_late_activity/__manifest__.py
  stock_picking_late_activity/data/ir_cron_data.xml
  stock_picking_late_activity/data/mail_activity_type_data.xml
  stock_picking_late_activity/i18n/es.po
  stock_picking_late_activity/i18n/stock_picking_late_activity.pot
  stock_picking_late_activity/models/__init__.py
  stock_picking_late_activity/models/stock_picking.py
  stock_picking_late_activity/models/stock_picking_type.py
  stock_picking_late_activity/readme/CONFIGURE.rst
  stock_picking_late_activity/readme/CONTRIBUTORS.rst
  stock_picking_late_activity/readme/DESCRIPTION.rst
  stock_picking_late_activity/static/description/index.html
  stock_picking_late_activity/tests/__init__.py
  stock_picking_late_activity/tests/test_stock_picking_late_activity.py
  stock_picking_late_activity/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#625 [12.0][ADD] product_supplierinfo_picking
  product_supplierinfo_picking/README.rst
  product_supplierinfo_picking/__init__.py
  product_supplierinfo_picking/__manifest__.py
  product_supplierinfo_picking/models/__init__.py
  product_supplierinfo_picking/models/stock_move.py
  product_supplierinfo_picking/readme/CONTRIBUTORS.rst
  product_supplierinfo_picking/readme/DESCRIPTION.rst
  product_supplierinfo_picking/readme/USAGE.rst
  product_supplierinfo_picking/static/description/icon.png
  product_supplierinfo_picking/static/description/index.html
  product_supplierinfo_picking/tests/__init__.py
  product_supplierinfo_picking/tests/test_product_supplierinfo_picking.py
  product_supplierinfo_picking/views/stock_picking_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#701 [13.0] Fix groups of transfers on sales
  stock_picking_group_by_partner_by_carrier/__manifest__.py
  stock_picking_group_by_partner_by_carrier/migrations/13.0.1.4.0/post-migration.py
  stock_picking_group_by_partner_by_carrier/models/__init__.py
  stock_picking_group_by_partner_by_carrier/models/procurement_group.py
  stock_picking_group_by_partner_by_carrier/models/sale_order.py
  stock_picking_group_by_partner_by_carrier/models/stock_move.py
  stock_picking_group_by_partner_by_carrier/models/stock_picking.py
  stock_picking_group_by_partner_by_carrier/models/stock_rule.py
  stock_picking_group_by_partner_by_carrier/tests/test_grouping.py
Labels: bot is merging ⏳, enhancement, needs review

#664 [11.0][FIX] product_expiry_simple: fix bad decorator on _action_done()
  product_expiry_simple/models/stock_move_line.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#669 [13.0][ADD] stock_move_line_reference_link
  stock_move_line_reference_link/__init__.py
  stock_move_line_reference_link/__manifest__.py
  stock_move_line_reference_link/models/__init__.py
  stock_move_line_reference_link/models/stock_move_line.py
  stock_move_line_reference_link/readme/CONTRIBUTORS.rst
  stock_move_line_reference_link/readme/DESCRIPTION.rst
  stock_move_line_reference_link/static/description/icon.png
  stock_move_line_reference_link/views/move_line_views.xml
Labels: approved, bot is merging ⏳
