Repository OCA/stock-logistics-workflow, pull requests merged in 2020-03, with the labels that each got.

#624 [12.0][MIG] stock_lot_scrap
  stock_lot_scrap/README.rst
  stock_lot_scrap/__init__.py
  stock_lot_scrap/__manifest__.py
  stock_lot_scrap/i18n/de.po
  stock_lot_scrap/i18n/es.po
  stock_lot_scrap/i18n/fr.po
  stock_lot_scrap/i18n/hr.po
  stock_lot_scrap/i18n/it.po
  stock_lot_scrap/i18n/pt.po
  stock_lot_scrap/i18n/sl.po
  stock_lot_scrap/i18n/stock_lot_scrap.pot
  stock_lot_scrap/models/__init__.py
  stock_lot_scrap/models/stock_production_lot.py
  stock_lot_scrap/models/stock_scrap.py
  stock_lot_scrap/readme/CONFIGURE.rst
  stock_lot_scrap/readme/CONTRIBUTORS.rst
  stock_lot_scrap/readme/DESCRIPTION.rst
  stock_lot_scrap/readme/USAGE.rst
  stock_lot_scrap/static/description/icon.png
  stock_lot_scrap/static/description/index.html
  stock_lot_scrap/tests/__init__.py
  stock_lot_scrap/tests/test_stock_lot_scrap.py
Labels: approved, ready to merge

#633 [FIX] product_cost_price_avco_sync: Aleatory error because compare value
  product_cost_price_avco_sync/tests/test_product_cost_price_avco_sync.py
Labels: approved, ready to merge

#630 [12.0] [FIX] stock_picking_line_sequence install with unuseful and very slow update of stock moves
  stock_picking_line_sequence/init_hooks.py
Labels: approved, ready to merge

#632 [12.0][IMP] stock_picking_batch_extended: Add followers, attachments, chatt…
  stock_picking_batch_extended/__manifest__.py
  stock_picking_batch_extended/models/stock_batch_picking.py
  stock_picking_batch_extended/views/stock_batch_picking.xml
Labels: approved, ready to merge

#629 [12.0] [ADD] sale_order_global_stock_route: New module
  sale_order_global_stock_route/README.rst
  sale_order_global_stock_route/__init__.py
  sale_order_global_stock_route/__manifest__.py
  sale_order_global_stock_route/i18n/es.po
  sale_order_global_stock_route/i18n/sale_order_global_stock_route.pot
  sale_order_global_stock_route/models/__init__.py
  sale_order_global_stock_route/models/sale_order.py
  sale_order_global_stock_route/readme/CONFIGURE.rst
  sale_order_global_stock_route/readme/CONTRIBUTORS.rst
  sale_order_global_stock_route/readme/DESCRIPTION.rst
  sale_order_global_stock_route/readme/USAGE.rst
  sale_order_global_stock_route/static/description/icon.png
  sale_order_global_stock_route/static/description/index.html
  sale_order_global_stock_route/tests/__init__.py
  sale_order_global_stock_route/tests/test_sale_order_global_stock_route.py
  sale_order_global_stock_route/views/sale_order_views.xml
Labels: needs review

#623 [12.0][IMP] stock_picking_invoice_link: Allow invoice lines linked with more than one stock move
  stock_picking_invoice_link/README.rst
  stock_picking_invoice_link/__manifest__.py
  stock_picking_invoice_link/i18n/es.po
  stock_picking_invoice_link/i18n/stock_picking_invoice_link.pot
  stock_picking_invoice_link/migrations/12.0.2.0.0/post-migrate.py
  stock_picking_invoice_link/models/account_invoice.py
  stock_picking_invoice_link/models/sale_order.py
  stock_picking_invoice_link/models/stock_move.py
  stock_picking_invoice_link/models/stock_picking.py
  stock_picking_invoice_link/readme/CONTRIBUTORS.rst
  stock_picking_invoice_link/static/description/index.html
  stock_picking_invoice_link/tests/test_stock_picking_invoice_link.py
  stock_picking_invoice_link/views/account_invoice_view.xml
  stock_picking_invoice_link/views/stock_view.xml
Labels: approved, bot is merging ⏳, enhancement, needs review
