Repository OCA/stock-logistics-workflow, pull requests merged in 2020-11, with the labels that each got.

#705 [11.0][ADD]stock_push_delay v11
  stock_push_delay/README.rst
  stock_push_delay/__init__.py
  stock_push_delay/__manifest__.py
  stock_push_delay/models/__init__.py
  stock_push_delay/models/stock.py
  stock_push_delay/readme/CONTRIBUTORS.rst
  stock_push_delay/readme/DESCRIPTION.rst
  stock_push_delay/readme/USAGE.rst
  stock_push_delay/static/description/index.html
Labels: approved, bot is merging ⏳, needs review, ready to merge

#725 [FIX] stock_picking_quick : do not raise an error, if the key is not in the context
  stock_picking_quick/models/product_product.py
Labels: bot is merging ⏳, enhancement, needs review

#727 [13.0][FIX]stock_picking_group_by_partner_by_carrier
  stock_picking_group_by_partner_by_carrier/__manifest__.py
Labels: bot is merging ⏳

#709 [13.0] Fix package dimensions overriden on write
  stock_quant_package_dimension/models/stock_quant_package.py
  stock_quant_package_dimension/tests/__init__.py
  stock_quant_package_dimension/tests/test_package_dimension.py
Labels: approved, bot is merging ⏳, ready to merge

#713 [13.0] stock_picking_group_by_partner_by_carrier: Fix cancelation of SO when multiple SO are grouped in a same delivery.
  stock_picking_group_by_partner_by_carrier/README.rst
  stock_picking_group_by_partner_by_carrier/__manifest__.py
  stock_picking_group_by_partner_by_carrier/models/stock_move.py
  stock_picking_group_by_partner_by_carrier/models/stock_picking.py
  stock_picking_group_by_partner_by_carrier/models/stock_rule.py
  stock_picking_group_by_partner_by_carrier/readme/CONTRIBUTORS.rst
  stock_picking_group_by_partner_by_carrier/tests/test_grouping.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#714 [ADD] stock_split_picking: Mode selection to split in different ways
  stock_split_picking/__init__.py
  stock_split_picking/__manifest__.py
  stock_split_picking/models/stock_picking.py
  stock_split_picking/readme/CONTRIBUTORS.rst
  stock_split_picking/readme/DESCRIPTION.rst
  stock_split_picking/tests/test_stock_split_picking.py
  stock_split_picking/views/stock_partial_picking.xml
  stock_split_picking/wizards/__init__.py
  stock_split_picking/wizards/stock_split_picking.py
  stock_split_picking/wizards/stock_split_picking.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#726 [REF] stock_no_negative: Make inheritable no-negative check
  stock_no_negative/__manifest__.py
  stock_no_negative/models/stock_location.py
  stock_no_negative/models/stock_quant.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#730 [13.0][FIX] stock_move_line_auto_fill: Fix action assign method for allowed states.
  stock_move_line_auto_fill/models/stock_move.py
  stock_move_line_auto_fill/tests/test_stock_picking_auto_fill.py
Labels: approved, bot is merging ⏳

#600 [13.0][MIG] stock_move_quick_lot
  setup/stock_move_quick_lot/odoo/addons/stock_move_quick_lot
  setup/stock_move_quick_lot/setup.py
  stock_move_quick_lot/README.rst
  stock_move_quick_lot/__init__.py
  stock_move_quick_lot/__manifest__.py
  stock_move_quick_lot/i18n/es.po
  stock_move_quick_lot/i18n/stock_move_quick_lot.pot
  stock_move_quick_lot/i18n/stock_pack_operation_quick_lot.pot
  stock_move_quick_lot/models/__init__.py
  stock_move_quick_lot/models/stock_move.py
  stock_move_quick_lot/readme/CONFIGURE.rst
  stock_move_quick_lot/readme/CONTRIBUTORS.rst
  stock_move_quick_lot/readme/DESCRIPTION.rst
  stock_move_quick_lot/readme/USAGE.rst
  stock_move_quick_lot/static/description/icon.png
  stock_move_quick_lot/static/description/icon.svg
  stock_move_quick_lot/static/description/index.html
  stock_move_quick_lot/tests/__init__.py
  stock_move_quick_lot/tests/test_stock_move_quick_lot.py
  stock_move_quick_lot/views/stock_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#742 [IMP] stock_picking_invoice_link: Allow to update stock move depending on context.
  stock_picking_invoice_link/models/stock_move.py
Labels: approved, bot is merging ⏳

#745 [13.0][IMP] stock_picking_invoice_link: Allow to update stock move depending on context.
  stock_picking_invoice_link/models/stock_move.py
Labels: approved, bot is merging ⏳
