Repository OCA/stock-logistics-workflow, pull requests merged in 2021-10, with the labels that each got.

#879 [13.0][MIG] stock_picking_line_sequence
  setup/stock_picking_line_sequence/odoo/addons/stock_picking_line_sequence
  setup/stock_picking_line_sequence/setup.py
  stock_picking_line_sequence/README.rst
  stock_picking_line_sequence/__init__.py
  stock_picking_line_sequence/__manifest__.py
  stock_picking_line_sequence/i18n/ca.po
  stock_picking_line_sequence/i18n/de.po
  stock_picking_line_sequence/i18n/es.po
  stock_picking_line_sequence/i18n/es_MX.po
  stock_picking_line_sequence/i18n/fi.po
  stock_picking_line_sequence/i18n/fr.po
  stock_picking_line_sequence/i18n/hr.po
  stock_picking_line_sequence/i18n/it.po
  stock_picking_line_sequence/i18n/nl_NL.po
  stock_picking_line_sequence/i18n/pt.po
  stock_picking_line_sequence/i18n/pt_BR.po
  stock_picking_line_sequence/i18n/sl.po
  stock_picking_line_sequence/i18n/stock_picking_line_sequence.pot
  stock_picking_line_sequence/i18n/tr.po
  stock_picking_line_sequence/i18n/tr_TR.po
  stock_picking_line_sequence/init_hooks.py
  stock_picking_line_sequence/models/__init__.py
  stock_picking_line_sequence/models/stock.py
  stock_picking_line_sequence/readme/CONTRIBUTORS.rst
  stock_picking_line_sequence/readme/DESCRIPTION.rst
  stock_picking_line_sequence/readme/USAGE.rst
  stock_picking_line_sequence/report/report_deliveryslip.xml
  stock_picking_line_sequence/static/description/icon.png
  stock_picking_line_sequence/static/description/index.html
  stock_picking_line_sequence/tests/__init__.py
  stock_picking_line_sequence/tests/test_move_lines_sequence.py
  stock_picking_line_sequence/views/stock_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#897 [13.0][FIX] stock_picking_group_by_partner_by_carrier_by_date: group moves same day different time
  stock_picking_group_by_partner_by_carrier_by_date/models/stock_move.py
  stock_picking_group_by_partner_by_carrier_by_date/tests/test_grouping_by_date.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#900 [14.0][MIG] delivery_total_weight_from_packaging: Migration to 14.0
  delivery_total_weight_from_packaging/README.rst
  delivery_total_weight_from_packaging/__init__.py
  delivery_total_weight_from_packaging/__manifest__.py
  delivery_total_weight_from_packaging/i18n/delivery_total_weight_from_packaging.pot
  delivery_total_weight_from_packaging/models/__init__.py
  delivery_total_weight_from_packaging/models/stock_move.py
  delivery_total_weight_from_packaging/models/stock_picking.py
  delivery_total_weight_from_packaging/models/stock_quant_package.py
  delivery_total_weight_from_packaging/readme/CONTRIBUTORS.rst
  delivery_total_weight_from_packaging/readme/CREDITS.rst
  delivery_total_weight_from_packaging/readme/DESCRIPTION.rst
  delivery_total_weight_from_packaging/static/description/icon.png
  delivery_total_weight_from_packaging/static/description/index.html
  delivery_total_weight_from_packaging/tests/__init__.py
  delivery_total_weight_from_packaging/tests/common.py
  delivery_total_weight_from_packaging/tests/test_choose_delivery_package.py
  delivery_total_weight_from_packaging/tests/test_weight_from_packaging.py
  delivery_total_weight_from_packaging/wizard/__init__.py
  delivery_total_weight_from_packaging/wizard/choose_delivery_package.py
  setup/delivery_total_weight_from_packaging/odoo/addons/delivery_total_weight_from_packaging
  setup/delivery_total_weight_from_packaging/setup.py
Labels: bot is merging ⏳
