Repository OCA/stock-logistics-workflow, pull requests merged in 2021-02, with the labels that each got.

#785 [13.0][MIG] stock_picking_show_backorder: Migration to 13.0
  setup/stock_picking_show_backorder/odoo/addons/stock_picking_show_backorder
  setup/stock_picking_show_backorder/setup.py
  stock_picking_show_backorder/README.rst
  stock_picking_show_backorder/__init__.py
  stock_picking_show_backorder/__manifest__.py
  stock_picking_show_backorder/i18n/cs_CZ.po
  stock_picking_show_backorder/i18n/de.po
  stock_picking_show_backorder/i18n/es.po
  stock_picking_show_backorder/i18n/fr.po
  stock_picking_show_backorder/i18n/it.po
  stock_picking_show_backorder/i18n/nl_NL.po
  stock_picking_show_backorder/i18n/pt.po
  stock_picking_show_backorder/i18n/pt_BR.po
  stock_picking_show_backorder/i18n/sl.po
  stock_picking_show_backorder/i18n/stock_picking_show_backorder.pot
  stock_picking_show_backorder/models/__init__.py
  stock_picking_show_backorder/models/stock.py
  stock_picking_show_backorder/readme/CONTRIBUTORS.rst
  stock_picking_show_backorder/readme/DESCRIPTION.rst
  stock_picking_show_backorder/readme/USAGE.rst
  stock_picking_show_backorder/static/description/icon.png
  stock_picking_show_backorder/static/description/index.html
  stock_picking_show_backorder/tests/__init__.py
  stock_picking_show_backorder/tests/test_stock_picking_show_backorder.py
  stock_picking_show_backorder/views/stock_view.xml
Labels: approved, bot is merging ⏳

#781 [13.0][IMP] s_picking_group_by_partner_by_carrier: Fix MockedMove
  stock_picking_group_by_partner_by_carrier/models/stock_picking.py
  stock_picking_group_by_partner_by_carrier/readme/CONTRIBUTORS.rst
  stock_picking_group_by_partner_by_carrier/report/report_delivery_slip.xml
  stock_picking_group_by_partner_by_carrier/tests/__init__.py
  stock_picking_group_by_partner_by_carrier/tests/test_report.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#789 [13.0] [MIG] stock_picking_send_by_mail: Migration to v13.0
  setup/stock_picking_send_by_mail/odoo/addons/stock_picking_send_by_mail
  setup/stock_picking_send_by_mail/setup.py
  stock_picking_send_by_mail/README.rst
  stock_picking_send_by_mail/__init__.py
  stock_picking_send_by_mail/__manifest__.py
  stock_picking_send_by_mail/data/stock_picking_mail.xml
  stock_picking_send_by_mail/i18n/de.po
  stock_picking_send_by_mail/i18n/es.po
  stock_picking_send_by_mail/i18n/fr.po
  stock_picking_send_by_mail/i18n/it.po
  stock_picking_send_by_mail/i18n/pt_BR.po
  stock_picking_send_by_mail/i18n/stock_picking_send_by_mail.pot
  stock_picking_send_by_mail/models/__init__.py
  stock_picking_send_by_mail/models/stock_picking.py
  stock_picking_send_by_mail/readme/CONTRIBUTORS.rst
  stock_picking_send_by_mail/readme/DESCRIPTION.rst
  stock_picking_send_by_mail/readme/USAGE.rst
  stock_picking_send_by_mail/static/description/icon.png
  stock_picking_send_by_mail/static/description/index.html
  stock_picking_send_by_mail/tests/__init__.py
  stock_picking_send_by_mail/tests/test_stock_picking_send_by_mail.py
  stock_picking_send_by_mail/views/stock_picking_view.xml
Labels: approved, bot is merging ⏳

#788 [13.0][MIG] stock_return_request: Migration to v13.0
  setup/stock_return_request/odoo/addons/stock_return_request
  setup/stock_return_request/setup.py
  stock_return_request/README.rst
  stock_return_request/__init__.py
  stock_return_request/__manifest__.py
  stock_return_request/data/stock_return_request_data.xml
  stock_return_request/hooks.py
  stock_return_request/i18n/es.po
  stock_return_request/i18n/fr.po
  stock_return_request/i18n/pt_BR.po
  stock_return_request/i18n/stock_return_request.pot
  stock_return_request/models/__init__.py
  stock_return_request/models/stock_move.py
  stock_return_request/models/stock_picking.py
  stock_return_request/models/stock_return_request.py
  stock_return_request/readme/CONTRIBUTORS.rst
  stock_return_request/readme/DESCRIPTION.rst
  stock_return_request/readme/INSTALL.rst
  stock_return_request/readme/ROADMAP.rst
  stock_return_request/readme/USAGE.rst
  stock_return_request/report/stock_return_report.xml
  stock_return_request/security/ir.model.access.csv
  stock_return_request/static/description/icon.png
  stock_return_request/static/description/index.html
  stock_return_request/tests/__init__.py
  stock_return_request/tests/test_stock_return_request.py
  stock_return_request/tests/test_stock_return_request_common.py
  stock_return_request/views/stock_return_request_views.xml
  stock_return_request/wizard/__init__.py
  stock_return_request/wizard/suggest_return_request.xml
  stock_return_request/wizard/suggest_return_request_lot.py
Labels: approved, bot is merging ⏳, ready to merge
