Repository OCA/stock-logistics-workflow, pull requests merged in 2021-07, with the labels that each got.

#852 [14.0][MIG] - stock_auto_move
  setup/stock_auto_move/odoo/addons/stock_auto_move
  setup/stock_auto_move/setup.py
  stock_auto_move/README.rst
  stock_auto_move/__init__.py
  stock_auto_move/__manifest__.py
  stock_auto_move/data/procurement_group.xml
  stock_auto_move/demo/stock_location.xml
  stock_auto_move/demo/stock_location_route.xml
  stock_auto_move/demo/stock_rule.xml
  stock_auto_move/i18n/ca.po
  stock_auto_move/i18n/de.po
  stock_auto_move/i18n/es.po
  stock_auto_move/i18n/es_MX.po
  stock_auto_move/i18n/fi.po
  stock_auto_move/i18n/fr.po
  stock_auto_move/i18n/hr.po
  stock_auto_move/i18n/it.po
  stock_auto_move/i18n/nl_NL.po
  stock_auto_move/i18n/pt.po
  stock_auto_move/i18n/pt_BR.po
  stock_auto_move/i18n/pt_PT.po
  stock_auto_move/i18n/sl.po
  stock_auto_move/i18n/stock_auto_move.pot
  stock_auto_move/i18n/tr.po
  stock_auto_move/i18n/tr_TR.po
  stock_auto_move/i18n/zh_CN.po
  stock_auto_move/models/__init__.py
  stock_auto_move/models/stock_move.py
  stock_auto_move/models/stock_rule.py
  stock_auto_move/readme/CONFIGURE.rst
  stock_auto_move/readme/CONTRIBUTORS.rst
  stock_auto_move/readme/DESCRIPTION.rst
  stock_auto_move/readme/INSTALL.rst
  stock_auto_move/readme/USAGE.rst
  stock_auto_move/static/description/icon.png
  stock_auto_move/tests/__init__.py
  stock_auto_move/tests/test_stock_auto_move.py
  stock_auto_move/views/stock_move.xml
  stock_auto_move/views/stock_rule.xml
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#735 [13.0][MIG] stock_auto_move
  setup/stock_auto_move/odoo/addons/stock_auto_move
  setup/stock_auto_move/setup.py
  stock_auto_move/README.rst
  stock_auto_move/__init__.py
  stock_auto_move/__manifest__.py
  stock_auto_move/data/procurement_group.xml
  stock_auto_move/demo/stock_location.xml
  stock_auto_move/demo/stock_location_route.xml
  stock_auto_move/demo/stock_rule.xml
  stock_auto_move/i18n/ca.po
  stock_auto_move/i18n/de.po
  stock_auto_move/i18n/es.po
  stock_auto_move/i18n/es_MX.po
  stock_auto_move/i18n/fi.po
  stock_auto_move/i18n/fr.po
  stock_auto_move/i18n/hr.po
  stock_auto_move/i18n/it.po
  stock_auto_move/i18n/nl_NL.po
  stock_auto_move/i18n/pt.po
  stock_auto_move/i18n/pt_BR.po
  stock_auto_move/i18n/pt_PT.po
  stock_auto_move/i18n/sl.po
  stock_auto_move/i18n/stock_auto_move.pot
  stock_auto_move/i18n/tr.po
  stock_auto_move/i18n/tr_TR.po
  stock_auto_move/i18n/zh_CN.po
  stock_auto_move/models/__init__.py
  stock_auto_move/models/stock_move.py
  stock_auto_move/models/stock_rule.py
  stock_auto_move/readme/CONFIGURE.rst
  stock_auto_move/readme/CONTRIBUTORS.rst
  stock_auto_move/readme/DESCRIPTION.rst
  stock_auto_move/readme/INSTALL.rst
  stock_auto_move/readme/USAGE.rst
  stock_auto_move/static/description/icon.png
  stock_auto_move/tests/__init__.py
  stock_auto_move/tests/test_stock_auto_move.py
  stock_auto_move/views/stock_move.xml
  stock_auto_move/views/stock_rule.xml
Labels: approved, bot is merging ⏳, migration, needs review

#863 [14.0][PORT] stock_quant_package_dimension PR 777 from 13.0
  stock_quant_package_dimension/migrations/14.0.1.2.0/pre-migration.py
  stock_quant_package_dimension/models/stock_quant_package.py
  stock_quant_package_dimension/readme/DESCRIPTION.rst
  stock_quant_package_dimension/tests/common.py
  stock_quant_package_dimension/tests/test_package_dimension.py
  stock_quant_package_dimension/views/stock_quant_package.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#866 [IMP] stock_move_quick_lot: Allow to assign existing lots in detailed operations for pickings with create lots option enable.
  stock_move_quick_lot/models/__init__.py
  stock_move_quick_lot/models/stock_move_line.py
  stock_move_quick_lot/views/stock_view.xml
Labels: approved, bot is merging ⏳

#733 [11.0][IMP]stock_picking_show_return
  stock_picking_show_return/models/stock_picking.py
  stock_picking_show_return/views/stock_picking_view.xml
Labels: approved, bot is merging ⏳, enhancement

#775 [MIG] stock_partner_delivery_window: Migration to 14.0
  oca_dependencies.txt
  setup/stock_partner_delivery_window/odoo/addons/stock_partner_delivery_window
  setup/stock_partner_delivery_window/setup.py
  stock_partner_delivery_window/README.rst
  stock_partner_delivery_window/__init__.py
  stock_partner_delivery_window/__manifest__.py
  stock_partner_delivery_window/demo/delivery_time_window.xml
  stock_partner_delivery_window/models/__init__.py
  stock_partner_delivery_window/models/delivery_time_window.py
  stock_partner_delivery_window/models/res_partner.py
  stock_partner_delivery_window/models/stock_picking.py
  stock_partner_delivery_window/readme/CONFIGURE.rst
  stock_partner_delivery_window/readme/CONTRIBUTORS.rst
  stock_partner_delivery_window/readme/CREDITS.rst
  stock_partner_delivery_window/readme/DESCRIPTION.rst
  stock_partner_delivery_window/security/ir.model.access.csv
  stock_partner_delivery_window/static/description/index.html
  stock_partner_delivery_window/tests/__init__.py
  stock_partner_delivery_window/tests/test_delivery_window.py
  stock_partner_delivery_window/views/res_partner.xml
Labels: approved, bot is merging ⏳, migration, needs review

#846 [MIG] stock_split_picking: Migration to 14.0
  setup/stock_split_picking/odoo/addons/stock_split_picking
  setup/stock_split_picking/setup.py
  stock_split_picking/README.rst
  stock_split_picking/__init__.py
  stock_split_picking/__manifest__.py
  stock_split_picking/i18n/ar.po
  stock_split_picking/i18n/ca_ES.po
  stock_split_picking/i18n/de.po
  stock_split_picking/i18n/es.po
  stock_split_picking/i18n/es_MX.po
  stock_split_picking/i18n/fi.po
  stock_split_picking/i18n/fr.po
  stock_split_picking/i18n/hr.po
  stock_split_picking/i18n/it.po
  stock_split_picking/i18n/nl_NL.po
  stock_split_picking/i18n/pt.po
  stock_split_picking/i18n/pt_BR.po
  stock_split_picking/i18n/sl.po
  stock_split_picking/i18n/stock_split_picking.pot
  stock_split_picking/i18n/tr.po
  stock_split_picking/i18n/tr_TR.po
  stock_split_picking/i18n/zh_CN.po
  stock_split_picking/models/__init__.py
  stock_split_picking/models/stock_picking.py
  stock_split_picking/readme/CONTRIBUTORS.rst
  stock_split_picking/readme/DESCRIPTION.rst
  stock_split_picking/readme/USAGE.rst
  stock_split_picking/security/ir.model.access.csv
  stock_split_picking/static/description/icon.png
  stock_split_picking/static/description/index.html
  stock_split_picking/tests/__init__.py
  stock_split_picking/tests/test_stock_split_picking.py
  stock_split_picking/views/stock_partial_picking.xml
  stock_split_picking/wizards/__init__.py
  stock_split_picking/wizards/stock_split_picking.py
  stock_split_picking/wizards/stock_split_picking.xml
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#867 [ADD] stock_picking_force_assign
  stock_picking_force_assign/README.rst
  stock_picking_force_assign/__init__.py
  stock_picking_force_assign/__manifest__.py
  stock_picking_force_assign/demo/res_groups.xml
  stock_picking_force_assign/models/__init__.py
  stock_picking_force_assign/models/stock_picking.py
  stock_picking_force_assign/readme/CONTRIBUTORS.rst
  stock_picking_force_assign/readme/DESCRIPTION.rst
  stock_picking_force_assign/readme/USAGE.rst
  stock_picking_force_assign/security/stock_picking_force_assign_security.xml
  stock_picking_force_assign/static/description/index.html
  stock_picking_force_assign/tests/__init__.py
  stock_picking_force_assign/tests/test_stock_picking_force_assign.py
  stock_picking_force_assign/views/stock_picking.xml
Labels: approved, bot is merging ⏳, ready to merge

#783 [14.0][ADD] stock_picking_cancel_reason
  setup/stock_picking_cancel_reason/odoo/addons/stock_picking_cancel_reason
  setup/stock_picking_cancel_reason/setup.py
  stock_picking_cancel_reason/README.rst
  stock_picking_cancel_reason/__init__.py
  stock_picking_cancel_reason/__manifest__.py
  stock_picking_cancel_reason/data/stock_picking_cancel_reason.xml
  stock_picking_cancel_reason/model/__init__.py
  stock_picking_cancel_reason/model/stock_picking.py
  stock_picking_cancel_reason/readme/CONFIGURE.rst
  stock_picking_cancel_reason/readme/CONTRIBUTORS.rst
  stock_picking_cancel_reason/readme/CREDITS.rst
  stock_picking_cancel_reason/readme/DESCRIPTION.rst
  stock_picking_cancel_reason/security/ir.model.access.csv
  stock_picking_cancel_reason/static/description/icon.png
  stock_picking_cancel_reason/static/description/index.html
  stock_picking_cancel_reason/tests/__init__.py
  stock_picking_cancel_reason/tests/test_stock_picking_cancel_reason.py
  stock_picking_cancel_reason/views/stock_picking_views.xml
  stock_picking_cancel_reason/wizard/__init__.py
  stock_picking_cancel_reason/wizard/stock_picking_cancel_reason.py
  stock_picking_cancel_reason/wizard/stock_picking_cancel_reason_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#728 [13.0][IMP] stock_picking_auto_create_lot: Improve performances and UX
  stock_picking_auto_create_lot/__manifest__.py
  stock_picking_auto_create_lot/models/__init__.py
  stock_picking_auto_create_lot/models/stock_move.py
  stock_picking_auto_create_lot/models/stock_move_line.py
  stock_picking_auto_create_lot/models/stock_picking.py
  stock_picking_auto_create_lot/models/stock_picking_type.py
  stock_picking_auto_create_lot/readme/CONFIGURE.rst
  stock_picking_auto_create_lot/readme/CONTRIBUTORS.rst
  stock_picking_auto_create_lot/tests/__init__.py
  stock_picking_auto_create_lot/tests/common.py
  stock_picking_auto_create_lot/tests/test_stock_picking_auto_create_lot.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#833 [ADD] stock_move_manual_lot
  stock_move_manual_lot/README.rst
  stock_move_manual_lot/__init__.py
  stock_move_manual_lot/__manifest__.py
  stock_move_manual_lot/hooks.py
  stock_move_manual_lot/models/__init__.py
  stock_move_manual_lot/models/stock_move_line.py
  stock_move_manual_lot/models/stock_picking.py
  stock_move_manual_lot/models/stock_picking_type.py
  stock_move_manual_lot/readme/CONTRIBUTORS.rst
  stock_move_manual_lot/readme/DESCRIPTION.rst
  stock_move_manual_lot/readme/USAGE.rst
  stock_move_manual_lot/readme/newsfragments/.gitkeep
  stock_move_manual_lot/static/description/index.html
  stock_move_manual_lot/tests/__init__.py
  stock_move_manual_lot/tests/test_stock_move_manual_lot.py
  stock_move_manual_lot/views/stock_move_line.xml
  stock_move_manual_lot/views/stock_picking.xml
  stock_move_manual_lot/views/stock_picking_type.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#731 [13.0][ADD] stock_owner_restriction: New module to restrict quantities owned.
  setup/stock_owner_restriction/odoo/addons/stock_owner_restriction
  setup/stock_owner_restriction/setup.py
  stock_owner_restriction/README.rst
  stock_owner_restriction/__init__.py
  stock_owner_restriction/__manifest__.py
  stock_owner_restriction/i18n/es.po
  stock_owner_restriction/i18n/stock_owner_restriction.pot
  stock_owner_restriction/models/__init__.py
  stock_owner_restriction/models/product.py
  stock_owner_restriction/models/stock_move.py
  stock_owner_restriction/models/stock_picking.py
  stock_owner_restriction/models/stock_picking_type.py
  stock_owner_restriction/models/stock_quant.py
  stock_owner_restriction/readme/CONFIGURE.rst
  stock_owner_restriction/readme/CONTRIBUTORS.rst
  stock_owner_restriction/readme/DESCRIPTION.rst
  stock_owner_restriction/readme/USAGE.rst
  stock_owner_restriction/static/description/icon.png
  stock_owner_restriction/static/description/index.html
  stock_owner_restriction/tests/__init__.py
  stock_owner_restriction/tests/test_stock_owner_restriction.py
  stock_owner_restriction/views/stock_picking_type_views.xml
  stock_owner_restriction/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#868 [13.0][ADD] stock_move_change_source_location
  setup/stock_move_change_source_location/odoo/addons/stock_move_change_source_location
  setup/stock_move_change_source_location/setup.py
  stock_move_change_source_location/README.rst
  stock_move_change_source_location/__init__.py
  stock_move_change_source_location/__manifest__.py
  stock_move_change_source_location/readme/CONTRIBUTORS.rst
  stock_move_change_source_location/readme/DESCRIPTION.rst
  stock_move_change_source_location/readme/USAGE.rst
  stock_move_change_source_location/static/description/icon.png
  stock_move_change_source_location/tests/__init__.py
  stock_move_change_source_location/tests/test_stock_move_change_source_location.py
  stock_move_change_source_location/views/stock_picking_view.xml
  stock_move_change_source_location/wizards/__init__.py
  stock_move_change_source_location/wizards/stock_move_change_source_location_wizard.py
  stock_move_change_source_location/wizards/stock_move_change_source_location_wizard.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#872 [13.0][FIX] stock_picking_send_by_mail: Send delivery report instead of operations report
  stock_picking_send_by_mail/data/stock_picking_mail.xml
Labels: approved, bot is merging ⏳

#873 [13.0][IMP] s_p_g_by_p_by_carrier: hook to check state
  stock_picking_group_by_partner_by_carrier/models/stock_picking.py
Labels: approved, bot is merging ⏳, needs review

#869 [13.0][IMP] stock_picking_batch_extended: Add optional picking_count column in tree view
  stock_picking_batch_extended/views/stock_batch_picking.xml
Labels: approved, bot is merging ⏳, enhancement, needs review
