Repository OCA/stock-logistics-workflow, pull requests merged in 2021-03, with the labels that each got.

#772 [14.0][MIG] stock_putaway_hook
  setup/stock_putaway_hook/odoo/addons/stock_putaway_hook
  setup/stock_putaway_hook/setup.py
  stock_putaway_hook/README.rst
  stock_putaway_hook/__init__.py
  stock_putaway_hook/__manifest__.py
  stock_putaway_hook/i18n/stock_putaway_hook.pot
  stock_putaway_hook/models/__init__.py
  stock_putaway_hook/models/stock_location.py
  stock_putaway_hook/models/stock_putaway_rule.py
  stock_putaway_hook/readme/CONTRIBUTORS.rst
  stock_putaway_hook/readme/DESCRIPTION.rst
  stock_putaway_hook/readme/USAGE.rst
  stock_putaway_hook/static/description/icon.png
  stock_putaway_hook/static/description/index.html
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#760 [13.0] [MIG] stock_picking_product_assortment: Migration to v13.0
  setup/stock_picking_product_assortment/odoo/addons/stock_picking_product_assortment
  setup/stock_picking_product_assortment/setup.py
  stock_picking_product_assortment/README.rst
  stock_picking_product_assortment/__init__.py
  stock_picking_product_assortment/__manifest__.py
  stock_picking_product_assortment/i18n/es.po
  stock_picking_product_assortment/i18n/stock_picking_product_assortment.pot
  stock_picking_product_assortment/models/__init__.py
  stock_picking_product_assortment/models/stock_move.py
  stock_picking_product_assortment/models/stock_move_line.py
  stock_picking_product_assortment/models/stock_picking.py
  stock_picking_product_assortment/readme/CONFIGURE.rst
  stock_picking_product_assortment/readme/CONTRIBUTORS.rst
  stock_picking_product_assortment/readme/DESCRIPTION.rst
  stock_picking_product_assortment/readme/ROADMAP.rst
  stock_picking_product_assortment/readme/USAGE.rst
  stock_picking_product_assortment/static/description/icon.png
  stock_picking_product_assortment/static/description/index.html
  stock_picking_product_assortment/tests/__init__.py
  stock_picking_product_assortment/tests/test_stock_picking_product_assortment.py
  stock_picking_product_assortment/views/stock_picking_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#805 [13.0][FIX] stock_return_request: Fix tests
  stock_return_request/tests/test_stock_return_request.py
  stock_return_request/tests/test_stock_return_request_common.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#800 [14.0][FIX] stock_restrict_lot
  stock_restrict_lot/models/stock_move.py
Labels: approved, bot is merging ⏳, ready to merge

#814 [13.0][MIG] stock_picking_late_activity: Migration to 13.0
  setup/stock_picking_late_activity/odoo/addons/stock_picking_late_activity
  setup/stock_picking_late_activity/setup.py
  stock_picking_late_activity/README.rst
  stock_picking_late_activity/__init__.py
  stock_picking_late_activity/__manifest__.py
  stock_picking_late_activity/data/ir_cron_data.xml
  stock_picking_late_activity/data/mail_activity_type_data.xml
  stock_picking_late_activity/i18n/es.po
  stock_picking_late_activity/i18n/stock_picking_late_activity.pot
  stock_picking_late_activity/models/__init__.py
  stock_picking_late_activity/models/stock_picking.py
  stock_picking_late_activity/models/stock_picking_type.py
  stock_picking_late_activity/readme/CONFIGURE.rst
  stock_picking_late_activity/readme/CONTRIBUTORS.rst
  stock_picking_late_activity/readme/DESCRIPTION.rst
  stock_picking_late_activity/static/description/icon.png
  stock_picking_late_activity/static/description/index.html
  stock_picking_late_activity/tests/__init__.py
  stock_picking_late_activity/tests/test_stock_picking_late_activity.py
  stock_picking_late_activity/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳

#812 [13.0][ADD] stock_split_picking: Mode selection to split in different ways
  stock_split_picking/__init__.py
  stock_split_picking/__manifest__.py
  stock_split_picking/models/stock_picking.py
  stock_split_picking/readme/CONTRIBUTORS.rst
  stock_split_picking/readme/DESCRIPTION.rst
  stock_split_picking/tests/test_stock_split_picking.py
  stock_split_picking/views/stock_partial_picking.xml
  stock_split_picking/wizards/__init__.py
  stock_split_picking/wizards/stock_split_picking.py
  stock_split_picking/wizards/stock_split_picking.xml
Labels: approved, bot is merging ⏳

#817 [12.0] stock_picking_preparation_line: Fix tests after Odoo mess
  stock_picking_package_preparation_line/tests/test_package_preparation_line.py
Labels: approved, bot is merging ⏳

#776 [13.0][ADD] delivery_total_weight_from_packaging
  delivery_total_weight_from_packaging/README.rst
  delivery_total_weight_from_packaging/__init__.py
  delivery_total_weight_from_packaging/__manifest__.py
  delivery_total_weight_from_packaging/models/__init__.py
  delivery_total_weight_from_packaging/models/stock_move.py
  delivery_total_weight_from_packaging/models/stock_picking.py
  delivery_total_weight_from_packaging/models/stock_quant_package.py
  delivery_total_weight_from_packaging/readme/CONTRIBUTORS.rst
  delivery_total_weight_from_packaging/readme/CREDITS.rst
  delivery_total_weight_from_packaging/readme/DESCRIPTION.rst
  delivery_total_weight_from_packaging/static/description/index.html
  delivery_total_weight_from_packaging/tests/__init__.py
  delivery_total_weight_from_packaging/tests/test_weight_from_packaging.py
  setup/delivery_total_weight_from_packaging/odoo/addons/delivery_total_weight_from_packaging
  setup/delivery_total_weight_from_packaging/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#818 [13.0] delivery_total_weight_from_packaging improvements
  delivery_total_weight_from_packaging/__init__.py
  delivery_total_weight_from_packaging/models/stock_quant_package.py
  delivery_total_weight_from_packaging/tests/__init__.py
  delivery_total_weight_from_packaging/tests/common.py
  delivery_total_weight_from_packaging/tests/test_choose_delivery_package.py
  delivery_total_weight_from_packaging/tests/test_weight_from_packaging.py
  delivery_total_weight_from_packaging/wizard/__init__.py
  delivery_total_weight_from_packaging/wizard/choose_delivery_package.py
Labels: approved, bot is merging ⏳

#738 [14.0][MIG] stock_return_request
  setup/stock_return_request/odoo/addons/stock_return_request
  setup/stock_return_request/setup.py
  stock_return_request/README.rst
  stock_return_request/__init__.py
  stock_return_request/__manifest__.py
  stock_return_request/data/stock_return_request_data.xml
  stock_return_request/hooks.py
  stock_return_request/i18n/es.po
  stock_return_request/i18n/fr.po
  stock_return_request/i18n/pt_BR.po
  stock_return_request/i18n/stock_return_request.pot
  stock_return_request/models/__init__.py
  stock_return_request/models/stock_move.py
  stock_return_request/models/stock_picking.py
  stock_return_request/models/stock_return_request.py
  stock_return_request/readme/CONTRIBUTORS.rst
  stock_return_request/readme/DESCRIPTION.rst
  stock_return_request/readme/INSTALL.rst
  stock_return_request/readme/ROADMAP.rst
  stock_return_request/readme/USAGE.rst
  stock_return_request/report/stock_return_report.xml
  stock_return_request/security/ir.model.access.csv
  stock_return_request/static/description/icon.png
  stock_return_request/static/description/index.html
  stock_return_request/tests/__init__.py
  stock_return_request/tests/test_stock_return_request.py
  stock_return_request/tests/test_stock_return_request_common.py
  stock_return_request/views/stock_return_request_views.xml
  stock_return_request/wizard/__init__.py
  stock_return_request/wizard/suggest_return_request.xml
  stock_return_request/wizard/suggest_return_request_lot.py
Labels: approved, bot is merging ⏳, ready to merge

#787 12.0 ADD module stock_shifting_end_of_lot
  stock_shifting_end_of_lot/README.rst
  stock_shifting_end_of_lot/__init__.py
  stock_shifting_end_of_lot/__manifest__.py
  stock_shifting_end_of_lot/data/organisation_demo.xml
  stock_shifting_end_of_lot/data/product_demo.xml
  stock_shifting_end_of_lot/data/stock_demo.xml
  stock_shifting_end_of_lot/i18n/fr.po
  stock_shifting_end_of_lot/models/__init__.py
  stock_shifting_end_of_lot/models/stock_picking.py
  stock_shifting_end_of_lot/models/stock_picking_type.py
  stock_shifting_end_of_lot/readme/CONFIGURE.rst
  stock_shifting_end_of_lot/readme/CONTRIBUTORS.rst
  stock_shifting_end_of_lot/readme/DESCRIPTION.rst
  stock_shifting_end_of_lot/static/description/conf.png
  stock_shifting_end_of_lot/static/description/index.html
  stock_shifting_end_of_lot/static/description/main.png
  stock_shifting_end_of_lot/static/description/transfer.png
  stock_shifting_end_of_lot/tests/__init__.py
  stock_shifting_end_of_lot/tests/test_shifting.py
  stock_shifting_end_of_lot/views/picking_type.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#813 [11.0] [BACKPORT] stock_split_picking: Mode selection to split in different ways
  stock_split_picking/__init__.py
  stock_split_picking/__manifest__.py
  stock_split_picking/models/stock_picking.py
  stock_split_picking/tests/test_stock_split_picking.py
  stock_split_picking/views/stock_partial_picking.xml
  stock_split_picking/wizards/__init__.py
  stock_split_picking/wizards/stock_split_picking.py
  stock_split_picking/wizards/stock_split_picking.xml
Labels: approved, bot is merging ⏳, ready to merge
