Repository OCA/stock-logistics-workflow, pull requests merged in 2021-09, with the labels that each got.

#794 [MIG] stock_putaway_by_route: Migration to 14.0
  setup/stock_putaway_by_route/odoo/addons/stock_putaway_by_route
  setup/stock_putaway_by_route/setup.py
  stock_putaway_by_route/README.rst
  stock_putaway_by_route/__init__.py
  stock_putaway_by_route/__manifest__.py
  stock_putaway_by_route/i18n/stock_putaway_by_route.pot
  stock_putaway_by_route/models/__init__.py
  stock_putaway_by_route/models/stock_location.py
  stock_putaway_by_route/models/stock_move.py
  stock_putaway_by_route/models/stock_move_line.py
  stock_putaway_by_route/models/stock_putaway_rule.py
  stock_putaway_by_route/readme/CONFIGURATION.rst
  stock_putaway_by_route/readme/CONTRIBUTORS.rst
  stock_putaway_by_route/readme/CREDITS.rst
  stock_putaway_by_route/readme/DESCRIPTION.rst
  stock_putaway_by_route/static/description/icon.png
  stock_putaway_by_route/static/description/index.html
  stock_putaway_by_route/tests/__init__.py
  stock_putaway_by_route/tests/test_route_putaway.py
  stock_putaway_by_route/tests/test_view.py
  stock_putaway_by_route/views/stock_putaway_rule_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#888 [13.0][IMP] stock_picking_batch_extended: Add confirm to validate and done buttons.
  stock_picking_batch_extended/i18n/es.po
  stock_picking_batch_extended/i18n/stock_picking_batch_extended.pot
  stock_picking_batch_extended/views/stock_batch_picking.xml
Labels: approved, bot is merging ⏳

#877 [13.0][MIG] stock_picking_package_preparation: Migration to 13.0
  setup/stock_picking_package_preparation/odoo/addons/stock_picking_package_preparation
  setup/stock_picking_package_preparation/setup.py
  stock_picking_package_preparation/README.rst
  stock_picking_package_preparation/__init__.py
  stock_picking_package_preparation/__manifest__.py
  stock_picking_package_preparation/i18n/de.po
  stock_picking_package_preparation/i18n/en.po
  stock_picking_package_preparation/i18n/es.po
  stock_picking_package_preparation/i18n/fr.po
  stock_picking_package_preparation/i18n/it.po
  stock_picking_package_preparation/i18n/nl_NL.po
  stock_picking_package_preparation/i18n/pt_BR.po
  stock_picking_package_preparation/i18n/sl.po
  stock_picking_package_preparation/i18n/stock_picking_package_preparation.pot
  stock_picking_package_preparation/models/__init__.py
  stock_picking_package_preparation/models/stock_picking_package_preparation.py
  stock_picking_package_preparation/readme/CONTRIBUTORS.rst
  stock_picking_package_preparation/readme/DESCRIPTION.rst
  stock_picking_package_preparation/readme/ROADMAP.rst
  stock_picking_package_preparation/readme/USAGE.rst
  stock_picking_package_preparation/security/ir.model.access.csv
  stock_picking_package_preparation/security/package_preparation_security.xml
  stock_picking_package_preparation/static/description/icon.png
  stock_picking_package_preparation/static/description/index.html
  stock_picking_package_preparation/tests/__init__.py
  stock_picking_package_preparation/tests/test_package_preparation.py
  stock_picking_package_preparation/views/stock_picking_package_preparation_view.xml
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#883 [13.0][ADD] purchase_stock_picking_invoice_link
  purchase_stock_picking_invoice_link/README.rst
  purchase_stock_picking_invoice_link/__init__.py
  purchase_stock_picking_invoice_link/__manifest__.py
  purchase_stock_picking_invoice_link/i18n/es.po
  purchase_stock_picking_invoice_link/i18n/purchase_stock_picking_invoice_link.pot
  purchase_stock_picking_invoice_link/models/__init__.py
  purchase_stock_picking_invoice_link/models/account_move.py
  purchase_stock_picking_invoice_link/models/stock_move.py
  purchase_stock_picking_invoice_link/readme/CONTRIBUTORS.rst
  purchase_stock_picking_invoice_link/readme/DESCRIPTION.rst
  purchase_stock_picking_invoice_link/readme/USAGE.rst
  purchase_stock_picking_invoice_link/static/description/icon.png
  purchase_stock_picking_invoice_link/static/description/index.html
  purchase_stock_picking_invoice_link/tests/__init__.py
  purchase_stock_picking_invoice_link/tests/test_purchase_stock_picking_invoice_link.py
  setup/purchase_stock_picking_invoice_link/odoo/addons/purchase_stock_picking_invoice_link
  setup/purchase_stock_picking_invoice_link/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#791 [MIG] stock_picking_restrict_cancel_with_orig_move: Migration to 14.0
  setup/stock_picking_restrict_cancel_with_orig_move/odoo/addons/stock_picking_restrict_cancel_with_orig_move
  setup/stock_picking_restrict_cancel_with_orig_move/setup.py
  stock_picking_restrict_cancel_with_orig_move/README.rst
  stock_picking_restrict_cancel_with_orig_move/__init__.py
  stock_picking_restrict_cancel_with_orig_move/__manifest__.py
  stock_picking_restrict_cancel_with_orig_move/i18n/stock_picking_restrict_cancel_with_orig_move.pot
  stock_picking_restrict_cancel_with_orig_move/models/__init__.py
  stock_picking_restrict_cancel_with_orig_move/models/stock_move.py
  stock_picking_restrict_cancel_with_orig_move/readme/CONTRIBUTORS.rst
  stock_picking_restrict_cancel_with_orig_move/readme/CREDITS.rst
  stock_picking_restrict_cancel_with_orig_move/readme/DESCRIPTION.rst
  stock_picking_restrict_cancel_with_orig_move/readme/USAGE.rst
  stock_picking_restrict_cancel_with_orig_move/static/description/icon.png
  stock_picking_restrict_cancel_with_orig_move/static/description/index.html
  stock_picking_restrict_cancel_with_orig_move/tests/__init__.py
  stock_picking_restrict_cancel_with_orig_move/tests/test_restrict_cancel.py
Labels: approved, bot is merging ⏳

#891 [14.0][FIX] stock_picking_show_return fix tests
  stock_picking_show_return/tests/test_stock_picking_show_return.py
Labels: bot is merging ⏳

#793 [MIG] delivery_package_default_shipping_weight: Migration to 14.0
  delivery_package_default_shipping_weight/README.rst
  delivery_package_default_shipping_weight/__init__.py
  delivery_package_default_shipping_weight/__manifest__.py
  delivery_package_default_shipping_weight/i18n/delivery_package_default_shipping_weight.pot
  delivery_package_default_shipping_weight/models/__init__.py
  delivery_package_default_shipping_weight/models/product_packaging.py
  delivery_package_default_shipping_weight/models/stock_quant_package.py
  delivery_package_default_shipping_weight/readme/CONTRIBUTORS.rst
  delivery_package_default_shipping_weight/readme/CREDITS.rst
  delivery_package_default_shipping_weight/readme/DESCRIPTION.rst
  delivery_package_default_shipping_weight/static/description/icon.png
  delivery_package_default_shipping_weight/static/description/index.html
  delivery_package_default_shipping_weight/tests/__init__.py
  delivery_package_default_shipping_weight/tests/test_delivery_package_default_shipping_weight.py
  delivery_package_default_shipping_weight/views/product_packaging.xml
  setup/delivery_package_default_shipping_weight/odoo/addons/delivery_package_default_shipping_weight
  setup/delivery_package_default_shipping_weight/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#898 [14.0] cherry-pick [FIX] stock_no_negative: Use product display_name instead of name
  stock_no_negative/models/stock_quant.py
Labels: bot is merging ⏳

#899 [13.0] cherry-pick [FIX] stock_no_negative: Use product display_name instead of name
  stock_no_negative/models/stock_quant.py
Labels: bot is merging ⏳

#855 [14.0][MIG] product_supplierinfo_for_customer_picking
  product_supplierinfo_for_customer_picking/README.rst
  product_supplierinfo_for_customer_picking/__init__.py
  product_supplierinfo_for_customer_picking/__manifest__.py
  product_supplierinfo_for_customer_picking/i18n/de.po
  product_supplierinfo_for_customer_picking/i18n/it.po
  product_supplierinfo_for_customer_picking/i18n/product_supplierinfo_for_customer_picking.pot
  product_supplierinfo_for_customer_picking/i18n/pt_BR.po
  product_supplierinfo_for_customer_picking/models/__init__.py
  product_supplierinfo_for_customer_picking/models/stock_move.py
  product_supplierinfo_for_customer_picking/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_picking/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer_picking/static/description/icon.png
  product_supplierinfo_for_customer_picking/static/description/index.html
  product_supplierinfo_for_customer_picking/tests/__init__.py
  product_supplierinfo_for_customer_picking/tests/test_product_supplierinfo_for_customer_picking.py
  product_supplierinfo_for_customer_picking/views/stock_picking_view.xml
  setup/product_supplierinfo_for_customer_picking/odoo/addons/product_supplierinfo_for_customer_picking
  setup/product_supplierinfo_for_customer_picking/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#882 [14.0] [MIG] stock_picking_purchase_order_link
  setup/stock_picking_purchase_order_link/odoo/addons/stock_picking_purchase_order_link
  setup/stock_picking_purchase_order_link/setup.py
  stock_picking_purchase_order_link/README.rst
  stock_picking_purchase_order_link/__init__.py
  stock_picking_purchase_order_link/__manifest__.py
  stock_picking_purchase_order_link/i18n/stock_picking_purchase_order_link.pot
  stock_picking_purchase_order_link/models/__init__.py
  stock_picking_purchase_order_link/models/stock_picking.py
  stock_picking_purchase_order_link/readme/CONTRIBUTORS.rst
  stock_picking_purchase_order_link/readme/DESCRIPTION.rst
  stock_picking_purchase_order_link/readme/USAGE.rst
  stock_picking_purchase_order_link/static/description/icon.png
  stock_picking_purchase_order_link/static/description/index.html
  stock_picking_purchase_order_link/tests/__init__.py
  stock_picking_purchase_order_link/tests/test_stock_picking_purchase_order_link.py
  stock_picking_purchase_order_link/views/stock_picking_view.xml
Labels: approved, ready to merge, bot is merging ⏳
