Repository OCA/stock-logistics-workflow, pull requests merged in 2021-11, with the labels that each got.

#925 [14.0][FW] [13.0][FIX] stock_picking_group_by_partner_by_carrier_by_date: group moves same day different time
  stock_picking_group_by_partner_by_carrier_by_date/models/stock_move.py
  stock_picking_group_by_partner_by_carrier_by_date/tests/test_grouping_by_date.py
Labels: bug, bot is merging ⏳

#924 [14.0] Add hooks on stock_picking_group_by_partner_by_carrier
  stock_picking_group_by_partner_by_carrier/report/report_delivery_slip.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#920 [15.0][MIG] stock_split_picking
  setup/stock_split_picking/odoo/addons/stock_split_picking
  setup/stock_split_picking/setup.py
  stock_split_picking/README.rst
  stock_split_picking/__init__.py
  stock_split_picking/__manifest__.py
  stock_split_picking/i18n/ar.po
  stock_split_picking/i18n/ca_ES.po
  stock_split_picking/i18n/de.po
  stock_split_picking/i18n/es.po
  stock_split_picking/i18n/es_MX.po
  stock_split_picking/i18n/fi.po
  stock_split_picking/i18n/fr.po
  stock_split_picking/i18n/hr.po
  stock_split_picking/i18n/it.po
  stock_split_picking/i18n/nl_NL.po
  stock_split_picking/i18n/pt.po
  stock_split_picking/i18n/pt_BR.po
  stock_split_picking/i18n/sl.po
  stock_split_picking/i18n/stock_split_picking.pot
  stock_split_picking/i18n/tr.po
  stock_split_picking/i18n/tr_TR.po
  stock_split_picking/i18n/zh_CN.po
  stock_split_picking/models/__init__.py
  stock_split_picking/models/stock_picking.py
  stock_split_picking/readme/CONTRIBUTORS.rst
  stock_split_picking/readme/DESCRIPTION.rst
  stock_split_picking/readme/USAGE.rst
  stock_split_picking/security/ir.model.access.csv
  stock_split_picking/static/description/icon.png
  stock_split_picking/static/description/index.html
  stock_split_picking/tests/__init__.py
  stock_split_picking/tests/test_stock_split_picking.py
  stock_split_picking/views/stock_partial_picking.xml
  stock_split_picking/wizards/__init__.py
  stock_split_picking/wizards/stock_split_picking.py
  stock_split_picking/wizards/stock_split_picking.xml
Labels: approved, bot is merging ⏳

#927 [14.0][MIG] stock_push_delay
  setup/stock_push_delay/odoo/addons/stock_push_delay
  setup/stock_push_delay/setup.py
  stock_push_delay/README.rst
  stock_push_delay/__init__.py
  stock_push_delay/__manifest__.py
  stock_push_delay/i18n/stock_push_delay.pot
  stock_push_delay/models/__init__.py
  stock_push_delay/models/stock_move.py
  stock_push_delay/models/stock_picking.py
  stock_push_delay/readme/CONTRIBUTORS.rst
  stock_push_delay/readme/DESCRIPTION.rst
  stock_push_delay/readme/USAGE.rst
  stock_push_delay/static/description/icon.png
  stock_push_delay/static/description/index.html
  stock_push_delay/tests/__init__.py
  stock_push_delay/tests/test_stock_push_delay.py
Labels: approved, ready to merge, bot is merging ⏳

#933 [15.0][MIG] stock_picking_show_return
  setup/stock_picking_show_return/odoo/addons/stock_picking_show_return
  setup/stock_picking_show_return/setup.py
  stock_picking_show_return/README.rst
  stock_picking_show_return/__init__.py
  stock_picking_show_return/__manifest__.py
  stock_picking_show_return/i18n/de.po
  stock_picking_show_return/i18n/es.po
  stock_picking_show_return/i18n/fr.po
  stock_picking_show_return/i18n/it.po
  stock_picking_show_return/i18n/nl_NL.po
  stock_picking_show_return/i18n/pt.po
  stock_picking_show_return/i18n/pt_BR.po
  stock_picking_show_return/i18n/sl.po
  stock_picking_show_return/i18n/stock_picking_show_return.pot
  stock_picking_show_return/i18n/zh_CN.po
  stock_picking_show_return/models/__init__.py
  stock_picking_show_return/models/stock_picking.py
  stock_picking_show_return/readme/CONTRIBUTORS.rst
  stock_picking_show_return/readme/DESCRIPTION.rst
  stock_picking_show_return/readme/HISTORY.rst
  stock_picking_show_return/readme/USAGE.rst
  stock_picking_show_return/static/description/icon.png
  stock_picking_show_return/static/description/index.html
  stock_picking_show_return/tests/__init__.py
  stock_picking_show_return/tests/test_stock_picking_show_return.py
  stock_picking_show_return/views/stock_picking_view.xml
Labels: approved, bot is merging ⏳

#932 [15.0][MIG] stock_push_delay
  setup/stock_push_delay/odoo/addons/stock_push_delay
  setup/stock_push_delay/setup.py
  stock_push_delay/README.rst
  stock_push_delay/__init__.py
  stock_push_delay/__manifest__.py
  stock_push_delay/i18n/stock_push_delay.pot
  stock_push_delay/models/__init__.py
  stock_push_delay/models/stock_move.py
  stock_push_delay/models/stock_picking.py
  stock_push_delay/readme/CONTRIBUTORS.rst
  stock_push_delay/readme/DESCRIPTION.rst
  stock_push_delay/readme/USAGE.rst
  stock_push_delay/static/description/icon.png
  stock_push_delay/static/description/index.html
  stock_push_delay/tests/__init__.py
  stock_push_delay/tests/test_stock_push_delay.py
Labels: approved, bot is merging ⏳

#931 [14.0][FW] sale_stock_mto_as_mts_orderpoint: port #707 from 13.0
  sale_stock_mto_as_mts_orderpoint/models/sale_order.py
  sale_stock_mto_as_mts_orderpoint/tests/test_sale_stock_mto_as_mts_orderpoint.py
Labels: approved, bot is merging ⏳
