Repository OCA/stock-logistics-workflow, pull requests merged in 2021-04, with the labels that each got.

#822 [13.0][IMP] stock_partner_delivery_window: time format improvements
  stock_partner_delivery_window/models/res_partner.py
Labels: approved, bot is merging ⏳

#779 [13.0][FIX] stock_picking_group_by_partner_by_carrier
  stock_picking_group_by_partner_by_carrier/models/sale_order.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#823 FIX stock_shifting_: prevent to use a bad domain when multiple lots
  stock_shifting_end_of_lot/models/stock_picking.py
  stock_shifting_end_of_lot/readme/CONFIGURE.rst
  stock_shifting_end_of_lot/readme/DESCRIPTION.rst
Labels: approved, bot is merging ⏳

#798 14.0 mig stock picking back2draft
  setup/stock_picking_back2draft/odoo/addons/stock_picking_back2draft
  setup/stock_picking_back2draft/setup.py
  stock_picking_back2draft/README.rst
  stock_picking_back2draft/__init__.py
  stock_picking_back2draft/__manifest__.py
  stock_picking_back2draft/i18n/ca.po
  stock_picking_back2draft/i18n/de.po
  stock_picking_back2draft/i18n/es.po
  stock_picking_back2draft/i18n/es_AR.po
  stock_picking_back2draft/i18n/es_MX.po
  stock_picking_back2draft/i18n/fi.po
  stock_picking_back2draft/i18n/fr.po
  stock_picking_back2draft/i18n/hr.po
  stock_picking_back2draft/i18n/it.po
  stock_picking_back2draft/i18n/pt.po
  stock_picking_back2draft/i18n/pt_BR.po
  stock_picking_back2draft/i18n/sl.po
  stock_picking_back2draft/i18n/stock_picking_back2draft.pot
  stock_picking_back2draft/i18n/tr.po
  stock_picking_back2draft/i18n/tr_TR.po
  stock_picking_back2draft/i18n/zh_CN.po
  stock_picking_back2draft/models/__init__.py
  stock_picking_back2draft/models/stock_move.py
  stock_picking_back2draft/models/stock_picking.py
  stock_picking_back2draft/readme/CONTRIBUTORS.rst
  stock_picking_back2draft/readme/DESCRIPTION.rst
  stock_picking_back2draft/readme/USAGE.rst
  stock_picking_back2draft/static/description/icon.png
  stock_picking_back2draft/static/description/index.html
  stock_picking_back2draft/tests/__init__.py
  stock_picking_back2draft/tests/test_picking.py
  stock_picking_back2draft/views/picking_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#824 stock_partner_delivery_window: ease warning msg check/override
  stock_partner_delivery_window/models/stock_picking.py
Labels: approved, bot is merging ⏳

#826 delivery_total_weight_from_packaging: fix shipping_weight
  delivery_total_weight_from_packaging/models/stock_quant_package.py
Labels: bot is merging ⏳

#771 [14.0][MIG] stock_quant_package_product_packaging
  setup/stock_quant_package_product_packaging/odoo/addons/stock_quant_package_product_packaging
  setup/stock_quant_package_product_packaging/setup.py
  stock_quant_package_product_packaging/README.rst
  stock_quant_package_product_packaging/__init__.py
  stock_quant_package_product_packaging/__manifest__.py
  stock_quant_package_product_packaging/i18n/stock_quant_package_product_packaging.pot
  stock_quant_package_product_packaging/models/__init__.py
  stock_quant_package_product_packaging/models/stock_move_line.py
  stock_quant_package_product_packaging/models/stock_quant_package.py
  stock_quant_package_product_packaging/readme/CONTRIBUTORS.rst
  stock_quant_package_product_packaging/readme/DESCRIPTION.rst
  stock_quant_package_product_packaging/static/description/icon.png
  stock_quant_package_product_packaging/static/description/index.html
  stock_quant_package_product_packaging/tests/__init__.py
  stock_quant_package_product_packaging/tests/test_stock_quant_package_product_packaging.py
  stock_quant_package_product_packaging/views/stock_quant_package.xml
Labels: approved, bot is merging ⏳, migration, needs review

#829 [13.0][IMP] stock_picking_batch_extended: Add kanban view in batch action for small screens and minor improvements.
  stock_picking_batch_extended/data/batch_picking_actions_server.xml
  stock_picking_batch_extended/views/stock_batch_picking.xml
Labels: approved, bot is merging ⏳

#796 [MIG] stock_move_assign_picking_hook: Migration to 14.0
  setup/stock_move_assign_picking_hook/odoo/addons/stock_move_assign_picking_hook
  setup/stock_move_assign_picking_hook/setup.py
  stock_move_assign_picking_hook/README.rst
  stock_move_assign_picking_hook/__init__.py
  stock_move_assign_picking_hook/__manifest__.py
  stock_move_assign_picking_hook/i18n/stock_move_assign_picking_hook.pot
  stock_move_assign_picking_hook/models/__init__.py
  stock_move_assign_picking_hook/models/stock_move.py
  stock_move_assign_picking_hook/readme/CONTRIBUTORS.rst
  stock_move_assign_picking_hook/readme/CREDITS.rst
  stock_move_assign_picking_hook/readme/DESCRIPTION.rst
  stock_move_assign_picking_hook/readme/USAGE.rst
  stock_move_assign_picking_hook/static/description/icon.png
  stock_move_assign_picking_hook/static/description/index.html
Labels: approved, bot is merging ⏳, migration, needs review
