Repository OCA/stock-logistics-workflow, pull requests merged in 2021-05, with the labels that each got.

#768 [14.0][MIG] stock_picking_line_sequence
  stock_picking_line_sequence/README.rst
  stock_picking_line_sequence/__init__.py
  stock_picking_line_sequence/__manifest__.py
  stock_picking_line_sequence/i18n/ca.po
  stock_picking_line_sequence/i18n/de.po
  stock_picking_line_sequence/i18n/es.po
  stock_picking_line_sequence/i18n/es_MX.po
  stock_picking_line_sequence/i18n/fi.po
  stock_picking_line_sequence/i18n/fr.po
  stock_picking_line_sequence/i18n/hr.po
  stock_picking_line_sequence/i18n/it.po
  stock_picking_line_sequence/i18n/nl_NL.po
  stock_picking_line_sequence/i18n/pt.po
  stock_picking_line_sequence/i18n/pt_BR.po
  stock_picking_line_sequence/i18n/sl.po
  stock_picking_line_sequence/i18n/stock_picking_line_sequence.pot
  stock_picking_line_sequence/i18n/tr.po
  stock_picking_line_sequence/i18n/tr_TR.po
  stock_picking_line_sequence/init_hooks.py
  stock_picking_line_sequence/models/__init__.py
  stock_picking_line_sequence/models/stock.py
  stock_picking_line_sequence/readme/CONTRIBUTORS.rst
  stock_picking_line_sequence/readme/DESCRIPTION.rst
  stock_picking_line_sequence/readme/USAGE.rst
  stock_picking_line_sequence/report/report_deliveryslip.xml
  stock_picking_line_sequence/static/description/icon.png
  stock_picking_line_sequence/static/description/index.html
  stock_picking_line_sequence/tests/__init__.py
  stock_picking_line_sequence/tests/test_move_lines_sequence.py
  stock_picking_line_sequence/views/stock_view.xml
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#614 [13.0][MIG] stock_landed_costs_currency
  .isort.cfg
  setup/stock_landed_costs_currency/odoo/addons/stock_landed_costs_currency
  setup/stock_landed_costs_currency/setup.py
  stock_landed_costs_currency/README.rst
  stock_landed_costs_currency/__init__.py
  stock_landed_costs_currency/__manifest__.py
  stock_landed_costs_currency/i18n/stock_landed_costs_currency.pot
  stock_landed_costs_currency/models/__init__.py
  stock_landed_costs_currency/models/stock_landed_cost.py
  stock_landed_costs_currency/models/stock_landed_cost_lines.py
  stock_landed_costs_currency/readme/CONFIGURE.rst
  stock_landed_costs_currency/readme/CONTRIBUTORS.rst
  stock_landed_costs_currency/readme/DESCRIPTION.rst
  stock_landed_costs_currency/readme/USAGE.rst
  stock_landed_costs_currency/static/description/icon.png
  stock_landed_costs_currency/static/description/index.html
  stock_landed_costs_currency/tests/__init__.py
  stock_landed_costs_currency/tests/test_stock_landed_costs_currency.py
  stock_landed_costs_currency/views/stock_landed_cost_views.xml
  stock_lot_scrap/models/stock_production_lot.py
  stock_partner_delivery_window/tests/test_delivery_window.py
  stock_picking_group_by_partner_by_carrier_by_date/tests/test_grouping_by_date.py
  stock_putaway_hook/models/stock_putaway_rule.py
  stock_return_request/tests/test_stock_return_request_common.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#643 [12.0] NEW stock_picking_filter_product:
  stock_picking_filter_product/README.rst
  stock_picking_filter_product/__init__.py
  stock_picking_filter_product/__manifest__.py
  stock_picking_filter_product/models/__init__.py
  stock_picking_filter_product/models/product_product.py
  stock_picking_filter_product/readme/CONTRIBUTORS.rst
  stock_picking_filter_product/readme/DESCRIPTION.rst
  stock_picking_filter_product/readme/USAGE.rst
  stock_picking_filter_product/static/description/index.html
  stock_picking_filter_product/views/stock_picking_view.xml
  stock_picking_filter_product/views/stock_scrap_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#724 [13.0][MIG]stock_push_delay
  setup/stock_push_delay/odoo/addons/stock_push_delay
  setup/stock_push_delay/setup.py
  stock_push_delay/README.rst
  stock_push_delay/__init__.py
  stock_push_delay/__manifest__.py
  stock_push_delay/i18n/stock_push_delay.pot
  stock_push_delay/models/__init__.py
  stock_push_delay/models/stock_move.py
  stock_push_delay/models/stock_picking.py
  stock_push_delay/readme/CONTRIBUTORS.rst
  stock_push_delay/readme/DESCRIPTION.rst
  stock_push_delay/readme/USAGE.rst
  stock_push_delay/static/description/icon.png
  stock_push_delay/static/description/index.html
  stock_push_delay/tests/__init__.py
  stock_push_delay/tests/test_stock_push_delay.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#837 [13.0][FIX] s_p_g_by_partner_by_carrier: remaining to deliver
  stock_picking_group_by_partner_by_carrier/models/stock_picking.py
  stock_picking_group_by_partner_by_carrier/report/report_delivery_slip.py
  stock_picking_group_by_partner_by_carrier/tests/test_report.py
Labels: approved, bot is merging ⏳, ready to merge

#763 [14.0][MIG] stock_move_line_auto_fill
  setup/stock_move_line_auto_fill/odoo/addons/stock_move_line_auto_fill
  setup/stock_move_line_auto_fill/setup.py
  stock_move_line_auto_fill/README.rst
  stock_move_line_auto_fill/__init__.py
  stock_move_line_auto_fill/__manifest__.py
  stock_move_line_auto_fill/i18n/cs_CZ.po
  stock_move_line_auto_fill/i18n/de.po
  stock_move_line_auto_fill/i18n/es.po
  stock_move_line_auto_fill/i18n/fr.po
  stock_move_line_auto_fill/i18n/it.po
  stock_move_line_auto_fill/i18n/nl_NL.po
  stock_move_line_auto_fill/i18n/pt.po
  stock_move_line_auto_fill/i18n/pt_BR.po
  stock_move_line_auto_fill/i18n/stock_move_line_auto_fill.pot
  stock_move_line_auto_fill/i18n/zh_CN.po
  stock_move_line_auto_fill/models/__init__.py
  stock_move_line_auto_fill/models/stock_move.py
  stock_move_line_auto_fill/models/stock_picking.py
  stock_move_line_auto_fill/models/stock_picking_type.py
  stock_move_line_auto_fill/readme/CONFIGURE.rst
  stock_move_line_auto_fill/readme/CONTRIBUTORS.rst
  stock_move_line_auto_fill/readme/DESCRIPTION.rst
  stock_move_line_auto_fill/readme/USAGE.rst
  stock_move_line_auto_fill/static/description/icon.png
  stock_move_line_auto_fill/static/description/index.html
  stock_move_line_auto_fill/tests/__init__.py
  stock_move_line_auto_fill/tests/test_stock_picking_auto_fill.py
  stock_move_line_auto_fill/views/stock_picking.xml
  stock_move_line_auto_fill/views/stock_picking_type_views.xml
Labels: approved, bot is merging ⏳, migration, needs review

#834 [13.0][IMP] s_p_g_by_partner_by_carrier: disable grouping on partner
  stock_picking_group_by_partner_by_carrier/__manifest__.py
  stock_picking_group_by_partner_by_carrier/models/__init__.py
  stock_picking_group_by_partner_by_carrier/models/res_partner.py
  stock_picking_group_by_partner_by_carrier/models/stock_move.py
  stock_picking_group_by_partner_by_carrier/models/stock_picking.py
  stock_picking_group_by_partner_by_carrier/tests/__init__.py
  stock_picking_group_by_partner_by_carrier/tests/test_grouping_disable_on_partner.py
  stock_picking_group_by_partner_by_carrier/views/res_partner.xml
Labels: approved, bot is merging ⏳, ready to merge

#842 [14.0][MIG] stock_picking_filter_lot
  setup/stock_picking_filter_lot/odoo/addons/stock_picking_filter_lot
  setup/stock_picking_filter_lot/setup.py
  stock_picking_filter_lot/README.rst
  stock_picking_filter_lot/__init__.py
  stock_picking_filter_lot/__manifest__.py
  stock_picking_filter_lot/i18n/it.po
  stock_picking_filter_lot/i18n/stock_picking_filter_lot.pot
  stock_picking_filter_lot/models/__init__.py
  stock_picking_filter_lot/models/stock_production_lot.py
  stock_picking_filter_lot/readme/CONTRIBUTORS.rst
  stock_picking_filter_lot/readme/DESCRIPTION.rst
  stock_picking_filter_lot/readme/USAGE.rst
  stock_picking_filter_lot/static/description/icon.png
  stock_picking_filter_lot/static/description/index.html
  stock_picking_filter_lot/views/stock_move_line_view.xml
  stock_picking_filter_lot/views/stock_scrap_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#839 [14.0][IMP] stock_valuation_layer_by_category
  setup/stock_valuation_layer_by_category/odoo/addons/stock_valuation_layer_by_category
  setup/stock_valuation_layer_by_category/setup.py
  stock_valuation_layer_by_category/README.rst
  stock_valuation_layer_by_category/__init__.py
  stock_valuation_layer_by_category/__manifest__.py
  stock_valuation_layer_by_category/models/__init__.py
  stock_valuation_layer_by_category/models/stock_valuation_layer.py
  stock_valuation_layer_by_category/readme/CONTRIBUTORS.rst
  stock_valuation_layer_by_category/readme/DESCRIPTION.rst
  stock_valuation_layer_by_category/views/stock_valuation_layer.xml
Labels: approved, bot is merging ⏳, ready to merge

#843 [12.0][IMP] stock_picking_package_preparation xmlrpc compatibility
  stock_picking_package_preparation/models/stock_picking_package_preparation.py
Labels: approved, bot is merging ⏳, enhancement

#845 [13.0] [MIG] stock_picking_operation_quick_change: Migration to v13.0
  setup/stock_picking_operation_quick_change/odoo/addons/stock_picking_operation_quick_change
  setup/stock_picking_operation_quick_change/setup.py
  stock_picking_operation_quick_change/README.rst
  stock_picking_operation_quick_change/__init__.py
  stock_picking_operation_quick_change/__manifest__.py
  stock_picking_operation_quick_change/i18n/de.po
  stock_picking_operation_quick_change/i18n/es.po
  stock_picking_operation_quick_change/i18n/fr.po
  stock_picking_operation_quick_change/i18n/it.po
  stock_picking_operation_quick_change/i18n/pt_BR.po
  stock_picking_operation_quick_change/i18n/sl.po
  stock_picking_operation_quick_change/i18n/stock_picking_operation_quick_change.pot
  stock_picking_operation_quick_change/readme/CONTRIBUTORS.rst
  stock_picking_operation_quick_change/readme/DESCRIPTION.rst
  stock_picking_operation_quick_change/readme/USAGE.rst
  stock_picking_operation_quick_change/static/description/icon.png
  stock_picking_operation_quick_change/static/description/icon.svg
  stock_picking_operation_quick_change/static/description/index.html
  stock_picking_operation_quick_change/tests/__init__.py
  stock_picking_operation_quick_change/tests/test_stock_picking_operation_quick_change.py
  stock_picking_operation_quick_change/views/stock_picking_view.xml
  stock_picking_operation_quick_change/wizards/__init__.py
  stock_picking_operation_quick_change/wizards/stock_picking_wizard.py
  stock_picking_operation_quick_change/wizards/stock_picking_wizard_view.xml
Labels: approved, bot is merging ⏳, migration, needs review
