Repository OCA/stock-logistics-workflow, pull requests merged in 2021-06, with the labels that each got.

#838 [13.0][IMP] s_p_g_by_partner_by_carrier: Add hook on delivery report
  stock_picking_group_by_partner_by_carrier/models/stock_picking.py
Labels: approved, bot is merging ⏳

#850 [14.0][MIG] - stock_delivery_note
  setup/stock_delivery_note/odoo/addons/stock_delivery_note
  setup/stock_delivery_note/setup.py
  stock_delivery_note/README.rst
  stock_delivery_note/__init__.py
  stock_delivery_note/__manifest__.py
  stock_delivery_note/i18n/stock_delivery_note.pot
  stock_delivery_note/models/__init__.py
  stock_delivery_note/models/stock_picking.py
  stock_delivery_note/readme/CONTRIBUTORS.rst
  stock_delivery_note/readme/DESCRIPTION.rst
  stock_delivery_note/readme/USAGE.rst
  stock_delivery_note/reports/report_picking.xml
  stock_delivery_note/static/description/icon.png
  stock_delivery_note/static/description/index.html
  stock_delivery_note/views/stock_picking.xml
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#830 13.0 stock_partner_delivery_window: Handle working days
  stock_partner_delivery_window/README.rst
  stock_partner_delivery_window/models/res_partner.py
  stock_partner_delivery_window/models/stock_picking.py
  stock_partner_delivery_window/readme/CONFIGURE.rst
  stock_partner_delivery_window/readme/CONTRIBUTORS.rst
  stock_partner_delivery_window/static/description/index.html
  stock_partner_delivery_window/tests/test_delivery_window.py
Labels: approved, bot is merging ⏳, ready to merge

#707 [FIX] sale_stock_mto_as_mts_orderpoint: support product set
  sale_stock_mto_as_mts_orderpoint/models/sale_order.py
  sale_stock_mto_as_mts_orderpoint/tests/test_sale_stock_mto_as_mts_orderpoint.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#770 [14.0][MIG] stock_quant_package_dimension
  setup/stock_quant_package_dimension/odoo/addons/stock_quant_package_dimension
  setup/stock_quant_package_dimension/setup.py
  stock_quant_package_dimension/README.rst
  stock_quant_package_dimension/__init__.py
  stock_quant_package_dimension/__manifest__.py
  stock_quant_package_dimension/i18n/stock_quant_package_dimension.pot
  stock_quant_package_dimension/models/__init__.py
  stock_quant_package_dimension/models/stock_quant_package.py
  stock_quant_package_dimension/readme/CONTRIBUTORS.rst
  stock_quant_package_dimension/readme/DESCRIPTION.rst
  stock_quant_package_dimension/static/description/icon.png
  stock_quant_package_dimension/static/description/index.html
  stock_quant_package_dimension/tests/__init__.py
  stock_quant_package_dimension/tests/test_package_dimension.py
  stock_quant_package_dimension/views/stock_quant_package.xml
Labels: approved, bot is merging ⏳, migration, needs review

#858 [13.0][IMP] stock_split_picking: allow splitting pickings waiting for other operations
  stock_split_picking/views/stock_partial_picking.xml
Labels: approved, bot is merging ⏳

#862 [13.0] stock_partner_delivery_window:: Fix default value on delivery_time_preference
  stock_partner_delivery_window/models/res_partner.py
Labels: bot is merging ⏳
