Repository OCA/stock-logistics-workflow, pull requests merged in 2022-03, with the labels that each got.

#974 [13.0][MIG] stock_picking_batch_extended_account: Migration to 13.0
  setup/stock_picking_batch_extended_account/odoo/addons/stock_picking_batch_extended_account
  setup/stock_picking_batch_extended_account/setup.py
  stock_picking_batch_extended_account/README.rst
  stock_picking_batch_extended_account/__init__.py
  stock_picking_batch_extended_account/__manifest__.py
  stock_picking_batch_extended_account/i18n/stock_picking_batch_extended_account.pot
  stock_picking_batch_extended_account/models/__init__.py
  stock_picking_batch_extended_account/models/res_partner.py
  stock_picking_batch_extended_account/models/stock_batch_picking.py
  stock_picking_batch_extended_account/models/stock_picking.py
  stock_picking_batch_extended_account/readme/CONFIGURE.rst
  stock_picking_batch_extended_account/readme/CONTRIBUTORS.rst
  stock_picking_batch_extended_account/readme/DESCRIPTION.rst
  stock_picking_batch_extended_account/readme/USAGE.rst
  stock_picking_batch_extended_account/static/description/icon.png
  stock_picking_batch_extended_account/static/description/index.html
  stock_picking_batch_extended_account/views/res_partner_views.xml
  stock_picking_batch_extended_account/views/stock_batch_picking.xml
Labels: approved, bot is merging ⏳

#975 [14.0] stock_picking_group_by_partner_by_carrier: deliveryslip report - fix SO sections
  stock_picking_group_by_partner_by_carrier/report/report_delivery_slip.xml
Labels: bug, approved, bot is merging ⏳

#976 [MIG] stock_production_lot_active: Migration to 15.0
  setup/stock_production_lot_active/odoo/addons/stock_production_lot_active
  setup/stock_production_lot_active/setup.py
  stock_production_lot_active/README.rst
  stock_production_lot_active/__init__.py
  stock_production_lot_active/__manifest__.py
  stock_production_lot_active/i18n/stock_production_lot_active.pot
  stock_production_lot_active/models/__init__.py
  stock_production_lot_active/models/stock_production_lot.py
  stock_production_lot_active/readme/CONTRIBUTORS.rst
  stock_production_lot_active/readme/DESCRIPTION.rst
  stock_production_lot_active/static/description/icon.png
  stock_production_lot_active/static/description/index.html
  stock_production_lot_active/views/stock_production_lot.xml
Labels: needs review, approved, migration, bot is merging ⏳

#977 [15.0][MIG] stock_picking_back2draft: Migration to 15.0
  setup/stock_picking_back2draft/odoo/addons/stock_picking_back2draft
  setup/stock_picking_back2draft/setup.py
  stock_picking_back2draft/README.rst
  stock_picking_back2draft/__init__.py
  stock_picking_back2draft/__manifest__.py
  stock_picking_back2draft/i18n/ca.po
  stock_picking_back2draft/i18n/de.po
  stock_picking_back2draft/i18n/es.po
  stock_picking_back2draft/i18n/es_AR.po
  stock_picking_back2draft/i18n/es_MX.po
  stock_picking_back2draft/i18n/fi.po
  stock_picking_back2draft/i18n/fr.po
  stock_picking_back2draft/i18n/hr.po
  stock_picking_back2draft/i18n/it.po
  stock_picking_back2draft/i18n/pt.po
  stock_picking_back2draft/i18n/pt_BR.po
  stock_picking_back2draft/i18n/sl.po
  stock_picking_back2draft/i18n/stock_picking_back2draft.pot
  stock_picking_back2draft/i18n/tr.po
  stock_picking_back2draft/i18n/tr_TR.po
  stock_picking_back2draft/i18n/zh_CN.po
  stock_picking_back2draft/models/__init__.py
  stock_picking_back2draft/models/stock_move.py
  stock_picking_back2draft/models/stock_picking.py
  stock_picking_back2draft/readme/CONTRIBUTORS.rst
  stock_picking_back2draft/readme/DESCRIPTION.rst
  stock_picking_back2draft/readme/USAGE.rst
  stock_picking_back2draft/static/description/icon.png
  stock_picking_back2draft/static/description/index.html
  stock_picking_back2draft/tests/__init__.py
  stock_picking_back2draft/tests/test_picking.py
  stock_picking_back2draft/views/picking_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#943 [14.0] [MIG] stock_picking_batch_extended: Migrate to version 14.0
  setup/stock_picking_batch_extended/odoo/addons/stock_picking_batch_extended
  setup/stock_picking_batch_extended/setup.py
  stock_picking_batch_extended/README.rst
  stock_picking_batch_extended/__init__.py
  stock_picking_batch_extended/__manifest__.py
  stock_picking_batch_extended/data/batch_picking_actions_server.xml
  stock_picking_batch_extended/data/stock_batch_picking_sequence.xml
  stock_picking_batch_extended/hooks.py
  stock_picking_batch_extended/i18n/de.po
  stock_picking_batch_extended/i18n/es.po
  stock_picking_batch_extended/i18n/es_CL.po
  stock_picking_batch_extended/i18n/fr.po
  stock_picking_batch_extended/i18n/it.po
  stock_picking_batch_extended/i18n/pt_BR.po
  stock_picking_batch_extended/i18n/sl.po
  stock_picking_batch_extended/i18n/stock_picking_batch_extended.pot
  stock_picking_batch_extended/models/__init__.py
  stock_picking_batch_extended/models/product_product.py
  stock_picking_batch_extended/models/res_config_settings.py
  stock_picking_batch_extended/models/stock_batch_picking.py
  stock_picking_batch_extended/models/stock_picking.py
  stock_picking_batch_extended/models/stock_warehouse.py
  stock_picking_batch_extended/readme/CONTRIBUTORS.rst
  stock_picking_batch_extended/readme/CREDITS.rst
  stock_picking_batch_extended/readme/DESCRIPTION.rst
  stock_picking_batch_extended/report/__init__.py
  stock_picking_batch_extended/report/batch_report.py
  stock_picking_batch_extended/security/ir.model.access.csv
  stock_picking_batch_extended/static/batch_form.png
  stock_picking_batch_extended/static/batch_form_operation.png
  stock_picking_batch_extended/static/batch_wizard.png
  stock_picking_batch_extended/static/description/icon.png
  stock_picking_batch_extended/static/description/index.html
  stock_picking_batch_extended/static/stock_picking_list.png
  stock_picking_batch_extended/tests/__init__.py
  stock_picking_batch_extended/tests/test_batch.py
  stock_picking_batch_extended/views/product_product.xml
  stock_picking_batch_extended/views/report_batch_picking.xml
  stock_picking_batch_extended/views/res_config_settings_views.xml
  stock_picking_batch_extended/views/stock_batch_picking.xml
  stock_picking_batch_extended/views/stock_picking.xml
  stock_picking_batch_extended/views/stock_warehouse.xml
  stock_picking_batch_extended/wizard/__init__.py
  stock_picking_batch_extended/wizard/batch_picking_creator.py
  stock_picking_batch_extended/wizard/batch_picking_creator_view.xml
Labels: approved, migration, ready to merge, bot is merging ⏳
