Repository OCA/stock-logistics-workflow, pull requests merged in 2022-08, with the labels that each got.

#1051 [15.0] [MIG] stock_picking_return_restricted_qty: Migration to 15.0
  setup/stock_picking_return_restricted_qty/odoo/addons/stock_picking_return_restricted_qty
  setup/stock_picking_return_restricted_qty/setup.py
  stock_picking_return_restricted_qty/README.rst
  stock_picking_return_restricted_qty/__init__.py
  stock_picking_return_restricted_qty/__manifest__.py
  stock_picking_return_restricted_qty/i18n/es.po
  stock_picking_return_restricted_qty/i18n/stock_picking_return_restricted_qty.pot
  stock_picking_return_restricted_qty/i18n/zh_CN.po
  stock_picking_return_restricted_qty/readme/CONTRIBUTORS.rst
  stock_picking_return_restricted_qty/readme/DESCRIPTION.rst
  stock_picking_return_restricted_qty/readme/USAGE.rst
  stock_picking_return_restricted_qty/static/description/icon.png
  stock_picking_return_restricted_qty/static/description/index.html
  stock_picking_return_restricted_qty/tests/__init__.py
  stock_picking_return_restricted_qty/tests/test_stock_picking_return_restricted_qty.py
  stock_picking_return_restricted_qty/wizard/__init__.py
  stock_picking_return_restricted_qty/wizard/stock_picking_return.py
Labels: approved, bot is merging ⏳

#1055 [13.0][IMP] stock_landed_costs_security: restrict actions
  stock_landed_costs_security/views/stock_landed_costs_view.xml
Labels: approved, bot is merging ⏳

#1042 [14.0][ADD] Add stock_scheduler_assignation_horizon module
  requirements.txt
  setup/stock_scheduler_assignation_horizon/odoo/addons/stock_scheduler_assignation_horizon
  setup/stock_scheduler_assignation_horizon/setup.py
  stock_scheduler_assignation_horizon/__init__.py
  stock_scheduler_assignation_horizon/__manifest__.py
  stock_scheduler_assignation_horizon/models/__init__.py
  stock_scheduler_assignation_horizon/models/procurement_group.py
  stock_scheduler_assignation_horizon/models/res_company.py
  stock_scheduler_assignation_horizon/models/res_config_settings.py
  stock_scheduler_assignation_horizon/readme/CONTRIBUTORS.rst
  stock_scheduler_assignation_horizon/readme/DESCRIPTION.rst
  stock_scheduler_assignation_horizon/readme/ROADMAP.rst
  stock_scheduler_assignation_horizon/readme/USAGE.rst
  stock_scheduler_assignation_horizon/tests/__init__.py
  stock_scheduler_assignation_horizon/tests/test_res_config_settings.py
  stock_scheduler_assignation_horizon/tests/test_res_config_settings_common.py
  stock_scheduler_assignation_horizon/views/res_config_settings_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#986 Updated from template - Switch to Github actions
  .copier-answers.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
  delivery_total_weight_from_packaging/README.rst
  delivery_total_weight_from_packaging/__manifest__.py
  delivery_total_weight_from_packaging/models/stock_move.py
  delivery_total_weight_from_packaging/models/stock_picking.py
  delivery_total_weight_from_packaging/models/stock_quant_package.py
  delivery_total_weight_from_packaging/static/description/index.html
  delivery_total_weight_from_packaging/tests/common.py
  delivery_total_weight_from_packaging/tests/test_choose_delivery_package.py
  delivery_total_weight_from_packaging/tests/test_weight_from_packaging.py
  delivery_total_weight_from_packaging/wizard/choose_delivery_package.py
  stock_partner_delivery_window/__manifest__.py
  stock_picking_group_by_partner_by_carrier/__manifest__.py
  stock_quant_package_dimension_total_weight_from_packaging/README.rst
  stock_quant_package_dimension_total_weight_from_packaging/readme/CONTRIBUTORS.rst
  stock_quant_package_dimension_total_weight_from_packaging/readme/DESCRIPTION.rst
Labels: enhancement, work in progress, bot is merging ⏳

#1058 [15.0][FW] [14.0][FW] stock_split_picking: Port PR from 13.0 to 14.0
  stock_split_picking/README.rst
  stock_split_picking/readme/USAGE.rst
  stock_split_picking/static/description/index.html
  stock_split_picking/views/stock_partial_picking.xml
Labels: approved, migration, bot is merging ⏳

#1026 [12.0][ADD] stock_picking_responsible
  setup/_metapackage/setup.py
  setup/stock_picking_responsible/odoo/addons/stock_picking_responsible
  setup/stock_picking_responsible/setup.py
  stock_picking_responsible/README.rst
  stock_picking_responsible/__init__.py
  stock_picking_responsible/__manifest__.py
  stock_picking_responsible/i18n/fr_BE.po
  stock_picking_responsible/i18n/stock_picking_responsible.pot
  stock_picking_responsible/migrations/12.0.1.0.1/post-migration.py
  stock_picking_responsible/migrations/12.0.1.0.1/pre-migration.py
  stock_picking_responsible/models/__init__.py
  stock_picking_responsible/models/stock_picking.py
  stock_picking_responsible/readme/CONTRIBUTORS.rst
  stock_picking_responsible/readme/DESCRIPTION.rst
  stock_picking_responsible/static/description/index.html
  stock_picking_responsible/tests/__init__.py
  stock_picking_responsible/tests/test_picking_responsible.py
  stock_picking_responsible/views/stock_picking.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#946 [14.0] [MIG] stock_picking_mass_action: Port PR form 12.0 to 14.0
  stock_picking_mass_action/models/stock_picking.py
  stock_picking_mass_action/tests/test_mass_action.py
  stock_picking_mass_action/wizard/mass_action.py
Labels: approved, ready to merge, bot is merging ⏳

#918 [14.0][ADD] stock_picking_tier_validation
  setup/stock_picking_tier_validation/odoo/addons/stock_picking_tier_validation
  setup/stock_picking_tier_validation/setup.py
  stock_picking_tier_validation/README.rst
  stock_picking_tier_validation/__init__.py
  stock_picking_tier_validation/__manifest__.py
  stock_picking_tier_validation/models/__init__.py
  stock_picking_tier_validation/models/stock_picking.py
  stock_picking_tier_validation/models/tier_definition.py
  stock_picking_tier_validation/readme/CONFIGURE.rst
  stock_picking_tier_validation/readme/CONTRIBUTORS.rst
  stock_picking_tier_validation/readme/DESCRIPTION.rst
  stock_picking_tier_validation/readme/INSTALL.rst
  stock_picking_tier_validation/readme/USAGE.rst
  stock_picking_tier_validation/static/description/icon.png
  stock_picking_tier_validation/static/description/index.html
  stock_picking_tier_validation/tests/__init__.py
  stock_picking_tier_validation/tests/common.py
  stock_picking_tier_validation/tests/test_tier_validation.py
  stock_picking_tier_validation/tests/tier_validation_tester.py
  stock_picking_tier_validation/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳

#750 [13.0][IMP] stock_picking_invoice_link: Better link invoices to stock_moves process
  stock_picking_invoice_link/models/sale_order.py
  stock_picking_invoice_link/tests/test_stock_picking_invoice_link.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1056 [FIX] sale_line_returned_qty_mrp: fix error in init file
  sale_line_returned_qty_mrp/tests/__init__.py
  sale_line_returned_qty_mrp/tests/test_sale_line_returned_qty_mrp.py
Labels: enhancement, needs review, bot is merging ⏳

#1068 [13.0] [IMP] purchase_stock_picking_invoice_link: Use the same technique as in stock_picking_invoice_link
  purchase_stock_picking_invoice_link/README.rst
  purchase_stock_picking_invoice_link/models/__init__.py
  purchase_stock_picking_invoice_link/models/account_move.py
  purchase_stock_picking_invoice_link/models/purchase_order.py
  purchase_stock_picking_invoice_link/models/stock_move.py
  purchase_stock_picking_invoice_link/readme/CONTRIBUTORS.rst
  purchase_stock_picking_invoice_link/static/description/index.html
  purchase_stock_picking_invoice_link/tests/test_purchase_stock_picking_invoice_link.py
  stock_picking_invoice_link/views/account_invoice_view.xml
Labels: approved, bot is merging ⏳

#1073 [13.0][FIX] purchase_stock_picking_invoice_link: Consider DS pickings
  purchase_stock_picking_invoice_link/models/purchase_order.py
Labels: approved, bot is merging ⏳

#1071 [15.0][MIG] stock_picking_auto_create_lot
  setup/stock_picking_auto_create_lot/odoo/addons/stock_picking_auto_create_lot
  setup/stock_picking_auto_create_lot/setup.py
  stock_picking_auto_create_lot/README.rst
  stock_picking_auto_create_lot/__init__.py
  stock_picking_auto_create_lot/__manifest__.py
  stock_picking_auto_create_lot/i18n/es.po
  stock_picking_auto_create_lot/i18n/stock_picking_auto_create_lot.pot
  stock_picking_auto_create_lot/i18n/zh_CN.po
  stock_picking_auto_create_lot/models/__init__.py
  stock_picking_auto_create_lot/models/product.py
  stock_picking_auto_create_lot/models/stock_move.py
  stock_picking_auto_create_lot/models/stock_move_line.py
  stock_picking_auto_create_lot/models/stock_picking.py
  stock_picking_auto_create_lot/models/stock_picking_type.py
  stock_picking_auto_create_lot/readme/CONFIGURE.rst
  stock_picking_auto_create_lot/readme/CONTRIBUTORS.rst
  stock_picking_auto_create_lot/readme/DESCRIPTION.rst
  stock_picking_auto_create_lot/readme/USAGE.rst
  stock_picking_auto_create_lot/static/description/icon.png
  stock_picking_auto_create_lot/static/description/index.html
  stock_picking_auto_create_lot/tests/__init__.py
  stock_picking_auto_create_lot/tests/common.py
  stock_picking_auto_create_lot/tests/test_stock_picking_auto_create_lot.py
  stock_picking_auto_create_lot/views/product_views.xml
  stock_picking_auto_create_lot/views/stock_picking_type_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1076 [13.0][FIX] stock_picking_invoice_link: Consider DS pickings
  stock_picking_invoice_link/models/sale_order.py
Labels: bot is merging ⏳

#1074 [14.0][IMP] stock_picking_invoice_link: Better invoice link
  stock_picking_invoice_link/models/sale_order.py
  stock_picking_invoice_link/tests/test_stock_picking_invoice_link.py
  stock_picking_invoice_link/views/account_invoice_view.xml
Labels: approved, bot is merging ⏳

#1075 [14.0][IMP] purchase_stock_picking_invoice_link: Use the same technique as in stock_picking_invoice_link
  purchase_stock_picking_invoice_link/README.rst
  purchase_stock_picking_invoice_link/models/__init__.py
  purchase_stock_picking_invoice_link/models/account_move.py
  purchase_stock_picking_invoice_link/models/purchase_order.py
  purchase_stock_picking_invoice_link/models/stock_move.py
  purchase_stock_picking_invoice_link/readme/CONTRIBUTORS.rst
  purchase_stock_picking_invoice_link/static/description/index.html
  purchase_stock_picking_invoice_link/tests/test_purchase_stock_picking_invoice_link.py
Labels: approved, bot is merging ⏳

#1052 [13.0][IMP] stock_picking_batch_extended_account: Add some tests. And more inheritable
  stock_picking_batch_extended_account/__manifest__.py
  stock_picking_batch_extended_account/i18n/es.po
  stock_picking_batch_extended_account/i18n/stock_picking_batch_extended_account.pot
  stock_picking_batch_extended_account/migrations/13.0.1.1.0/post-migration.py
  stock_picking_batch_extended_account/models/res_partner.py
  stock_picking_batch_extended_account/models/stock_batch_picking.py
  stock_picking_batch_extended_account/models/stock_picking.py
  stock_picking_batch_extended_account/tests/__init__.py
  stock_picking_batch_extended_account/tests/test_stock_picking_batch_extended_account.py
Labels: approved, bot is merging ⏳
