Repository OCA/stock-logistics-workflow, pull requests merged in 2022-11, with the labels that each got.

#1119 [12.0][ADD] stock_picking_product_link
  setup/stock_picking_product_link/odoo/addons/stock_picking_product_link
  setup/stock_picking_product_link/setup.py
  stock_picking_product_link/README.rst
  stock_picking_product_link/__init__.py
  stock_picking_product_link/__manifest__.py
  stock_picking_product_link/models/__init__.py
  stock_picking_product_link/models/stock_picking.py
  stock_picking_product_link/readme/CONTRIBUTORS.rst
  stock_picking_product_link/readme/CREDITS.rst
  stock_picking_product_link/readme/DESCRIPTION.rst
  stock_picking_product_link/static/description/index.html
  stock_picking_product_link/tests/__init__.py
  stock_picking_product_link/tests/test_stock_picking_product_link.py
  stock_picking_product_link/views/stock_picking_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1104 [MIG] stock_quant_package_dimension: Migration to 16.0
  setup/stock_quant_package_dimension/odoo/addons/stock_quant_package_dimension
  setup/stock_quant_package_dimension/setup.py
  stock_quant_package_dimension/README.rst
  stock_quant_package_dimension/__init__.py
  stock_quant_package_dimension/__manifest__.py
  stock_quant_package_dimension/i18n/stock_quant_package_dimension.pot
  stock_quant_package_dimension/models/__init__.py
  stock_quant_package_dimension/models/stock_quant_package.py
  stock_quant_package_dimension/readme/CONTRIBUTORS.rst
  stock_quant_package_dimension/readme/DESCRIPTION.rst
  stock_quant_package_dimension/static/description/icon.png
  stock_quant_package_dimension/static/description/index.html
  stock_quant_package_dimension/tests/__init__.py
  stock_quant_package_dimension/tests/common.py
  stock_quant_package_dimension/tests/test_package_dimension.py
  stock_quant_package_dimension/views/stock_quant_package.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1122 [14.0][FIX] Update from copier template to fix pre-commit
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
Labels: bug

#1120 [14.0][ADD] stock_picking_product_link
  setup/stock_picking_product_link/odoo/addons/stock_picking_product_link
  setup/stock_picking_product_link/setup.py
  stock_picking_product_link/README.rst
  stock_picking_product_link/__init__.py
  stock_picking_product_link/__manifest__.py
  stock_picking_product_link/models/__init__.py
  stock_picking_product_link/models/stock_picking.py
  stock_picking_product_link/readme/CONTRIBUTORS.rst
  stock_picking_product_link/readme/CREDITS.rst
  stock_picking_product_link/readme/DESCRIPTION.rst
  stock_picking_product_link/static/description/index.html
  stock_picking_product_link/tests/__init__.py
  stock_picking_product_link/tests/test_stock_picking_product_link.py
  stock_picking_product_link/views/stock_picking_views.xml
Labels: approved, migration

#1063 [MIG] stock_picking_import_serial_number: Migration to 14.0
  requirements.txt
  setup/stock_picking_import_serial_number/odoo/addons/stock_picking_import_serial_number
  setup/stock_picking_import_serial_number/setup.py
  stock_picking_import_serial_number/README.rst
  stock_picking_import_serial_number/__init__.py
  stock_picking_import_serial_number/__manifest__.py
  stock_picking_import_serial_number/i18n/es.po
  stock_picking_import_serial_number/i18n/stock_picking_import_serial_number.pot
  stock_picking_import_serial_number/models/__init__.py
  stock_picking_import_serial_number/models/res_config_settings.py
  stock_picking_import_serial_number/readme/CONFIGURE.rst
  stock_picking_import_serial_number/readme/CONTRIBUTORS.rst
  stock_picking_import_serial_number/readme/DESCRIPTION.rst
  stock_picking_import_serial_number/readme/USAGE.rst
  stock_picking_import_serial_number/security/ir.model.access.csv
  stock_picking_import_serial_number/static/description/icon.png
  stock_picking_import_serial_number/static/description/index.html
  stock_picking_import_serial_number/tests/__init__.py
  stock_picking_import_serial_number/tests/common.py
  stock_picking_import_serial_number/tests/test_stock_picking_import_serial_number.py
  stock_picking_import_serial_number/views/res_config_settings_views.xml
  stock_picking_import_serial_number/views/stock_picking.xml
  stock_picking_import_serial_number/wizard/__init__.py
  stock_picking_import_serial_number/wizard/import_serial_number_view.xml
  stock_picking_import_serial_number/wizard/import_serial_number_wizard.py
Labels: migration, bot is merging ⏳

#1032 [15.0][MIG] stock_return_request: Migration to 15.0
  setup/stock_return_request/odoo/addons/stock_return_request
  setup/stock_return_request/setup.py
  stock_return_request/README.rst
  stock_return_request/__init__.py
  stock_return_request/__manifest__.py
  stock_return_request/data/stock_return_request_data.xml
  stock_return_request/hooks.py
  stock_return_request/i18n/es.po
  stock_return_request/i18n/fr.po
  stock_return_request/i18n/pt_BR.po
  stock_return_request/i18n/pt_PT.po
  stock_return_request/i18n/stock_return_request.pot
  stock_return_request/models/__init__.py
  stock_return_request/models/stock_move.py
  stock_return_request/models/stock_picking.py
  stock_return_request/models/stock_return_request.py
  stock_return_request/readme/CONTRIBUTORS.rst
  stock_return_request/readme/DESCRIPTION.rst
  stock_return_request/readme/INSTALL.rst
  stock_return_request/readme/ROADMAP.rst
  stock_return_request/readme/USAGE.rst
  stock_return_request/report/stock_return_report.xml
  stock_return_request/security/ir.model.access.csv
  stock_return_request/static/description/icon.png
  stock_return_request/static/description/index.html
  stock_return_request/tests/__init__.py
  stock_return_request/tests/test_stock_return_request.py
  stock_return_request/tests/test_stock_return_request_common.py
  stock_return_request/views/stock_return_request_views.xml
  stock_return_request/wizard/__init__.py
  stock_return_request/wizard/suggest_return_request.xml
  stock_return_request/wizard/suggest_return_request_lot.py
Labels: needs review, approved, migration, bot is merging ⏳

#1081 [14.0] [MIG] sale_line_returned_qty_mrp
  sale_line_returned_qty_mrp/README.rst
  sale_line_returned_qty_mrp/__init__.py
  sale_line_returned_qty_mrp/__manifest__.py
  sale_line_returned_qty_mrp/i18n/sale_line_returned_qty_mrp.pot
  sale_line_returned_qty_mrp/models/__init__.py
  sale_line_returned_qty_mrp/models/sale_order_line.py
  sale_line_returned_qty_mrp/readme/CONTRIBUTORS.rst
  sale_line_returned_qty_mrp/readme/DESCRIPTION.rst
  sale_line_returned_qty_mrp/static/description/icon.png
  sale_line_returned_qty_mrp/static/description/index.html
  sale_line_returned_qty_mrp/tests/__init__.py
  sale_line_returned_qty_mrp/tests/test_sale_line_returned_qty_mrp.py
  setup/sale_line_returned_qty_mrp/odoo/addons/sale_line_returned_qty_mrp
  setup/sale_line_returned_qty_mrp/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1134 [15.0][FIX] Update copier template + deprecated method
  .copier-answers.yml
  .pre-commit-config.yaml
  stock_return_request/hooks.py
Labels: bot is merging ⏳

#1126 [15.0][MIG] stock_picking_product_availability_inline: Migration to version 15.0
  setup/stock_picking_product_availability_inline/odoo/addons/stock_picking_product_availability_inline
  setup/stock_picking_product_availability_inline/setup.py
  stock_picking_product_availability_inline/README.rst
  stock_picking_product_availability_inline/__init__.py
  stock_picking_product_availability_inline/__manifest__.py
  stock_picking_product_availability_inline/i18n/stock_picking_product_availability_inline.pot
  stock_picking_product_availability_inline/models/__init__.py
  stock_picking_product_availability_inline/models/product_product.py
  stock_picking_product_availability_inline/models/stock_picking.py
  stock_picking_product_availability_inline/readme/CONTRIBUTORS.rst
  stock_picking_product_availability_inline/readme/DESCRIPTION.rst
  stock_picking_product_availability_inline/readme/USAGE.rst
  stock_picking_product_availability_inline/static/description/icon.png
  stock_picking_product_availability_inline/static/description/index.html
  stock_picking_product_availability_inline/tests/__init__.py
  stock_picking_product_availability_inline/tests/test_stock_picking_product_availability_inline.py
  stock_picking_product_availability_inline/views/stock_move_line_views.xml
  stock_picking_product_availability_inline/views/stock_picking_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1113 [16.0] [ADD] stock receipt lot info
  setup/stock_receipt_lot_info/odoo/addons/stock_receipt_lot_info
  setup/stock_receipt_lot_info/setup.py
  stock_receipt_lot_info/README.rst
  stock_receipt_lot_info/__init__.py
  stock_receipt_lot_info/__manifest__.py
  stock_receipt_lot_info/i18n/stock_account_product_run_fifo_hook.pot
  stock_receipt_lot_info/model/__init__.py
  stock_receipt_lot_info/model/stock_move_line.py
  stock_receipt_lot_info/readme/CONTRIBUTORS.rst
  stock_receipt_lot_info/readme/DESCRIPTION.rst
  stock_receipt_lot_info/readme/USAGE.rst
  stock_receipt_lot_info/static/description/icon.png
  stock_receipt_lot_info/static/description/index.html
  stock_receipt_lot_info/tests/__init__.py
  stock_receipt_lot_info/tests/test_receipt_lot_info.py
  stock_receipt_lot_info/views/stock_move_line_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1124 [16.0][MIG] stock_picking_back2draft
  setup/stock_picking_back2draft/odoo/addons/stock_picking_back2draft
  setup/stock_picking_back2draft/setup.py
  stock_picking_back2draft/README.rst
  stock_picking_back2draft/__init__.py
  stock_picking_back2draft/__manifest__.py
  stock_picking_back2draft/i18n/ca.po
  stock_picking_back2draft/i18n/de.po
  stock_picking_back2draft/i18n/es.po
  stock_picking_back2draft/i18n/es_AR.po
  stock_picking_back2draft/i18n/es_MX.po
  stock_picking_back2draft/i18n/fi.po
  stock_picking_back2draft/i18n/fr.po
  stock_picking_back2draft/i18n/hr.po
  stock_picking_back2draft/i18n/it.po
  stock_picking_back2draft/i18n/pt.po
  stock_picking_back2draft/i18n/pt_BR.po
  stock_picking_back2draft/i18n/sl.po
  stock_picking_back2draft/i18n/stock_picking_back2draft.pot
  stock_picking_back2draft/i18n/tr.po
  stock_picking_back2draft/i18n/tr_TR.po
  stock_picking_back2draft/i18n/zh_CN.po
  stock_picking_back2draft/models/__init__.py
  stock_picking_back2draft/models/stock_move.py
  stock_picking_back2draft/models/stock_picking.py
  stock_picking_back2draft/readme/CONTRIBUTORS.rst
  stock_picking_back2draft/readme/DESCRIPTION.rst
  stock_picking_back2draft/readme/USAGE.rst
  stock_picking_back2draft/static/description/icon.png
  stock_picking_back2draft/static/description/index.html
  stock_picking_back2draft/tests/__init__.py
  stock_picking_back2draft/tests/test_picking.py
  stock_picking_back2draft/views/picking_view.xml
Labels: needs review, approved, migration, bot is merging ⏳

#956 [14.0][add][stock_landed_costs_mrp_subcontracting] This module allows to add landed costs to your subcontracted products.
  setup/stock_landed_costs_mrp_subcontracting/odoo/addons/stock_landed_costs_mrp_subcontracting
  setup/stock_landed_costs_mrp_subcontracting/setup.py
  stock_landed_costs_mrp_subcontracting/README.rst
  stock_landed_costs_mrp_subcontracting/__init__.py
  stock_landed_costs_mrp_subcontracting/__manifest__.py
  stock_landed_costs_mrp_subcontracting/models/__init__.py
  stock_landed_costs_mrp_subcontracting/models/mrp_production.py
  stock_landed_costs_mrp_subcontracting/models/stock_landed_cost.py
  stock_landed_costs_mrp_subcontracting/readme/CONTRIBUTORS.rst
  stock_landed_costs_mrp_subcontracting/readme/DESCRIPTION.rst
  stock_landed_costs_mrp_subcontracting/readme/USAGE.rst
  stock_landed_costs_mrp_subcontracting/static/description/icon.png
  stock_landed_costs_mrp_subcontracting/static/description/index.html
  stock_landed_costs_mrp_subcontracting/tests/__init__.py
  stock_landed_costs_mrp_subcontracting/tests/test_stock_landed_costs_mrp_subcontracting.py
Labels: needs review, approved, bot is merging ⏳

#1116 [14.0] Add stock_picking_progress
  setup/stock_picking_progress/odoo/addons/stock_picking_progress
  setup/stock_picking_progress/setup.py
  stock_picking_progress/README.rst
  stock_picking_progress/__init__.py
  stock_picking_progress/__manifest__.py
  stock_picking_progress/hooks.py
  stock_picking_progress/models/__init__.py
  stock_picking_progress/models/stock_move_line.py
  stock_picking_progress/models/stock_picking.py
  stock_picking_progress/readme/CONTRIBUTORS.rst
  stock_picking_progress/readme/DESCRIPTION.rst
  stock_picking_progress/tests/__init__.py
  stock_picking_progress/tests/test_progress.py
  stock_picking_progress/views/stock_picking.xml
Labels: bot is merging ⏳

#1140 [13.0][FIX] stock_picking_invoice_link: inventory users cannot validate picking
  stock_picking_invoice_link/models/stock_move.py
Labels: approved, bot is merging ⏳

#1137 [16][MIG] stock_restrict_lot
  setup/stock_restrict_lot/odoo/addons/stock_restrict_lot
  setup/stock_restrict_lot/setup.py
  stock_restrict_lot/README.rst
  stock_restrict_lot/__init__.py
  stock_restrict_lot/__manifest__.py
  stock_restrict_lot/i18n/stock_restrict_lot.pot
  stock_restrict_lot/models/__init__.py
  stock_restrict_lot/models/stock_move.py
  stock_restrict_lot/models/stock_rule.py
  stock_restrict_lot/readme/CONTRIBUTORS.rst
  stock_restrict_lot/readme/DESCRIPTION.rst
  stock_restrict_lot/static/description/icon.png
  stock_restrict_lot/static/description/index.html
  stock_restrict_lot/tests/__init__.py
  stock_restrict_lot/tests/test_restrict_lot.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1142 [15.0][FIX] stock_picking_mass_action: Change SavepointCase to TransactionCase
  stock_picking_mass_action/tests/test_mass_action.py
Labels: bot is merging ⏳
