Repository OCA/stock-logistics-workflow, pull requests merged in 2022-07, with the labels that each got.

#999 [13.0][IMP] stock_picking_operation_quick_change: Allow to filter by product
  stock_picking_operation_quick_change/README.rst
  stock_picking_operation_quick_change/readme/USAGE.rst
  stock_picking_operation_quick_change/static/description/index.html
  stock_picking_operation_quick_change/wizards/stock_picking_wizard.py
  stock_picking_operation_quick_change/wizards/stock_picking_wizard_view.xml
Labels: bot is merging ⏳

#1031 [13.0][FIX] stock_picking_import_serial_number: Be more resilient in tests
  stock_picking_import_serial_number/tests/common.py
Labels: approved, ready to merge, bot is merging ⏳

#1045 [15.0][FIX] stock_production_lot_active: prevent duplicating lots
  stock_production_lot_active/models/stock_production_lot.py
  stock_production_lot_active/readme/CONTRIBUTORS.rst
  stock_production_lot_active/tests/__init__.py
  stock_production_lot_active/tests/test_lot_active.py
Labels: approved, bot is merging ⏳

#1044 [FIX] stock_production_lot_active: prevent duplicating lots
  stock_production_lot_active/models/stock_production_lot.py
  stock_production_lot_active/readme/CONTRIBUTORS.rst
  stock_production_lot_active/tests/__init__.py
  stock_production_lot_active/tests/test_lot_active.py
Labels: approved, bot is merging ⏳

#1037 [13.0][ADD] stock_picking_product_availability_inline: new module.
  setup/stock_picking_product_availability_inline/odoo/addons/stock_picking_product_availability_inline
  setup/stock_picking_product_availability_inline/setup.py
  stock_picking_product_availability_inline/README.rst
  stock_picking_product_availability_inline/__init__.py
  stock_picking_product_availability_inline/__manifest__.py
  stock_picking_product_availability_inline/models/__init__.py
  stock_picking_product_availability_inline/models/product_product.py
  stock_picking_product_availability_inline/models/stock_picking.py
  stock_picking_product_availability_inline/readme/CONTRIBUTORS.rst
  stock_picking_product_availability_inline/readme/DESCRIPTION.rst
  stock_picking_product_availability_inline/readme/USAGE.rst
  stock_picking_product_availability_inline/static/description/icon.png
  stock_picking_product_availability_inline/static/description/index.html
  stock_picking_product_availability_inline/tests/__init__.py
  stock_picking_product_availability_inline/tests/test_stock_picking_product_availability_inline.py
  stock_picking_product_availability_inline/views/stock_picking_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1036 [13.0][FIX] stock_picking_invoice_link: Consider DS pickings
  stock_picking_invoice_link/models/sale_order.py
Labels: approved, bot is merging ⏳

#1047 [13.0][FIX] stock_picking_product_availability_inline: Non store fields
  stock_picking_product_availability_inline/__init__.py
  stock_picking_product_availability_inline/__manifest__.py
  stock_picking_product_availability_inline/hooks.py
  stock_picking_product_availability_inline/migrations/13.0.1.0.1/pre-migration.py
  stock_picking_product_availability_inline/models/stock_picking.py
Labels: bot is merging ⏳

#1043 [13.0][ADD] sale_line_returned_qty
  sale_line_returned_qty/README.rst
  sale_line_returned_qty/__init__.py
  sale_line_returned_qty/__manifest__.py
  sale_line_returned_qty/models/__init__.py
  sale_line_returned_qty/models/sale_order_line.py
  sale_line_returned_qty/readme/CONTRIBUTORS.rst
  sale_line_returned_qty/readme/DESCRIPTION.rst
  sale_line_returned_qty/static/description/icon.png
  sale_line_returned_qty/static/description/index.html
  sale_line_returned_qty/tests/__init__.py
  sale_line_returned_qty/tests/test_sale_line_returned_qty.py
  sale_line_returned_qty/views/sale_order_views.xml
  setup/sale_line_returned_qty/odoo/addons/sale_line_returned_qty
  setup/sale_line_returned_qty/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1048 [13.0][ADD] sale_line_returned_qty_mrp
  sale_line_returned_qty_mrp/README.rst
  sale_line_returned_qty_mrp/__init__.py
  sale_line_returned_qty_mrp/__manifest__.py
  sale_line_returned_qty_mrp/models/__init__.py
  sale_line_returned_qty_mrp/models/sale_order_line.py
  sale_line_returned_qty_mrp/readme/CONTRIBUTORS.rst
  sale_line_returned_qty_mrp/readme/DESCRIPTION.rst
  sale_line_returned_qty_mrp/static/description/icon.png
  sale_line_returned_qty_mrp/static/description/index.html
  sale_line_returned_qty_mrp/tests/__init__.py
  sale_line_returned_qty_mrp/tests/test_sale_line_returned_qty_mrp.py
  setup/sale_line_returned_qty_mrp/odoo/addons/sale_line_returned_qty_mrp
  setup/sale_line_returned_qty_mrp/setup.py
Labels: approved, bot is merging ⏳
