Repository OCA/stock-logistics-workflow, pull requests merged in 2022-12, with the labels that each got.

#1147 [15.0][MIG] stock_picking_invoice_link: Migration to 15.0
  setup/stock_picking_invoice_link/odoo/addons/stock_picking_invoice_link
  setup/stock_picking_invoice_link/setup.py
  stock_picking_invoice_link/README.rst
  stock_picking_invoice_link/__init__.py
  stock_picking_invoice_link/__manifest__.py
  stock_picking_invoice_link/i18n/ca.po
  stock_picking_invoice_link/i18n/de.po
  stock_picking_invoice_link/i18n/es.po
  stock_picking_invoice_link/i18n/es_MX.po
  stock_picking_invoice_link/i18n/fi.po
  stock_picking_invoice_link/i18n/fr.po
  stock_picking_invoice_link/i18n/hr.po
  stock_picking_invoice_link/i18n/it.po
  stock_picking_invoice_link/i18n/nl_NL.po
  stock_picking_invoice_link/i18n/pt.po
  stock_picking_invoice_link/i18n/pt_BR.po
  stock_picking_invoice_link/i18n/sl.po
  stock_picking_invoice_link/i18n/stock_picking_invoice_link.pot
  stock_picking_invoice_link/i18n/tr.po
  stock_picking_invoice_link/i18n/tr_TR.po
  stock_picking_invoice_link/models/__init__.py
  stock_picking_invoice_link/models/account_move.py
  stock_picking_invoice_link/models/sale_order.py
  stock_picking_invoice_link/models/stock_move.py
  stock_picking_invoice_link/models/stock_picking.py
  stock_picking_invoice_link/readme/CONTRIBUTORS.rst
  stock_picking_invoice_link/readme/DESCRIPTION.rst
  stock_picking_invoice_link/readme/USAGE.rst
  stock_picking_invoice_link/static/description/icon.png
  stock_picking_invoice_link/static/description/index.html
  stock_picking_invoice_link/tests/__init__.py
  stock_picking_invoice_link/tests/test_stock_picking_invoice_link.py
  stock_picking_invoice_link/views/account_invoice_view.xml
  stock_picking_invoice_link/views/stock_view.xml
  stock_picking_invoice_link/wizards/__init__.py
  stock_picking_invoice_link/wizards/account_move_reversal.py
Labels: bot is merging ⏳

#1144 [16.0][MIG] stock_move_line_auto_fill
  setup/stock_move_line_auto_fill/odoo/addons/stock_move_line_auto_fill
  setup/stock_move_line_auto_fill/setup.py
  stock_move_line_auto_fill/README.rst
  stock_move_line_auto_fill/__init__.py
  stock_move_line_auto_fill/__manifest__.py
  stock_move_line_auto_fill/i18n/cs_CZ.po
  stock_move_line_auto_fill/i18n/de.po
  stock_move_line_auto_fill/i18n/es.po
  stock_move_line_auto_fill/i18n/fr.po
  stock_move_line_auto_fill/i18n/it.po
  stock_move_line_auto_fill/i18n/nl_NL.po
  stock_move_line_auto_fill/i18n/pt.po
  stock_move_line_auto_fill/i18n/pt_BR.po
  stock_move_line_auto_fill/i18n/stock_move_line_auto_fill.pot
  stock_move_line_auto_fill/i18n/zh_CN.po
  stock_move_line_auto_fill/models/__init__.py
  stock_move_line_auto_fill/models/stock_move.py
  stock_move_line_auto_fill/models/stock_picking.py
  stock_move_line_auto_fill/models/stock_picking_type.py
  stock_move_line_auto_fill/readme/CONFIGURE.rst
  stock_move_line_auto_fill/readme/CONTRIBUTORS.rst
  stock_move_line_auto_fill/readme/DESCRIPTION.rst
  stock_move_line_auto_fill/readme/USAGE.rst
  stock_move_line_auto_fill/static/description/icon.png
  stock_move_line_auto_fill/static/description/index.html
  stock_move_line_auto_fill/tests/__init__.py
  stock_move_line_auto_fill/tests/test_stock_picking_auto_fill.py
  stock_move_line_auto_fill/views/stock_picking.xml
  stock_move_line_auto_fill/views/stock_picking_type_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1041 [15.0][MIG] stock_picking_batch_extended: Migration to 15.0
  setup/stock_picking_batch_extended/odoo/addons/stock_picking_batch_extended
  setup/stock_picking_batch_extended/setup.py
  stock_picking_batch_extended/README.rst
  stock_picking_batch_extended/__init__.py
  stock_picking_batch_extended/__manifest__.py
  stock_picking_batch_extended/data/batch_picking_actions_server.xml
  stock_picking_batch_extended/hooks.py
  stock_picking_batch_extended/i18n/de.po
  stock_picking_batch_extended/i18n/es.po
  stock_picking_batch_extended/i18n/es_CL.po
  stock_picking_batch_extended/i18n/fr.po
  stock_picking_batch_extended/i18n/it.po
  stock_picking_batch_extended/i18n/pt_BR.po
  stock_picking_batch_extended/i18n/sl.po
  stock_picking_batch_extended/i18n/stock_picking_batch_extended.pot
  stock_picking_batch_extended/migrations/15.0.1.0/pre-migration.py
  stock_picking_batch_extended/models/__init__.py
  stock_picking_batch_extended/models/product_product.py
  stock_picking_batch_extended/models/res_config_settings.py
  stock_picking_batch_extended/models/stock_batch_picking.py
  stock_picking_batch_extended/models/stock_warehouse.py
  stock_picking_batch_extended/readme/CONTRIBUTORS.rst
  stock_picking_batch_extended/readme/CREDITS.rst
  stock_picking_batch_extended/readme/DESCRIPTION.rst
  stock_picking_batch_extended/report/__init__.py
  stock_picking_batch_extended/report/batch_report.py
  stock_picking_batch_extended/security/ir.model.access.csv
  stock_picking_batch_extended/static/batch_form.png
  stock_picking_batch_extended/static/batch_form_operation.png
  stock_picking_batch_extended/static/batch_wizard.png
  stock_picking_batch_extended/static/description/icon.png
  stock_picking_batch_extended/static/description/index.html
  stock_picking_batch_extended/static/stock_picking_list.png
  stock_picking_batch_extended/tests/__init__.py
  stock_picking_batch_extended/tests/test_batch.py
  stock_picking_batch_extended/views/product_product.xml
  stock_picking_batch_extended/views/report_batch_picking.xml
  stock_picking_batch_extended/views/res_config_settings_views.xml
  stock_picking_batch_extended/views/stock_batch_picking.xml
  stock_picking_batch_extended/views/stock_warehouse.xml
  stock_picking_batch_extended/wizard/__init__.py
  stock_picking_batch_extended/wizard/stock_picking_to_batch.py
  stock_picking_batch_extended/wizard/stock_picking_to_batch_views.xml
Labels: approved, migration, bot is merging ⏳

#1156 [WIP][15.0][MIG] stock_picking_batch_extended_account: Migration to version 15.0
  setup/stock_picking_batch_extended_account/odoo/addons/stock_picking_batch_extended_account
  setup/stock_picking_batch_extended_account/setup.py
  stock_picking_batch_extended_account/README.rst
  stock_picking_batch_extended_account/__init__.py
  stock_picking_batch_extended_account/__manifest__.py
  stock_picking_batch_extended_account/i18n/es.po
  stock_picking_batch_extended_account/i18n/stock_picking_batch_extended_account.pot
  stock_picking_batch_extended_account/models/__init__.py
  stock_picking_batch_extended_account/models/res_partner.py
  stock_picking_batch_extended_account/models/stock_batch_picking.py
  stock_picking_batch_extended_account/models/stock_picking.py
  stock_picking_batch_extended_account/readme/CONFIGURE.rst
  stock_picking_batch_extended_account/readme/CONTRIBUTORS.rst
  stock_picking_batch_extended_account/readme/DESCRIPTION.rst
  stock_picking_batch_extended_account/readme/USAGE.rst
  stock_picking_batch_extended_account/static/description/icon.png
  stock_picking_batch_extended_account/static/description/index.html
  stock_picking_batch_extended_account/tests/__init__.py
  stock_picking_batch_extended_account/tests/test_stock_picking_batch_extended_account.py
  stock_picking_batch_extended_account/views/res_partner_views.xml
  stock_picking_batch_extended_account/views/stock_batch_picking.xml
Labels: approved, bot is merging ⏳

#1157 [15.0][MIG] stock_picking_batch_extended_account_sale_type: Migration to version 15.0
  setup/stock_picking_batch_extended_account_sale_type/odoo/addons/stock_picking_batch_extended_account_sale_type
  setup/stock_picking_batch_extended_account_sale_type/setup.py
  stock_picking_batch_extended_account_sale_type/README.rst
  stock_picking_batch_extended_account_sale_type/__init__.py
  stock_picking_batch_extended_account_sale_type/__manifest__.py
  stock_picking_batch_extended_account_sale_type/i18n/es.po
  stock_picking_batch_extended_account_sale_type/i18n/stock_picking_batch_extended_account_sale_type.pot
  stock_picking_batch_extended_account_sale_type/models/__init__.py
  stock_picking_batch_extended_account_sale_type/models/res_partner.py
  stock_picking_batch_extended_account_sale_type/models/sale_order_type.py
  stock_picking_batch_extended_account_sale_type/models/stock_batch_picking.py
  stock_picking_batch_extended_account_sale_type/readme/CONTRIBUTORS.rst
  stock_picking_batch_extended_account_sale_type/readme/DESCRIPTION.rst
  stock_picking_batch_extended_account_sale_type/static/description/icon.png
  stock_picking_batch_extended_account_sale_type/static/description/index.html
  stock_picking_batch_extended_account_sale_type/tests/__init__.py
  stock_picking_batch_extended_account_sale_type/tests/test_stock_picking_batch_extended_account_sale_type.py
  stock_picking_batch_extended_account_sale_type/views/sale_order_type_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1153 [15.0] [ADD] `stock_picking_product_availability_search`
  setup/stock_picking_product_availability_search/odoo/addons/stock_picking_product_availability_search
  setup/stock_picking_product_availability_search/setup.py
  stock_picking_product_availability_search/README.rst
  stock_picking_product_availability_search/__init__.py
  stock_picking_product_availability_search/__manifest__.py
  stock_picking_product_availability_search/models/__init__.py
  stock_picking_product_availability_search/models/stock_picking.py
  stock_picking_product_availability_search/readme/CONTRIBUTORS.rst
  stock_picking_product_availability_search/readme/DESCRIPTION.rst
  stock_picking_product_availability_search/tests/__init__.py
  stock_picking_product_availability_search/tests/test_search.py
  stock_picking_product_availability_search/views/stock_picking.xml
Labels: approved, ready to merge, bot is merging ⏳

#1065 [13.0][IMP] stock_picking_import_serial_number: Allow import S/N from file in internal and outgoing operations
  stock_picking_import_serial_number/README.rst
  stock_picking_import_serial_number/i18n/es.po
  stock_picking_import_serial_number/i18n/stock_picking_import_serial_number.pot
  stock_picking_import_serial_number/models/__init__.py
  stock_picking_import_serial_number/models/stock_picking.py
  stock_picking_import_serial_number/readme/CONFIGURE.rst
  stock_picking_import_serial_number/static/description/index.html
  stock_picking_import_serial_number/tests/common.py
  stock_picking_import_serial_number/tests/test_stock_picking_import_serial_number.py
  stock_picking_import_serial_number/views/stock_picking.xml
  stock_picking_import_serial_number/wizard/import_serial_number_view.xml
  stock_picking_import_serial_number/wizard/import_serial_number_wizard.py
Labels: bot is merging ⏳

#1166 [IMP/FIX] stock_move_line_auto_fill: Fix _action_assign signature + Improve tests
  stock_move_line_auto_fill/models/stock_move.py
  stock_move_line_auto_fill/tests/test_stock_picking_auto_fill.py
Labels: enhancement, needs review, bot is merging ⏳

#1169 [15.0][FIX] stock_picking_product_availability_search: avoid built-in 'type'
  stock_picking_product_availability_search/tests/test_search.py
Labels: bot is merging ⏳

#1170 [14.0][FIX] stock_landed_costs_mrp_subcontracting: improve tests
  stock_landed_costs_mrp_subcontracting/__manifest__.py
  stock_landed_costs_mrp_subcontracting/tests/test_stock_landed_costs_mrp_subcontracting.py
Labels: approved, bot is merging ⏳

#1034 [14.0][MIG] product_supplierinfo_picking
  product_supplierinfo_picking/README.rst
  product_supplierinfo_picking/__init__.py
  product_supplierinfo_picking/__manifest__.py
  product_supplierinfo_picking/i18n/product_supplierinfo_picking.pot
  product_supplierinfo_picking/i18n/sl.po
  product_supplierinfo_picking/models/__init__.py
  product_supplierinfo_picking/models/stock_move.py
  product_supplierinfo_picking/readme/CONTRIBUTORS.rst
  product_supplierinfo_picking/readme/DESCRIPTION.rst
  product_supplierinfo_picking/readme/USAGE.rst
  product_supplierinfo_picking/static/description/icon.png
  product_supplierinfo_picking/static/description/index.html
  product_supplierinfo_picking/tests/__init__.py
  product_supplierinfo_picking/tests/test_product_supplierinfo_picking.py
  product_supplierinfo_picking/views/stock_picking_view.xml
  setup/product_supplierinfo_picking/odoo/addons/product_supplierinfo_picking
  setup/product_supplierinfo_picking/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1176 [14.0][ADD] stock_move_forced_lot
  setup/stock_move_forced_lot/odoo/addons/stock_move_forced_lot
  setup/stock_move_forced_lot/setup.py
  stock_move_forced_lot/README.rst
  stock_move_forced_lot/__init__.py
  stock_move_forced_lot/__manifest__.py
  stock_move_forced_lot/models/__init__.py
  stock_move_forced_lot/models/stock_move.py
  stock_move_forced_lot/models/stock_rule.py
  stock_move_forced_lot/readme/CONTRIBUTORS.rst
  stock_move_forced_lot/readme/DESCRIPTION.rst
  stock_move_forced_lot/tests/__init__.py
  stock_move_forced_lot/tests/test_stock_move_forced_lot.py
Labels: approved, bot is merging ⏳

#1154 [MIG] stock_picking_invoice_link: Migration to 16.0
  setup/stock_picking_invoice_link/odoo/addons/stock_picking_invoice_link
  setup/stock_picking_invoice_link/setup.py
  stock_picking_invoice_link/README.rst
  stock_picking_invoice_link/__init__.py
  stock_picking_invoice_link/__manifest__.py
  stock_picking_invoice_link/i18n/ca.po
  stock_picking_invoice_link/i18n/de.po
  stock_picking_invoice_link/i18n/es.po
  stock_picking_invoice_link/i18n/es_MX.po
  stock_picking_invoice_link/i18n/fi.po
  stock_picking_invoice_link/i18n/fr.po
  stock_picking_invoice_link/i18n/hr.po
  stock_picking_invoice_link/i18n/it.po
  stock_picking_invoice_link/i18n/nl_NL.po
  stock_picking_invoice_link/i18n/pt.po
  stock_picking_invoice_link/i18n/pt_BR.po
  stock_picking_invoice_link/i18n/sl.po
  stock_picking_invoice_link/i18n/stock_picking_invoice_link.pot
  stock_picking_invoice_link/i18n/tr.po
  stock_picking_invoice_link/i18n/tr_TR.po
  stock_picking_invoice_link/models/__init__.py
  stock_picking_invoice_link/models/account_move.py
  stock_picking_invoice_link/models/sale_order.py
  stock_picking_invoice_link/models/stock_move.py
  stock_picking_invoice_link/models/stock_picking.py
  stock_picking_invoice_link/readme/CONTRIBUTORS.rst
  stock_picking_invoice_link/readme/DESCRIPTION.rst
  stock_picking_invoice_link/readme/USAGE.rst
  stock_picking_invoice_link/static/description/icon.png
  stock_picking_invoice_link/static/description/index.html
  stock_picking_invoice_link/tests/__init__.py
  stock_picking_invoice_link/tests/test_stock_picking_invoice_link.py
  stock_picking_invoice_link/views/account_invoice_view.xml
  stock_picking_invoice_link/views/stock_view.xml
  stock_picking_invoice_link/wizards/__init__.py
  stock_picking_invoice_link/wizards/account_move_reversal.py
Labels: needs review, approved, migration, bot is merging ⏳
