Repository OCA/stock-logistics-workflow, pull requests merged in 2022-02, with the labels that each got.

#959 [14.0][FIX] Fix access right issues when using actions
  stock_picking_invoice_link/models/account_move.py
  stock_picking_invoice_link/models/stock_picking.py
  stock_picking_purchase_order_link/models/stock_picking.py
  stock_return_request/models/stock_return_request.py
Labels: bug, approved, bot is merging ⏳

#957 [MIG] product_supplierinfo_for_customer_picking: Migration to 13.0
  product_supplierinfo_for_customer_picking/README.rst
  product_supplierinfo_for_customer_picking/__init__.py
  product_supplierinfo_for_customer_picking/__manifest__.py
  product_supplierinfo_for_customer_picking/i18n/de.po
  product_supplierinfo_for_customer_picking/i18n/it.po
  product_supplierinfo_for_customer_picking/i18n/product_supplierinfo_for_customer_picking.pot
  product_supplierinfo_for_customer_picking/i18n/pt_BR.po
  product_supplierinfo_for_customer_picking/models/__init__.py
  product_supplierinfo_for_customer_picking/models/stock_move.py
  product_supplierinfo_for_customer_picking/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_picking/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer_picking/static/description/icon.png
  product_supplierinfo_for_customer_picking/static/description/index.html
  product_supplierinfo_for_customer_picking/tests/__init__.py
  product_supplierinfo_for_customer_picking/tests/test_product_supplierinfo_for_customer_picking.py
  product_supplierinfo_for_customer_picking/views/stock_picking_view.xml
  setup/product_supplierinfo_for_customer_picking/odoo/addons/product_supplierinfo_for_customer_picking
  setup/product_supplierinfo_for_customer_picking/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#963 [13.0][FIX] stock_lot_scrap: scraps with no lot
  stock_lot_scrap/models/stock_scrap.py
Labels: approved, bot is merging ⏳

#907 [14.0][MIG] stock_picking_warn_message: Migration to 14.0
  README.md
  setup/stock_picking_warn_message/odoo/addons/stock_picking_warn_message
  setup/stock_picking_warn_message/setup.py
  stock_picking_warn_message/README.rst
  stock_picking_warn_message/__init__.py
  stock_picking_warn_message/__manifest__.py
  stock_picking_warn_message/i18n/stock_picking_warn_message.pot
  stock_picking_warn_message/models/__init__.py
  stock_picking_warn_message/models/stock_picking.py
  stock_picking_warn_message/readme/CONTRIBUTORS.rst
  stock_picking_warn_message/readme/DESCRIPTION.rst
  stock_picking_warn_message/static/description/icon.png
  stock_picking_warn_message/static/description/index.html
  stock_picking_warn_message/tests/__init__.py
  stock_picking_warn_message/tests/test_stock_picking_warn_message.py
  stock_picking_warn_message/views/stock_picking_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#594 [10.0][FIX]stock_cancel. quant cancellation
  stock_cancel/models/stock_move.py
  stock_cancel/models/stock_picking.py
  stock_cancel/models/stock_quant.py
Labels: work in progress, bot is merging ⏳, stale

#878 [12.0][IMP] stock_picking_force_assign: allow partial
  stock_picking_force_assign/README.rst
  stock_picking_force_assign/__manifest__.py
  stock_picking_force_assign/data/ir_config_parameter.xml
  stock_picking_force_assign/models/stock_picking.py
  stock_picking_force_assign/readme/CONFIGURE.rst
  stock_picking_force_assign/readme/CONTRIBUTORS.rst
  stock_picking_force_assign/static/description/index.html
  stock_picking_force_assign/tests/test_stock_picking_force_assign.py
Labels: enhancement, needs review, bot is merging ⏳

#962 [13.0][ADD] stock_scrap_cancel: New addon
  setup/stock_scrap_cancel/odoo/addons/stock_scrap_cancel
  setup/stock_scrap_cancel/setup.py
  stock_scrap_cancel/README.rst
  stock_scrap_cancel/__init__.py
  stock_scrap_cancel/__manifest__.py
  stock_scrap_cancel/i18n/es.po
  stock_scrap_cancel/i18n/stock_scrap_cancel.pot
  stock_scrap_cancel/models/__init__.py
  stock_scrap_cancel/models/stock_scrap.py
  stock_scrap_cancel/readme/CONTRIBUTORS.rst
  stock_scrap_cancel/readme/DESCRIPTION.rst
  stock_scrap_cancel/readme/USAGE.rst
  stock_scrap_cancel/static/description/icon.png
  stock_scrap_cancel/static/description/index.html
  stock_scrap_cancel/tests/__init__.py
  stock_scrap_cancel/tests/test_stock_scrap_cancel.py
  stock_scrap_cancel/views/stock_scrap_view.xml
Labels: needs review, approved, bot is merging ⏳

#971 [10.0] stock_no_negative: backport allow_negative_stock on stock.location
  stock_no_negative/__manifest__.py
  stock_no_negative/models/__init__.py
  stock_no_negative/models/stock_location.py
  stock_no_negative/models/stock_quant.py
  stock_no_negative/tests/test_stock_no_negative.py
  stock_no_negative/views/stock_location.xml
Labels: enhancement, needs review, bot is merging ⏳
