Repository OCA/stock-logistics-workflow, pull requests merged in 2022-05, with the labels that each got.

#997 [14.0][FIX] stock_picking_invoice_link: test needs post install decorator + fix in test
  stock_picking_invoice_link/tests/test_stock_picking_invoice_link.py
Labels: bot is merging ⏳

#743 [10.0] backport stock_quant_package_product_packaging from 13.0
  setup/stock_quant_package_product_packaging/odoo/__init__.py
  setup/stock_quant_package_product_packaging/odoo/addons/__init__.py
  setup/stock_quant_package_product_packaging/odoo/addons/stock_quant_package_product_packaging
  setup/stock_quant_package_product_packaging/setup.py
  stock_quant_package_product_packaging/README.rst
  stock_quant_package_product_packaging/__init__.py
  stock_quant_package_product_packaging/__manifest__.py
  stock_quant_package_product_packaging/i18n/stock_quant_package_product_packaging.pot
  stock_quant_package_product_packaging/models/__init__.py
  stock_quant_package_product_packaging/models/stock_move.py
  stock_quant_package_product_packaging/models/stock_pack_operation.py
  stock_quant_package_product_packaging/models/stock_quant_package.py
  stock_quant_package_product_packaging/readme/CONTRIBUTORS.rst
  stock_quant_package_product_packaging/readme/DESCRIPTION.rst
  stock_quant_package_product_packaging/static/description/icon.png
  stock_quant_package_product_packaging/static/description/index.html
  stock_quant_package_product_packaging/tests/__init__.py
  stock_quant_package_product_packaging/tests/test_stock_quant_package_product_packaging.py
  stock_quant_package_product_packaging/views/stock_quant_package.xml
Labels: needs review, migration, bot is merging ⏳

#819 [14.0][MIG] stock_owner_restriction: Migration to 14.0
  setup/stock_owner_restriction/odoo/addons/stock_owner_restriction
  setup/stock_owner_restriction/setup.py
  stock_owner_restriction/README.rst
  stock_owner_restriction/__init__.py
  stock_owner_restriction/__manifest__.py
  stock_owner_restriction/i18n/es.po
  stock_owner_restriction/i18n/stock_owner_restriction.pot
  stock_owner_restriction/models/__init__.py
  stock_owner_restriction/models/product.py
  stock_owner_restriction/models/stock_move.py
  stock_owner_restriction/models/stock_picking.py
  stock_owner_restriction/models/stock_picking_type.py
  stock_owner_restriction/models/stock_quant.py
  stock_owner_restriction/readme/CONFIGURE.rst
  stock_owner_restriction/readme/CONTRIBUTORS.rst
  stock_owner_restriction/readme/DESCRIPTION.rst
  stock_owner_restriction/readme/USAGE.rst
  stock_owner_restriction/static/description/icon.png
  stock_owner_restriction/static/description/index.html
  stock_owner_restriction/tests/__init__.py
  stock_owner_restriction/tests/test_stock_owner_restriction.py
  stock_owner_restriction/views/stock_picking_type_views.xml
  stock_owner_restriction/views/stock_picking_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1000 [15.0][MIG] stock picking send by mail: Migration to 15.0
  setup/stock_picking_send_by_mail/odoo/addons/stock_picking_send_by_mail
  setup/stock_picking_send_by_mail/setup.py
  stock_picking_send_by_mail/README.rst
  stock_picking_send_by_mail/__init__.py
  stock_picking_send_by_mail/__manifest__.py
  stock_picking_send_by_mail/i18n/de.po
  stock_picking_send_by_mail/i18n/es.po
  stock_picking_send_by_mail/i18n/fr.po
  stock_picking_send_by_mail/i18n/it.po
  stock_picking_send_by_mail/i18n/pt_BR.po
  stock_picking_send_by_mail/i18n/stock_picking_send_by_mail.pot
  stock_picking_send_by_mail/models/__init__.py
  stock_picking_send_by_mail/models/stock_picking.py
  stock_picking_send_by_mail/readme/CONTRIBUTORS.rst
  stock_picking_send_by_mail/readme/DESCRIPTION.rst
  stock_picking_send_by_mail/readme/USAGE.rst
  stock_picking_send_by_mail/static/description/icon.png
  stock_picking_send_by_mail/static/description/index.html
  stock_picking_send_by_mail/tests/__init__.py
  stock_picking_send_by_mail/tests/test_stock_picking_send_by_mail.py
  stock_picking_send_by_mail/views/stock_picking_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1008 [15.0][MIG] stock_picking_whole_scrap: Migration to 15.0
  setup/stock_picking_whole_scrap/odoo/addons/stock_picking_whole_scrap
  setup/stock_picking_whole_scrap/setup.py
  stock_picking_whole_scrap/README.rst
  stock_picking_whole_scrap/__init__.py
  stock_picking_whole_scrap/__manifest__.py
  stock_picking_whole_scrap/i18n/es.po
  stock_picking_whole_scrap/i18n/stock_picking_whole_scrap.pot
  stock_picking_whole_scrap/i18n/zh_CN.po
  stock_picking_whole_scrap/models/__init__.py
  stock_picking_whole_scrap/models/stock_picking.py
  stock_picking_whole_scrap/readme/CONTRIBUTORS.rst
  stock_picking_whole_scrap/readme/DESCRIPTION.rst
  stock_picking_whole_scrap/readme/USAGE.rst
  stock_picking_whole_scrap/security/ir.model.access.csv
  stock_picking_whole_scrap/static/description/icon.png
  stock_picking_whole_scrap/static/description/index.html
  stock_picking_whole_scrap/tests/__init__.py
  stock_picking_whole_scrap/tests/test_stock_picking_whole_scrap.py
  stock_picking_whole_scrap/views/stock_picking_views.xml
  stock_picking_whole_scrap/wizards/__init__.py
  stock_picking_whole_scrap/wizards/stock_picking_whole_scrap.py
  stock_picking_whole_scrap/wizards/stock_picking_whole_scrap.xml
Labels: approved, bot is merging ⏳
