Repository OCA/stock-logistics-workflow, pull requests merged in 2022-09, with the labels that each got.

#1077 [13.0][FIX] stock_picking_batch_extended_account prod: Rename column in migration script
  stock_picking_batch_extended_account/migrations/13.0.1.1.0/post-migration.py
Labels: approved, bot is merging ⏳

#1069 [14.0][FIX] stock_restrict_lot: do not merge stock move with different restrict_lot_id
  stock_restrict_lot/models/stock_move.py
  stock_restrict_lot/tests/test_restrict_lot.py
Labels: bug, approved, ready to merge, bot is merging ⏳

#1038 [15.0][MIG] delivery_procurement_group_carrier: Migrate 14.0 to 15.0
  delivery_procurement_group_carrier/README.rst
  delivery_procurement_group_carrier/__init__.py
  delivery_procurement_group_carrier/__manifest__.py
  delivery_procurement_group_carrier/i18n/delivery_procurement_group_carrier.pot
  delivery_procurement_group_carrier/models/__init__.py
  delivery_procurement_group_carrier/models/procurement_group.py
  delivery_procurement_group_carrier/models/sale_order.py
  delivery_procurement_group_carrier/readme/CONTRIBUTORS.rst
  delivery_procurement_group_carrier/readme/CREDITS.rst
  delivery_procurement_group_carrier/readme/DESCRIPTION.rst
  delivery_procurement_group_carrier/static/description/icon.png
  delivery_procurement_group_carrier/static/description/index.html
  delivery_procurement_group_carrier/tests/__init__.py
  delivery_procurement_group_carrier/tests/test_carrier.py
  delivery_procurement_group_carrier/views/procurement_group.xml
  setup/delivery_procurement_group_carrier/odoo/addons/delivery_procurement_group_carrier
  setup/delivery_procurement_group_carrier/setup.py
Labels: approved, bot is merging ⏳

#1054 [14.0][MIG] stock_lot_scrap
  setup/stock_lot_scrap/odoo/addons/stock_lot_scrap
  setup/stock_lot_scrap/setup.py
  stock_lot_scrap/README.rst
  stock_lot_scrap/__init__.py
  stock_lot_scrap/__manifest__.py
  stock_lot_scrap/i18n/de.po
  stock_lot_scrap/i18n/es.po
  stock_lot_scrap/i18n/fr.po
  stock_lot_scrap/i18n/hr.po
  stock_lot_scrap/i18n/it.po
  stock_lot_scrap/i18n/pt.po
  stock_lot_scrap/i18n/pt_BR.po
  stock_lot_scrap/i18n/sl.po
  stock_lot_scrap/i18n/stock_lot_scrap.pot
  stock_lot_scrap/models/__init__.py
  stock_lot_scrap/models/stock_production_lot.py
  stock_lot_scrap/models/stock_scrap.py
  stock_lot_scrap/readme/CONFIGURE.rst
  stock_lot_scrap/readme/CONTRIBUTORS.rst
  stock_lot_scrap/readme/DESCRIPTION.rst
  stock_lot_scrap/readme/USAGE.rst
  stock_lot_scrap/static/description/icon.png
  stock_lot_scrap/static/description/index.html
  stock_lot_scrap/tests/__init__.py
  stock_lot_scrap/tests/test_stock_lot_scrap.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1020 [15.0][MIG] stock_picking_show_backorder
  setup/stock_picking_show_backorder/odoo/addons/stock_picking_show_backorder
  setup/stock_picking_show_backorder/setup.py
  stock_picking_send_by_mail/tests/test_stock_picking_send_by_mail.py
  stock_picking_show_backorder/README.rst
  stock_picking_show_backorder/__init__.py
  stock_picking_show_backorder/__manifest__.py
  stock_picking_show_backorder/i18n/cs_CZ.po
  stock_picking_show_backorder/i18n/de.po
  stock_picking_show_backorder/i18n/es.po
  stock_picking_show_backorder/i18n/fr.po
  stock_picking_show_backorder/i18n/it.po
  stock_picking_show_backorder/i18n/nl_NL.po
  stock_picking_show_backorder/i18n/pt.po
  stock_picking_show_backorder/i18n/pt_BR.po
  stock_picking_show_backorder/i18n/sl.po
  stock_picking_show_backorder/i18n/stock_picking_show_backorder.pot
  stock_picking_show_backorder/models/__init__.py
  stock_picking_show_backorder/models/stock.py
  stock_picking_show_backorder/readme/CONTRIBUTORS.rst
  stock_picking_show_backorder/readme/DESCRIPTION.rst
  stock_picking_show_backorder/readme/USAGE.rst
  stock_picking_show_backorder/static/description/icon.png
  stock_picking_show_backorder/static/description/index.html
  stock_picking_show_backorder/tests/__init__.py
  stock_picking_show_backorder/tests/test_stock_picking_show_backorder.py
  stock_picking_show_backorder/views/stock_view.xml
  stock_picking_whole_scrap/tests/test_stock_picking_whole_scrap.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1066 [FIX]stock_picking_return_restricted_qty: fix quantity on return chain
  stock_picking_return_restricted_qty/wizard/stock_picking_return.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1078 [15.0][FW] [14.0][FIX] stock_restrict_lot: do not merge stock move with different restrict_lot_id
  stock_restrict_lot/models/stock_move.py
  stock_restrict_lot/tests/test_restrict_lot.py
Labels: bug, needs review, bot is merging ⏳

#1018 [13.0][MIG] stock_picking_customer_ref: Migration to 13.0
  setup/stock_picking_customer_ref/odoo/addons/stock_picking_customer_ref
  setup/stock_picking_customer_ref/setup.py
  stock_picking_customer_ref/README.rst
  stock_picking_customer_ref/__init__.py
  stock_picking_customer_ref/__manifest__.py
  stock_picking_customer_ref/i18n/de.po
  stock_picking_customer_ref/i18n/es.po
  stock_picking_customer_ref/i18n/fr.po
  stock_picking_customer_ref/i18n/hr.po
  stock_picking_customer_ref/i18n/it.po
  stock_picking_customer_ref/i18n/nl.po
  stock_picking_customer_ref/i18n/pt.po
  stock_picking_customer_ref/i18n/pt_BR.po
  stock_picking_customer_ref/i18n/sl_SI.po
  stock_picking_customer_ref/i18n/stock_picking_customer_ref.pot
  stock_picking_customer_ref/models/__init__.py
  stock_picking_customer_ref/models/stock_picking.py
  stock_picking_customer_ref/readme/CONTRIBUTORS.rst
  stock_picking_customer_ref/readme/CREDITS.rst
  stock_picking_customer_ref/readme/DESCRIPTION.rst
  stock_picking_customer_ref/readme/USAGE.rst
  stock_picking_customer_ref/static/description/icon.png
  stock_picking_customer_ref/static/description/index.html
  stock_picking_customer_ref/tests/__init__.py
  stock_picking_customer_ref/tests/test_stock_picking_customer_ref.py
  stock_picking_customer_ref/views/stock_picking_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1033 [15.0][MIG] stock_owner_restriction: Migration to 15.0
  setup/stock_owner_restriction/odoo/addons/stock_owner_restriction
  setup/stock_owner_restriction/setup.py
  stock_owner_restriction/README.rst
  stock_owner_restriction/__init__.py
  stock_owner_restriction/__manifest__.py
  stock_owner_restriction/i18n/es.po
  stock_owner_restriction/i18n/stock_owner_restriction.pot
  stock_owner_restriction/models/__init__.py
  stock_owner_restriction/models/product.py
  stock_owner_restriction/models/stock_move.py
  stock_owner_restriction/models/stock_picking.py
  stock_owner_restriction/models/stock_picking_type.py
  stock_owner_restriction/models/stock_quant.py
  stock_owner_restriction/readme/CONFIGURE.rst
  stock_owner_restriction/readme/CONTRIBUTORS.rst
  stock_owner_restriction/readme/DESCRIPTION.rst
  stock_owner_restriction/readme/USAGE.rst
  stock_owner_restriction/static/description/icon.png
  stock_owner_restriction/static/description/index.html
  stock_owner_restriction/tests/__init__.py
  stock_owner_restriction/tests/test_stock_owner_restriction.py
  stock_owner_restriction/views/stock_picking_type_views.xml
  stock_owner_restriction/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳

#1007 [15.0] [MIG] stock_picking_product_assortment: Migration to 15.0
  setup/stock_picking_product_assortment/odoo/addons/stock_picking_product_assortment
  setup/stock_picking_product_assortment/setup.py
  stock_picking_product_assortment/README.rst
  stock_picking_product_assortment/__init__.py
  stock_picking_product_assortment/__manifest__.py
  stock_picking_product_assortment/i18n/es.po
  stock_picking_product_assortment/i18n/stock_picking_product_assortment.pot
  stock_picking_product_assortment/models/__init__.py
  stock_picking_product_assortment/models/stock_move.py
  stock_picking_product_assortment/models/stock_move_line.py
  stock_picking_product_assortment/models/stock_picking.py
  stock_picking_product_assortment/readme/CONFIGURE.rst
  stock_picking_product_assortment/readme/CONTRIBUTORS.rst
  stock_picking_product_assortment/readme/DESCRIPTION.rst
  stock_picking_product_assortment/readme/USAGE.rst
  stock_picking_product_assortment/static/description/icon.png
  stock_picking_product_assortment/static/description/index.html
  stock_picking_product_assortment/tests/__init__.py
  stock_picking_product_assortment/tests/test_stock_picking_product_assortment.py
  stock_picking_product_assortment/views/stock_picking_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1083 [12.0][UPD] Switch to Github Actions
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  sale_order_global_stock_route/__manifest__.py
  stock_move_line_auto_fill/__manifest__.py
  stock_picking_back2draft/__manifest__.py
  stock_picking_batch_extended/__manifest__.py
  stock_picking_filter_lot/__manifest__.py
  stock_picking_invoice_link/__manifest__.py
  stock_picking_mass_action/__manifest__.py
  stock_picking_package_preparation/__manifest__.py
  stock_picking_package_preparation_line/__manifest__.py
  stock_picking_return_lot/__manifest__.py
  stock_picking_return_restricted_qty/__manifest__.py
  stock_picking_sale_order_link/__manifest__.py
  stock_shifting_end_of_lot/__manifest__.py
Labels: bot is merging ⏳

#1084 [FIX] stock_picking_purchase_order_link: remove read access to ir.actions
  stock_picking_purchase_order_link/models/stock_picking.py
Labels: enhancement, approved, bot is merging ⏳

#1080 [15.0] [MIG] sale_line_returned_qty
  sale_line_returned_qty/README.rst
  sale_line_returned_qty/__init__.py
  sale_line_returned_qty/__manifest__.py
  sale_line_returned_qty/i18n/sale_line_returned_qty.pot
  sale_line_returned_qty/models/__init__.py
  sale_line_returned_qty/models/sale_order_line.py
  sale_line_returned_qty/readme/CONTRIBUTORS.rst
  sale_line_returned_qty/readme/DESCRIPTION.rst
  sale_line_returned_qty/static/description/icon.png
  sale_line_returned_qty/static/description/index.html
  sale_line_returned_qty/tests/__init__.py
  sale_line_returned_qty/tests/test_sale_line_returned_qty.py
  sale_line_returned_qty/views/sale_order_views.xml
  setup/sale_line_returned_qty/odoo/addons/sale_line_returned_qty
  setup/sale_line_returned_qty/setup.py
Labels: approved, bot is merging ⏳

#1079 [14.0] [MIG] sale_line_returned_qty
  sale_line_returned_qty/README.rst
  sale_line_returned_qty/__init__.py
  sale_line_returned_qty/__manifest__.py
  sale_line_returned_qty/i18n/sale_line_returned_qty.pot
  sale_line_returned_qty/models/__init__.py
  sale_line_returned_qty/models/sale_order_line.py
  sale_line_returned_qty/readme/CONTRIBUTORS.rst
  sale_line_returned_qty/readme/DESCRIPTION.rst
  sale_line_returned_qty/static/description/icon.png
  sale_line_returned_qty/static/description/index.html
  sale_line_returned_qty/tests/__init__.py
  sale_line_returned_qty/tests/test_sale_line_returned_qty.py
  sale_line_returned_qty/views/sale_order_views.xml
  setup/sale_line_returned_qty/odoo/addons/sale_line_returned_qty
  setup/sale_line_returned_qty/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1089 [13.0][FIX] purchase_stock_picking_invoice_link: Incorrect relation when backorders
  purchase_stock_picking_invoice_link/models/stock_move.py
  purchase_stock_picking_invoice_link/tests/test_purchase_stock_picking_invoice_link.py
Labels: approved, bot is merging ⏳

#1090 [14.0][FIX] purchase_stock_picking_invoice_link: Incorrect relation when backorders
  purchase_stock_picking_invoice_link/models/stock_move.py
  purchase_stock_picking_invoice_link/tests/test_purchase_stock_picking_invoice_link.py
Labels: bot is merging ⏳

#1053 [13.0][ADD] stock_picking_batch_extended_account_sale_type: New module to create invoices from batch pickings setting by sale order type
  setup/stock_picking_batch_extended_account_sale_type/odoo/addons/stock_picking_batch_extended_account_sale_type
  setup/stock_picking_batch_extended_account_sale_type/setup.py
  stock_picking_batch_extended_account_sale_type/__init__.py
  stock_picking_batch_extended_account_sale_type/__manifest__.py
  stock_picking_batch_extended_account_sale_type/i18n/es.po
  stock_picking_batch_extended_account_sale_type/i18n/stock_picking_batch_extended_account_sale_type.pot
  stock_picking_batch_extended_account_sale_type/models/__init__.py
  stock_picking_batch_extended_account_sale_type/models/res_partner.py
  stock_picking_batch_extended_account_sale_type/models/sale_order_type.py
  stock_picking_batch_extended_account_sale_type/models/stock_batch_picking.py
  stock_picking_batch_extended_account_sale_type/tests/__init__.py
  stock_picking_batch_extended_account_sale_type/tests/test_stock_picking_batch_extended_account_sale_type.py
  stock_picking_batch_extended_account_sale_type/views/sale_order_type_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1087 [13.0][IMP] stock_picking_invoice_link: Allow link more than one invoice
  purchase_stock_picking_invoice_link/models/purchase_order.py
  purchase_stock_picking_invoice_link/tests/test_purchase_stock_picking_invoice_link.py
  stock_picking_invoice_link/__init__.py
  stock_picking_invoice_link/i18n/es.po
  stock_picking_invoice_link/i18n/stock_picking_invoice_link.pot
  stock_picking_invoice_link/models/sale_order.py
  stock_picking_invoice_link/tests/test_stock_picking_invoice_link.py
  stock_picking_invoice_link/wizards/__init__.py
  stock_picking_invoice_link/wizards/account_move_reversal.py
Labels: approved, bot is merging ⏳

#1100 [14.0][IMP] stock_picking_invoice_link: FW-PORT of PR 1087
  purchase_stock_picking_invoice_link/models/purchase_order.py
  purchase_stock_picking_invoice_link/tests/test_purchase_stock_picking_invoice_link.py
  stock_picking_invoice_link/__init__.py
  stock_picking_invoice_link/i18n/es.po
  stock_picking_invoice_link/i18n/stock_picking_invoice_link.pot
  stock_picking_invoice_link/models/sale_order.py
  stock_picking_invoice_link/tests/test_stock_picking_invoice_link.py
  stock_picking_invoice_link/wizards/__init__.py
  stock_picking_invoice_link/wizards/account_move_reversal.py
Labels: approved, bot is merging ⏳
