Repository OCA/stock-logistics-workflow, pull requests merged in 2022-04, with the labels that each got.

#953 s_p_group_by_partner_by_carrier: Fix translations in report
  stock_picking_group_by_partner_by_carrier/report/report_delivery_slip.py
Labels: bug, approved, ready to merge, bot is merging ⏳

#968 [14.0][ADD] stock_picking_invoice_link: add context key to get_stock_moves_link_invoice in order to allow to use it from external script
  stock_picking_invoice_link/models/sale_order.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#966 [13.0][ADD] Add new module sale_order_deliverable_rate
  sale_order_deliverable_rate/README.rst
  sale_order_deliverable_rate/__init__.py
  sale_order_deliverable_rate/__manifest__.py
  sale_order_deliverable_rate/data/decimal_precision.xml
  sale_order_deliverable_rate/i18n/fr.po
  sale_order_deliverable_rate/models/__init__.py
  sale_order_deliverable_rate/models/sale_order.py
  sale_order_deliverable_rate/models/sale_order_line.py
  sale_order_deliverable_rate/readme/CONFIGURE.rst
  sale_order_deliverable_rate/readme/CONTRIBUTORS.rst
  sale_order_deliverable_rate/readme/DESCRIPTION.rst
  sale_order_deliverable_rate/readme/USAGE.rst
  sale_order_deliverable_rate/static/description/index.html
  sale_order_deliverable_rate/tests/__init__.py
  sale_order_deliverable_rate/tests/common.py
  sale_order_deliverable_rate/tests/test_sale_order.py
  sale_order_deliverable_rate/tests/test_sale_order_line.py
  sale_order_deliverable_rate/views/sale_order.xml
  setup/sale_order_deliverable_rate/odoo/addons/sale_order_deliverable_rate
  setup/sale_order_deliverable_rate/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#993 [13.0][FIX] delivery_total_weight_from_packaging: Match license by dependencies
  delivery_total_weight_from_packaging/__manifest__.py
  stock_partner_delivery_window/__manifest__.py
Labels: bot is merging ⏳
