Repository OCA/stock-logistics-workflow, pull requests merged in 2022-01, with the labels that each got.

#947 [14.0][FIX] stock_picking_invoice_link: Read action as sudo
  stock_picking_invoice_link/models/stock_picking.py
Labels: bot is merging ⏳

#912 [14.0][MIG] stock_picking_send_by_mail: Migration to V14
  setup/stock_picking_send_by_mail/odoo/addons/stock_picking_send_by_mail
  setup/stock_picking_send_by_mail/setup.py
  stock_picking_send_by_mail/README.rst
  stock_picking_send_by_mail/__init__.py
  stock_picking_send_by_mail/__manifest__.py
  stock_picking_send_by_mail/i18n/de.po
  stock_picking_send_by_mail/i18n/es.po
  stock_picking_send_by_mail/i18n/fr.po
  stock_picking_send_by_mail/i18n/it.po
  stock_picking_send_by_mail/i18n/pt_BR.po
  stock_picking_send_by_mail/i18n/stock_picking_send_by_mail.pot
  stock_picking_send_by_mail/models/__init__.py
  stock_picking_send_by_mail/models/stock_picking.py
  stock_picking_send_by_mail/readme/CONTRIBUTORS.rst
  stock_picking_send_by_mail/readme/DESCRIPTION.rst
  stock_picking_send_by_mail/readme/USAGE.rst
  stock_picking_send_by_mail/static/description/icon.png
  stock_picking_send_by_mail/static/description/index.html
  stock_picking_send_by_mail/tests/__init__.py
  stock_picking_send_by_mail/tests/test_stock_picking_send_by_mail.py
  stock_picking_send_by_mail/views/stock_picking_view.xml
Labels: needs fixing, approved, migration, bot is merging ⏳

#950 [13.0][MIG] sale_order_global_stock_route: Migration to v13
  sale_order_global_stock_route/README.rst
  sale_order_global_stock_route/__init__.py
  sale_order_global_stock_route/__manifest__.py
  sale_order_global_stock_route/i18n/es.po
  sale_order_global_stock_route/i18n/it.po
  sale_order_global_stock_route/i18n/pt_BR.po
  sale_order_global_stock_route/i18n/sale_order_global_stock_route.pot
  sale_order_global_stock_route/models/__init__.py
  sale_order_global_stock_route/models/sale_order.py
  sale_order_global_stock_route/readme/CONFIGURE.rst
  sale_order_global_stock_route/readme/CONTRIBUTORS.rst
  sale_order_global_stock_route/readme/DESCRIPTION.rst
  sale_order_global_stock_route/readme/USAGE.rst
  sale_order_global_stock_route/static/description/icon.png
  sale_order_global_stock_route/static/description/index.html
  sale_order_global_stock_route/tests/__init__.py
  sale_order_global_stock_route/tests/test_sale_order_global_stock_route.py
  sale_order_global_stock_route/views/sale_order_views.xml
  setup/sale_order_global_stock_route/odoo/addons/sale_order_global_stock_route
  setup/sale_order_global_stock_route/setup.py
Labels: approved, bot is merging ⏳

#960 [14.0][UPD] contributors: Eficent -> ForgeFlow
  product_supplierinfo_for_customer_picking/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_picking/tests/test_product_supplierinfo_for_customer_picking.py
  stock_picking_line_sequence/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳
