Repository OCA/stock-logistics-workflow, pull requests merged in 2023-12, with the labels that each got.

#1432 [16.0][MIG ] stock_picking_product_link
  setup/stock_picking_product_link/odoo/addons/stock_picking_product_link
  setup/stock_picking_product_link/setup.py
  stock_picking_product_link/README.rst
  stock_picking_product_link/__init__.py
  stock_picking_product_link/__manifest__.py
  stock_picking_product_link/i18n/stock_picking_product_link.pot
  stock_picking_product_link/models/__init__.py
  stock_picking_product_link/models/stock_picking.py
  stock_picking_product_link/readme/CONTRIBUTORS.rst
  stock_picking_product_link/readme/CREDITS.rst
  stock_picking_product_link/readme/DESCRIPTION.rst
  stock_picking_product_link/static/description/icon.png
  stock_picking_product_link/static/description/index.html
  stock_picking_product_link/tests/__init__.py
  stock_picking_product_link/tests/test_stock_picking_product_link.py
  stock_picking_product_link/views/stock_picking_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1443 [14.0][IMP] stock_restrict_lot: validate lot moved is correct
  stock_restrict_lot/README.rst
  stock_restrict_lot/models/stock_move.py
  stock_restrict_lot/readme/CONTRIBUTORS.rst
  stock_restrict_lot/static/description/index.html
  stock_restrict_lot/tests/test_restrict_lot.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1442 [ADD] stock_restrict_lot_update
  setup/stock_restrict_lot_update/odoo/addons/stock_restrict_lot_update
  setup/stock_restrict_lot_update/setup.py
  stock_restrict_lot_update/README.rst
  stock_restrict_lot_update/__init__.py
  stock_restrict_lot_update/__manifest__.py
  stock_restrict_lot_update/models/__init__.py
  stock_restrict_lot_update/models/res_company.py
  stock_restrict_lot_update/models/res_config_settings.py
  stock_restrict_lot_update/models/stock_move.py
  stock_restrict_lot_update/readme/CONTEXT.rst
  stock_restrict_lot_update/readme/CONTRIBUTORS.rst
  stock_restrict_lot_update/readme/DESCRIPTION.rst
  stock_restrict_lot_update/readme/USAGE.rst
  stock_restrict_lot_update/static/description/icon.png
  stock_restrict_lot_update/static/description/index.html
  stock_restrict_lot_update/tests/__init__.py
  stock_restrict_lot_update/tests/test_restrict_lot_update.py
  stock_restrict_lot_update/views/res_config_settings_views.xml
  stock_restrict_lot_update/views/stock_picking_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1446 [17.0][MIG] stock_picking_invoice_link: Migration to 17.0
  stock_picking_invoice_link/README.rst
  stock_picking_invoice_link/__init__.py
  stock_picking_invoice_link/__manifest__.py
  stock_picking_invoice_link/i18n/ca.po
  stock_picking_invoice_link/i18n/de.po
  stock_picking_invoice_link/i18n/es.po
  stock_picking_invoice_link/i18n/es_MX.po
  stock_picking_invoice_link/i18n/fi.po
  stock_picking_invoice_link/i18n/fr.po
  stock_picking_invoice_link/i18n/hr.po
  stock_picking_invoice_link/i18n/it.po
  stock_picking_invoice_link/i18n/nl_NL.po
  stock_picking_invoice_link/i18n/pt.po
  stock_picking_invoice_link/i18n/pt_BR.po
  stock_picking_invoice_link/i18n/sl.po
  stock_picking_invoice_link/i18n/stock_picking_invoice_link.pot
  stock_picking_invoice_link/i18n/tr.po
  stock_picking_invoice_link/i18n/tr_TR.po
  stock_picking_invoice_link/models/__init__.py
  stock_picking_invoice_link/models/account_move.py
  stock_picking_invoice_link/models/sale_order.py
  stock_picking_invoice_link/models/stock_move.py
  stock_picking_invoice_link/models/stock_picking.py
  stock_picking_invoice_link/pyproject.toml
  stock_picking_invoice_link/readme/CONTRIBUTORS.md
  stock_picking_invoice_link/readme/CREDITS.md
  stock_picking_invoice_link/readme/DESCRIPTION.md
  stock_picking_invoice_link/readme/USAGE.md
  stock_picking_invoice_link/static/description/icon.png
  stock_picking_invoice_link/static/description/index.html
  stock_picking_invoice_link/tests/__init__.py
  stock_picking_invoice_link/tests/test_stock_picking_invoice_link.py
  stock_picking_invoice_link/views/account_invoice_view.xml
  stock_picking_invoice_link/views/stock_view.xml
  stock_picking_invoice_link/wizards/__init__.py
  stock_picking_invoice_link/wizards/account_move_reversal.py
Labels: needs review, migration, bot is merging ⏳

#1165 [MIG][16.0] stock_picking_group_by_partner_by_carrier
  setup/stock_picking_group_by_partner_by_carrier/odoo/addons/stock_picking_group_by_partner_by_carrier
  setup/stock_picking_group_by_partner_by_carrier/setup.py
  stock_picking_group_by_partner_by_carrier/README.rst
  stock_picking_group_by_partner_by_carrier/__init__.py
  stock_picking_group_by_partner_by_carrier/__manifest__.py
  stock_picking_group_by_partner_by_carrier/i18n/de.po
  stock_picking_group_by_partner_by_carrier/i18n/fr.po
  stock_picking_group_by_partner_by_carrier/i18n/it.po
  stock_picking_group_by_partner_by_carrier/i18n/stock_picking_group_by_partner_by_carrier.pot
  stock_picking_group_by_partner_by_carrier/models/__init__.py
  stock_picking_group_by_partner_by_carrier/models/procurement_group.py
  stock_picking_group_by_partner_by_carrier/models/res_partner.py
  stock_picking_group_by_partner_by_carrier/models/sale_order.py
  stock_picking_group_by_partner_by_carrier/models/sale_order_line.py
  stock_picking_group_by_partner_by_carrier/models/stock_move.py
  stock_picking_group_by_partner_by_carrier/models/stock_picking.py
  stock_picking_group_by_partner_by_carrier/models/stock_picking_type.py
  stock_picking_group_by_partner_by_carrier/models/stock_rule.py
  stock_picking_group_by_partner_by_carrier/models/stock_warehouse.py
  stock_picking_group_by_partner_by_carrier/readme/CONFIGURE.rst
  stock_picking_group_by_partner_by_carrier/readme/CONTRIBUTORS.rst
  stock_picking_group_by_partner_by_carrier/readme/CREDITS.rst
  stock_picking_group_by_partner_by_carrier/readme/DESCRIPTION.rst
  stock_picking_group_by_partner_by_carrier/readme/USAGE.rst
  stock_picking_group_by_partner_by_carrier/report/__init__.py
  stock_picking_group_by_partner_by_carrier/report/report_delivery_slip.py
  stock_picking_group_by_partner_by_carrier/report/report_delivery_slip.xml
  stock_picking_group_by_partner_by_carrier/security/ir.model.access.csv
  stock_picking_group_by_partner_by_carrier/static/description/icon.png
  stock_picking_group_by_partner_by_carrier/static/description/index.html
  stock_picking_group_by_partner_by_carrier/static/src/scss/report_delivery_slip.scss
  stock_picking_group_by_partner_by_carrier/tests/__init__.py
  stock_picking_group_by_partner_by_carrier/tests/common.py
  stock_picking_group_by_partner_by_carrier/tests/test_grouping.py
  stock_picking_group_by_partner_by_carrier/tests/test_grouping_disable_on_partner.py
  stock_picking_group_by_partner_by_carrier/tests/test_merge_wizard.py
  stock_picking_group_by_partner_by_carrier/tests/test_report.py
  stock_picking_group_by_partner_by_carrier/views/res_partner.xml
  stock_picking_group_by_partner_by_carrier/views/stock_picking_type.xml
  stock_picking_group_by_partner_by_carrier/views/stock_warehouse.xml
  stock_picking_group_by_partner_by_carrier/wizards/__init__.py
  stock_picking_group_by_partner_by_carrier/wizards/stock_picking_merge_wiz.py
  stock_picking_group_by_partner_by_carrier/wizards/stock_picking_merge_wiz.xml
  stock_picking_group_by_partner_by_carrier/wizards/stock_picking_merge_wiz_info_template.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1455 [15.0][IMP] stock_landed_costs_purchase_auto: FWP changes from 14.0
  stock_landed_costs_delivery/README.rst
  stock_landed_costs_delivery/models/__init__.py
  stock_landed_costs_delivery/models/purchase_order.py
  stock_landed_costs_delivery/models/stock_picking.py
  stock_landed_costs_delivery/readme/USAGE.rst
  stock_landed_costs_delivery/static/description/index.html
  stock_landed_costs_delivery/tests/test_purchase_order.py
  stock_landed_costs_purchase_auto/models/__init__.py
  stock_landed_costs_purchase_auto/models/purchase_order.py
  stock_landed_costs_purchase_auto/models/stock_picking.py
  stock_landed_costs_purchase_auto/tests/common.py
  stock_landed_costs_purchase_auto/tests/test_purchase_order.py
Labels: approved, bot is merging ⏳

#1458 [14.0] [IMP] stock_picking_inter_warehouse: sync picking on validate
  stock_picking_inter_warehouse/models/stock_move.py
  stock_picking_inter_warehouse/models/stock_rule.py
Labels: approved, bot is merging ⏳

#1457 [14.0] [FIX] stock_picking_inter_warehouse: fix destination location
  stock_picking_inter_warehouse/models/stock_picking.py
  stock_picking_inter_warehouse/tests/test_stock_picking_inter_warehouse.py
Labels: approved, bot is merging ⏳

#1434 [16.0][REF] stock_move_line_auto_fill
  stock_move_line_auto_fill/models/stock_move.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1384 [15.0][MIG] stock_picking_customer_ref to v15
  setup/stock_picking_customer_ref/odoo/addons/stock_picking_customer_ref
  setup/stock_picking_customer_ref/setup.py
  stock_picking_customer_ref/README.rst
  stock_picking_customer_ref/__init__.py
  stock_picking_customer_ref/__manifest__.py
  stock_picking_customer_ref/i18n/de.po
  stock_picking_customer_ref/i18n/es.po
  stock_picking_customer_ref/i18n/fr.po
  stock_picking_customer_ref/i18n/hr.po
  stock_picking_customer_ref/i18n/it.po
  stock_picking_customer_ref/i18n/nl.po
  stock_picking_customer_ref/i18n/pt.po
  stock_picking_customer_ref/i18n/pt_BR.po
  stock_picking_customer_ref/i18n/sl_SI.po
  stock_picking_customer_ref/i18n/stock_picking_customer_ref.pot
  stock_picking_customer_ref/models/__init__.py
  stock_picking_customer_ref/models/stock_picking.py
  stock_picking_customer_ref/readme/CONTRIBUTORS.rst
  stock_picking_customer_ref/readme/CREDITS.rst
  stock_picking_customer_ref/readme/DESCRIPTION.rst
  stock_picking_customer_ref/readme/USAGE.rst
  stock_picking_customer_ref/static/description/icon.png
  stock_picking_customer_ref/static/description/index.html
  stock_picking_customer_ref/tests/__init__.py
  stock_picking_customer_ref/tests/test_stock_picking_customer_ref.py
  stock_picking_customer_ref/views/stock_picking_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1448 [14.0] Create module sale_purchase_stock_line_note
  sale_purchase_stock_line_note/README.rst
  sale_purchase_stock_line_note/__init__.py
  sale_purchase_stock_line_note/__manifest__.py
  sale_purchase_stock_line_note/models/__init__.py
  sale_purchase_stock_line_note/models/purchase_order_line.py
  sale_purchase_stock_line_note/models/sale_order_line.py
  sale_purchase_stock_line_note/models/stock_move.py
  sale_purchase_stock_line_note/models/stock_rule.py
  sale_purchase_stock_line_note/readme/CONTRIBUTORS.md
  sale_purchase_stock_line_note/readme/DESCRIPTION.md
  sale_purchase_stock_line_note/tests/__init__.py
  sale_purchase_stock_line_note/tests/test_sale_stock_purchase_line_note.py
  sale_purchase_stock_line_note/views/purchase_order.xml
  sale_purchase_stock_line_note/views/stock_picking.xml
  setup/sale_purchase_stock_line_note/odoo/addons/sale_purchase_stock_line_note
  setup/sale_purchase_stock_line_note/setup.py
Labels: approved, ready to merge, bot is merging ⏳
