Repository OCA/stock-logistics-workflow, pull requests merged in 2023-10, with the labels that each got.

#1216 [15.0][ADD] stock_remote_measure: New module
  setup/stock_remote_measure/odoo/addons/stock_remote_measure
  setup/stock_remote_measure/setup.py
  stock_remote_measure/README.rst
  stock_remote_measure/__init__.py
  stock_remote_measure/__manifest__.py
  stock_remote_measure/models/__init__.py
  stock_remote_measure/models/stock_move_line.py
  stock_remote_measure/models/stock_picking.py
  stock_remote_measure/models/stock_picking_type.py
  stock_remote_measure/readme/CONFIGURE.rst
  stock_remote_measure/readme/CONTRIBUTORS.rst
  stock_remote_measure/readme/DESCRIPTION.rst
  stock_remote_measure/readme/ROADMAP.rst
  stock_remote_measure/readme/USAGE.rst
  stock_remote_measure/static/description/index.html
  stock_remote_measure/views/stock_move_line_views.xml
  stock_remote_measure/views/stock_picking_type_views.xml
  stock_remote_measure/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳, stale

#1329 [IMP] stock_quant_package_dimension: Don't rely on max_weight on product.packaging + change weight_uom_name type
  stock_quant_package_dimension/models/stock_quant_package.py
  stock_quant_package_dimension/tests/common.py
  stock_quant_package_dimension/tests/test_package_dimension.py
Labels: needs review, approved, bot is merging ⏳

#1021 [15.0][MIG] product_supplierinfo_for_customer_picking
  product_supplierinfo_for_customer_picking/README.rst
  product_supplierinfo_for_customer_picking/__init__.py
  product_supplierinfo_for_customer_picking/__manifest__.py
  product_supplierinfo_for_customer_picking/i18n/de.po
  product_supplierinfo_for_customer_picking/i18n/it.po
  product_supplierinfo_for_customer_picking/i18n/product_supplierinfo_for_customer_picking.pot
  product_supplierinfo_for_customer_picking/i18n/pt_BR.po
  product_supplierinfo_for_customer_picking/models/__init__.py
  product_supplierinfo_for_customer_picking/models/stock_move.py
  product_supplierinfo_for_customer_picking/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_picking/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer_picking/static/description/icon.png
  product_supplierinfo_for_customer_picking/static/description/index.html
  product_supplierinfo_for_customer_picking/tests/__init__.py
  product_supplierinfo_for_customer_picking/tests/test_product_supplierinfo_for_customer_picking.py
  product_supplierinfo_for_customer_picking/views/stock_picking_view.xml
  setup/product_supplierinfo_for_customer_picking/odoo/addons/product_supplierinfo_for_customer_picking
  setup/product_supplierinfo_for_customer_picking/setup.py
Labels: duplicate, needs review, approved, migration, ready to merge, bot is merging ⏳

#1378 [16.0][ADD] stock_partner_delivery_window
  setup/stock_partner_delivery_window/odoo/addons/stock_partner_delivery_window
  setup/stock_partner_delivery_window/setup.py
  stock_partner_delivery_window/README.rst
  stock_partner_delivery_window/__init__.py
  stock_partner_delivery_window/__manifest__.py
  stock_partner_delivery_window/demo/delivery_time_window.xml
  stock_partner_delivery_window/i18n/stock_partner_delivery_window.pot
  stock_partner_delivery_window/models/__init__.py
  stock_partner_delivery_window/models/delivery_time_window.py
  stock_partner_delivery_window/models/res_partner.py
  stock_partner_delivery_window/models/stock_picking.py
  stock_partner_delivery_window/readme/CONFIGURE.rst
  stock_partner_delivery_window/readme/CONTRIBUTORS.rst
  stock_partner_delivery_window/readme/CREDITS.rst
  stock_partner_delivery_window/readme/DESCRIPTION.rst
  stock_partner_delivery_window/security/ir.model.access.csv
  stock_partner_delivery_window/static/description/icon.png
  stock_partner_delivery_window/static/description/index.html
  stock_partner_delivery_window/tests/__init__.py
  stock_partner_delivery_window/tests/test_delivery_window.py
  stock_partner_delivery_window/views/res_partner.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1271 [14.0][MIG] product_expiry_simple #tryagain
  .copier-answers.yml
  .github/workflows/test.yml
  README.md
  product_expiry_simple/README.rst
  product_expiry_simple/__init__.py
  product_expiry_simple/__manifest__.py
  product_expiry_simple/data/product_removal.xml
  product_expiry_simple/i18n/de.po
  product_expiry_simple/i18n/es.po
  product_expiry_simple/i18n/it.po
  product_expiry_simple/i18n/nl_NL.po
  product_expiry_simple/i18n/product_expiry_simple.pot
  product_expiry_simple/i18n/sl.po
  product_expiry_simple/models/__init__.py
  product_expiry_simple/models/stock_move_line.py
  product_expiry_simple/models/stock_picking.py
  product_expiry_simple/models/stock_production_lot.py
  product_expiry_simple/models/stock_quant.py
  product_expiry_simple/readme/CONTRIBUTORS.rst
  product_expiry_simple/readme/DESCRIPTION.rst
  product_expiry_simple/static/description/icon.png
  product_expiry_simple/views/stock_move_line.xml
  product_expiry_simple/views/stock_picking.xml
  product_expiry_simple/views/stock_production_lot.xml
  product_expiry_simple/views/stock_quant.xml
  setup/product_expiry_simple/odoo/addons/product_expiry_simple
  setup/product_expiry_simple/setup.py
Labels: approved, bot is merging ⏳, no stale

#1316 [16.0][MIG] stock_picking_line_sequence
  setup/stock_picking_line_sequence/odoo/addons/stock_picking_line_sequence
  setup/stock_picking_line_sequence/setup.py
  stock_picking_line_sequence/README.rst
  stock_picking_line_sequence/__init__.py
  stock_picking_line_sequence/__manifest__.py
  stock_picking_line_sequence/i18n/ca.po
  stock_picking_line_sequence/i18n/de.po
  stock_picking_line_sequence/i18n/es.po
  stock_picking_line_sequence/i18n/es_MX.po
  stock_picking_line_sequence/i18n/fi.po
  stock_picking_line_sequence/i18n/fr.po
  stock_picking_line_sequence/i18n/hr.po
  stock_picking_line_sequence/i18n/it.po
  stock_picking_line_sequence/i18n/nl_NL.po
  stock_picking_line_sequence/i18n/pt.po
  stock_picking_line_sequence/i18n/pt_BR.po
  stock_picking_line_sequence/i18n/sl.po
  stock_picking_line_sequence/i18n/stock_picking_line_sequence.pot
  stock_picking_line_sequence/i18n/tr.po
  stock_picking_line_sequence/i18n/tr_TR.po
  stock_picking_line_sequence/init_hooks.py
  stock_picking_line_sequence/models/__init__.py
  stock_picking_line_sequence/models/stock.py
  stock_picking_line_sequence/readme/CONTRIBUTORS.rst
  stock_picking_line_sequence/readme/DESCRIPTION.rst
  stock_picking_line_sequence/readme/USAGE.rst
  stock_picking_line_sequence/report/report_deliveryslip.xml
  stock_picking_line_sequence/static/description/icon.png
  stock_picking_line_sequence/static/description/index.html
  stock_picking_line_sequence/tests/__init__.py
  stock_picking_line_sequence/tests/test_move_lines_sequence.py
  stock_picking_line_sequence/views/stock_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1398 [13.0][FIX] product_cost_price_avco_sync: Avoid infinite loop writing current SVL
  product_cost_price_avco_sync/models/stock_valuation_layer.py
Labels: bot is merging ⏳

#1395 [16.0] [MIG] stock_picking_batch_extended_account
  setup/stock_picking_batch_extended_account/odoo/addons/stock_picking_batch_extended_account
  setup/stock_picking_batch_extended_account/setup.py
  stock_picking_batch_extended_account/README.rst
  stock_picking_batch_extended_account/__init__.py
  stock_picking_batch_extended_account/__manifest__.py
  stock_picking_batch_extended_account/i18n/es.po
  stock_picking_batch_extended_account/i18n/stock_picking_batch_extended_account.pot
  stock_picking_batch_extended_account/models/__init__.py
  stock_picking_batch_extended_account/models/res_partner.py
  stock_picking_batch_extended_account/models/stock_batch_picking.py
  stock_picking_batch_extended_account/models/stock_picking.py
  stock_picking_batch_extended_account/readme/CONFIGURE.rst
  stock_picking_batch_extended_account/readme/CONTRIBUTORS.rst
  stock_picking_batch_extended_account/readme/DESCRIPTION.rst
  stock_picking_batch_extended_account/readme/USAGE.rst
  stock_picking_batch_extended_account/static/description/icon.png
  stock_picking_batch_extended_account/static/description/index.html
  stock_picking_batch_extended_account/tests/__init__.py
  stock_picking_batch_extended_account/tests/test_stock_picking_batch_extended_account.py
  stock_picking_batch_extended_account/views/res_partner_views.xml
  stock_picking_batch_extended_account/views/stock_batch_picking.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1396 [16.0] [MIG] stock_picking_batch_extended_account_sale_type
  setup/stock_picking_batch_extended_account_sale_type/odoo/addons/stock_picking_batch_extended_account_sale_type
  setup/stock_picking_batch_extended_account_sale_type/setup.py
  stock_picking_batch_extended_account_sale_type/README.rst
  stock_picking_batch_extended_account_sale_type/__init__.py
  stock_picking_batch_extended_account_sale_type/__manifest__.py
  stock_picking_batch_extended_account_sale_type/i18n/es.po
  stock_picking_batch_extended_account_sale_type/i18n/stock_picking_batch_extended_account_sale_type.pot
  stock_picking_batch_extended_account_sale_type/models/__init__.py
  stock_picking_batch_extended_account_sale_type/models/res_partner.py
  stock_picking_batch_extended_account_sale_type/models/sale_order_type.py
  stock_picking_batch_extended_account_sale_type/models/stock_batch_picking.py
  stock_picking_batch_extended_account_sale_type/readme/CONTRIBUTORS.rst
  stock_picking_batch_extended_account_sale_type/readme/DESCRIPTION.rst
  stock_picking_batch_extended_account_sale_type/static/description/icon.png
  stock_picking_batch_extended_account_sale_type/static/description/index.html
  stock_picking_batch_extended_account_sale_type/tests/__init__.py
  stock_picking_batch_extended_account_sale_type/tests/test_stock_picking_batch_extended_account_sale_type.py
  stock_picking_batch_extended_account_sale_type/views/sale_order_type_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1392 [15.0][MIG] stock_picking_import_serial_number: Migration to version 15.0
  requirements.txt
  setup/stock_picking_import_serial_number/odoo/addons/stock_picking_import_serial_number
  setup/stock_picking_import_serial_number/setup.py
  stock_picking_import_serial_number/README.rst
  stock_picking_import_serial_number/__init__.py
  stock_picking_import_serial_number/__manifest__.py
  stock_picking_import_serial_number/i18n/es.po
  stock_picking_import_serial_number/i18n/stock_picking_import_serial_number.pot
  stock_picking_import_serial_number/models/__init__.py
  stock_picking_import_serial_number/models/res_config_settings.py
  stock_picking_import_serial_number/readme/CONFIGURE.rst
  stock_picking_import_serial_number/readme/CONTRIBUTORS.rst
  stock_picking_import_serial_number/readme/DESCRIPTION.rst
  stock_picking_import_serial_number/readme/USAGE.rst
  stock_picking_import_serial_number/security/ir.model.access.csv
  stock_picking_import_serial_number/static/description/icon.png
  stock_picking_import_serial_number/static/description/index.html
  stock_picking_import_serial_number/tests/__init__.py
  stock_picking_import_serial_number/tests/common.py
  stock_picking_import_serial_number/tests/test_stock_picking_import_serial_number.py
  stock_picking_import_serial_number/views/res_config_settings_views.xml
  stock_picking_import_serial_number/views/stock_picking.xml
  stock_picking_import_serial_number/wizard/__init__.py
  stock_picking_import_serial_number/wizard/import_serial_number_view.xml
  stock_picking_import_serial_number/wizard/import_serial_number_wizard.py
Labels: approved, ready to merge, bot is merging ⏳

#1399 [16.0][FIX] stock_picking_batch_extended: correction of the url of the read…
  stock_picking_batch_extended/README.rst
  stock_picking_batch_extended/readme/CONFIGURE.rst
  stock_picking_batch_extended/readme/DESCRIPTION.rst
  stock_picking_batch_extended/readme/USAGE.rst
  stock_picking_batch_extended/static/batch_form.jpg
  stock_picking_batch_extended/static/batch_form_done.png
  stock_picking_batch_extended/static/batch_form_draft.png
  stock_picking_batch_extended/static/batch_form_in_progress.png
  stock_picking_batch_extended/static/batch_form_operation.jpg
  stock_picking_batch_extended/static/batch_wizard.jpg
  stock_picking_batch_extended/static/batch_wizard.png
  stock_picking_batch_extended/static/description/index.html
  stock_picking_batch_extended/static/picking_batch_configuration_settings.jpg
  stock_picking_batch_extended/static/picking_batch_configuration_settings.png
  stock_picking_batch_extended/static/stock_picking_list.jpg
Labels: needs review, approved, bot is merging ⏳

#1406 [16.0] [FIX] stock_picking_batch_extended_account: Remove `stock_picking_batch_extended` dependency
  stock_picking_batch_extended_account/__manifest__.py
  stock_picking_batch_extended_account/readme/CONTRIBUTORS.rst
  stock_picking_batch_extended_account/tests/test_stock_picking_batch_extended_account.py
  stock_picking_batch_extended_account/views/stock_batch_picking.xml
  stock_picking_batch_extended_account_sale_type/tests/test_stock_picking_batch_extended_account_sale_type.py
Labels: needs review, approved, bot is merging ⏳

#1401 [14.0][IMP] update copier template
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  sale_stock_mto_as_mts_orderpoint/data/stock_data.xml
  stock_move_change_source_location/wizards/stock_move_change_source_location_wizard.xml
  stock_picking_batch_extended/views/stock_batch_picking.xml
  stock_picking_batch_extended/wizard/batch_picking_creator_view.xml
  stock_picking_cancel_reason/views/stock_picking_views.xml
  stock_picking_filter_lot/views/stock_picking_type_view.xml
  stock_picking_group_by_partner_by_carrier/report/report_delivery_slip.xml
  stock_picking_import_serial_number/views/res_config_settings_views.xml
  stock_picking_progress/migrations/14.0.1.1.0/post-migrate.py
  stock_picking_progress/migrations/14.0.1.1.0/pre-migrate.py
  stock_picking_progress/migrations/14.0.1.2.0/post-migrate.py
  stock_picking_progress/migrations/14.0.1.2.0/pre-migrate.py
  stock_picking_quick/views/product_view.xml
  stock_return_request/views/stock_return_request_views.xml
  stock_split_picking/wizards/stock_split_picking.xml
Labels: bot is merging ⏳

#1412 [15.0][IMP] stock-logistics-workflow : test performance improvement
  product_cost_price_avco_sync/tests/test_product_cost_price_avco_sync.py
  stock_move_line_auto_fill/tests/test_stock_picking_auto_fill.py
  stock_owner_restriction/tests/test_stock_owner_restriction.py
  stock_picking_auto_create_lot/tests/common.py
  stock_picking_batch_extended_account/tests/test_stock_picking_batch_extended_account.py
  stock_picking_batch_extended_account_sale_type/tests/test_stock_picking_batch_extended_account_sale_type.py
  stock_picking_invoice_link/tests/test_stock_picking_invoice_link.py
  stock_picking_mass_action/tests/test_mass_action.py
  stock_picking_product_availability_inline/tests/test_stock_picking_product_availability_inline.py
  stock_picking_return_restricted_qty/tests/test_stock_picking_return_restricted_qty.py
  stock_picking_sale_order_link/tests/test_stock_picking_sale_order_link.py
  stock_picking_send_by_mail/tests/test_stock_picking_send_by_mail.py
  stock_picking_whole_scrap/tests/test_stock_picking_whole_scrap.py
Labels: bot is merging ⏳

#1348 16.0 mig stock picking customer ref
  setup/stock_picking_customer_ref/odoo/addons/stock_picking_customer_ref
  setup/stock_picking_customer_ref/setup.py
  stock_picking_customer_ref/README.rst
  stock_picking_customer_ref/__init__.py
  stock_picking_customer_ref/__manifest__.py
  stock_picking_customer_ref/i18n/de.po
  stock_picking_customer_ref/i18n/es.po
  stock_picking_customer_ref/i18n/fr.po
  stock_picking_customer_ref/i18n/hr.po
  stock_picking_customer_ref/i18n/it.po
  stock_picking_customer_ref/i18n/nl.po
  stock_picking_customer_ref/i18n/pt.po
  stock_picking_customer_ref/i18n/pt_BR.po
  stock_picking_customer_ref/i18n/sl_SI.po
  stock_picking_customer_ref/i18n/stock_picking_customer_ref.pot
  stock_picking_customer_ref/models/__init__.py
  stock_picking_customer_ref/models/stock_picking.py
  stock_picking_customer_ref/readme/CONTRIBUTORS.rst
  stock_picking_customer_ref/readme/CREDITS.rst
  stock_picking_customer_ref/readme/DESCRIPTION.rst
  stock_picking_customer_ref/readme/USAGE.rst
  stock_picking_customer_ref/static/description/icon.png
  stock_picking_customer_ref/static/description/index.html
  stock_picking_customer_ref/tests/__init__.py
  stock_picking_customer_ref/tests/test_stock_picking_customer_ref.py
  stock_picking_customer_ref/views/stock_picking_view.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1413 delivery_procurement_group_carrier: Bump dev status
  delivery_procurement_group_carrier/__manifest__.py
Labels: bot is merging ⏳

#1414 [16.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  stock_partner_delivery_window/i18n/es.po
  stock_partner_delivery_window/i18n/stock_partner_delivery_window.pot
  stock_partner_delivery_window/models/res_partner.py
  stock_partner_delivery_window/models/stock_picking.py
  stock_putaway_hook/tests/model.py
Labels: help wanted, needs review, bot is merging ⏳

#1409 [14.0] stock_picking_group_by_partner_by_carrier: Bump dev status
  stock_picking_group_by_partner_by_carrier/__manifest__.py
Labels: approved, bot is merging ⏳

#1415 [14.0][MIG] stock_landed_costs_security: Migration to 14.0
  setup/stock_landed_costs_security/odoo/addons/stock_landed_costs_security
  setup/stock_landed_costs_security/setup.py
  stock_landed_costs_security/README.rst
  stock_landed_costs_security/__init__.py
  stock_landed_costs_security/__manifest__.py
  stock_landed_costs_security/i18n/stock_landed_costs_security.pot
  stock_landed_costs_security/readme/CONFIGURE.rst
  stock_landed_costs_security/readme/CONTRIBUTORS.rst
  stock_landed_costs_security/readme/DESCRIPTION.rst
  stock_landed_costs_security/readme/USAGE.rst
  stock_landed_costs_security/security/ir.model.access.csv
  stock_landed_costs_security/security/stock_landed_costs_security.xml
  stock_landed_costs_security/static/description/icon.png
  stock_landed_costs_security/static/description/icon.svg
  stock_landed_costs_security/static/description/index.html
  stock_landed_costs_security/views/stock_landed_costs_view.xml
Labels: bot is merging ⏳

#1416 [14.0][MIG] stock_landed_costs_purchase_auto: Migration to 14.0
  setup/stock_landed_costs_purchase_auto/odoo/addons/stock_landed_costs_purchase_auto
  setup/stock_landed_costs_purchase_auto/setup.py
  stock_landed_costs_purchase_auto/README.rst
  stock_landed_costs_purchase_auto/__init__.py
  stock_landed_costs_purchase_auto/__manifest__.py
  stock_landed_costs_purchase_auto/i18n/es.po
  stock_landed_costs_purchase_auto/i18n/stock_landed_costs_purchase_auto.pot
  stock_landed_costs_purchase_auto/models/__init__.py
  stock_landed_costs_purchase_auto/models/purchase_order.py
  stock_landed_costs_purchase_auto/models/stock_landed_cost.py
  stock_landed_costs_purchase_auto/readme/CONTRIBUTORS.rst
  stock_landed_costs_purchase_auto/readme/DESCRIPTION.rst
  stock_landed_costs_purchase_auto/readme/USAGE.rst
  stock_landed_costs_purchase_auto/static/description/icon.png
  stock_landed_costs_purchase_auto/static/description/index.html
  stock_landed_costs_purchase_auto/tests/__init__.py
  stock_landed_costs_purchase_auto/tests/test_purchase_order.py
  stock_landed_costs_purchase_auto/views/purchase_order_view.xml
  stock_landed_costs_purchase_auto/views/stock_landed_cost_view.xml
Labels: approved, bot is merging ⏳

#1404 [16.0] [REF] stock_picking_batch_extended: Move settings option under Batch Picking group
  stock_picking_batch_extended/README.rst
  stock_picking_batch_extended/readme/CONFIGURE.rst
  stock_picking_batch_extended/static/description/index.html
  stock_picking_batch_extended/static/picking_batch_configuration_settings.png
  stock_picking_batch_extended/views/res_config_settings_views.xml
Labels: needs review, approved, bot is merging ⏳
