Repository OCA/stock-logistics-workflow, pull requests merged in 2023-01, with the labels that each got.

#1172 [12.0] [ADD] `stock_production_lot_traceability`
  setup/stock_production_lot_traceability/odoo/addons/stock_production_lot_traceability
  setup/stock_production_lot_traceability/setup.py
  stock_production_lot_traceability/__init__.py
  stock_production_lot_traceability/__manifest__.py
  stock_production_lot_traceability/models/__init__.py
  stock_production_lot_traceability/models/stock_move_line.py
  stock_production_lot_traceability/models/stock_production_lot.py
  stock_production_lot_traceability/readme/CONTRIBUTORS.rst
  stock_production_lot_traceability/readme/DESCRIPTION.rst
  stock_production_lot_traceability/readme/USAGE.rst
  stock_production_lot_traceability/tests/__init__.py
  stock_production_lot_traceability/tests/common.py
  stock_production_lot_traceability/tests/test_stock_lot_traceability.py
  stock_production_lot_traceability/views/stock_production_lot.xml
Labels: approved, ready to merge, bot is merging ⏳

#1181 [15.0][IMP] stock_picking_invoice_link: change development status
  stock_picking_invoice_link/__manifest__.py
Labels: approved, bot is merging ⏳

#1003 [14.0][MIG] sale_order_global_stock_route: Migration to 14.0
  sale_order_global_stock_route/README.rst
  sale_order_global_stock_route/__init__.py
  sale_order_global_stock_route/__manifest__.py
  sale_order_global_stock_route/i18n/es.po
  sale_order_global_stock_route/i18n/it.po
  sale_order_global_stock_route/i18n/pt_BR.po
  sale_order_global_stock_route/i18n/sale_order_global_stock_route.pot
  sale_order_global_stock_route/models/__init__.py
  sale_order_global_stock_route/models/sale_order.py
  sale_order_global_stock_route/readme/CONFIGURE.rst
  sale_order_global_stock_route/readme/CONTRIBUTORS.rst
  sale_order_global_stock_route/readme/DESCRIPTION.rst
  sale_order_global_stock_route/readme/USAGE.rst
  sale_order_global_stock_route/static/description/icon.png
  sale_order_global_stock_route/static/description/index.html
  sale_order_global_stock_route/tests/__init__.py
  sale_order_global_stock_route/tests/test_sale_order_global_stock_route.py
  sale_order_global_stock_route/views/sale_order_views.xml
  setup/sale_order_global_stock_route/odoo/addons/sale_order_global_stock_route
  setup/sale_order_global_stock_route/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1135 [14.0][IMP] stock_picking_invoice_link: Add support to order invoice policy
  stock_picking_invoice_link/models/stock_move.py
  stock_picking_invoice_link/tests/test_stock_picking_invoice_link.py
Labels: approved, bot is merging ⏳

#1180 [15.0][MIG] purchase_stock_picking_invoice_link: Migration to version 15.0
  purchase_stock_picking_invoice_link/README.rst
  purchase_stock_picking_invoice_link/__init__.py
  purchase_stock_picking_invoice_link/__manifest__.py
  purchase_stock_picking_invoice_link/i18n/es.po
  purchase_stock_picking_invoice_link/i18n/purchase_stock_picking_invoice_link.pot
  purchase_stock_picking_invoice_link/models/__init__.py
  purchase_stock_picking_invoice_link/models/purchase_order.py
  purchase_stock_picking_invoice_link/models/stock_move.py
  purchase_stock_picking_invoice_link/readme/CONTRIBUTORS.rst
  purchase_stock_picking_invoice_link/readme/DESCRIPTION.rst
  purchase_stock_picking_invoice_link/readme/USAGE.rst
  purchase_stock_picking_invoice_link/static/description/icon.png
  purchase_stock_picking_invoice_link/static/description/index.html
  purchase_stock_picking_invoice_link/tests/__init__.py
  purchase_stock_picking_invoice_link/tests/test_purchase_stock_picking_invoice_link.py
  setup/purchase_stock_picking_invoice_link/odoo/addons/purchase_stock_picking_invoice_link
  setup/purchase_stock_picking_invoice_link/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1162 [14.0][ADD] stock_lot_production_date
  setup/stock_lot_production_date/odoo/addons/stock_lot_production_date
  setup/stock_lot_production_date/setup.py
  stock_lot_production_date/README.rst
  stock_lot_production_date/__init__.py
  stock_lot_production_date/__manifest__.py
  stock_lot_production_date/models/__init__.py
  stock_lot_production_date/models/stock_lot.py
  stock_lot_production_date/readme/CONTRIBUTORS.rst
  stock_lot_production_date/readme/CREDITS.rst
  stock_lot_production_date/readme/DESCRIPTION.rst
  stock_lot_production_date/readme/USAGE.rst
  stock_lot_production_date/static/description/index.html
  stock_lot_production_date/static/description/lot.png
  stock_lot_production_date/views/stock_lot.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1050 [14.0] [FIX] delivery_total_weight_from_packaging: keep package weight on picking transfer
  delivery_total_weight_from_packaging/README.rst
  delivery_total_weight_from_packaging/models/stock_quant_package.py
  delivery_total_weight_from_packaging/readme/CONTRIBUTORS.rst
  delivery_total_weight_from_packaging/tests/test_weight_from_packaging.py
Labels: bug, bot is merging ⏳

#1125 [15.0][MIG] stock_move_quick_lot: Migration to version 15.0
  setup/stock_move_quick_lot/odoo/addons/stock_move_quick_lot
  setup/stock_move_quick_lot/setup.py
  stock_move_quick_lot/README.rst
  stock_move_quick_lot/__init__.py
  stock_move_quick_lot/__manifest__.py
  stock_move_quick_lot/i18n/es.po
  stock_move_quick_lot/i18n/stock_move_quick_lot.pot
  stock_move_quick_lot/i18n/stock_pack_operation_quick_lot.pot
  stock_move_quick_lot/models/__init__.py
  stock_move_quick_lot/models/stock_move.py
  stock_move_quick_lot/readme/CONFIGURE.rst
  stock_move_quick_lot/readme/CONTRIBUTORS.rst
  stock_move_quick_lot/readme/DESCRIPTION.rst
  stock_move_quick_lot/readme/USAGE.rst
  stock_move_quick_lot/static/description/icon.png
  stock_move_quick_lot/static/description/icon.svg
  stock_move_quick_lot/static/description/index.html
  stock_move_quick_lot/tests/__init__.py
  stock_move_quick_lot/tests/test_stock_move_quick_lot.py
  stock_move_quick_lot/views/stock_view.xml
Labels: approved, bot is merging ⏳

#1001 [15.0][MIG] stock_picking_warn_message: Migration to 15.0
  setup/stock_picking_warn_message/odoo/addons/stock_picking_warn_message
  setup/stock_picking_warn_message/setup.py
  stock_picking_warn_message/README.rst
  stock_picking_warn_message/__init__.py
  stock_picking_warn_message/__manifest__.py
  stock_picking_warn_message/i18n/stock_picking_warn_message.pot
  stock_picking_warn_message/models/__init__.py
  stock_picking_warn_message/models/stock_picking.py
  stock_picking_warn_message/readme/CONTRIBUTORS.rst
  stock_picking_warn_message/readme/DESCRIPTION.rst
  stock_picking_warn_message/static/description/icon.png
  stock_picking_warn_message/static/description/index.html
  stock_picking_warn_message/tests/__init__.py
  stock_picking_warn_message/tests/test_stock_picking_warn_message.py
  stock_picking_warn_message/views/stock_picking_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1174 [15.0] [MIG] `stock_production_lot_traceability`
  setup/stock_production_lot_traceability/odoo/addons/stock_production_lot_traceability
  setup/stock_production_lot_traceability/setup.py
  stock_production_lot_traceability/README.rst
  stock_production_lot_traceability/__init__.py
  stock_production_lot_traceability/__manifest__.py
  stock_production_lot_traceability/models/__init__.py
  stock_production_lot_traceability/models/stock_move_line.py
  stock_production_lot_traceability/models/stock_production_lot.py
  stock_production_lot_traceability/readme/CONTRIBUTORS.rst
  stock_production_lot_traceability/readme/DESCRIPTION.rst
  stock_production_lot_traceability/readme/USAGE.rst
  stock_production_lot_traceability/tests/__init__.py
  stock_production_lot_traceability/tests/common.py
  stock_production_lot_traceability/tests/test_stock_lot_traceability.py
  stock_production_lot_traceability/views/stock_production_lot.xml
Labels: approved, ready to merge, bot is merging ⏳

#1127 [16.0] [ADD] stock_picking_start: Add button start on picking form
  setup/stock_picking_start/odoo/addons/stock_picking_start
  setup/stock_picking_start/setup.py
  stock_picking_start/README.rst
  stock_picking_start/__init__.py
  stock_picking_start/__manifest__.py
  stock_picking_start/i18n/fr.po
  stock_picking_start/models/__init__.py
  stock_picking_start/models/res_company.py
  stock_picking_start/models/res_config_settings.py
  stock_picking_start/models/stock_picking.py
  stock_picking_start/readme/CONTRIBUTORS.rst
  stock_picking_start/readme/DESCRIPTION.rst
  stock_picking_start/static/description/icon.png
  stock_picking_start/static/description/index.html
  stock_picking_start/tests/__init__.py
  stock_picking_start/tests/test_stock_picking_start.py
  stock_picking_start/views/res_config_settings.xml
  stock_picking_start/views/stock_picking.xml
Labels: needs review, approved, bot is merging ⏳

#1163 [16.0][ADD] stock_grn
  setup/stock_grn/odoo/addons/stock_grn
  setup/stock_grn/setup.py
  stock_grn/README.rst
  stock_grn/__init__.py
  stock_grn/__manifest__.py
  stock_grn/data/stock_grn.xml
  stock_grn/i18n/stock_grn.pot
  stock_grn/models/__init__.py
  stock_grn/models/stock_grn.py
  stock_grn/models/stock_grn_type.py
  stock_grn/models/stock_move.py
  stock_grn/models/stock_picking.py
  stock_grn/models/stock_picking_type.py
  stock_grn/readme/CONTRIBUTORS.rst
  stock_grn/readme/DESCRIPTION.rst
  stock_grn/readme/USAGE.rst
  stock_grn/security/ir.model.access.csv
  stock_grn/security/ir_rule.xml
  stock_grn/static/description/icon.png
  stock_grn/tests/__init__.py
  stock_grn/tests/test_stock_grn.py
  stock_grn/views/stock_grn_views.xml
  stock_grn/views/stock_move_views.xml
  stock_grn/views/stock_picking_type_views.xml
  stock_grn/views/stock_picking_views.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1107 [16.0][MIG] stock_split_picking
  setup/stock_split_picking/odoo/addons/stock_split_picking
  setup/stock_split_picking/setup.py
  stock_split_picking/README.rst
  stock_split_picking/__init__.py
  stock_split_picking/__manifest__.py
  stock_split_picking/i18n/ar.po
  stock_split_picking/i18n/ca_ES.po
  stock_split_picking/i18n/de.po
  stock_split_picking/i18n/es.po
  stock_split_picking/i18n/es_MX.po
  stock_split_picking/i18n/fi.po
  stock_split_picking/i18n/fr.po
  stock_split_picking/i18n/hr.po
  stock_split_picking/i18n/it.po
  stock_split_picking/i18n/nl_NL.po
  stock_split_picking/i18n/pt.po
  stock_split_picking/i18n/pt_BR.po
  stock_split_picking/i18n/sl.po
  stock_split_picking/i18n/stock_split_picking.pot
  stock_split_picking/i18n/tr.po
  stock_split_picking/i18n/tr_TR.po
  stock_split_picking/i18n/zh_CN.po
  stock_split_picking/models/__init__.py
  stock_split_picking/models/stock_picking.py
  stock_split_picking/readme/CONTRIBUTORS.rst
  stock_split_picking/readme/DESCRIPTION.rst
  stock_split_picking/readme/USAGE.rst
  stock_split_picking/security/ir.model.access.csv
  stock_split_picking/static/description/icon.png
  stock_split_picking/static/description/index.html
  stock_split_picking/tests/__init__.py
  stock_split_picking/tests/test_stock_split_picking.py
  stock_split_picking/views/stock_partial_picking.xml
  stock_split_picking/wizards/__init__.py
  stock_split_picking/wizards/stock_split_picking.py
  stock_split_picking/wizards/stock_split_picking.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1195 [13.0][FIX] stock_return_request: missing cache
  stock_return_request/models/stock_move.py
Labels: approved, ready to merge, bot is merging ⏳

#1189 [15.0][FIX] stock_picking_filter_lot: Update location_ids correctly when creating a new inventory adjustment
  stock_picking_filter_lot/models/stock_production_lot.py
Labels: approved, bot is merging ⏳

#1198 [16.0][MIG] purchase_stock_picking_invoice_link: Migration to 16.0
  purchase_stock_picking_invoice_link/README.rst
  purchase_stock_picking_invoice_link/__init__.py
  purchase_stock_picking_invoice_link/__manifest__.py
  purchase_stock_picking_invoice_link/i18n/es.po
  purchase_stock_picking_invoice_link/i18n/purchase_stock_picking_invoice_link.pot
  purchase_stock_picking_invoice_link/models/__init__.py
  purchase_stock_picking_invoice_link/models/purchase_order.py
  purchase_stock_picking_invoice_link/models/stock_move.py
  purchase_stock_picking_invoice_link/readme/CONTRIBUTORS.rst
  purchase_stock_picking_invoice_link/readme/DESCRIPTION.rst
  purchase_stock_picking_invoice_link/readme/USAGE.rst
  purchase_stock_picking_invoice_link/static/description/icon.png
  purchase_stock_picking_invoice_link/static/description/index.html
  purchase_stock_picking_invoice_link/tests/__init__.py
  purchase_stock_picking_invoice_link/tests/test_purchase_stock_picking_invoice_link.py
  setup/purchase_stock_picking_invoice_link/odoo/addons/purchase_stock_picking_invoice_link
  setup/purchase_stock_picking_invoice_link/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳
