Repository OCA/stock-logistics-workflow, pull requests merged in 2023-04, with the labels that each got.

#1263 [16.0][IMP] stock_picking_start: Speedup install
  stock_picking_start/__init__.py
  stock_picking_start/__manifest__.py
  stock_picking_start/hooks.py
  stock_picking_start/models/stock_picking.py
Labels: approved, ready to merge, bot is merging ⏳

#1255 [12.0][MIG] stock_picking_tier_validation: Migration to 12.0
  setup/stock_picking_tier_validation/odoo/addons/stock_picking_tier_validation
  setup/stock_picking_tier_validation/setup.py
  stock_picking_tier_validation/README.rst
  stock_picking_tier_validation/__init__.py
  stock_picking_tier_validation/__manifest__.py
  stock_picking_tier_validation/i18n/stock_picking_tier_validation.pot
  stock_picking_tier_validation/models/__init__.py
  stock_picking_tier_validation/models/stock_picking.py
  stock_picking_tier_validation/models/tier_definition.py
  stock_picking_tier_validation/readme/CONFIGURE.rst
  stock_picking_tier_validation/readme/CONTRIBUTORS.rst
  stock_picking_tier_validation/readme/DESCRIPTION.rst
  stock_picking_tier_validation/readme/INSTALL.rst
  stock_picking_tier_validation/readme/USAGE.rst
  stock_picking_tier_validation/static/description/icon.png
  stock_picking_tier_validation/static/description/index.html
  stock_picking_tier_validation/tests/__init__.py
  stock_picking_tier_validation/tests/common.py
  stock_picking_tier_validation/tests/test_tier_validation.py
  stock_picking_tier_validation/tests/tier_validation_tester.py
  stock_picking_tier_validation/views/stock_picking_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1257 [MIG] stock_picking_filter_lot: Migration to 16.0
  setup/stock_picking_filter_lot/odoo/addons/stock_picking_filter_lot
  setup/stock_picking_filter_lot/setup.py
  stock_picking_filter_lot/README.rst
  stock_picking_filter_lot/__init__.py
  stock_picking_filter_lot/__manifest__.py
  stock_picking_filter_lot/i18n/it.po
  stock_picking_filter_lot/i18n/stock_picking_filter_lot.pot
  stock_picking_filter_lot/models/__init__.py
  stock_picking_filter_lot/models/stock_production_lot.py
  stock_picking_filter_lot/readme/CONTRIBUTORS.rst
  stock_picking_filter_lot/readme/DESCRIPTION.rst
  stock_picking_filter_lot/readme/USAGE.rst
  stock_picking_filter_lot/static/description/icon.png
  stock_picking_filter_lot/static/description/index.html
  stock_picking_filter_lot/views/stock_move_line_view.xml
  stock_picking_filter_lot/views/stock_scrap_view.xml
Labels: needs fixing, migration, bot is merging ⏳

#1131 stock_scheduler_assignation_horizon: wider settings approach
  stock_scheduler_assignation_horizon/__manifest__.py
  stock_scheduler_assignation_horizon/data/ir_config_parameter.xml
  stock_scheduler_assignation_horizon/migrations/14.0.1.0.1/pre-migration.py
  stock_scheduler_assignation_horizon/models/__init__.py
  stock_scheduler_assignation_horizon/models/procurement_group.py
  stock_scheduler_assignation_horizon/models/res_company.py
  stock_scheduler_assignation_horizon/models/res_config_settings.py
  stock_scheduler_assignation_horizon/readme/DESCRIPTION.rst
  stock_scheduler_assignation_horizon/tests/test_res_config_settings.py
  stock_scheduler_assignation_horizon/tests/test_res_config_settings_common.py
  stock_scheduler_assignation_horizon/views/res_config_settings_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#1277 [15.0][FIX] stock_picking_batch_extended: Administration settings required. Use _for_xml_id...
  stock_picking_batch_extended/models/stock_batch_picking.py
  stock_picking_batch_extended/wizard/stock_picking_to_batch.py
Labels: approved, bot is merging ⏳

#1276 [15.0][IMP] stock_picking_batch_extended: Display standard picking tree view in batch pickings
  stock_picking_batch_extended/views/stock_batch_picking.xml
Labels: approved, bot is merging ⏳

#1274 [ADD] stock_move_line_reserved_quant
  setup/stock_move_line_reserved_quant/odoo/addons/stock_move_line_reserved_quant
  setup/stock_move_line_reserved_quant/setup.py
  stock_move_line_reserved_quant/README.rst
  stock_move_line_reserved_quant/__init__.py
  stock_move_line_reserved_quant/__manifest__.py
  stock_move_line_reserved_quant/models/__init__.py
  stock_move_line_reserved_quant/models/stock_move.py
  stock_move_line_reserved_quant/models/stock_move_line.py
  stock_move_line_reserved_quant/readme/CONTRIBUTORS.rst
  stock_move_line_reserved_quant/readme/DESCRIPTION.rst
  stock_move_line_reserved_quant/static/description/icon.png
  stock_move_line_reserved_quant/static/description/index.html
  stock_move_line_reserved_quant/tests/__init__.py
  stock_move_line_reserved_quant/tests/test_reserved_quant.py
  stock_move_line_reserved_quant/views/stock_move_line.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳
