Repository OCA/stock-logistics-workflow, pull requests merged in 2023-11, with the labels that each got.

#1356 [16.0][MIG] stock_picking_warn_message: Migration to 16.0
  setup/stock_picking_warn_message/odoo/addons/stock_picking_warn_message
  setup/stock_picking_warn_message/setup.py
  stock_picking_warn_message/README.rst
  stock_picking_warn_message/__init__.py
  stock_picking_warn_message/__manifest__.py
  stock_picking_warn_message/i18n/stock_picking_warn_message.pot
  stock_picking_warn_message/models/__init__.py
  stock_picking_warn_message/models/stock_picking.py
  stock_picking_warn_message/readme/CONTRIBUTORS.rst
  stock_picking_warn_message/readme/DESCRIPTION.rst
  stock_picking_warn_message/static/description/icon.png
  stock_picking_warn_message/static/description/index.html
  stock_picking_warn_message/tests/__init__.py
  stock_picking_warn_message/tests/test_stock_picking_warn_message.py
  stock_picking_warn_message/views/stock_picking_views.xml
Labels: approved, migration, ready to merge

#1419 [16.0] stock_picking_invoice_link: fix string
  stock_picking_invoice_link/models/stock_picking.py
Labels: bot is merging ⏳

#1303 [FIX] stock_picking_start: Don't evaluate void browse records to boolean value
  stock_picking_start/models/stock_picking.py
  stock_picking_start/tests/test_stock_picking_start.py
Labels: enhancement, needs review, approved

#1372 [16.0][MIG] stock_picking_supplier_ref
  setup/stock_picking_supplier_ref/odoo/addons/stock_picking_supplier_ref
  setup/stock_picking_supplier_ref/setup.py
  stock_picking_supplier_ref/README.rst
  stock_picking_supplier_ref/__init__.py
  stock_picking_supplier_ref/__manifest__.py
  stock_picking_supplier_ref/i18n/es.po
  stock_picking_supplier_ref/i18n/stock_picking_supplier_ref.pot
  stock_picking_supplier_ref/models/__init__.py
  stock_picking_supplier_ref/models/stock_picking.py
  stock_picking_supplier_ref/readme/CONTRIBUTORS.rst
  stock_picking_supplier_ref/readme/DESCRIPTION.rst
  stock_picking_supplier_ref/readme/HISTORY.rst
  stock_picking_supplier_ref/readme/USAGE.rst
  stock_picking_supplier_ref/static/description/icon.png
  stock_picking_supplier_ref/static/description/index.html
  stock_picking_supplier_ref/views/stock_picking.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#998 [14.0] [ADD] stock_picking_reallocation
  setup/stock_picking_reallocation/odoo/addons/stock_picking_reallocation
  setup/stock_picking_reallocation/setup.py
  stock_picking_reallocation/README.rst
  stock_picking_reallocation/__init__.py
  stock_picking_reallocation/__manifest__.py
  stock_picking_reallocation/models/__init__.py
  stock_picking_reallocation/models/stock_picking.py
  stock_picking_reallocation/models/stock_picking_reallocation.py
  stock_picking_reallocation/readme/CONTRIBUTORS.rst
  stock_picking_reallocation/readme/DESCRIPTION.rst
  stock_picking_reallocation/readme/ROADMAP.rst
  stock_picking_reallocation/readme/USAGE.rst
  stock_picking_reallocation/security/ir.model.access.csv
  stock_picking_reallocation/static/description/index.html
  stock_picking_reallocation/tests/__init__.py
  stock_picking_reallocation/tests/test_stock_picking_reallocation.py
  stock_picking_reallocation/views/stock_picking_reallocation_views.xml
  stock_picking_reallocation/views/stock_picking_views.xml
Labels: needs review, approved, bot is merging ⏳

#1309 [16.0][MIG] sale_line_returned_qty: Migration to 16.0
  sale_line_returned_qty/README.rst
  sale_line_returned_qty/__init__.py
  sale_line_returned_qty/__manifest__.py
  sale_line_returned_qty/i18n/sale_line_returned_qty.pot
  sale_line_returned_qty/models/__init__.py
  sale_line_returned_qty/models/sale_order_line.py
  sale_line_returned_qty/readme/CONTRIBUTORS.rst
  sale_line_returned_qty/readme/DESCRIPTION.rst
  sale_line_returned_qty/static/description/icon.png
  sale_line_returned_qty/static/description/index.html
  sale_line_returned_qty/tests/__init__.py
  sale_line_returned_qty/tests/test_sale_line_returned_qty.py
  sale_line_returned_qty/views/sale_order_views.xml
  setup/sale_line_returned_qty/odoo/addons/sale_line_returned_qty
  setup/sale_line_returned_qty/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳, stale

#1417 [16.0][FIX] stock_move_line_auto_fill: to fix installation error when mrp & stock_barcode apps exist on the db
  stock_move_line_auto_fill/views/stock_picking_type_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1383 [14.0] [ADD] stock_picking_inter_warehouse
  setup/stock_picking_inter_warehouse/odoo/addons/stock_picking_inter_warehouse
  setup/stock_picking_inter_warehouse/setup.py
  stock_picking_inter_warehouse/README.rst
  stock_picking_inter_warehouse/__init__.py
  stock_picking_inter_warehouse/__manifest__.py
  stock_picking_inter_warehouse/data/stock_location_route.xml
  stock_picking_inter_warehouse/demo/res_config_settings_demo.xml
  stock_picking_inter_warehouse/demo/stock_warehouse_demo.xml
  stock_picking_inter_warehouse/models/__init__.py
  stock_picking_inter_warehouse/models/res_partner.py
  stock_picking_inter_warehouse/models/stock_location.py
  stock_picking_inter_warehouse/models/stock_move.py
  stock_picking_inter_warehouse/models/stock_picking.py
  stock_picking_inter_warehouse/models/stock_picking_type.py
  stock_picking_inter_warehouse/models/stock_rule.py
  stock_picking_inter_warehouse/models/stock_warehouse.py
  stock_picking_inter_warehouse/readme/CONFIGURE.rst
  stock_picking_inter_warehouse/readme/CONTRIBUTORS.rst
  stock_picking_inter_warehouse/readme/DESCRIPTION.rst
  stock_picking_inter_warehouse/readme/USAGE.rst
  stock_picking_inter_warehouse/static/description/icon.png
  stock_picking_inter_warehouse/static/description/index.html
  stock_picking_inter_warehouse/tests/__init__.py
  stock_picking_inter_warehouse/tests/test_stock_picking_inter_warehouse.py
  stock_picking_inter_warehouse/views/stock_picking_type_views.xml
  stock_picking_inter_warehouse/views/stock_picking_views.xml
  stock_picking_inter_warehouse/views/stock_warehouse_views.xml
Labels: approved, bot is merging ⏳

#1425 [FIX] stock_picking_inter_warehouse: demo data in demo manifest key
  stock_picking_inter_warehouse/README.rst
  stock_picking_inter_warehouse/__manifest__.py
  stock_picking_inter_warehouse/static/description/index.html
Labels: bot is merging ⏳

#1430 [15.0][FIX] stock_return_request: Fix string to translate
  stock_return_request/i18n/es.po
  stock_return_request/i18n/fr.po
  stock_return_request/i18n/pt_BR.po
  stock_return_request/i18n/pt_PT.po
  stock_return_request/i18n/stock_return_request.pot
  stock_return_request/models/stock_return_request.py
Labels: approved, bot is merging ⏳

#1426 [14.0][FIX] stock_picking_inter_warehouse: multiple fixes
  stock_picking_inter_warehouse/README.rst
  stock_picking_inter_warehouse/__init__.py
  stock_picking_inter_warehouse/__manifest__.py
  stock_picking_inter_warehouse/data/stock_location_route.xml
  stock_picking_inter_warehouse/hooks.py
  stock_picking_inter_warehouse/migrations/14.0.1.1.0/post-migrate.py
  stock_picking_inter_warehouse/models/__init__.py
  stock_picking_inter_warehouse/models/res_company.py
  stock_picking_inter_warehouse/models/res_partner.py
  stock_picking_inter_warehouse/models/stock_picking.py
  stock_picking_inter_warehouse/models/stock_picking_type.py
  stock_picking_inter_warehouse/models/stock_warehouse.py
  stock_picking_inter_warehouse/static/description/index.html
  stock_picking_inter_warehouse/tests/test_stock_picking_inter_warehouse.py
  stock_picking_inter_warehouse/views/stock_picking_type_views.xml
Labels: bot is merging ⏳

#1365 [16.0][MIG] delivery_total_weight_from_packaging: Migrate to 16.0
  delivery_total_weight_from_packaging/README.rst
  delivery_total_weight_from_packaging/__init__.py
  delivery_total_weight_from_packaging/__manifest__.py
  delivery_total_weight_from_packaging/i18n/delivery_total_weight_from_packaging.pot
  delivery_total_weight_from_packaging/models/__init__.py
  delivery_total_weight_from_packaging/models/stock_move.py
  delivery_total_weight_from_packaging/models/stock_picking.py
  delivery_total_weight_from_packaging/models/stock_quant_package.py
  delivery_total_weight_from_packaging/readme/CONTRIBUTORS.rst
  delivery_total_weight_from_packaging/readme/CREDITS.rst
  delivery_total_weight_from_packaging/readme/DESCRIPTION.rst
  delivery_total_weight_from_packaging/static/description/icon.png
  delivery_total_weight_from_packaging/static/description/index.html
  delivery_total_weight_from_packaging/tests/__init__.py
  delivery_total_weight_from_packaging/tests/common.py
  delivery_total_weight_from_packaging/tests/test_choose_delivery_package.py
  delivery_total_weight_from_packaging/tests/test_weight_from_packaging.py
  delivery_total_weight_from_packaging/wizard/__init__.py
  delivery_total_weight_from_packaging/wizard/choose_delivery_package.py
  setup/delivery_total_weight_from_packaging/odoo/addons/delivery_total_weight_from_packaging
  setup/delivery_total_weight_from_packaging/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1433 [15.0][IMP] stock_owner_restriction: Prevent a negative quant from being created with owner
  stock_owner_restriction/models/stock_quant.py
Labels: approved, bot is merging ⏳

#1287 [15.0][IMP] stock_picking_auto_create_lot: Compute quantities to reservation for moves which lots will be created in picking validation
  stock_picking_auto_create_lot/models/stock_move.py
  stock_picking_auto_create_lot/tests/test_stock_picking_auto_create_lot.py
Labels: approved, bot is merging ⏳

#1366 [16.0][MIG] stock_quant_package_dimension_total_weight_from_packaging: Migrate to 16.0
  setup/stock_quant_package_dimension_total_weight_from_packaging/odoo/addons/stock_quant_package_dimension_total_weight_from_packaging
  setup/stock_quant_package_dimension_total_weight_from_packaging/setup.py
  stock_quant_package_dimension_total_weight_from_packaging/README.rst
  stock_quant_package_dimension_total_weight_from_packaging/__init__.py
  stock_quant_package_dimension_total_weight_from_packaging/__manifest__.py
  stock_quant_package_dimension_total_weight_from_packaging/i18n/stock_quant_package_dimension_total_weight_from_packaging.pot
  stock_quant_package_dimension_total_weight_from_packaging/models/__init__.py
  stock_quant_package_dimension_total_weight_from_packaging/models/stock_quant_package.py
  stock_quant_package_dimension_total_weight_from_packaging/readme/CONTRIBUTORS.rst
  stock_quant_package_dimension_total_weight_from_packaging/readme/CREDITS.rst
  stock_quant_package_dimension_total_weight_from_packaging/readme/DESCRIPTION.rst
  stock_quant_package_dimension_total_weight_from_packaging/static/description/icon.png
  stock_quant_package_dimension_total_weight_from_packaging/static/description/index.html
  stock_quant_package_dimension_total_weight_from_packaging/tests/__init__.py
  stock_quant_package_dimension_total_weight_from_packaging/tests/test_package_weight.py
Labels: needs review, approved, migration, bot is merging ⏳

#1439 [14.0][IMP] stock_picking_inter_warehouse: maintainers
  stock_picking_inter_warehouse/README.rst
  stock_picking_inter_warehouse/__manifest__.py
  stock_picking_inter_warehouse/static/description/index.html
Labels: bot is merging ⏳

#1314 [15.0][ADD] stock_picking_batch_set_quantity: New module
  setup/stock_picking_batch_set_quantity/odoo/addons/stock_picking_batch_set_quantity
  setup/stock_picking_batch_set_quantity/setup.py
  stock_picking_batch_set_quantity/README.rst
  stock_picking_batch_set_quantity/__init__.py
  stock_picking_batch_set_quantity/__manifest__.py
  stock_picking_batch_set_quantity/models/__init__.py
  stock_picking_batch_set_quantity/models/stock_move.py
  stock_picking_batch_set_quantity/models/stock_move_line.py
  stock_picking_batch_set_quantity/readme/CONTRIBUTORS.rst
  stock_picking_batch_set_quantity/readme/DESCRIPTION.rst
  stock_picking_batch_set_quantity/readme/USAGE.rst
  stock_picking_batch_set_quantity/static/description/icon.png
  stock_picking_batch_set_quantity/static/description/index.html
  stock_picking_batch_set_quantity/views/stock_picking_batch_views.xml
Labels: approved, bot is merging ⏳, stale
