Repository OCA/stock-logistics-workflow, pull requests merged in 2023-07, with the labels that each got.

#1304 16.0 mig stock_picking_info_lot
  setup/stock_picking_info_lot/odoo/addons/stock_picking_info_lot
  setup/stock_picking_info_lot/setup.py
  stock_picking_info_lot/README.rst
  stock_picking_info_lot/__init__.py
  stock_picking_info_lot/__manifest__.py
  stock_picking_info_lot/i18n/stock_picking_info_lot.pot
  stock_picking_info_lot/models/__init__.py
  stock_picking_info_lot/models/product_template.py
  stock_picking_info_lot/models/stock_move_line.py
  stock_picking_info_lot/models/stock_picking.py
  stock_picking_info_lot/readme/CONFIGURE.rst
  stock_picking_info_lot/readme/CONTRIBUTORS.rst
  stock_picking_info_lot/readme/DESCRIPTION.rst
  stock_picking_info_lot/readme/ROADMAP.rst
  stock_picking_info_lot/readme/USAGE.rst
  stock_picking_info_lot/static/description/icon.png
  stock_picking_info_lot/static/description/index.html
  stock_picking_info_lot/tests/__init__.py
  stock_picking_info_lot/tests/test_picking_validation.py
  stock_picking_info_lot/views/product_template_views.xml
  stock_picking_info_lot/views/stock_move_line_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1317 [15.0] Create module stock_move_consu_location_from_putaway
  setup/stock_move_consu_location_from_putaway/odoo/addons/stock_move_consu_location_from_putaway
  setup/stock_move_consu_location_from_putaway/setup.py
  stock_move_consu_location_from_putaway/README.rst
  stock_move_consu_location_from_putaway/__init__.py
  stock_move_consu_location_from_putaway/__manifest__.py
  stock_move_consu_location_from_putaway/models/__init__.py
  stock_move_consu_location_from_putaway/models/stock_move.py
  stock_move_consu_location_from_putaway/readme/CONTRIBUTORS.rst
  stock_move_consu_location_from_putaway/readme/DESCRIPTION.rst
  stock_move_consu_location_from_putaway/tests/__init__.py
  stock_move_consu_location_from_putaway/tests/test_consumable_move_location.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1254 [16.0][ADD] stock_picking_kind
  setup/stock_picking_kind/odoo/addons/stock_picking_kind
  setup/stock_picking_kind/setup.py
  stock_picking_kind/README.rst
  stock_picking_kind/__init__.py
  stock_picking_kind/__manifest__.py
  stock_picking_kind/hooks.py
  stock_picking_kind/i18n/fr.po
  stock_picking_kind/i18n/stock_picking_kind.pot
  stock_picking_kind/models/__init__.py
  stock_picking_kind/models/stock_picking.py
  stock_picking_kind/readme/CONTRIBUTORS.rst
  stock_picking_kind/readme/DESCRIPTION.rst
  stock_picking_kind/static/description/icon.png
  stock_picking_kind/static/description/index.html
  stock_picking_kind/tests/__init__.py
  stock_picking_kind/tests/test_stock_picking_kind.py
  stock_picking_kind/views/stock_picking_views.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1327 [MIG] stock_landed_costs_currency: Migration to 16.0
  setup/stock_landed_costs_currency/odoo/addons/stock_landed_costs_currency
  setup/stock_landed_costs_currency/setup.py
  stock_landed_costs_currency/README.rst
  stock_landed_costs_currency/__init__.py
  stock_landed_costs_currency/__manifest__.py
  stock_landed_costs_currency/i18n/stock_landed_costs_currency.pot
  stock_landed_costs_currency/models/__init__.py
  stock_landed_costs_currency/models/stock_landed_cost.py
  stock_landed_costs_currency/models/stock_landed_cost_lines.py
  stock_landed_costs_currency/readme/CONFIGURE.rst
  stock_landed_costs_currency/readme/CONTRIBUTORS.rst
  stock_landed_costs_currency/readme/DESCRIPTION.rst
  stock_landed_costs_currency/readme/USAGE.rst
  stock_landed_costs_currency/static/description/icon.png
  stock_landed_costs_currency/static/description/index.html
  stock_landed_costs_currency/tests/__init__.py
  stock_landed_costs_currency/tests/test_stock_landed_costs_currency.py
  stock_landed_costs_currency/views/stock_landed_cost_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#941 [FIX][12.0] stock_move_manual_lot: various fixes
  stock_move_manual_lot/__manifest__.py
  stock_move_manual_lot/migrations/12.0.1.1.0/post-migration.py
  stock_move_manual_lot/models/__init__.py
  stock_move_manual_lot/models/stock_move.py
  stock_move_manual_lot/models/stock_move_line.py
  stock_move_manual_lot/models/stock_picking.py
  stock_move_manual_lot/readme/CONTRIBUTORS.rst
  stock_move_manual_lot/tests/test_stock_move_manual_lot.py
Labels: bug, bot is merging ⏳, stale

#1292 [14.0][IMP] delivery_procurement_group_carrier: Set Carrier on new picking from procurement.group
  delivery_procurement_group_carrier/README.rst
  delivery_procurement_group_carrier/__manifest__.py
  delivery_procurement_group_carrier/models/__init__.py
  delivery_procurement_group_carrier/models/stock_move.py
  delivery_procurement_group_carrier/readme/CONTRIBUTORS.rst
  delivery_procurement_group_carrier/static/description/index.html
Labels: enhancement, needs review, bot is merging ⏳

#1313 [ADD] stock_picking_auto_create_package
  README.md
  setup/stock_picking_auto_create_package/odoo/addons/stock_picking_auto_create_package
  setup/stock_picking_auto_create_package/setup.py
  stock_picking_auto_create_package/README.rst
  stock_picking_auto_create_package/__init__.py
  stock_picking_auto_create_package/__manifest__.py
  stock_picking_auto_create_package/models/__init__.py
  stock_picking_auto_create_package/models/stock_picking.py
  stock_picking_auto_create_package/models/stock_picking_type.py
  stock_picking_auto_create_package/readme/CONFIGURE.rst
  stock_picking_auto_create_package/readme/CONTRIBUTORS.rst
  stock_picking_auto_create_package/readme/DESCRIPTION.rst
  stock_picking_auto_create_package/static/description/icon.png
  stock_picking_auto_create_package/static/description/index.html
  stock_picking_auto_create_package/tests/__init__.py
  stock_picking_auto_create_package/tests/test_automatic_package.py
  stock_picking_auto_create_package/views/stock_picking_type.xml
Labels: bot is merging ⏳
