Repository OCA/stock-logistics-workflow, pull requests merged in 2023-02, with the labels that each got.

#1207 [14.0][FIX] stock_picking_invoice_link: inventory users cannot validate picking
  stock_picking_invoice_link/models/stock_move.py
Labels: bot is merging ⏳

#1208 [15.0][FIX] stock_picking_invoice_link: inventory users cannot validate picking
  stock_picking_invoice_link/models/stock_move.py
Labels: bot is merging ⏳

#1210 [16.0][FIX] stock_picking_invoice_link: inventory users cannot validate picking
  stock_picking_invoice_link/models/stock_move.py
Labels: bot is merging ⏳

#1004 [14.0][MIG] stock_valuation_layer_usage and stock_account_product_run_fifo_hook
  setup/stock_account_product_run_fifo_hook/odoo/addons/stock_account_product_run_fifo_hook
  setup/stock_account_product_run_fifo_hook/setup.py
  setup/stock_valuation_layer_usage/odoo/addons/stock_valuation_layer_usage
  setup/stock_valuation_layer_usage/setup.py
  stock_account_product_run_fifo_hook/README.rst
  stock_account_product_run_fifo_hook/__init__.py
  stock_account_product_run_fifo_hook/__manifest__.py
  stock_account_product_run_fifo_hook/hooks.py
  stock_account_product_run_fifo_hook/i18n/stock_account_product_run_fifo_hook.pot
  stock_account_product_run_fifo_hook/model/__init__.py
  stock_account_product_run_fifo_hook/model/product.py
  stock_account_product_run_fifo_hook/readme/CONTRIBUTORS.rst
  stock_account_product_run_fifo_hook/readme/DESCRIPTION.rst
  stock_account_product_run_fifo_hook/readme/USAGE.rst
  stock_account_product_run_fifo_hook/static/description/icon.png
  stock_account_product_run_fifo_hook/static/description/index.html
  stock_valuation_layer_usage/README.rst
  stock_valuation_layer_usage/__init__.py
  stock_valuation_layer_usage/__manifest__.py
  stock_valuation_layer_usage/i18n/stock_valuation_layer_usage.pot
  stock_valuation_layer_usage/models/__init__.py
  stock_valuation_layer_usage/models/stock_move.py
  stock_valuation_layer_usage/models/stock_valuation_layer.py
  stock_valuation_layer_usage/models/stock_valuation_layer_usage.py
  stock_valuation_layer_usage/readme/CONTRIBUTORS.rst
  stock_valuation_layer_usage/readme/DESCRIPTION.rst
  stock_valuation_layer_usage/readme/HISTORY.rst
  stock_valuation_layer_usage/readme/INSTALL.rst
  stock_valuation_layer_usage/readme/USAGE.rst
  stock_valuation_layer_usage/security/ir.model.access.csv
  stock_valuation_layer_usage/static/description/icon.png
  stock_valuation_layer_usage/static/description/index.html
  stock_valuation_layer_usage/tests/__init__.py
  stock_valuation_layer_usage/tests/test_stock_valuation_layer_usage.py
  stock_valuation_layer_usage/views/stock_move_views.xml
  stock_valuation_layer_usage/views/stock_valuation_layer_usage_views.xml
  stock_valuation_layer_usage/views/stock_valuation_layer_views.xml
Labels: approved, bot is merging ⏳

#1150 [14.0][ADD] stock_picking_default_planned_transfer
  setup/stock_picking_default_planned_transfer/odoo/addons/stock_picking_default_planned_transfer
  setup/stock_picking_default_planned_transfer/setup.py
  stock_picking_default_planned_transfer/__init__.py
  stock_picking_default_planned_transfer/__manifest__.py
  stock_picking_default_planned_transfer/hooks.py
  stock_picking_default_planned_transfer/readme/CONTRIBUTORS.rst
  stock_picking_default_planned_transfer/readme/DESCRIPTION.rst
Labels: question, needs review, approved, ready to merge, bot is merging ⏳

#1088 [14.0][MIG] stock_picking_quick
  setup/stock_picking_quick/odoo/addons/stock_picking_quick
  setup/stock_picking_quick/setup.py
  stock_picking_quick/README.rst
  stock_picking_quick/__init__.py
  stock_picking_quick/__manifest__.py
  stock_picking_quick/i18n/pt_BR.po
  stock_picking_quick/i18n/sl.po
  stock_picking_quick/i18n/stock_picking_quick.pot
  stock_picking_quick/models/__init__.py
  stock_picking_quick/models/product_product.py
  stock_picking_quick/models/stock_picking.py
  stock_picking_quick/readme/CONTRIBUTORS.rst
  stock_picking_quick/readme/DESCRIPTION.rst
  stock_picking_quick/readme/USAGE.rst
  stock_picking_quick/static/description/filter.png
  stock_picking_quick/static/description/icon.png
  stock_picking_quick/static/description/index.html
  stock_picking_quick/static/description/po-product.png
  stock_picking_quick/static/description/po.png
  stock_picking_quick/tests/__init__.py
  stock_picking_quick/tests/test_stock_picking_quick.py
  stock_picking_quick/views/picking_view.xml
  stock_picking_quick/views/product_view.xml
Labels: needs review, approved, migration, bot is merging ⏳, stale

#1211 [15.0][MIG] stock_picking_line_sequence
  setup/stock_picking_line_sequence/odoo/addons/stock_picking_line_sequence
  setup/stock_picking_line_sequence/setup.py
  stock_picking_line_sequence/README.rst
  stock_picking_line_sequence/__init__.py
  stock_picking_line_sequence/__manifest__.py
  stock_picking_line_sequence/i18n/ca.po
  stock_picking_line_sequence/i18n/de.po
  stock_picking_line_sequence/i18n/es.po
  stock_picking_line_sequence/i18n/es_MX.po
  stock_picking_line_sequence/i18n/fi.po
  stock_picking_line_sequence/i18n/fr.po
  stock_picking_line_sequence/i18n/hr.po
  stock_picking_line_sequence/i18n/it.po
  stock_picking_line_sequence/i18n/nl_NL.po
  stock_picking_line_sequence/i18n/pt.po
  stock_picking_line_sequence/i18n/pt_BR.po
  stock_picking_line_sequence/i18n/sl.po
  stock_picking_line_sequence/i18n/stock_picking_line_sequence.pot
  stock_picking_line_sequence/i18n/tr.po
  stock_picking_line_sequence/i18n/tr_TR.po
  stock_picking_line_sequence/init_hooks.py
  stock_picking_line_sequence/models/__init__.py
  stock_picking_line_sequence/models/stock.py
  stock_picking_line_sequence/readme/CONTRIBUTORS.rst
  stock_picking_line_sequence/readme/DESCRIPTION.rst
  stock_picking_line_sequence/readme/USAGE.rst
  stock_picking_line_sequence/report/report_deliveryslip.xml
  stock_picking_line_sequence/static/description/icon.png
  stock_picking_line_sequence/static/description/index.html
  stock_picking_line_sequence/tests/__init__.py
  stock_picking_line_sequence/tests/test_move_lines_sequence.py
  stock_picking_line_sequence/views/stock_view.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1212 [15.0][MIG] stock_landed_costs_purchase_auto: Migration to 15.0
  setup/stock_landed_costs_purchase_auto/odoo/addons/stock_landed_costs_purchase_auto
  setup/stock_landed_costs_purchase_auto/setup.py
  stock_landed_costs_purchase_auto/README.rst
  stock_landed_costs_purchase_auto/__init__.py
  stock_landed_costs_purchase_auto/__manifest__.py
  stock_landed_costs_purchase_auto/i18n/es.po
  stock_landed_costs_purchase_auto/i18n/stock_landed_costs_purchase_auto.pot
  stock_landed_costs_purchase_auto/models/__init__.py
  stock_landed_costs_purchase_auto/models/purchase_order.py
  stock_landed_costs_purchase_auto/models/stock_landed_cost.py
  stock_landed_costs_purchase_auto/readme/CONTRIBUTORS.rst
  stock_landed_costs_purchase_auto/readme/DESCRIPTION.rst
  stock_landed_costs_purchase_auto/readme/USAGE.rst
  stock_landed_costs_purchase_auto/static/description/icon.png
  stock_landed_costs_purchase_auto/static/description/index.html
  stock_landed_costs_purchase_auto/tests/__init__.py
  stock_landed_costs_purchase_auto/tests/test_purchase_order.py
  stock_landed_costs_purchase_auto/views/purchase_order_view.xml
  stock_landed_costs_purchase_auto/views/stock_landed_cost_view.xml
Labels: approved, bot is merging ⏳

#1213 [15.0][FIX] stock_owner_restriction: Change SavepointCase to TransactionCase
  stock_owner_restriction/tests/test_stock_owner_restriction.py
Labels: approved, bot is merging ⏳

#1217 [14.0][FIX]product_supplierinfo_for_customer_picking - Wrong supplier…
  product_supplierinfo_for_customer_picking/models/stock_move.py
  product_supplierinfo_for_customer_picking/tests/test_product_supplierinfo_for_customer_picking.py
Labels: enhancement, approved, bot is merging ⏳

#1005 [14.0][MIG] stock_picking_supplier_ref: Migration to 14.0
  requirements.txt
  setup/stock_picking_supplier_ref/odoo/addons/stock_picking_supplier_ref
  setup/stock_picking_supplier_ref/setup.py
  stock_picking_supplier_ref/README.rst
  stock_picking_supplier_ref/__init__.py
  stock_picking_supplier_ref/__manifest__.py
  stock_picking_supplier_ref/i18n/es.po
  stock_picking_supplier_ref/i18n/stock_picking_supplier_ref.pot
  stock_picking_supplier_ref/migrations/14.0.1.1.0/pre-migration.py
  stock_picking_supplier_ref/models/__init__.py
  stock_picking_supplier_ref/models/stock_picking.py
  stock_picking_supplier_ref/readme/CONTRIBUTORS.rst
  stock_picking_supplier_ref/readme/DESCRIPTION.rst
  stock_picking_supplier_ref/readme/HISTORY.rst
  stock_picking_supplier_ref/readme/USAGE.rst
  stock_picking_supplier_ref/static/description/icon.png
  stock_picking_supplier_ref/views/stock_picking.xml
Labels: needs fixing, approved, migration, ready to merge, bot is merging ⏳

#1112 16.0 mig stock no negative
  setup/stock_no_negative/odoo/addons/stock_no_negative
  setup/stock_no_negative/setup.py
  stock_no_negative/README.rst
  stock_no_negative/__init__.py
  stock_no_negative/__manifest__.py
  stock_no_negative/i18n/ar.po
  stock_no_negative/i18n/es.po
  stock_no_negative/i18n/fr.po
  stock_no_negative/i18n/pt.po
  stock_no_negative/i18n/stock_no_negative.pot
  stock_no_negative/models/__init__.py
  stock_no_negative/models/product.py
  stock_no_negative/models/stock_location.py
  stock_no_negative/models/stock_quant.py
  stock_no_negative/readme/CONFIGURE.rst
  stock_no_negative/readme/CONTRIBUTORS.rst
  stock_no_negative/readme/DESCRIPTION.rst
  stock_no_negative/readme/HISTORY.rst
  stock_no_negative/readme/USAGE.rst
  stock_no_negative/static/description/icon.png
  stock_no_negative/static/description/index.html
  stock_no_negative/tests/__init__.py
  stock_no_negative/tests/test_stock_no_negative.py
  stock_no_negative/views/product_product_views.xml
  stock_no_negative/views/stock_location_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1220 [15.0][MIG] stock_landed_costs_security: Migration to version 15.0
  setup/stock_landed_costs_security/odoo/addons/stock_landed_costs_security
  setup/stock_landed_costs_security/setup.py
  stock_landed_costs_security/README.rst
  stock_landed_costs_security/__init__.py
  stock_landed_costs_security/__manifest__.py
  stock_landed_costs_security/i18n/stock_landed_costs_security.pot
  stock_landed_costs_security/readme/CONFIGURE.rst
  stock_landed_costs_security/readme/CONTRIBUTORS.rst
  stock_landed_costs_security/readme/DESCRIPTION.rst
  stock_landed_costs_security/readme/USAGE.rst
  stock_landed_costs_security/security/ir.model.access.csv
  stock_landed_costs_security/security/stock_landed_costs_security.xml
  stock_landed_costs_security/static/description/icon.png
  stock_landed_costs_security/static/description/icon.svg
  stock_landed_costs_security/static/description/index.html
  stock_landed_costs_security/views/stock_landed_costs_view.xml
Labels: approved, bot is merging ⏳

#1221 [15.0][MIG] stock_picking_assign_serial_final: Migration to version 15.0
  setup/stock_picking_assign_serial_final/odoo/addons/stock_picking_assign_serial_final
  setup/stock_picking_assign_serial_final/setup.py
  stock_picking_assign_serial_final/README.rst
  stock_picking_assign_serial_final/__init__.py
  stock_picking_assign_serial_final/__manifest__.py
  stock_picking_assign_serial_final/i18n/es.po
  stock_picking_assign_serial_final/i18n/stock_picking_assign_serial_final.pot
  stock_picking_assign_serial_final/models/__init__.py
  stock_picking_assign_serial_final/models/assign_serial_final_mixin.py
  stock_picking_assign_serial_final/models/stock_move.py
  stock_picking_assign_serial_final/readme/CONTRIBUTORS.rst
  stock_picking_assign_serial_final/readme/DESCRIPTION.rst
  stock_picking_assign_serial_final/readme/USAGE.rst
  stock_picking_assign_serial_final/static/description/icon.png
  stock_picking_assign_serial_final/static/description/index.html
  stock_picking_assign_serial_final/tests/__init__.py
  stock_picking_assign_serial_final/tests/common.py
  stock_picking_assign_serial_final/tests/test_stock_picking_assign_serial_final.py
  stock_picking_assign_serial_final/wizards/__init__.py
  stock_picking_assign_serial_final/wizards/stock_assign_serial_numbers.py
  stock_picking_assign_serial_final/wizards/stock_assign_serial_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#937 [14.0][MIG] stock_dangerous_goods
  setup/stock_dangerous_goods/odoo/addons/stock_dangerous_goods
  setup/stock_dangerous_goods/setup.py
  stock_dangerous_goods/README.rst
  stock_dangerous_goods/__init__.py
  stock_dangerous_goods/__manifest__.py
  stock_dangerous_goods/models/__init__.py
  stock_dangerous_goods/models/product_product.py
  stock_dangerous_goods/models/stock_move_line.py
  stock_dangerous_goods/models/stock_quant_package.py
  stock_dangerous_goods/readme/CONTRIBUTORS.rst
  stock_dangerous_goods/readme/DESCRIPTION.rst
  stock_dangerous_goods/static/description/index.html
Labels: approved, migration, bot is merging ⏳

#1219 [15.0][MIG] sale_order_global_stock_route: Migration to version 15.0
  sale_order_global_stock_route/README.rst
  sale_order_global_stock_route/__init__.py
  sale_order_global_stock_route/__manifest__.py
  sale_order_global_stock_route/i18n/es.po
  sale_order_global_stock_route/i18n/it.po
  sale_order_global_stock_route/i18n/pt_BR.po
  sale_order_global_stock_route/i18n/sale_order_global_stock_route.pot
  sale_order_global_stock_route/models/__init__.py
  sale_order_global_stock_route/models/sale_order.py
  sale_order_global_stock_route/readme/CONFIGURE.rst
  sale_order_global_stock_route/readme/CONTRIBUTORS.rst
  sale_order_global_stock_route/readme/DESCRIPTION.rst
  sale_order_global_stock_route/readme/USAGE.rst
  sale_order_global_stock_route/static/description/icon.png
  sale_order_global_stock_route/static/description/index.html
  sale_order_global_stock_route/tests/__init__.py
  sale_order_global_stock_route/tests/test_sale_order_global_stock_route.py
  sale_order_global_stock_route/views/sale_order_views.xml
  setup/sale_order_global_stock_route/odoo/addons/sale_order_global_stock_route
  setup/sale_order_global_stock_route/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1230 [15.0][MIG] stock_landed_costs_delivery: Migration to 15.0
  setup/stock_landed_costs_delivery/odoo/addons/stock_landed_costs_delivery
  setup/stock_landed_costs_delivery/setup.py
  stock_landed_costs_delivery/README.rst
  stock_landed_costs_delivery/__init__.py
  stock_landed_costs_delivery/__manifest__.py
  stock_landed_costs_delivery/i18n/stock_landed_costs_delivery.pot
  stock_landed_costs_delivery/models/__init__.py
  stock_landed_costs_delivery/models/delivery_carrier.py
  stock_landed_costs_delivery/models/purchase_order.py
  stock_landed_costs_delivery/readme/CONTRIBUTORS.rst
  stock_landed_costs_delivery/readme/DESCRIPTION.rst
  stock_landed_costs_delivery/readme/USAGE.rst
  stock_landed_costs_delivery/static/description/icon.png
  stock_landed_costs_delivery/static/description/index.html
  stock_landed_costs_delivery/tests/__init__.py
  stock_landed_costs_delivery/tests/test_purchase_order.py
  stock_landed_costs_delivery/views/delivery_carrier_view.xml
Labels: approved, bot is merging ⏳

#1115 [15.0][MIG] stock_picking_operation_quick_change: Migration to 15.0
  setup/stock_picking_operation_quick_change/odoo/addons/stock_picking_operation_quick_change
  setup/stock_picking_operation_quick_change/setup.py
  stock_picking_operation_quick_change/README.rst
  stock_picking_operation_quick_change/__init__.py
  stock_picking_operation_quick_change/__manifest__.py
  stock_picking_operation_quick_change/i18n/de.po
  stock_picking_operation_quick_change/i18n/es.po
  stock_picking_operation_quick_change/i18n/fr.po
  stock_picking_operation_quick_change/i18n/it.po
  stock_picking_operation_quick_change/i18n/pt_BR.po
  stock_picking_operation_quick_change/i18n/sl.po
  stock_picking_operation_quick_change/i18n/stock_picking_operation_quick_change.pot
  stock_picking_operation_quick_change/readme/CONTRIBUTORS.rst
  stock_picking_operation_quick_change/readme/DESCRIPTION.rst
  stock_picking_operation_quick_change/readme/USAGE.rst
  stock_picking_operation_quick_change/security/ir.model.access.csv
  stock_picking_operation_quick_change/static/description/icon.png
  stock_picking_operation_quick_change/static/description/icon.svg
  stock_picking_operation_quick_change/static/description/index.html
  stock_picking_operation_quick_change/tests/__init__.py
  stock_picking_operation_quick_change/tests/test_stock_picking_operation_quick_change.py
  stock_picking_operation_quick_change/views/stock_picking_view.xml
  stock_picking_operation_quick_change/wizards/__init__.py
  stock_picking_operation_quick_change/wizards/stock_picking_wizard.py
  stock_picking_operation_quick_change/wizards/stock_picking_wizard_view.xml
Labels: approved, migration, bot is merging ⏳

#1222 [IMP][14.0] stock_move_assign_picking_hook: use standard hook
  stock_move_assign_picking_hook/models/stock_move.py
Labels: approved, bot is merging ⏳

#1148 [MIG][16.0] stock_delivery_note
  setup/stock_delivery_note/odoo/addons/stock_delivery_note
  setup/stock_delivery_note/setup.py
  stock_delivery_note/README.rst
  stock_delivery_note/__init__.py
  stock_delivery_note/__manifest__.py
  stock_delivery_note/i18n/stock_delivery_note.pot
  stock_delivery_note/models/__init__.py
  stock_delivery_note/models/stock_picking.py
  stock_delivery_note/readme/CONTRIBUTORS.rst
  stock_delivery_note/readme/DESCRIPTION.rst
  stock_delivery_note/readme/USAGE.rst
  stock_delivery_note/reports/report_picking.xml
  stock_delivery_note/static/description/icon.png
  stock_delivery_note/static/description/index.html
  stock_delivery_note/views/stock_picking.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1218 [MIG][16.0] stock_lot_production_date
  setup/stock_lot_production_date/odoo/addons/stock_lot_production_date
  setup/stock_lot_production_date/setup.py
  stock_lot_production_date/README.rst
  stock_lot_production_date/__init__.py
  stock_lot_production_date/__manifest__.py
  stock_lot_production_date/i18n/stock_lot_production_date.pot
  stock_lot_production_date/models/__init__.py
  stock_lot_production_date/models/stock_lot.py
  stock_lot_production_date/readme/CONTRIBUTORS.rst
  stock_lot_production_date/readme/CREDITS.rst
  stock_lot_production_date/readme/DESCRIPTION.rst
  stock_lot_production_date/readme/USAGE.rst
  stock_lot_production_date/static/description/icon.png
  stock_lot_production_date/static/description/index.html
  stock_lot_production_date/static/description/lot.png
  stock_lot_production_date/views/stock_lot.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳
