Repository OCA/stock-logistics-workflow, pull requests merged in 2023-09, with the labels that each got.

#1367 [15.0][ADD] stock_scrap_tier_validation: new module to add tier validation
  setup/stock_scrap_tier_validation/odoo/addons/stock_scrap_tier_validation
  setup/stock_scrap_tier_validation/setup.py
  stock_scrap_tier_validation/README.rst
  stock_scrap_tier_validation/__init__.py
  stock_scrap_tier_validation/__manifest__.py
  stock_scrap_tier_validation/data/mail_message_subtype_data.xml
  stock_scrap_tier_validation/models/__init__.py
  stock_scrap_tier_validation/models/stock_scrap.py
  stock_scrap_tier_validation/models/tier_definition.py
  stock_scrap_tier_validation/readme/CONFIGURE.rst
  stock_scrap_tier_validation/readme/CONTRIBUTORS.rst
  stock_scrap_tier_validation/readme/DESCRIPTION.rst
  stock_scrap_tier_validation/readme/INSTALL.rst
  stock_scrap_tier_validation/readme/USAGE.rst
  stock_scrap_tier_validation/static/description/index.html
  stock_scrap_tier_validation/tests/__init__.py
  stock_scrap_tier_validation/tests/test_tier_validation.py
  stock_scrap_tier_validation/views/stock_scrap_view.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1361 [16.0][ADD] stock_move_free_reservation_reassign: New Addon
  setup/stock_move_free_reservation_reassign/odoo/addons/stock_move_free_reservation_reassign
  setup/stock_move_free_reservation_reassign/setup.py
  stock_move_free_reservation_reassign/README.rst
  stock_move_free_reservation_reassign/__init__.py
  stock_move_free_reservation_reassign/__manifest__.py
  stock_move_free_reservation_reassign/models/__init__.py
  stock_move_free_reservation_reassign/models/res_config_settings.py
  stock_move_free_reservation_reassign/models/stock_move_line.py
  stock_move_free_reservation_reassign/models/stock_quant.py
  stock_move_free_reservation_reassign/readme/CONTRIBUTORS.rst
  stock_move_free_reservation_reassign/readme/DESCRIPTION.rst
  stock_move_free_reservation_reassign/readme/USAGE.rst
  stock_move_free_reservation_reassign/static/description/icon.png
  stock_move_free_reservation_reassign/tests/__init__.py
  stock_move_free_reservation_reassign/tests/test_stock_move_free_reservation_reassign.py
  stock_move_free_reservation_reassign/views/res_config_settings.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1370 [13.0][IMP] product_cost_price_avco_sync: detect returns using correct field
  product_cost_price_avco_sync/models/stock_valuation_layer.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1138 [15.0][MIG] product_cost_price_avco_sync: Migration to 15.0
  product_cost_price_avco_sync/README.rst
  product_cost_price_avco_sync/__init__.py
  product_cost_price_avco_sync/__manifest__.py
  product_cost_price_avco_sync/i18n/es.po
  product_cost_price_avco_sync/i18n/product_cost_price_avco_sync.pot
  product_cost_price_avco_sync/i18n/pt_BR.po
  product_cost_price_avco_sync/models/__init__.py
  product_cost_price_avco_sync/models/stock_move_line.py
  product_cost_price_avco_sync/models/stock_picking.py
  product_cost_price_avco_sync/models/stock_valuation_layer.py
  product_cost_price_avco_sync/readme/CONTRIBUTORS.rst
  product_cost_price_avco_sync/readme/DESCRIPTION.rst
  product_cost_price_avco_sync/static/description/icon.png
  product_cost_price_avco_sync/static/description/index.html
  product_cost_price_avco_sync/tests/__init__.py
  product_cost_price_avco_sync/tests/test_product_cost_price_avco_sync.py
  setup/product_cost_price_avco_sync/odoo/addons/product_cost_price_avco_sync
  setup/product_cost_price_avco_sync/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1286 [14.0][MIG] product_cost_price_avco_sync: Migration to 14.0
  product_cost_price_avco_sync/README.rst
  product_cost_price_avco_sync/__init__.py
  product_cost_price_avco_sync/__manifest__.py
  product_cost_price_avco_sync/i18n/es.po
  product_cost_price_avco_sync/i18n/product_cost_price_avco_sync.pot
  product_cost_price_avco_sync/i18n/pt_BR.po
  product_cost_price_avco_sync/models/__init__.py
  product_cost_price_avco_sync/models/stock_move_line.py
  product_cost_price_avco_sync/models/stock_picking.py
  product_cost_price_avco_sync/models/stock_valuation_layer.py
  product_cost_price_avco_sync/readme/CONTRIBUTORS.rst
  product_cost_price_avco_sync/readme/DESCRIPTION.rst
  product_cost_price_avco_sync/static/description/icon.png
  product_cost_price_avco_sync/static/description/index.html
  product_cost_price_avco_sync/tests/__init__.py
  product_cost_price_avco_sync/tests/test_product_cost_price_avco_sync.py
  setup/product_cost_price_avco_sync/odoo/addons/product_cost_price_avco_sync
  setup/product_cost_price_avco_sync/setup.py
Labels: approved, bot is merging ⏳

#1373 [15.0][IMP] stock_picking_batch_extended_account: Make tests resilient
  stock_picking_batch_extended_account/tests/test_stock_picking_batch_extended_account.py
Labels: approved, bot is merging ⏳

#1353 [16.0] [MIG] stock_picking_batch_extended: Migration to 16.0
  setup/stock_picking_batch_extended/odoo/addons/stock_picking_batch_extended
  setup/stock_picking_batch_extended/setup.py
  stock_picking_batch_extended/README.rst
  stock_picking_batch_extended/__init__.py
  stock_picking_batch_extended/__manifest__.py
  stock_picking_batch_extended/data/batch_picking_actions_server.xml
  stock_picking_batch_extended/hooks.py
  stock_picking_batch_extended/i18n/de.po
  stock_picking_batch_extended/i18n/es.po
  stock_picking_batch_extended/i18n/es_CL.po
  stock_picking_batch_extended/i18n/fr.po
  stock_picking_batch_extended/i18n/it.po
  stock_picking_batch_extended/i18n/pt_BR.po
  stock_picking_batch_extended/i18n/sl.po
  stock_picking_batch_extended/i18n/stock_picking_batch_extended.pot
  stock_picking_batch_extended/models/__init__.py
  stock_picking_batch_extended/models/product_product.py
  stock_picking_batch_extended/models/res_config_settings.py
  stock_picking_batch_extended/models/stock_batch_picking.py
  stock_picking_batch_extended/models/stock_warehouse.py
  stock_picking_batch_extended/readme/CONTRIBUTORS.rst
  stock_picking_batch_extended/readme/CREDITS.rst
  stock_picking_batch_extended/readme/DESCRIPTION.rst
  stock_picking_batch_extended/report/__init__.py
  stock_picking_batch_extended/report/batch_report.py
  stock_picking_batch_extended/security/ir.model.access.csv
  stock_picking_batch_extended/static/batch_form.jpg
  stock_picking_batch_extended/static/batch_form_operation.jpg
  stock_picking_batch_extended/static/batch_wizard.jpg
  stock_picking_batch_extended/static/description/icon.png
  stock_picking_batch_extended/static/description/index.html
  stock_picking_batch_extended/static/picking_batch_configuration_settings.jpg
  stock_picking_batch_extended/static/stock_picking_list.jpg
  stock_picking_batch_extended/tests/__init__.py
  stock_picking_batch_extended/tests/test_batch.py
  stock_picking_batch_extended/views/product_product.xml
  stock_picking_batch_extended/views/report_batch_picking.xml
  stock_picking_batch_extended/views/res_config_settings_views.xml
  stock_picking_batch_extended/views/stock_batch_picking.xml
  stock_picking_batch_extended/views/stock_picking_views.xml
  stock_picking_batch_extended/views/stock_warehouse.xml
  stock_picking_batch_extended/wizard/__init__.py
  stock_picking_batch_extended/wizard/stock_picking_to_batch.py
  stock_picking_batch_extended/wizard/stock_picking_to_batch_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1284 [16.0][IMP] stock_no_negative: add option to skip negative qty check
  stock_no_negative/models/stock_quant.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1323 [16.0][MIG] stock_account_product_run_fifo_hook: Migration to 16.0
  setup/stock_account_product_run_fifo_hook/odoo/addons/stock_account_product_run_fifo_hook
  setup/stock_account_product_run_fifo_hook/setup.py
  stock_account_product_run_fifo_hook/README.rst
  stock_account_product_run_fifo_hook/__init__.py
  stock_account_product_run_fifo_hook/__manifest__.py
  stock_account_product_run_fifo_hook/hooks.py
  stock_account_product_run_fifo_hook/i18n/stock_account_product_run_fifo_hook.pot
  stock_account_product_run_fifo_hook/model/__init__.py
  stock_account_product_run_fifo_hook/model/product.py
  stock_account_product_run_fifo_hook/readme/CONTRIBUTORS.rst
  stock_account_product_run_fifo_hook/readme/DESCRIPTION.rst
  stock_account_product_run_fifo_hook/readme/USAGE.rst
  stock_account_product_run_fifo_hook/static/description/icon.png
  stock_account_product_run_fifo_hook/static/description/index.html
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1337 [16.0][MIG] sale order global stock route
  sale_order_global_stock_route/README.rst
  sale_order_global_stock_route/__init__.py
  sale_order_global_stock_route/__manifest__.py
  sale_order_global_stock_route/i18n/es.po
  sale_order_global_stock_route/i18n/it.po
  sale_order_global_stock_route/i18n/pt_BR.po
  sale_order_global_stock_route/i18n/sale_order_global_stock_route.pot
  sale_order_global_stock_route/models/__init__.py
  sale_order_global_stock_route/models/sale_order.py
  sale_order_global_stock_route/readme/CONFIGURE.rst
  sale_order_global_stock_route/readme/CONTRIBUTORS.rst
  sale_order_global_stock_route/readme/DESCRIPTION.rst
  sale_order_global_stock_route/readme/USAGE.rst
  sale_order_global_stock_route/static/description/icon.png
  sale_order_global_stock_route/static/description/index.html
  sale_order_global_stock_route/tests/__init__.py
  sale_order_global_stock_route/tests/test_sale_order_global_stock_route.py
  sale_order_global_stock_route/views/sale_order_views.xml
  setup/sale_order_global_stock_route/odoo/addons/sale_order_global_stock_route
  setup/sale_order_global_stock_route/setup.py
Labels: needs review, migration, bot is merging ⏳

#1379 [16.0][FIX] cannot re-assign move after applying inventory
  stock_move_free_reservation_reassign/models/stock_quant.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1326 [16.0][MIG] stock_valuation_layer_usage: Migration to 16.0
  setup/stock_valuation_layer_usage/odoo/addons/stock_valuation_layer_usage
  setup/stock_valuation_layer_usage/setup.py
  stock_valuation_layer_usage/README.rst
  stock_valuation_layer_usage/__init__.py
  stock_valuation_layer_usage/__manifest__.py
  stock_valuation_layer_usage/i18n/stock_valuation_layer_usage.pot
  stock_valuation_layer_usage/models/__init__.py
  stock_valuation_layer_usage/models/stock_move.py
  stock_valuation_layer_usage/models/stock_valuation_layer.py
  stock_valuation_layer_usage/models/stock_valuation_layer_usage.py
  stock_valuation_layer_usage/readme/CONTRIBUTORS.rst
  stock_valuation_layer_usage/readme/DESCRIPTION.rst
  stock_valuation_layer_usage/readme/HISTORY.rst
  stock_valuation_layer_usage/readme/INSTALL.rst
  stock_valuation_layer_usage/readme/USAGE.rst
  stock_valuation_layer_usage/security/ir.model.access.csv
  stock_valuation_layer_usage/static/description/icon.png
  stock_valuation_layer_usage/static/description/index.html
  stock_valuation_layer_usage/tests/__init__.py
  stock_valuation_layer_usage/tests/test_stock_valuation_layer_usage.py
  stock_valuation_layer_usage/views/stock_move_views.xml
  stock_valuation_layer_usage/views/stock_valuation_layer_usage_views.xml
  stock_valuation_layer_usage/views/stock_valuation_layer_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1382 [15.0][ADD] stock_reception_discrepancy_distribution: New module to distribute outgoing demand for mto orders
  setup/stock_reception_discrepancy_distribution/odoo/addons/stock_reception_discrepancy_distribution
  setup/stock_reception_discrepancy_distribution/setup.py
  stock_reception_discrepancy_distribution/README.rst
  stock_reception_discrepancy_distribution/__init__.py
  stock_reception_discrepancy_distribution/__manifest__.py
  stock_reception_discrepancy_distribution/i18n/es.po
  stock_reception_discrepancy_distribution/i18n/stock_reception_discrepancy_distribution.pot
  stock_reception_discrepancy_distribution/models/__init__.py
  stock_reception_discrepancy_distribution/models/stock_move.py
  stock_reception_discrepancy_distribution/readme/CONTRIBUTORS.rst
  stock_reception_discrepancy_distribution/readme/DESCRIPTION.rst
  stock_reception_discrepancy_distribution/readme/USAGE.rst
  stock_reception_discrepancy_distribution/security/ir.model.access.csv
  stock_reception_discrepancy_distribution/static/description/icon.png
  stock_reception_discrepancy_distribution/static/description/index.html
  stock_reception_discrepancy_distribution/tests/__init__.py
  stock_reception_discrepancy_distribution/tests/test_stock_reception_discrepancy_distribution.py
  stock_reception_discrepancy_distribution/views/stock_picking_views.xml
  stock_reception_discrepancy_distribution/wizards/__init__.py
  stock_reception_discrepancy_distribution/wizards/stock_reception_discrepancy_distribution_views.xml
  stock_reception_discrepancy_distribution/wizards/stock_reception_discrepancy_distribution_wiz.py
Labels: approved, ready to merge, bot is merging ⏳
