Repository OCA/stock-logistics-workflow, pull requests merged in 2023-05, with the labels that each got.

#1280 [16.0][FW-PORT] stock_split_picking: hook to validate split
  stock_split_picking/models/stock_picking.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1279 [15.0][FW-PORT] stock_split_picking: hook to validate split
  stock_split_picking/models/stock_picking.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1278 [14.0][FW-PORT] stock_split_picking: hook to validate split
  stock_split_picking/models/stock_picking.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#892 [13.0][ADD] stock_deferred_assign: Add new module
  setup/stock_deferred_assign/odoo/addons/stock_deferred_assign
  setup/stock_deferred_assign/setup.py
  stock_deferred_assign/README.rst
  stock_deferred_assign/__init__.py
  stock_deferred_assign/__manifest__.py
  stock_deferred_assign/i18n/es.po
  stock_deferred_assign/i18n/stock_deferred_assign.pot
  stock_deferred_assign/migrations/13.0.1.0.0/pre-migration.py
  stock_deferred_assign/models/__init__.py
  stock_deferred_assign/models/sale.py
  stock_deferred_assign/models/stock_move.py
  stock_deferred_assign/models/stock_picking.py
  stock_deferred_assign/models/stock_picking_type.py
  stock_deferred_assign/models/stock_rule.py
  stock_deferred_assign/readme/CONFIGURATION.rst
  stock_deferred_assign/readme/CONTRIBUTORS.rst
  stock_deferred_assign/readme/DESCRIPTION.rst
  stock_deferred_assign/static/description/icon.png
  stock_deferred_assign/static/description/index.html
  stock_deferred_assign/tests/__init__.py
  stock_deferred_assign/tests/test_stock_deferred_assign.py
  stock_deferred_assign/views/picking_type.xml
Labels: needs review, approved, bot is merging ⏳

#1288 [15.0][FIX] stock_picking_batch_extended: New batch is created when existing mode is selected.
  stock_picking_batch_extended/tests/test_batch.py
  stock_picking_batch_extended/wizard/stock_picking_to_batch.py
Labels: approved, bot is merging ⏳

#1130 [15.0][FIX] stock_split_picking: 'done' mode
  stock_split_picking/models/stock_picking.py
  stock_split_picking/readme/CONTRIBUTORS.rst
  stock_split_picking/tests/test_stock_split_picking.py
Labels: approved, bot is merging ⏳, stale

#1290 [IMP] product_supplierinfo_for_customer_picking: compute picking move…
  product_supplierinfo_for_customer_picking/models/stock_move.py
  product_supplierinfo_for_customer_picking/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_picking/tests/test_product_supplierinfo_for_customer_picking.py
  product_supplierinfo_for_customer_picking/views/stock_picking_view.xml
Labels: approved, bot is merging ⏳

#1132 [14.0][IMP] stock_owner_restriction: Partner or unassigned stock option
  stock_owner_restriction/models/stock_move.py
  stock_owner_restriction/models/stock_picking_type.py
  stock_owner_restriction/tests/test_stock_owner_restriction.py
Labels: enhancement, needs review, approved, bot is merging ⏳, stale

#1294 [15.0][IMP] stock_owner_restriction: Partner or unassigned stock option
  stock_owner_restriction/README.rst
  stock_owner_restriction/models/stock_move.py
  stock_owner_restriction/models/stock_picking_type.py
  stock_owner_restriction/tests/test_stock_owner_restriction.py
Labels: approved, bot is merging ⏳

#1185 [16.0][ADD] stock_procurement_customer
  setup/stock_procurement_customer/odoo/addons/stock_procurement_customer
  setup/stock_procurement_customer/setup.py
  stock_procurement_customer/README.rst
  stock_procurement_customer/__init__.py
  stock_procurement_customer/__manifest__.py
  stock_procurement_customer/models/__init__.py
  stock_procurement_customer/models/procurement_group.py
  stock_procurement_customer/models/stock_move.py
  stock_procurement_customer/models/stock_picking.py
  stock_procurement_customer/readme/CONTRIBUTORS.rst
  stock_procurement_customer/readme/DESCRIPTION.rst
  stock_procurement_customer/readme/USAGE.rst
  stock_procurement_customer/static/description/icon.png
  stock_procurement_customer/static/description/index.html
  stock_procurement_customer/tests/__init__.py
  stock_procurement_customer/tests/test_stock_procurement_customer.py
  stock_procurement_customer/views/procurement_group.xml
  stock_procurement_customer/views/stock_picking.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1295 [15.0][FIX] stock_picking_invoice_link: Wrong link when several lines have same product
  stock_picking_invoice_link/models/account_move.py
  stock_picking_invoice_link/models/sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#1291 [FIX] stock_picking_batch_extended: An user without Administrator group security can not select fields to group picking batch
  stock_picking_batch_extended/security/ir.model.access.csv
Labels: approved, ready to merge, bot is merging ⏳

#1190 [MIG] stock_move_backdating
  setup/stock_move_backdating/odoo/addons/stock_move_backdating
  setup/stock_move_backdating/setup.py
  stock_move_backdating/README.rst
  stock_move_backdating/__init__.py
  stock_move_backdating/__manifest__.py
  stock_move_backdating/i18n/am.po
  stock_move_backdating/i18n/ca.po
  stock_move_backdating/i18n/de.po
  stock_move_backdating/i18n/es.po
  stock_move_backdating/i18n/es_AR.po
  stock_move_backdating/i18n/es_MX.po
  stock_move_backdating/i18n/fi.po
  stock_move_backdating/i18n/fr.po
  stock_move_backdating/i18n/gl.po
  stock_move_backdating/i18n/hr.po
  stock_move_backdating/i18n/hr_HR.po
  stock_move_backdating/i18n/it.po
  stock_move_backdating/i18n/nl.po
  stock_move_backdating/i18n/pt.po
  stock_move_backdating/i18n/pt_BR.po
  stock_move_backdating/i18n/pt_PT.po
  stock_move_backdating/i18n/ro.po
  stock_move_backdating/i18n/sl.po
  stock_move_backdating/i18n/stock_move_backdating.pot
  stock_move_backdating/i18n/tr.po
  stock_move_backdating/i18n/tr_TR.po
  stock_move_backdating/models/__init__.py
  stock_move_backdating/models/stock_inventory.py
  stock_move_backdating/models/stock_inventory_line.py
  stock_move_backdating/models/stock_move.py
  stock_move_backdating/models/stock_move_line.py
  stock_move_backdating/models/stock_picking.py
  stock_move_backdating/models/stock_quant.py
  stock_move_backdating/readme/CONTRIBUTORS.rst
  stock_move_backdating/readme/DESCRIPTION.rst
  stock_move_backdating/static/description/icon.png
  stock_move_backdating/static/description/index.html
  stock_move_backdating/tests/__init__.py
  stock_move_backdating/tests/common.py
  stock_move_backdating/tests/test_inventory.py
  stock_move_backdating/tests/test_picking.py
  stock_move_backdating/views/stock_inventory_views.xml
  stock_move_backdating/views/stock_picking.xml
  stock_move_backdating/wizards/__init__.py
  stock_move_backdating/wizards/fill_date_backdating.py
  stock_move_backdating/wizards/fill_date_backdating.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳, stale
