Repository OCA/stock-logistics-workflow, pull requests merged in 2024-05, with the labels that each got.

#1584 [17.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .ruff.toml
  stock_picking_invoice_link/models/account_move.py
  stock_picking_invoice_link/tests/test_stock_picking_invoice_link.py
  stock_picking_show_return/tests/test_stock_picking_show_return.py
Labels: help wanted, needs review, bot is merging ⏳

#1514 [16.0][FIX] stock_picking_auto_create_lot: immediate transfer with auto_create_lot option
  stock_picking_auto_create_lot/README.rst
  stock_picking_auto_create_lot/models/stock_move.py
  stock_picking_auto_create_lot/readme/CONTRIBUTORS.rst
  stock_picking_auto_create_lot/static/description/index.html
  stock_picking_auto_create_lot/tests/test_stock_picking_auto_create_lot.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1452 [16.0][IMP] delivery_procurement_group_carrier: Set Carrier on new picking from procurement.group and group new moves per carrier
  delivery_procurement_group_carrier/README.rst
  delivery_procurement_group_carrier/__manifest__.py
  delivery_procurement_group_carrier/models/__init__.py
  delivery_procurement_group_carrier/models/stock_move.py
  delivery_procurement_group_carrier/readme/CONTRIBUTORS.rst
  delivery_procurement_group_carrier/static/description/index.html
Labels: enhancement, needs review, bot is merging ⏳, stale

#1585 [16.0][ADD] stock_customer_deposit_sale_margin
  .copier-answers.yml
  .github/workflows/test.yml
  setup/stock_customer_deposit_sale_margin/odoo/addons/stock_customer_deposit_sale_margin
  setup/stock_customer_deposit_sale_margin/setup.py
  stock_customer_deposit_sale_margin/README.rst
  stock_customer_deposit_sale_margin/__init__.py
  stock_customer_deposit_sale_margin/__manifest__.py
  stock_customer_deposit_sale_margin/i18n/es.po
  stock_customer_deposit_sale_margin/i18n/stock_customer_deposit_sale_margin.pot
  stock_customer_deposit_sale_margin/models/__init__.py
  stock_customer_deposit_sale_margin/models/sale_order_line.py
  stock_customer_deposit_sale_margin/readme/CONTEXT.md
  stock_customer_deposit_sale_margin/readme/CONTRIBUTORS.md
  stock_customer_deposit_sale_margin/readme/DESCRIPTION.md
  stock_customer_deposit_sale_margin/readme/USAGE.md
  stock_customer_deposit_sale_margin/static/description/icon.png
  stock_customer_deposit_sale_margin/static/description/index.html
  stock_customer_deposit_sale_margin/tests/__init__.py
  stock_customer_deposit_sale_margin/tests/test_stock_customer_deposit_sale_margin.py
Labels: approved, bot is merging ⏳

#1528 [16.0][MIG] stock_picking_group_by_partner_by_carrier_by_date: Migration to 16.0
  setup/stock_picking_group_by_partner_by_carrier_by_date/odoo/addons/stock_picking_group_by_partner_by_carrier_by_date
  setup/stock_picking_group_by_partner_by_carrier_by_date/setup.py
  stock_picking_group_by_partner_by_carrier_by_date/README.rst
  stock_picking_group_by_partner_by_carrier_by_date/__init__.py
  stock_picking_group_by_partner_by_carrier_by_date/__manifest__.py
  stock_picking_group_by_partner_by_carrier_by_date/i18n/it.po
  stock_picking_group_by_partner_by_carrier_by_date/i18n/stock_picking_group_by_partner_by_carrier_by_date.pot
  stock_picking_group_by_partner_by_carrier_by_date/models/__init__.py
  stock_picking_group_by_partner_by_carrier_by_date/models/stock_move.py
  stock_picking_group_by_partner_by_carrier_by_date/models/stock_picking_type.py
  stock_picking_group_by_partner_by_carrier_by_date/readme/CONTRIBUTORS.rst
  stock_picking_group_by_partner_by_carrier_by_date/readme/CREDITS.rst
  stock_picking_group_by_partner_by_carrier_by_date/readme/DESCRIPTION.rst
  stock_picking_group_by_partner_by_carrier_by_date/readme/USAGE.rst
  stock_picking_group_by_partner_by_carrier_by_date/static/description/icon.png
  stock_picking_group_by_partner_by_carrier_by_date/static/description/index.html
  stock_picking_group_by_partner_by_carrier_by_date/tests/__init__.py
  stock_picking_group_by_partner_by_carrier_by_date/tests/test_grouping_by_date.py
  stock_picking_group_by_partner_by_carrier_by_date/views/stock_picking_type.xml
Labels: approved, migration, ready to merge, bot is merging ⏳

#1588 [15.0][FIX] product_cost_price_avco_sync: Product singleton after Odoo refactor
  product_cost_price_avco_sync/models/stock_valuation_layer.py
  stock_account_product_run_fifo_hook/hooks.py
  stock_account_product_run_fifo_hook/model/product.py
Labels: approved, bot is merging ⏳

#1589 [ADD] stock_picking_batch_validate_confirm
  setup/stock_picking_batch_validate_confirm/odoo/addons/stock_picking_batch_validate_confirm
  setup/stock_picking_batch_validate_confirm/setup.py
  stock_picking_batch_validate_confirm/README.rst
  stock_picking_batch_validate_confirm/__init__.py
  stock_picking_batch_validate_confirm/__manifest__.py
  stock_picking_batch_validate_confirm/i18n/es.po
  stock_picking_batch_validate_confirm/i18n/stock_picking_batch_validate_confirm.pot
  stock_picking_batch_validate_confirm/models/__init__.py
  stock_picking_batch_validate_confirm/models/stock_picking_batch.py
  stock_picking_batch_validate_confirm/readme/CONFIGURE.md
  stock_picking_batch_validate_confirm/readme/CONTRIBUTORS.md
  stock_picking_batch_validate_confirm/readme/DESCRIPTION.md
  stock_picking_batch_validate_confirm/readme/USAGE.md
  stock_picking_batch_validate_confirm/security/ir.model.access.csv
  stock_picking_batch_validate_confirm/static/description/icon.png
  stock_picking_batch_validate_confirm/static/description/index.html
  stock_picking_batch_validate_confirm/tests/__init__.py
  stock_picking_batch_validate_confirm/tests/test_batch_confirm.py
  stock_picking_batch_validate_confirm/wizards/__init__.py
  stock_picking_batch_validate_confirm/wizards/stock_picking_batch_confirm.py
  stock_picking_batch_validate_confirm/wizards/stock_picking_batch_confirm.xml
Labels: approved, ready to merge, bot is merging ⏳

#1375 [14.0][ADD] add stock_picking_auto_create_lot_qty
  setup/stock_picking_auto_create_lot_qty/odoo/addons/stock_picking_auto_create_lot_qty
  setup/stock_picking_auto_create_lot_qty/setup.py
  stock_picking_auto_create_lot_qty/README.rst
  stock_picking_auto_create_lot_qty/__init__.py
  stock_picking_auto_create_lot_qty/__manifest__.py
  stock_picking_auto_create_lot_qty/models/__init__.py
  stock_picking_auto_create_lot_qty/models/product_template.py
  stock_picking_auto_create_lot_qty/models/res_company.py
  stock_picking_auto_create_lot_qty/models/res_config_settings.py
  stock_picking_auto_create_lot_qty/models/stock_picking.py
  stock_picking_auto_create_lot_qty/models/stock_production_lot.py
  stock_picking_auto_create_lot_qty/readme/CONFIGURE.md
  stock_picking_auto_create_lot_qty/readme/CONTRIBUTORS.md
  stock_picking_auto_create_lot_qty/readme/DESCRIPTION.md
  stock_picking_auto_create_lot_qty/readme/USAGE.md
  stock_picking_auto_create_lot_qty/static/description/index.html
  stock_picking_auto_create_lot_qty/tests/__init__.py
  stock_picking_auto_create_lot_qty/tests/common.py
  stock_picking_auto_create_lot_qty/tests/test_stock_picking_auto_create_lot_qty.py
  stock_picking_auto_create_lot_qty/views/product_template_view.xml
  stock_picking_auto_create_lot_qty/views/res_config_settings_view.xml
  test-requirements.txt
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1595 [FIX] [16.0] stock_customer_deposit: Lines taken from deposit has 100% discount and the original price_unit
  stock_customer_deposit/README.rst
  stock_customer_deposit/models/sale_order_line.py
  stock_customer_deposit/readme/CONTRIBUTORS.md
  stock_customer_deposit/readme/USAGE.md
  stock_customer_deposit/static/description/index.html
  stock_customer_deposit/tests/test_deliver_customer_deposit.py
Labels: approved, bot is merging ⏳

#1582 [15.0][ADD] ``stock_picking_propagate_scheduled_date``
  setup/stock_picking_propagate_scheduled_date/odoo/addons/stock_picking_propagate_scheduled_date
  setup/stock_picking_propagate_scheduled_date/setup.py
  stock_picking_propagate_scheduled_date/README.rst
  stock_picking_propagate_scheduled_date/__init__.py
  stock_picking_propagate_scheduled_date/__manifest__.py
  stock_picking_propagate_scheduled_date/models/__init__.py
  stock_picking_propagate_scheduled_date/models/stock_move.py
  stock_picking_propagate_scheduled_date/readme/CONTRIBUTORS.rst
  stock_picking_propagate_scheduled_date/readme/DESCRIPTION.rst
  stock_picking_propagate_scheduled_date/static/description/icon.png
  stock_picking_propagate_scheduled_date/static/description/index.html
  stock_picking_propagate_scheduled_date/tests/__init__.py
  stock_picking_propagate_scheduled_date/tests/test_stock_picking_propagate_scheduled_date.py
Labels: approved, ready to merge, bot is merging ⏳

#1596 [17.0][MIG] stock_move_line_reference_link
  stock_move_line_reference_link/README.rst
  stock_move_line_reference_link/__init__.py
  stock_move_line_reference_link/__manifest__.py
  stock_move_line_reference_link/i18n/stock_move_line_reference_link.pot
  stock_move_line_reference_link/models/__init__.py
  stock_move_line_reference_link/models/stock_move_line.py
  stock_move_line_reference_link/pyproject.toml
  stock_move_line_reference_link/readme/CONTRIBUTORS.md
  stock_move_line_reference_link/readme/DESCRIPTION.md
  stock_move_line_reference_link/static/description/icon.png
  stock_move_line_reference_link/static/description/index.html
  stock_move_line_reference_link/views/move_line_views.xml
Labels: approved, bot is merging ⏳

#1604 [15.0][IMP] stock_picking_propagate_scheduled_date: tests
  stock_picking_propagate_scheduled_date/tests/test_stock_picking_propagate_scheduled_date.py
Labels: merged 🎉

#1601 [15.0][IMP] stock_picking_auto_create_lot: Use Odoo core mechanism to create lots in pickings filling lot_name field instead of create all lots.
  stock_picking_auto_create_lot/models/__init__.py
  stock_picking_auto_create_lot/models/stock_move_line.py
  stock_picking_auto_create_lot/models/stock_picking.py
  stock_picking_auto_create_lot/tests/test_stock_picking_auto_create_lot.py
Labels: enhancement, needs review, approved, merged 🎉

#1605 [16.0][REM] stock_account_product_run_fifo_hook: Not usable right now
  .pre-commit-config.yaml
  setup/stock_account_product_run_fifo_hook/odoo/addons/stock_account_product_run_fifo_hook
  setup/stock_account_product_run_fifo_hook/setup.py
  setup/stock_valuation_layer_usage/odoo/addons/stock_valuation_layer_usage
  setup/stock_valuation_layer_usage/setup.py
  stock_account_product_run_fifo_hook/__init__.py
  stock_account_product_run_fifo_hook/__manifest__.py
  stock_valuation_layer_usage/__manifest__.py
Labels: bot is merging ⏳

#1559 [16.0][MIG] stock_landed_costs_delivery: Migration to version 16.0
  setup/stock_landed_costs_delivery/odoo/addons/stock_landed_costs_delivery
  setup/stock_landed_costs_delivery/setup.py
  stock_landed_costs_delivery/README.rst
  stock_landed_costs_delivery/__init__.py
  stock_landed_costs_delivery/__manifest__.py
  stock_landed_costs_delivery/i18n/it.po
  stock_landed_costs_delivery/i18n/stock_landed_costs_delivery.pot
  stock_landed_costs_delivery/models/__init__.py
  stock_landed_costs_delivery/models/delivery_carrier.py
  stock_landed_costs_delivery/models/purchase_order.py
  stock_landed_costs_delivery/models/stock_picking.py
  stock_landed_costs_delivery/readme/CONTRIBUTORS.rst
  stock_landed_costs_delivery/readme/DESCRIPTION.rst
  stock_landed_costs_delivery/readme/USAGE.rst
  stock_landed_costs_delivery/static/description/icon.png
  stock_landed_costs_delivery/static/description/index.html
  stock_landed_costs_delivery/tests/__init__.py
  stock_landed_costs_delivery/tests/test_purchase_order.py
  stock_landed_costs_delivery/views/delivery_carrier_view.xml
Labels: approved, bot is merging ⏳

#1597 [16.0][FIX] stock_account_product_run_fifo_hook, rewrite to original method
  .pre-commit-config.yaml
  setup/stock_account_product_run_fifo_hook/odoo/addons/stock_account_product_run_fifo_hook
  setup/stock_account_product_run_fifo_hook/setup.py
  setup/stock_valuation_layer_usage/odoo/addons/stock_valuation_layer_usage
  setup/stock_valuation_layer_usage/setup.py
  stock_account_product_run_fifo_hook/__init__.py
  stock_account_product_run_fifo_hook/__manifest__.py
  stock_account_product_run_fifo_hook/hooks.py
  stock_account_product_run_fifo_hook/model/product.py
  stock_valuation_layer_usage/__manifest__.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1602 [REF] stock_picking_batch_print_pickings: Upgrading for dynamic printing
  stock_picking_batch_print_invoices/README.rst
  stock_picking_batch_print_invoices/i18n/es.po
  stock_picking_batch_print_invoices/i18n/stock_picking_batch_print_invoices.pot
  stock_picking_batch_print_invoices/migrations/16.0.1.0.3/post-migrate.py
  stock_picking_batch_print_invoices/models/stock_picking_batch.py
  stock_picking_batch_print_invoices/models/stock_picking_type.py
  stock_picking_batch_print_invoices/readme/CONFIGURE.md
  stock_picking_batch_print_invoices/readme/DESCRIPTION.md
  stock_picking_batch_print_invoices/static/description/index.html
  stock_picking_batch_print_invoices/tests/test_batch_print_invoices.py
  stock_picking_batch_print_invoices/views/report_picking_batch_print_invoices.xml
  stock_picking_batch_print_invoices/views/stock_picking_type_views.xml
  stock_picking_batch_print_pickings/README.rst
  stock_picking_batch_print_pickings/i18n/es.po
  stock_picking_batch_print_pickings/i18n/stock_picking_batch_print_pickings.pot
  stock_picking_batch_print_pickings/migrations/16.0.1.0.3/post-migrate.py
  stock_picking_batch_print_pickings/models/stock_picking_batch.py
  stock_picking_batch_print_pickings/models/stock_picking_type.py
  stock_picking_batch_print_pickings/readme/USAGE.md
  stock_picking_batch_print_pickings/static/description/index.html
  stock_picking_batch_print_pickings/tests/test_batch_print_pickings.py
  stock_picking_batch_print_pickings/views/report_picking_batch_print_pickings.xml
  stock_picking_batch_print_pickings/views/stock_picking_batch_views.xml
  stock_picking_batch_print_pickings/views/stock_picking_type_views.xml
Labels: needs review, approved, bot is merging ⏳
