Repository OCA/stock-logistics-workflow, pull requests merged in 2024-01, with the labels that each got.

#1471 [16.0][MIG] stock_lot_scrap: Migration to version 16.0
  setup/stock_lot_scrap/odoo/addons/stock_lot_scrap
  setup/stock_lot_scrap/setup.py
  stock_lot_scrap/README.rst
  stock_lot_scrap/__init__.py
  stock_lot_scrap/__manifest__.py
  stock_lot_scrap/i18n/de.po
  stock_lot_scrap/i18n/es.po
  stock_lot_scrap/i18n/fr.po
  stock_lot_scrap/i18n/hr.po
  stock_lot_scrap/i18n/it.po
  stock_lot_scrap/i18n/pt.po
  stock_lot_scrap/i18n/pt_BR.po
  stock_lot_scrap/i18n/sl.po
  stock_lot_scrap/i18n/stock_lot_scrap.pot
  stock_lot_scrap/models/__init__.py
  stock_lot_scrap/models/stock_lot.py
  stock_lot_scrap/models/stock_scrap.py
  stock_lot_scrap/readme/CONFIGURE.rst
  stock_lot_scrap/readme/CONTRIBUTORS.rst
  stock_lot_scrap/readme/DESCRIPTION.rst
  stock_lot_scrap/readme/USAGE.rst
  stock_lot_scrap/static/description/icon.png
  stock_lot_scrap/static/description/index.html
  stock_lot_scrap/tests/__init__.py
  stock_lot_scrap/tests/test_stock_lot_scrap.py
Labels: approved, bot is merging ⏳

#1475 [16.0][ADD] stock_picking_batch_invoice_frequency
  setup/stock_picking_batch_invoice_frequency/odoo/addons/stock_picking_batch_invoice_frequency
  setup/stock_picking_batch_invoice_frequency/setup.py
  stock_picking_batch_invoice_frequency/README.rst
  stock_picking_batch_invoice_frequency/__init__.py
  stock_picking_batch_invoice_frequency/__manifest__.py
  stock_picking_batch_invoice_frequency/i18n/es.po
  stock_picking_batch_invoice_frequency/i18n/stock_picking_batch_invoice_frecuency.pot
  stock_picking_batch_invoice_frequency/models/__init__.py
  stock_picking_batch_invoice_frequency/models/sale_invoice_frequency.py
  stock_picking_batch_invoice_frequency/models/stock_picking.py
  stock_picking_batch_invoice_frequency/models/stock_picking_batch.py
  stock_picking_batch_invoice_frequency/readme/CONFIGURE.md
  stock_picking_batch_invoice_frequency/readme/CONTRIBUTORS.md
  stock_picking_batch_invoice_frequency/readme/DESCRIPTION.md
  stock_picking_batch_invoice_frequency/readme/USAGE.md
  stock_picking_batch_invoice_frequency/static/description/index.html
  stock_picking_batch_invoice_frequency/tests/__init__.py
  stock_picking_batch_invoice_frequency/tests/test_batch_invoice.py
  stock_picking_batch_invoice_frequency/views/sale_invoice_frequency.xml
Labels: needs review, approved, bot is merging ⏳

#1474 [16.0][MIG] stock_picking_send_by_mail: Migration to version 16.0
  setup/stock_picking_send_by_mail/odoo/addons/stock_picking_send_by_mail
  setup/stock_picking_send_by_mail/setup.py
  stock_picking_send_by_mail/README.rst
  stock_picking_send_by_mail/__init__.py
  stock_picking_send_by_mail/__manifest__.py
  stock_picking_send_by_mail/i18n/de.po
  stock_picking_send_by_mail/i18n/es.po
  stock_picking_send_by_mail/i18n/fr.po
  stock_picking_send_by_mail/i18n/it.po
  stock_picking_send_by_mail/i18n/pt.po
  stock_picking_send_by_mail/i18n/pt_BR.po
  stock_picking_send_by_mail/i18n/stock_picking_send_by_mail.pot
  stock_picking_send_by_mail/models/__init__.py
  stock_picking_send_by_mail/models/stock_picking.py
  stock_picking_send_by_mail/readme/CONTRIBUTORS.rst
  stock_picking_send_by_mail/readme/DESCRIPTION.rst
  stock_picking_send_by_mail/readme/USAGE.rst
  stock_picking_send_by_mail/static/description/icon.png
  stock_picking_send_by_mail/static/description/index.html
  stock_picking_send_by_mail/tests/__init__.py
  stock_picking_send_by_mail/tests/test_stock_picking_send_by_mail.py
  stock_picking_send_by_mail/views/stock_picking_view.xml
Labels: bot is merging ⏳

#1301 [15][ADD] stock_move_name_from_sale_line: New module
  setup/stock_move_name_from_sale_line/odoo/addons/stock_move_name_from_sale_line
  setup/stock_move_name_from_sale_line/setup.py
  stock_move_name_from_sale_line/README.rst
  stock_move_name_from_sale_line/__init__.py
  stock_move_name_from_sale_line/__manifest__.py
  stock_move_name_from_sale_line/models/__init__.py
  stock_move_name_from_sale_line/models/sale_order.py
  stock_move_name_from_sale_line/models/stock_rule.py
  stock_move_name_from_sale_line/readme/CONTRIBUTORS.rst
  stock_move_name_from_sale_line/readme/DESCRIPTION.rst
  stock_move_name_from_sale_line/static/description/icon.png
  stock_move_name_from_sale_line/static/description/index.html
  stock_move_name_from_sale_line/tests/__init__.py
  stock_move_name_from_sale_line/tests/test_stock_move_name_from_sale_line.py
Labels: bot is merging ⏳

#1477 [14.0][IMP] product_supplierinfo_for_customer_picking: no compute old pickings
  product_supplierinfo_for_customer_picking/models/stock_move.py
  product_supplierinfo_for_customer_picking/tests/test_product_supplierinfo_for_customer_picking.py
Labels: approved, bot is merging ⏳

#1480 [14.0][FIX] stock_landed_costs_delivery: Filtering the correct Landed Cost
  stock_landed_costs_delivery/models/purchase_order.py
  stock_landed_costs_delivery/models/stock_picking.py
  stock_landed_costs_delivery/tests/test_purchase_order.py
Labels: approved, bot is merging ⏳

#1462 [15.0][ADD] stock_product_set: New module
  setup/stock_product_set/odoo/addons/stock_product_set
  setup/stock_product_set/setup.py
  stock_product_set/README.rst
  stock_product_set/__init__.py
  stock_product_set/__manifest__.py
  stock_product_set/i18n/es.po
  stock_product_set/i18n/stock_product_set.pot
  stock_product_set/models/__init__.py
  stock_product_set/models/product_set_line.py
  stock_product_set/readme/CONTRIBUTORS.rst
  stock_product_set/readme/DESCRIPTION.rst
  stock_product_set/readme/ROADMAP.rst
  stock_product_set/readme/USAGE.rst
  stock_product_set/security/ir.model.access.csv
  stock_product_set/static/description/icon.png
  stock_product_set/static/description/index.html
  stock_product_set/tests/__init__.py
  stock_product_set/tests/test_stock_product_set.py
  stock_product_set/views/stock_picking_views.xml
  stock_product_set/wizard/__init__.py
  stock_product_set/wizard/product_set_add_from_picking.py
  stock_product_set/wizard/product_set_add_from_picking_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1197 [16.0][ADD] stock_move_manage_priority
  setup/stock_move_manage_priority/odoo/addons/stock_move_manage_priority
  setup/stock_move_manage_priority/setup.py
  stock_move_manage_priority/README.rst
  stock_move_manage_priority/__init__.py
  stock_move_manage_priority/__manifest__.py
  stock_move_manage_priority/i18n/fr.po
  stock_move_manage_priority/i18n/stock_move_manage_priority.pot
  stock_move_manage_priority/models/__init__.py
  stock_move_manage_priority/models/res_company.py
  stock_move_manage_priority/models/res_config_settings.py
  stock_move_manage_priority/models/stock_move.py
  stock_move_manage_priority/readme/CONTRIBUTORS.rst
  stock_move_manage_priority/readme/DESCRIPTION.rst
  stock_move_manage_priority/readme/USAGE.rst
  stock_move_manage_priority/security/groups.xml
  stock_move_manage_priority/static/description/icon.png
  stock_move_manage_priority/static/description/index.html
  stock_move_manage_priority/tests/__init__.py
  stock_move_manage_priority/tests/test_manage_move_priority.py
  stock_move_manage_priority/views/res_config_settings_views.xml
  stock_move_manage_priority/views/stock_move_views.xml
  stock_move_manage_priority/views/stock_picking_views.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳, stale

#1484 [15.0][FIX] stock_landed_costs_delivery: Filtering the correct Landed Cost
  stock_landed_costs_delivery/models/purchase_order.py
  stock_landed_costs_delivery/models/stock_picking.py
  stock_landed_costs_delivery/tests/test_purchase_order.py
Labels: bot is merging ⏳

#1473 [ADD] [16.0] stock_move_line_expiration_date_required
  setup/stock_move_line_expiration_date_required/odoo/addons/stock_move_line_expiration_date_required
  setup/stock_move_line_expiration_date_required/setup.py
  stock_move_line_expiration_date_required/README.rst
  stock_move_line_expiration_date_required/__init__.py
  stock_move_line_expiration_date_required/__manifest__.py
  stock_move_line_expiration_date_required/i18n/es.po
  stock_move_line_expiration_date_required/i18n/stock_move_line_expiration_date_required.pot
  stock_move_line_expiration_date_required/models/__init__.py
  stock_move_line_expiration_date_required/models/stock_move.py
  stock_move_line_expiration_date_required/models/stock_move_line.py
  stock_move_line_expiration_date_required/models/stock_picking.py
  stock_move_line_expiration_date_required/readme/CONTRIBUTORS.rst
  stock_move_line_expiration_date_required/readme/DESCRIPTION.rst
  stock_move_line_expiration_date_required/readme/USAGE.rst
  stock_move_line_expiration_date_required/static/description/icon.png
  stock_move_line_expiration_date_required/static/description/index.html
  stock_move_line_expiration_date_required/tests/__init__.py
  stock_move_line_expiration_date_required/tests/test_expiration_date_required.py
Labels: needs review, approved, bot is merging ⏳

#1481 [16.0][ADD] stock_picking_batch_print_pickings
  setup/stock_picking_batch_print_pickings/odoo/addons/stock_picking_batch_print_pickings
  setup/stock_picking_batch_print_pickings/setup.py
  stock_picking_batch_print_pickings/README.rst
  stock_picking_batch_print_pickings/__init__.py
  stock_picking_batch_print_pickings/__manifest__.py
  stock_picking_batch_print_pickings/i18n/es.po
  stock_picking_batch_print_pickings/i18n/stock_picking_batch_print_pickings.pot
  stock_picking_batch_print_pickings/models/__init__.py
  stock_picking_batch_print_pickings/models/stock_picking_batch.py
  stock_picking_batch_print_pickings/models/stock_picking_type.py
  stock_picking_batch_print_pickings/readme/CONFIGURE.md
  stock_picking_batch_print_pickings/readme/CONTEXT.md
  stock_picking_batch_print_pickings/readme/CONTRIBUTORS.md
  stock_picking_batch_print_pickings/readme/DESCRIPTION.md
  stock_picking_batch_print_pickings/readme/USAGE.md
  stock_picking_batch_print_pickings/report/stock_picking_batch_print_pickings_report.xml
  stock_picking_batch_print_pickings/static/description/icon.png
  stock_picking_batch_print_pickings/static/description/index.html
  stock_picking_batch_print_pickings/tests/__init__.py
  stock_picking_batch_print_pickings/tests/test_batch_print_pickings.py
  stock_picking_batch_print_pickings/views/report_picking_batch_print_pickings.xml
  stock_picking_batch_print_pickings/views/stock_picking_batch_views.xml
  stock_picking_batch_print_pickings/views/stock_picking_type_views.xml
Labels: needs review, bot is merging ⏳

#1486 [16.0][FIX] stock_split_picking: pass backorder context when splitting
  stock_split_picking/models/stock_picking.py
Labels: approved, ready to merge, bot is merging ⏳

#1485 [16.0][ADD] stock_picking_batch_print_invoices
  setup/stock_picking_batch_print_invoices/odoo/addons/stock_picking_batch_print_invoices
  setup/stock_picking_batch_print_invoices/setup.py
  stock_picking_batch_print_invoices/README.rst
  stock_picking_batch_print_invoices/__init__.py
  stock_picking_batch_print_invoices/__manifest__.py
  stock_picking_batch_print_invoices/i18n/es.po
  stock_picking_batch_print_invoices/i18n/stock_picking_batch_print_invoices.pot
  stock_picking_batch_print_invoices/models/__init__.py
  stock_picking_batch_print_invoices/models/stock_picking_batch.py
  stock_picking_batch_print_invoices/models/stock_picking_type.py
  stock_picking_batch_print_invoices/readme/CONFIGURE.md
  stock_picking_batch_print_invoices/readme/CONTEXT.md
  stock_picking_batch_print_invoices/readme/CONTRIBUTORS.md
  stock_picking_batch_print_invoices/readme/DESCRIPTION.md
  stock_picking_batch_print_invoices/readme/USAGE.md
  stock_picking_batch_print_invoices/static/description/icon.png
  stock_picking_batch_print_invoices/static/description/index.html
  stock_picking_batch_print_invoices/tests/__init__.py
  stock_picking_batch_print_invoices/tests/test_batch_print_invoices.py
  stock_picking_batch_print_invoices/views/report_picking_batch_print_invoices.xml
  stock_picking_batch_print_invoices/views/stock_picking_batch_views.xml
  stock_picking_batch_print_invoices/views/stock_picking_type_views.xml
  stock_picking_batch_print_pickings/views/report_picking_batch_print_pickings.xml
  stock_picking_group_by_partner_by_carrier/report/report_delivery_slip.xml
Labels: needs review, bot is merging ⏳
