Repository OCA/stock-logistics-workflow, pull requests merged in 2024-08, with the labels that each got.

#1662 [17.0][MIG] stock_picking_show_backorder: Migration to 17.0
  stock_picking_show_backorder/README.rst
  stock_picking_show_backorder/__init__.py
  stock_picking_show_backorder/__manifest__.py
  stock_picking_show_backorder/i18n/cs_CZ.po
  stock_picking_show_backorder/i18n/de.po
  stock_picking_show_backorder/i18n/es.po
  stock_picking_show_backorder/i18n/fr.po
  stock_picking_show_backorder/i18n/hr.po
  stock_picking_show_backorder/i18n/it.po
  stock_picking_show_backorder/i18n/nl_NL.po
  stock_picking_show_backorder/i18n/pt.po
  stock_picking_show_backorder/i18n/pt_BR.po
  stock_picking_show_backorder/i18n/sl.po
  stock_picking_show_backorder/i18n/stock_picking_show_backorder.pot
  stock_picking_show_backorder/models/__init__.py
  stock_picking_show_backorder/models/stock.py
  stock_picking_show_backorder/pyproject.toml
  stock_picking_show_backorder/readme/CONTRIBUTORS.md
  stock_picking_show_backorder/readme/DESCRIPTION.md
  stock_picking_show_backorder/readme/USAGE.md
  stock_picking_show_backorder/static/description/icon.png
  stock_picking_show_backorder/static/description/index.html
  stock_picking_show_backorder/tests/__init__.py
  stock_picking_show_backorder/tests/test_stock_picking_show_backorder.py
  stock_picking_show_backorder/views/stock_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1667 [17.0][FIX] stock_picking_invoice_link: development status
  stock_picking_invoice_link/README.rst
  stock_picking_invoice_link/__manifest__.py
  stock_picking_invoice_link/static/description/index.html
Labels: approved, bot is merging ⏳

#1652 [17.0][MIG] stock_restrict_lot
  stock_restrict_lot/README.rst
  stock_restrict_lot/__init__.py
  stock_restrict_lot/__manifest__.py
  stock_restrict_lot/i18n/es.po
  stock_restrict_lot/i18n/hr.po
  stock_restrict_lot/i18n/it.po
  stock_restrict_lot/i18n/stock_restrict_lot.pot
  stock_restrict_lot/models/__init__.py
  stock_restrict_lot/models/stock_move.py
  stock_restrict_lot/models/stock_picking.py
  stock_restrict_lot/models/stock_rule.py
  stock_restrict_lot/pyproject.toml
  stock_restrict_lot/readme/CONTRIBUTORS.md
  stock_restrict_lot/readme/DESCRIPTION.md
  stock_restrict_lot/static/description/icon.png
  stock_restrict_lot/static/description/index.html
  stock_restrict_lot/tests/__init__.py
  stock_restrict_lot/tests/test_restrict_lot.py
  stock_restrict_lot/views/stock_move_views.xml
  stock_restrict_lot/views/stock_picking.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1669 [15.0][IMP] product_cost_price_avco_sync: Don't apply qty changes to landed costs
  product_cost_price_avco_sync/models/stock_move_line.py
Labels: approved, bot is merging ⏳

#1671 [14.0][IMP] stock_restrict_lot: Add index to restrict_lot_id
  stock_restrict_lot/models/stock_move.py
Labels: approved, bot is merging ⏳

#1535 [17.0][MIG] stock_picking_warn_message
  stock_picking_warn_message/README.rst
  stock_picking_warn_message/__init__.py
  stock_picking_warn_message/__manifest__.py
  stock_picking_warn_message/i18n/es.po
  stock_picking_warn_message/i18n/it.po
  stock_picking_warn_message/i18n/stock_picking_warn_message.pot
  stock_picking_warn_message/models/__init__.py
  stock_picking_warn_message/models/stock_picking.py
  stock_picking_warn_message/pyproject.toml
  stock_picking_warn_message/readme/CONFIGURE.md
  stock_picking_warn_message/readme/CONTRIBUTORS.md
  stock_picking_warn_message/readme/DESCRIPTION.md
  stock_picking_warn_message/readme/USAGE.md
  stock_picking_warn_message/static/description/icon.png
  stock_picking_warn_message/static/description/index.html
  stock_picking_warn_message/tests/__init__.py
  stock_picking_warn_message/tests/test_stock_picking_warn_message.py
  stock_picking_warn_message/views/stock_picking_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1665 [FIX]: stock_customer_deposit: default location dest when activate customer deposit
  stock_customer_deposit/models/stock_warehouse.py
  stock_customer_deposit/tests/test_stock_warehouse.py
Labels: approved, ready to merge, bot is merging ⏳

#1517 [16.0][FIX] stock_picking_auto_create_lot: fix creating lot for 0 qty move lines for serial product
  stock_picking_auto_create_lot/models/stock_picking.py
  stock_picking_auto_create_lot/tests/test_stock_picking_auto_create_lot.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1674 [FIX] stock_picking_batch_validate_confirm: wrong inheritance in tests
  stock_picking_batch_validate_confirm/tests/test_batch_confirm.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1422 [16.0][ADD] stock_picking_move_package_to_package
  setup/stock_picking_move_package_to_package/odoo/addons/stock_picking_move_package_to_package
  setup/stock_picking_move_package_to_package/setup.py
  stock_picking_move_package_to_package/README.rst
  stock_picking_move_package_to_package/__init__.py
  stock_picking_move_package_to_package/__manifest__.py
  stock_picking_move_package_to_package/models/__init__.py
  stock_picking_move_package_to_package/models/stock_package_level.py
  stock_picking_move_package_to_package/readme/CONFIGURE.md
  stock_picking_move_package_to_package/readme/CONTEXT.md
  stock_picking_move_package_to_package/readme/CONTRIBUTORS.md
  stock_picking_move_package_to_package/readme/DESCRIPTION.md
  stock_picking_move_package_to_package/readme/USAGE.md
  stock_picking_move_package_to_package/static/description/icon.png
  stock_picking_move_package_to_package/static/description/icon.svg
  stock_picking_move_package_to_package/static/description/index.html
  stock_picking_move_package_to_package/static/img/picking_destination_package.png
  stock_picking_move_package_to_package/tests/__init__.py
  stock_picking_move_package_to_package/tests/test_move_package_to_package.py
  stock_picking_move_package_to_package/views/stock_package_level_view.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1675 [16.0][FIX] stock_picking_move_package_to_package Index
  stock_picking_move_package_to_package/static/description/index.html
Labels: bot is merging ⏳

#1557 [16.0][FIX] stock_picking_line_sequence
  stock_picking_line_sequence/models/stock.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1521 [15.0][ADD] stock_picking_batch_outgoing: New module to get outgoing batch picking in origin chained pickicngs
  setup/stock_picking_batch_outgoing/odoo/addons/stock_picking_batch_outgoing
  setup/stock_picking_batch_outgoing/setup.py
  stock_picking_batch_outgoing/README.rst
  stock_picking_batch_outgoing/__init__.py
  stock_picking_batch_outgoing/__manifest__.py
  stock_picking_batch_outgoing/i18n/es.po
  stock_picking_batch_outgoing/i18n/stock_picking_batch_outgoing.pot
  stock_picking_batch_outgoing/models/__init__.py
  stock_picking_batch_outgoing/models/stock_picking.py
  stock_picking_batch_outgoing/readme/CONTRIBUTORS.rst
  stock_picking_batch_outgoing/readme/DESCRIPTION.rst
  stock_picking_batch_outgoing/static/description/icon.png
  stock_picking_batch_outgoing/static/description/index.html
  stock_picking_batch_outgoing/static/picking_outgoing_batch_list.png
  stock_picking_batch_outgoing/static/picking_pick_batch.png
  stock_picking_batch_outgoing/tests/__init__.py
  stock_picking_batch_outgoing/tests/test_stock_picking_batch_outgoing.py
  stock_picking_batch_outgoing/views/stock_picking_views.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳, stale

#1376 [15.0][IMP] stock_picking_product_assortment: use base_view_inheritance_extension module to extend product domain. Unnecessary code removed
  stock_picking_product_assortment/README.rst
  stock_picking_product_assortment/__manifest__.py
  stock_picking_product_assortment/models/__init__.py
  stock_picking_product_assortment/models/stock_move.py
  stock_picking_product_assortment/models/stock_move_line.py
  stock_picking_product_assortment/models/stock_picking.py
  stock_picking_product_assortment/readme/CONTRIBUTORS.rst
  stock_picking_product_assortment/static/description/index.html
  stock_picking_product_assortment/tests/test_stock_picking_product_assortment.py
  stock_picking_product_assortment/views/stock_picking_view.xml
  stock_picking_product_assortment_availability_inline/README.rst
  stock_picking_product_assortment_availability_inline/__manifest__.py
  stock_picking_product_assortment_availability_inline/readme/DESCRIPTION.rst
  stock_picking_product_assortment_availability_inline/static/description/index.html
  stock_picking_product_assortment_availability_inline/tests/__init__.py
  stock_picking_product_assortment_availability_inline/tests/test_stock_picking_product_assortment_availability_inline.py
  stock_picking_product_assortment_availability_inline/views/stock_picking_view.xml
Labels: approved, bot is merging ⏳

#1633 [17.0][MIG] stock_picking_origin_reference
  stock_picking_origin_reference/README.rst
  stock_picking_origin_reference/__init__.py
  stock_picking_origin_reference/__manifest__.py
  stock_picking_origin_reference/i18n/it.po
  stock_picking_origin_reference/i18n/stock_picking_origin_reference.pot
  stock_picking_origin_reference/models/__init__.py
  stock_picking_origin_reference/models/stock_picking.py
  stock_picking_origin_reference/pyproject.toml
  stock_picking_origin_reference/readme/CONFIGURE.md
  stock_picking_origin_reference/readme/CONTRIBUTORS.md
  stock_picking_origin_reference/readme/DESCRIPTION.md
  stock_picking_origin_reference/static/description/icon.png
  stock_picking_origin_reference/static/description/index.html
  stock_picking_origin_reference/tests/__init__.py
  stock_picking_origin_reference/tests/test_stock_picking_origin_reference.py
  stock_picking_origin_reference/views/stock_picking_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1687 [16.0][FIX] stock_picking_batch_extended: Printed batch report instead of picking report on "print deliveries" button
  stock_picking_batch_extended/models/stock_batch_picking.py
  stock_picking_batch_extended/tests/test_batch.py
Labels: approved, bot is merging ⏳
