Repository OCA/stock-logistics-workflow, pull requests merged in 2024-10, with the labels that each got.

#1645 [16.0] [MIG] stock_lot_on_hand_first: Migration to 16.0
  setup/stock_lot_on_hand_first/odoo/addons/stock_lot_on_hand_first
  setup/stock_lot_on_hand_first/setup.py
  stock_lot_on_hand_first/README.rst
  stock_lot_on_hand_first/__init__.py
  stock_lot_on_hand_first/__manifest__.py
  stock_lot_on_hand_first/i18n/es.po
  stock_lot_on_hand_first/i18n/it.po
  stock_lot_on_hand_first/i18n/stock_lot_on_hand_first.pot
  stock_lot_on_hand_first/models/__init__.py
  stock_lot_on_hand_first/models/stock_lot.py
  stock_lot_on_hand_first/models/stock_move.py
  stock_lot_on_hand_first/models/stock_picking.py
  stock_lot_on_hand_first/models/stock_picking_type.py
  stock_lot_on_hand_first/readme/CONFIGURE.rst
  stock_lot_on_hand_first/readme/CONTRIBUTORS.rst
  stock_lot_on_hand_first/readme/DESCRIPTION.rst
  stock_lot_on_hand_first/static/description/icon.png
  stock_lot_on_hand_first/static/description/index.html
  stock_lot_on_hand_first/tests/__init__.py
  stock_lot_on_hand_first/tests/test_lot_on_hand_first.py
  stock_lot_on_hand_first/views/stock_move.xml
  stock_lot_on_hand_first/views/stock_move_line.xml
  stock_lot_on_hand_first/views/stock_picking.xml
  stock_lot_on_hand_first/views/stock_picking_type.xml
Labels: approved, bot is merging ⏳

#1642 [16.0] [MIG] stock_picking_return_restricted_qty: Migration to 16.0
  setup/stock_picking_return_restricted_qty/odoo/addons/stock_picking_return_restricted_qty
  setup/stock_picking_return_restricted_qty/setup.py
  stock_picking_return_restricted_qty/README.rst
  stock_picking_return_restricted_qty/__init__.py
  stock_picking_return_restricted_qty/__manifest__.py
  stock_picking_return_restricted_qty/i18n/es.po
  stock_picking_return_restricted_qty/i18n/it.po
  stock_picking_return_restricted_qty/i18n/stock_picking_return_restricted_qty.pot
  stock_picking_return_restricted_qty/i18n/zh_CN.po
  stock_picking_return_restricted_qty/models/__init__.py
  stock_picking_return_restricted_qty/models/stock_picking_type.py
  stock_picking_return_restricted_qty/readme/CONFIGURE.rst
  stock_picking_return_restricted_qty/readme/CONTRIBUTORS.rst
  stock_picking_return_restricted_qty/readme/DESCRIPTION.rst
  stock_picking_return_restricted_qty/readme/USAGE.rst
  stock_picking_return_restricted_qty/static/description/icon.png
  stock_picking_return_restricted_qty/static/description/index.html
  stock_picking_return_restricted_qty/tests/__init__.py
  stock_picking_return_restricted_qty/tests/test_stock_picking_return_restricted_qty.py
  stock_picking_return_restricted_qty/views/stock_picking_type_views.xml
  stock_picking_return_restricted_qty/wizard/__init__.py
  stock_picking_return_restricted_qty/wizard/stock_picking_return.py
Labels: approved, ready to merge, bot is merging ⏳

#1468 [17.0][MIG] stock_picking_send_by_mail: Migration to 17.0
  stock_picking_send_by_mail/README.rst
  stock_picking_send_by_mail/__init__.py
  stock_picking_send_by_mail/__manifest__.py
  stock_picking_send_by_mail/i18n/de.po
  stock_picking_send_by_mail/i18n/es.po
  stock_picking_send_by_mail/i18n/fr.po
  stock_picking_send_by_mail/i18n/it.po
  stock_picking_send_by_mail/i18n/pt.po
  stock_picking_send_by_mail/i18n/pt_BR.po
  stock_picking_send_by_mail/i18n/stock_picking_send_by_mail.pot
  stock_picking_send_by_mail/models/__init__.py
  stock_picking_send_by_mail/models/stock_picking.py
  stock_picking_send_by_mail/pyproject.toml
  stock_picking_send_by_mail/readme/CONTRIBUTORS.md
  stock_picking_send_by_mail/readme/DESCRIPTION.md
  stock_picking_send_by_mail/readme/USAGE.md
  stock_picking_send_by_mail/static/description/icon.png
  stock_picking_send_by_mail/static/description/index.html
  stock_picking_send_by_mail/tests/__init__.py
  stock_picking_send_by_mail/tests/test_stock_picking_send_by_mail.py
  stock_picking_send_by_mail/views/stock_picking_view.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1736 [FIX] stock_owner_restriction : apply standard behaviour if picking_t…
  stock_owner_restriction/models/stock_move.py
Labels: approved, ready to merge, bot is merging ⏳

#1560 [16.0][IMP][stock_restrict_lot] propagation of restrict_lot changes
  stock_restrict_lot/models/stock_move.py
  stock_restrict_lot/models/stock_rule.py
  stock_restrict_lot/tests/test_restrict_lot.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1445 [ADD][12.0] product_weighable_default_weight : new module to guess weight field from products UoM, for weighable products
  product_weighable_default_weight/README.rst
  product_weighable_default_weight/__init__.py
  product_weighable_default_weight/__manifest__.py
  product_weighable_default_weight/demo/res_groups.xml
  product_weighable_default_weight/hooks.py
  product_weighable_default_weight/i18n/fr.po
  product_weighable_default_weight/models/__init__.py
  product_weighable_default_weight/models/product_product.py
  product_weighable_default_weight/models/product_template.py
  product_weighable_default_weight/readme/CONTRIBUTORS.rst
  product_weighable_default_weight/readme/DESCRIPTION.rst
  product_weighable_default_weight/tests/__init__.py
  product_weighable_default_weight/tests/test_module.py
  setup/product_weighable_default_weight/odoo/addons/product_weighable_default_weight
  setup/product_weighable_default_weight/setup.py
Labels: approved, bot is merging ⏳

#1451 [16.0][IMP] stock_picking_group_by_max_weight: Split if max weight exceed
  stock_picking_group_by_max_weight/README.rst
  stock_picking_group_by_max_weight/models/stock_move.py
  stock_picking_group_by_max_weight/models/stock_picking.py
  stock_picking_group_by_max_weight/readme/newsfragments/.gitignore
  stock_picking_group_by_max_weight/readme/newsfragments/1451.feature
  stock_picking_group_by_max_weight/static/description/index.html
  stock_picking_group_by_max_weight/tests/test_group_maxweight.py
Labels: approved, bot is merging ⏳, stale

#1744 [16.0][FIX] stock_picking_group_by_max_weight: Don't recompute all pickings
  stock_picking_group_by_max_weight/models/stock_picking.py
  stock_picking_group_by_max_weight/tests/test_group_maxweight.py
Labels: enhancement, needs review, bot is merging ⏳

#1679 [14.0][FIX]stock_picking_return_lot: handle list ValueError
  stock_picking_return_lot/wizard/stock_picking_return.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1743 [17.0][FW] [14.0][IMP] delivery_procurement_group_carrier: Set Carrier on new picking from procurement.group
  delivery_procurement_group_carrier/README.rst
  delivery_procurement_group_carrier/__manifest__.py
  delivery_procurement_group_carrier/models/__init__.py
  delivery_procurement_group_carrier/models/stock_move.py
  delivery_procurement_group_carrier/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#1648 [17.0][MIG]stock_picking_origin_reference_purchase
  stock_picking_origin_reference_purchase/README.rst
  stock_picking_origin_reference_purchase/__init__.py
  stock_picking_origin_reference_purchase/__manifest__.py
  stock_picking_origin_reference_purchase/i18n/it.po
  stock_picking_origin_reference_purchase/i18n/stock_picking_origin_reference_purchase.pot
  stock_picking_origin_reference_purchase/models/__init__.py
  stock_picking_origin_reference_purchase/models/stock_picking.py
  stock_picking_origin_reference_purchase/pyproject.toml
  stock_picking_origin_reference_purchase/readme/CONTRIBUTORS.md
  stock_picking_origin_reference_purchase/readme/DESCRIPTION.md
  stock_picking_origin_reference_purchase/static/description/icon.png
  stock_picking_origin_reference_purchase/static/description/index.html
  stock_picking_origin_reference_purchase/tests/__init__.py
  stock_picking_origin_reference_purchase/tests/test_stock_picking_origin_reference_purchase.py
Labels: needs review, approved, migration, bot is merging ⏳

#1647 [17.0][MIG]stock_picking_origin_reference_sale
  stock_picking_origin_reference_sale/README.rst
  stock_picking_origin_reference_sale/__init__.py
  stock_picking_origin_reference_sale/__manifest__.py
  stock_picking_origin_reference_sale/i18n/it.po
  stock_picking_origin_reference_sale/i18n/stock_picking_origin_reference_sale.pot
  stock_picking_origin_reference_sale/models/__init__.py
  stock_picking_origin_reference_sale/models/stock_picking.py
  stock_picking_origin_reference_sale/pyproject.toml
  stock_picking_origin_reference_sale/readme/CONTRIBUTORS.md
  stock_picking_origin_reference_sale/readme/DESCRIPTION.md
  stock_picking_origin_reference_sale/static/description/icon.png
  stock_picking_origin_reference_sale/static/description/index.html
  stock_picking_origin_reference_sale/tests/__init__.py
  stock_picking_origin_reference_sale/tests/test_stock_picking_origin_reference_sale.py
Labels: approved, bot is merging ⏳

#1745 [17.0][MIG] stock_picking_return_lot: Migration to 17.0
  stock_picking_return_lot/README.rst
  stock_picking_return_lot/__init__.py
  stock_picking_return_lot/__manifest__.py
  stock_picking_return_lot/i18n/it.po
  stock_picking_return_lot/i18n/stock_picking_return_lot.pot
  stock_picking_return_lot/pyproject.toml
  stock_picking_return_lot/readme/CONTRIBUTORS.md
  stock_picking_return_lot/readme/DESCRIPTION.md
  stock_picking_return_lot/static/description/icon.png
  stock_picking_return_lot/static/description/index.html
  stock_picking_return_lot/tests/__init__.py
  stock_picking_return_lot/tests/test_stock_picking_return_lot.py
  stock_picking_return_lot/wizards/__init__.py
  stock_picking_return_lot/wizards/stock_return_picking.py
  stock_picking_return_lot/wizards/stock_return_picking.xml
  stock_picking_return_lot/wizards/stock_return_picking_line.py
Labels: needs review, approved, migration, bot is merging ⏳

#1470 [16.0][ADD] Lock Done Quantity Changes in Stock Moves
  setup/stock_move_line_lock_qty_done/odoo/addons/stock_move_line_lock_qty_done
  setup/stock_move_line_lock_qty_done/setup.py
  stock_move_line_lock_qty_done/README.rst
  stock_move_line_lock_qty_done/__init__.py
  stock_move_line_lock_qty_done/__manifest__.py
  stock_move_line_lock_qty_done/models/__init__.py
  stock_move_line_lock_qty_done/models/stock_move_line.py
  stock_move_line_lock_qty_done/readme/CONFIGURE.rst
  stock_move_line_lock_qty_done/readme/CONTRIBUTORS.rst
  stock_move_line_lock_qty_done/readme/DESCRIPTION.rst
  stock_move_line_lock_qty_done/security/res_groups.xml
  stock_move_line_lock_qty_done/static/description/index.html
  stock_move_line_lock_qty_done/tests/__init__.py
  stock_move_line_lock_qty_done/tests/test_stock_move_line_lock_qty_done.py
Labels: needs review, approved, bot is merging ⏳

#1707 [FIX] stock_move_manage_priorty: Don't use selection_badge in tree views
  stock_move_manage_priority/views/stock_move_views.xml
  stock_move_manage_priority/views/stock_picking_views.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1749 [FIX] [16.0] stock_customer_deposit_sale_margin: Fix case when deposit is equal to product_uom_qty
  stock_customer_deposit_sale_margin/README.rst
  stock_customer_deposit_sale_margin/models/sale_order_line.py
  stock_customer_deposit_sale_margin/readme/CONTRIBUTORS.md
  stock_customer_deposit_sale_margin/static/description/index.html
  stock_customer_deposit_sale_margin/tests/test_stock_customer_deposit_sale_margin.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1750 [FIX] [16.0] stock_customer_deposit: Create valuation layers when performing a deposit
  stock_customer_deposit/models/stock_move.py
  stock_customer_deposit/tests/test_deliver_customer_deposit.py
  stock_customer_deposit/tests/test_sale_customer_deposit.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1705 [17.0][MIG] stock_picking_supplier_ref: Migration to 17.0
  stock_picking_supplier_ref/README.rst
  stock_picking_supplier_ref/__init__.py
  stock_picking_supplier_ref/__manifest__.py
  stock_picking_supplier_ref/i18n/es.po
  stock_picking_supplier_ref/i18n/it.po
  stock_picking_supplier_ref/i18n/stock_picking_supplier_ref.pot
  stock_picking_supplier_ref/models/__init__.py
  stock_picking_supplier_ref/models/stock_picking.py
  stock_picking_supplier_ref/pyproject.toml
  stock_picking_supplier_ref/readme/CONTRIBUTORS.md
  stock_picking_supplier_ref/readme/DESCRIPTION.md
  stock_picking_supplier_ref/readme/HISTORY.md
  stock_picking_supplier_ref/readme/USAGE.md
  stock_picking_supplier_ref/static/description/icon.png
  stock_picking_supplier_ref/static/description/index.html
  stock_picking_supplier_ref/views/stock_picking.xml
Labels: approved, migration, ready to merge, bot is merging ⏳

#1232 [16.0][MIG] stock_picking_operation_quick_change
  setup/stock_picking_operation_quick_change/odoo/addons/stock_picking_operation_quick_change
  setup/stock_picking_operation_quick_change/setup.py
  stock_picking_operation_quick_change/README.rst
  stock_picking_operation_quick_change/__init__.py
  stock_picking_operation_quick_change/__manifest__.py
  stock_picking_operation_quick_change/i18n/de.po
  stock_picking_operation_quick_change/i18n/es.po
  stock_picking_operation_quick_change/i18n/fr.po
  stock_picking_operation_quick_change/i18n/it.po
  stock_picking_operation_quick_change/i18n/pt_BR.po
  stock_picking_operation_quick_change/i18n/sl.po
  stock_picking_operation_quick_change/i18n/stock_picking_operation_quick_change.pot
  stock_picking_operation_quick_change/readme/CONTRIBUTORS.rst
  stock_picking_operation_quick_change/readme/DESCRIPTION.rst
  stock_picking_operation_quick_change/readme/USAGE.rst
  stock_picking_operation_quick_change/security/ir.model.access.csv
  stock_picking_operation_quick_change/static/description/icon.png
  stock_picking_operation_quick_change/static/description/icon.svg
  stock_picking_operation_quick_change/static/description/index.html
  stock_picking_operation_quick_change/tests/__init__.py
  stock_picking_operation_quick_change/tests/test_stock_picking_operation_quick_change.py
  stock_picking_operation_quick_change/views/stock_picking_view.xml
  stock_picking_operation_quick_change/wizards/__init__.py
  stock_picking_operation_quick_change/wizards/stock_picking_wizard.py
  stock_picking_operation_quick_change/wizards/stock_picking_wizard_view.xml
Labels: needs review, approved, migration, bot is merging ⏳
