Repository OCA/stock-logistics-workflow, pull requests merged in 2024-02, with the labels that each got.

#1489 [15.0][IMP] stock_picking_import_serial_number: Add package compatibility
  stock_picking_import_serial_number/README.rst
  stock_picking_import_serial_number/i18n/es.po
  stock_picking_import_serial_number/i18n/stock_picking_import_serial_number.pot
  stock_picking_import_serial_number/models/res_config_settings.py
  stock_picking_import_serial_number/readme/CONTRIBUTORS.rst
  stock_picking_import_serial_number/static/description/index.html
  stock_picking_import_serial_number/tests/common.py
  stock_picking_import_serial_number/tests/data/SNImport-1.xls
  stock_picking_import_serial_number/tests/data/SNImport-2.xls
  stock_picking_import_serial_number/tests/test_stock_picking_import_serial_number.py
  stock_picking_import_serial_number/views/res_config_settings_views.xml
  stock_picking_import_serial_number/wizard/import_serial_number_wizard.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1363 [15.0][MIG] stock_receipt_lot_info
  setup/stock_receipt_lot_info/odoo/addons/stock_receipt_lot_info
  setup/stock_receipt_lot_info/setup.py
  stock_receipt_lot_info/README.rst
  stock_receipt_lot_info/__init__.py
  stock_receipt_lot_info/__manifest__.py
  stock_receipt_lot_info/i18n/stock_account_product_run_fifo_hook.pot
  stock_receipt_lot_info/migrations/15.0.1.0.0/pre-migration.py
  stock_receipt_lot_info/migrations/15.0.1.1.0/pre-migration.py
  stock_receipt_lot_info/model/__init__.py
  stock_receipt_lot_info/model/stock_move_line.py
  stock_receipt_lot_info/readme/CONTRIBUTORS.rst
  stock_receipt_lot_info/readme/DESCRIPTION.rst
  stock_receipt_lot_info/readme/USAGE.rst
  stock_receipt_lot_info/static/description/icon.png
  stock_receipt_lot_info/static/description/index.html
  stock_receipt_lot_info/tests/__init__.py
  stock_receipt_lot_info/tests/test_receipt_lot_info.py
  stock_receipt_lot_info/views/stock_move_line_views.xml
Labels: needs review, approved, migration, bot is merging ⏳, no stale

#1492 [16.0][FIX] stock_receipt_lot_info: hook merged into odoo
  stock_receipt_lot_info/README.rst
  stock_receipt_lot_info/__manifest__.py
  stock_receipt_lot_info/migrations/16.0.1.1.0/pre-migration.py
  stock_receipt_lot_info/model/stock_move_line.py
  stock_receipt_lot_info/readme/DESCRIPTION.rst
  stock_receipt_lot_info/static/description/index.html
  stock_receipt_lot_info/tests/test_receipt_lot_info.py
  stock_receipt_lot_info/views/stock_move_line_views.xml
Labels: bot is merging ⏳

#1476 [FIX] simplify the name of merged procurment groups
  stock_picking_group_by_partner_by_carrier/models/stock_picking.py
  stock_picking_group_by_partner_by_carrier/tests/test_grouping.py
Labels: approved, bot is merging ⏳

#1501 [FIX] [16.0] stock_move_line_expiration_date_required: Remove required from field definition
  stock_move_line_expiration_date_required/README.rst
  stock_move_line_expiration_date_required/__manifest__.py
  stock_move_line_expiration_date_required/i18n/es.po
  stock_move_line_expiration_date_required/i18n/stock_move_line_expiration_date_required.pot
  stock_move_line_expiration_date_required/migrations/16.0.1.0.2/post-migration.py
  stock_move_line_expiration_date_required/models/stock_move.py
  stock_move_line_expiration_date_required/models/stock_move_line.py
  stock_move_line_expiration_date_required/static/description/index.html
  stock_move_line_expiration_date_required/views/stock_move_line_view.xml
  stock_move_line_expiration_date_required/views/stock_move_view.xml
Labels: needs review, approved, bot is merging ⏳

#1497 [16.0][ADD] stock_picking_to_batch_group_fields
  .copier-answers.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  setup/stock_picking_to_batch_group_fields/odoo/addons/stock_picking_to_batch_group_fields
  setup/stock_picking_to_batch_group_fields/setup.py
  stock_picking_to_batch_group_fields/README.rst
  stock_picking_to_batch_group_fields/__init__.py
  stock_picking_to_batch_group_fields/__manifest__.py
  stock_picking_to_batch_group_fields/i18n/es.po
  stock_picking_to_batch_group_fields/i18n/stock_picking_batch_group_field.pot
  stock_picking_to_batch_group_fields/readme/CONFIGURE.md
  stock_picking_to_batch_group_fields/readme/CONTEXT.md
  stock_picking_to_batch_group_fields/readme/CONTRIBUTORS.md
  stock_picking_to_batch_group_fields/readme/DESCRIPTION.md
  stock_picking_to_batch_group_fields/readme/USAGE.md
  stock_picking_to_batch_group_fields/security/ir.model.access.csv
  stock_picking_to_batch_group_fields/static/description/icon.png
  stock_picking_to_batch_group_fields/static/description/index.html
  stock_picking_to_batch_group_fields/tests/__init__.py
  stock_picking_to_batch_group_fields/tests/test_batch_group_field.py
  stock_picking_to_batch_group_fields/wizard/__init__.py
  stock_picking_to_batch_group_fields/wizard/stock_picking_to_batch.py
  stock_picking_to_batch_group_fields/wizard/stock_picking_to_batch_views.xml
Labels: needs review, approved, bot is merging ⏳

#1496 [16.0][ADD] stock_picking_partner_note
  setup/stock_picking_partner_note/odoo/addons/stock_picking_partner_note
  setup/stock_picking_partner_note/setup.py
  stock_picking_partner_note/README.rst
  stock_picking_partner_note/__init__.py
  stock_picking_partner_note/__manifest__.py
  stock_picking_partner_note/i18n/fr.po
  stock_picking_partner_note/i18n/stock_picking_partner_note.pot
  stock_picking_partner_note/models/__init__.py
  stock_picking_partner_note/models/res_partner.py
  stock_picking_partner_note/models/stock_picking.py
  stock_picking_partner_note/models/stock_picking_note.py
  stock_picking_partner_note/models/stock_picking_note_type.py
  stock_picking_partner_note/models/stock_picking_type.py
  stock_picking_partner_note/readme/CONFIGURE.rst
  stock_picking_partner_note/readme/CONTRIBUTORS.rst
  stock_picking_partner_note/readme/DESCRIPTION.rst
  stock_picking_partner_note/security/ir.model.access.csv
  stock_picking_partner_note/static/description/index.html
  stock_picking_partner_note/tests/__init__.py
  stock_picking_partner_note/tests/test_stock_picking_partner_note.py
  stock_picking_partner_note/views/res_partner.xml
  stock_picking_partner_note/views/stock_picking_note.xml
  stock_picking_partner_note/views/stock_picking_note_type.xml
  stock_picking_partner_note/views/stock_picking_partner_note_menus.xml
  stock_picking_partner_note/views/stock_picking_type.xml
Labels: approved, ready to merge, bot is merging ⏳

#1505 [15.0][IMP] stock_picking_batch_extended: Open wave after creation
  stock_picking_batch_extended/models/__init__.py
  stock_picking_batch_extended/models/stock_move_line.py
  stock_picking_batch_extended/wizard/stock_picking_to_batch.py
Labels: approved, merged 🎉

#1352 [13.0][ADD] product_cost_price_avco_sync_mrp: New module to process result svls from a production
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  product_cost_price_avco_sync_mrp/README.rst
  product_cost_price_avco_sync_mrp/__init__.py
  product_cost_price_avco_sync_mrp/__manifest__.py
  product_cost_price_avco_sync_mrp/i18n/es.po
  product_cost_price_avco_sync_mrp/i18n/product_cost_price_avco_sync_mrp.pot
  product_cost_price_avco_sync_mrp/models/__init__.py
  product_cost_price_avco_sync_mrp/models/stock_valuation_layer.py
  product_cost_price_avco_sync_mrp/readme/CONTRIBUTORS.rst
  product_cost_price_avco_sync_mrp/readme/DESCRIPTION.rst
  product_cost_price_avco_sync_mrp/static/description/index.html
  product_cost_price_avco_sync_mrp/tests/__init__.py
  product_cost_price_avco_sync_mrp/tests/test_product_cost_price_avco_sync_mrp.py
  product_cost_price_avco_sync_mrp_subcontracting/README.rst
  product_cost_price_avco_sync_mrp_subcontracting/__init__.py
  product_cost_price_avco_sync_mrp_subcontracting/__manifest__.py
  product_cost_price_avco_sync_mrp_subcontracting/hooks.py
  product_cost_price_avco_sync_mrp_subcontracting/i18n/es.po
  product_cost_price_avco_sync_mrp_subcontracting/i18n/product_cost_price_avco_sync_mrp_subcontracting.pot
  product_cost_price_avco_sync_mrp_subcontracting/models/__init__.py
  product_cost_price_avco_sync_mrp_subcontracting/models/stock_move.py
  product_cost_price_avco_sync_mrp_subcontracting/models/stock_valuation_layer.py
  product_cost_price_avco_sync_mrp_subcontracting/readme/CONTRIBUTORS.rst
  product_cost_price_avco_sync_mrp_subcontracting/readme/DESCRIPTION.rst
  product_cost_price_avco_sync_mrp_subcontracting/static/description/index.html
  setup/product_cost_price_avco_sync_mrp/odoo/addons/product_cost_price_avco_sync_mrp
  setup/product_cost_price_avco_sync_mrp/setup.py
  setup/product_cost_price_avco_sync_mrp_subcontracting/odoo/addons/product_cost_price_avco_sync_mrp_subcontracting
  setup/product_cost_price_avco_sync_mrp_subcontracting/setup.py
Labels: bot is merging ⏳, stale

#1506 [16.0][FIX] stock_picking_batch_print_invoices: Print all invoices from pickings
  stock_picking_batch_print_invoices/views/report_picking_batch_print_invoices.xml
Labels: needs review, approved, bot is merging ⏳

#1285 [16.0][FIX] stock_grn: bad widget for grn_id
  stock_grn/views/stock_move_views.xml
Labels: enhancement, needs review, bot is merging ⏳, stale

#1515 [15.0][IMP] stock_picking_batch_extended: Display operations and detailed operations from batch picking with smart buttons
  stock_picking_batch_extended/README.rst
  stock_picking_batch_extended/__manifest__.py
  stock_picking_batch_extended/models/stock_batch_picking.py
  stock_picking_batch_extended/static/description/index.html
  stock_picking_batch_extended/views/stock_batch_picking.xml
  stock_picking_batch_extended/views/stock_move_views.xml
Labels: approved, bot is merging ⏳

#1516 [15.0][IMP] stock_picking_batch_set_quantity: Better invisible domain and biggest icon
  stock_picking_batch_set_quantity/views/stock_picking_batch_views.xml
Labels: approved, bot is merging ⏳

#1390 [FIX] stock_picking_start: fix user_id vals in _prepare_start_values
  stock_picking_start/models/stock_picking.py
Labels: needs review, approved, bot is merging ⏳

#1490 [16.0][IMP] stock_picking_mass_action: Added the possibility to indicate to the method if we want other types of operation.
  stock_picking_mass_action/README.rst
  stock_picking_mass_action/models/stock_picking.py
  stock_picking_mass_action/readme/CONFIGURE.rst
  stock_picking_mass_action/static/description/index.html
  stock_picking_mass_action/tests/test_mass_action.py
Labels: approved, ready to merge, bot is merging ⏳

#1518 [16.0][MIG] stock_picking_import_serial_number: Migration to 16.0
  requirements.txt
  setup/stock_picking_import_serial_number/odoo/addons/stock_picking_import_serial_number
  setup/stock_picking_import_serial_number/setup.py
  stock_picking_import_serial_number/README.rst
  stock_picking_import_serial_number/__init__.py
  stock_picking_import_serial_number/__manifest__.py
  stock_picking_import_serial_number/i18n/es.po
  stock_picking_import_serial_number/i18n/it.po
  stock_picking_import_serial_number/i18n/stock_picking_import_serial_number.pot
  stock_picking_import_serial_number/models/__init__.py
  stock_picking_import_serial_number/models/res_config_settings.py
  stock_picking_import_serial_number/readme/CONFIGURE.rst
  stock_picking_import_serial_number/readme/CONTRIBUTORS.rst
  stock_picking_import_serial_number/readme/DESCRIPTION.rst
  stock_picking_import_serial_number/readme/USAGE.rst
  stock_picking_import_serial_number/security/ir.model.access.csv
  stock_picking_import_serial_number/static/description/icon.png
  stock_picking_import_serial_number/static/description/index.html
  stock_picking_import_serial_number/tests/__init__.py
  stock_picking_import_serial_number/tests/common.py
  stock_picking_import_serial_number/tests/data/SNImport-1.xls
  stock_picking_import_serial_number/tests/data/SNImport-2.xls
  stock_picking_import_serial_number/tests/test_stock_picking_import_serial_number.py
  stock_picking_import_serial_number/views/res_config_settings_views.xml
  stock_picking_import_serial_number/views/stock_picking.xml
  stock_picking_import_serial_number/wizard/__init__.py
  stock_picking_import_serial_number/wizard/import_serial_number_view.xml
  stock_picking_import_serial_number/wizard/import_serial_number_wizard.py
Labels: needs review, approved, migration, merged 🎉

#1449 [17.0] [MIG] stock_split_picking: Migration to 17.0
  stock_split_picking/README.rst
  stock_split_picking/__init__.py
  stock_split_picking/__manifest__.py
  stock_split_picking/i18n/ar.po
  stock_split_picking/i18n/ca_ES.po
  stock_split_picking/i18n/de.po
  stock_split_picking/i18n/es.po
  stock_split_picking/i18n/es_MX.po
  stock_split_picking/i18n/fi.po
  stock_split_picking/i18n/fr.po
  stock_split_picking/i18n/hr.po
  stock_split_picking/i18n/it.po
  stock_split_picking/i18n/nl_NL.po
  stock_split_picking/i18n/pt.po
  stock_split_picking/i18n/pt_BR.po
  stock_split_picking/i18n/sl.po
  stock_split_picking/i18n/stock_split_picking.pot
  stock_split_picking/i18n/tr.po
  stock_split_picking/i18n/tr_TR.po
  stock_split_picking/i18n/zh_CN.po
  stock_split_picking/models/__init__.py
  stock_split_picking/models/stock_picking.py
  stock_split_picking/pyproject.toml
  stock_split_picking/readme/CONTRIBUTORS.md
  stock_split_picking/readme/DESCRIPTION.md
  stock_split_picking/readme/USAGE.md
  stock_split_picking/security/ir.model.access.csv
  stock_split_picking/static/description/icon.png
  stock_split_picking/static/description/index.html
  stock_split_picking/tests/__init__.py
  stock_split_picking/tests/test_stock_split_picking.py
  stock_split_picking/views/stock_partial_picking.xml
  stock_split_picking/wizards/__init__.py
  stock_split_picking/wizards/stock_split_picking.py
  stock_split_picking/wizards/stock_split_picking.xml
Labels: approved, bot is merging ⏳
