Repository OCA/stock-logistics-workflow, pull requests merged in 2024-09, with the labels that each got.

#1690 [14.0][IMP] stock_no_negative: add option to skip negative qty check
  stock_no_negative/models/stock_quant.py
Labels: approved, bot is merging ⏳

#1677 [16.0][MIG] stock_picking_return_lot
  setup/stock_picking_return_lot/odoo/addons/stock_picking_return_lot
  setup/stock_picking_return_lot/setup.py
  stock_picking_return_lot/README.rst
  stock_picking_return_lot/__init__.py
  stock_picking_return_lot/__manifest__.py
  stock_picking_return_lot/i18n/stock_picking_return_lot.pot
  stock_picking_return_lot/readme/CONTRIBUTORS.rst
  stock_picking_return_lot/readme/DESCRIPTION.rst
  stock_picking_return_lot/static/description/icon.png
  stock_picking_return_lot/static/description/index.html
  stock_picking_return_lot/tests/__init__.py
  stock_picking_return_lot/tests/test_stock_picking_return_lot.py
  stock_picking_return_lot/wizards/__init__.py
  stock_picking_return_lot/wizards/stock_return_picking.py
  stock_picking_return_lot/wizards/stock_return_picking.xml
  stock_picking_return_lot/wizards/stock_return_picking_line.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1593 [17.0][MIG] stock_picking_back2draft: Migration to 17.0
  stock_picking_back2draft/README.rst
  stock_picking_back2draft/__init__.py
  stock_picking_back2draft/__manifest__.py
  stock_picking_back2draft/i18n/ca.po
  stock_picking_back2draft/i18n/de.po
  stock_picking_back2draft/i18n/es.po
  stock_picking_back2draft/i18n/es_AR.po
  stock_picking_back2draft/i18n/es_MX.po
  stock_picking_back2draft/i18n/fi.po
  stock_picking_back2draft/i18n/fr.po
  stock_picking_back2draft/i18n/hr.po
  stock_picking_back2draft/i18n/it.po
  stock_picking_back2draft/i18n/pt.po
  stock_picking_back2draft/i18n/pt_BR.po
  stock_picking_back2draft/i18n/sl.po
  stock_picking_back2draft/i18n/stock_picking_back2draft.pot
  stock_picking_back2draft/i18n/tr.po
  stock_picking_back2draft/i18n/tr_TR.po
  stock_picking_back2draft/i18n/zh_CN.po
  stock_picking_back2draft/models/__init__.py
  stock_picking_back2draft/models/stock_move.py
  stock_picking_back2draft/models/stock_picking.py
  stock_picking_back2draft/pyproject.toml
  stock_picking_back2draft/readme/CONTRIBUTORS.md
  stock_picking_back2draft/readme/DESCRIPTION.md
  stock_picking_back2draft/readme/USAGE.md
  stock_picking_back2draft/static/description/icon.png
  stock_picking_back2draft/static/description/index.html
  stock_picking_back2draft/tests/__init__.py
  stock_picking_back2draft/tests/test_picking.py
  stock_picking_back2draft/views/picking_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1696 [14.0][FIX] sale_stock_mto_as_mts_orderpoint: fix orderpoint creation
  sale_stock_mto_as_mts_orderpoint/models/sale_order.py
Labels: bot is merging ⏳

#1655 [14.0][MIG] stock_picking_customer_ref: Backport from 16.0 to 14.0
  setup/stock_picking_customer_ref/odoo/addons/stock_picking_customer_ref
  setup/stock_picking_customer_ref/setup.py
  stock_picking_customer_ref/README.rst
  stock_picking_customer_ref/__init__.py
  stock_picking_customer_ref/__manifest__.py
  stock_picking_customer_ref/i18n/de.po
  stock_picking_customer_ref/i18n/es.po
  stock_picking_customer_ref/i18n/fr.po
  stock_picking_customer_ref/i18n/hr.po
  stock_picking_customer_ref/i18n/it.po
  stock_picking_customer_ref/i18n/nl.po
  stock_picking_customer_ref/i18n/pt.po
  stock_picking_customer_ref/i18n/pt_BR.po
  stock_picking_customer_ref/i18n/sl_SI.po
  stock_picking_customer_ref/i18n/stock_picking_customer_ref.pot
  stock_picking_customer_ref/models/__init__.py
  stock_picking_customer_ref/models/stock_picking.py
  stock_picking_customer_ref/readme/CONTRIBUTORS.rst
  stock_picking_customer_ref/readme/CREDITS.rst
  stock_picking_customer_ref/readme/DESCRIPTION.rst
  stock_picking_customer_ref/readme/USAGE.rst
  stock_picking_customer_ref/static/description/icon.png
  stock_picking_customer_ref/static/description/index.html
  stock_picking_customer_ref/tests/__init__.py
  stock_picking_customer_ref/tests/test_stock_picking_customer_ref.py
  stock_picking_customer_ref/views/stock_picking_view.xml
Labels: approved, bot is merging ⏳

#1670 [14.0][FIX] sale-stock_mto_as_mts_orderpoint
  sale_stock_mto_as_mts_orderpoint/models/sale_order.py
  sale_stock_mto_as_mts_orderpoint/readme/DESCRIPTION.rst
Labels: approved, bot is merging ⏳

#1699 [14.0][FIX] sale_stock_mto_as_mts_orderpoint: fix orderpoint activation condition
  sale_stock_mto_as_mts_orderpoint/models/sale_order.py
Labels: approved, bot is merging ⏳

#1666 [IMP] stock_grn: grn type & menu
  stock_grn/__manifest__.py
  stock_grn/models/stock_grn.py
  stock_grn/models/stock_grn_type.py
  stock_grn/views/stock_grn_type_views.xml
  stock_grn/views/stock_grn_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1692 [17.0][MIG]stock_picking_kind: Migration to 17.0
  stock_picking_kind/README.rst
  stock_picking_kind/__init__.py
  stock_picking_kind/__manifest__.py
  stock_picking_kind/hooks.py
  stock_picking_kind/i18n/es.po
  stock_picking_kind/i18n/fr.po
  stock_picking_kind/i18n/it.po
  stock_picking_kind/i18n/stock_picking_kind.pot
  stock_picking_kind/models/__init__.py
  stock_picking_kind/models/stock_picking.py
  stock_picking_kind/pyproject.toml
  stock_picking_kind/readme/CONTRIBUTORS.md
  stock_picking_kind/readme/DESCRIPTION.md
  stock_picking_kind/static/description/icon.png
  stock_picking_kind/static/description/index.html
  stock_picking_kind/tests/__init__.py
  stock_picking_kind/tests/test_stock_picking_kind.py
  stock_picking_kind/views/stock_picking_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1702 [14.0][IMP] stock_picking_auto_create_package: Without packaging assume qty of 1
  stock_picking_auto_create_package/models/stock_picking.py
  stock_picking_auto_create_package/tests/test_automatic_package.py
Labels: approved, ready to merge, bot is merging ⏳

#1712 [17.0][IMP] stock_picking_invoice_link: Fix argument in reverse_moves
  stock_picking_invoice_link/tests/test_stock_picking_invoice_link.py
  stock_picking_invoice_link/wizards/account_move_reversal.py
Labels: approved, bot is merging ⏳

#1608 [17.0][ADD] Add Stock Account Show Automatic Valuation Module
  stock_account_show_automatic_valuation/README.rst
  stock_account_show_automatic_valuation/__init__.py
  stock_account_show_automatic_valuation/__manifest__.py
  stock_account_show_automatic_valuation/pyproject.toml
  stock_account_show_automatic_valuation/readme/CONTRIBUTORS.md
  stock_account_show_automatic_valuation/readme/DESCRIPTION.md
  stock_account_show_automatic_valuation/readme/USAGE.md
  stock_account_show_automatic_valuation/static/description/icon.png
  stock_account_show_automatic_valuation/static/description/index.html
  stock_account_show_automatic_valuation/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#1713 [15.0][IMP] stock_picking_batch_outgoing: Allow search pickings by outgoing batch picking
  stock_picking_batch_outgoing/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳

#1714 [16.0][FW] stock_restrict_lot: Multiple ports from 14.0
  .oca/oca-port/blacklist/stock_restrict_lot.json
  stock_restrict_lot/README.rst
  stock_restrict_lot/models/__init__.py
  stock_restrict_lot/models/product_product.py
  stock_restrict_lot/models/stock_move.py
  stock_restrict_lot/readme/CONTRIBUTORS.rst
  stock_restrict_lot/static/description/index.html
  stock_restrict_lot/tests/test_restrict_lot.py
Labels: approved, migration, bot is merging ⏳

#1715 [17.0][FW] stock_restrict_lot: Multiple ports from 16.0
  stock_restrict_lot/models/__init__.py
  stock_restrict_lot/models/product_product.py
  stock_restrict_lot/models/stock_move.py
  stock_restrict_lot/static/description/index.html
  stock_restrict_lot/tests/test_restrict_lot.py
Labels: needs review, approved, migration, bot is merging ⏳

#1719 [15.0][IMP] stock_picking_batch_outgoing: Allow group pickings by outgoing batch picking
  stock_picking_batch_outgoing/i18n/es.po
  stock_picking_batch_outgoing/i18n/stock_picking_batch_outgoing.pot
  stock_picking_batch_outgoing/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳

#1720 [14.0][FIX] stock_picking_auto_create_package: Zero check on selecting product packaging
  stock_picking_auto_create_package/models/stock_picking.py
  stock_picking_auto_create_package/tests/test_automatic_package.py
Labels: bot is merging ⏳

#1716 [17.0][MIG] stock_account_product_run_fifo_hook
  stock_account_product_run_fifo_hook/README.rst
  stock_account_product_run_fifo_hook/__init__.py
  stock_account_product_run_fifo_hook/__manifest__.py
  stock_account_product_run_fifo_hook/hooks.py
  stock_account_product_run_fifo_hook/i18n/es.po
  stock_account_product_run_fifo_hook/i18n/it.po
  stock_account_product_run_fifo_hook/i18n/stock_account_product_run_fifo_hook.pot
  stock_account_product_run_fifo_hook/model/__init__.py
  stock_account_product_run_fifo_hook/model/product.py
  stock_account_product_run_fifo_hook/pyproject.toml
  stock_account_product_run_fifo_hook/readme/CONTRIBUTORS.md
  stock_account_product_run_fifo_hook/readme/DESCRIPTION.md
  stock_account_product_run_fifo_hook/readme/USAGE.md
  stock_account_product_run_fifo_hook/static/description/icon.png
  stock_account_product_run_fifo_hook/static/description/index.html
Labels: approved, bot is merging ⏳

#1328 [FIX] stock_picking_group_by_base: Avoid module load error due to DB lock timeout
  stock_picking_group_by_base/models/stock_picking.py
Labels: enhancement, needs review, needs fixing, approved, bot is merging ⏳, stale

#1728 [15.0][FIX] stock_owner_restriction: Wrong qty available computation for owner and product at the same time
  stock_owner_restriction/README.rst
  stock_owner_restriction/models/product.py
  stock_owner_restriction/readme/CONFIGURE.rst
  stock_owner_restriction/static/description/index.html
  stock_owner_restriction/tests/test_stock_owner_restriction.py
Labels: approved, bot is merging ⏳

#1320 [16.0][MIG] product_expiry_simple
  .copier-answers.yml
  .github/workflows/test.yml
  product_expiry_simple/README.rst
  product_expiry_simple/__init__.py
  product_expiry_simple/__manifest__.py
  product_expiry_simple/data/product_removal.xml
  product_expiry_simple/i18n/de.po
  product_expiry_simple/i18n/es.po
  product_expiry_simple/i18n/fr.po
  product_expiry_simple/i18n/it.po
  product_expiry_simple/i18n/nl_NL.po
  product_expiry_simple/i18n/product_expiry_simple.pot
  product_expiry_simple/i18n/sl.po
  product_expiry_simple/models/__init__.py
  product_expiry_simple/models/product_template.py
  product_expiry_simple/models/stock_lot.py
  product_expiry_simple/models/stock_move_line.py
  product_expiry_simple/models/stock_picking.py
  product_expiry_simple/models/stock_quant.py
  product_expiry_simple/readme/CONTRIBUTORS.rst
  product_expiry_simple/readme/DESCRIPTION.rst
  product_expiry_simple/static/description/icon.png
  product_expiry_simple/static/description/index.html
  product_expiry_simple/views/product_template.xml
  product_expiry_simple/views/stock_lot.xml
  product_expiry_simple/views/stock_move_line.xml
  product_expiry_simple/views/stock_picking.xml
  product_expiry_simple/views/stock_quant.xml
  setup/product_expiry_simple/odoo/addons/product_expiry_simple
  setup/product_expiry_simple/setup.py
Labels: help wanted, needs fixing, approved, migration, ready to merge, bot is merging ⏳

#1722 [16.0][FIX] stock_account_product_run_fifo_hook: update monkey patches
  stock_account_product_run_fifo_hook/hooks.py
  stock_account_product_run_fifo_hook/model/product.py
Labels: approved, ready to merge, bot is merging ⏳

#1730 [IMP] sale_global_stock_route: prevent to update route_id on confirme…
  sale_order_global_stock_route/views/sale_order_views.xml
Labels: approved, bot is merging ⏳

#1721 [FIX] stock_picking_return_lot: group return line by move and lot
  stock_picking_return_lot/tests/test_stock_picking_return_lot.py
  stock_picking_return_lot/wizards/stock_return_picking.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1727 [14.0][ADD] stock_restrict_expiration_date
  setup/stock_restrict_expiration_date/odoo/addons/stock_restrict_expiration_date
  setup/stock_restrict_expiration_date/setup.py
  stock_restrict_expiration_date/README.rst
  stock_restrict_expiration_date/__init__.py
  stock_restrict_expiration_date/__manifest__.py
  stock_restrict_expiration_date/i18n/fr.po
  stock_restrict_expiration_date/i18n/stock_restrict_expiration_date.pot
  stock_restrict_expiration_date/models/__init__.py
  stock_restrict_expiration_date/models/stock_move.py
  stock_restrict_expiration_date/models/stock_quant.py
  stock_restrict_expiration_date/models/stock_rule.py
  stock_restrict_expiration_date/readme/CONTRIBUTORS.rst
  stock_restrict_expiration_date/readme/DESCRIPTION.rst
  stock_restrict_expiration_date/static/description/icon.png
  stock_restrict_expiration_date/static/description/index.html
  stock_restrict_expiration_date/tests/__init__.py
  stock_restrict_expiration_date/tests/test_restrict_expiration_date.py
  stock_restrict_expiration_date/views/stock_picking_views.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1732 [14.0][IMP] stock_putaway_by_route: Make used routes for putaway hookable
  stock_putaway_by_route/models/stock_move.py
  stock_putaway_by_route/readme/CONTRIBUTORS.rst
Labels: enhancement, needs review, approved, bot is merging ⏳

#1717 [17.0][MIG] stock_valuation_layer_usage
  stock_valuation_layer_usage/README.rst
  stock_valuation_layer_usage/__init__.py
  stock_valuation_layer_usage/__manifest__.py
  stock_valuation_layer_usage/i18n/es.po
  stock_valuation_layer_usage/i18n/it.po
  stock_valuation_layer_usage/i18n/stock_valuation_layer_usage.pot
  stock_valuation_layer_usage/models/__init__.py
  stock_valuation_layer_usage/models/stock_move.py
  stock_valuation_layer_usage/models/stock_valuation_layer.py
  stock_valuation_layer_usage/models/stock_valuation_layer_usage.py
  stock_valuation_layer_usage/pyproject.toml
  stock_valuation_layer_usage/readme/CONTRIBUTORS.md
  stock_valuation_layer_usage/readme/DESCRIPTION.md
  stock_valuation_layer_usage/readme/HISTORY.md
  stock_valuation_layer_usage/readme/INSTALL.md
  stock_valuation_layer_usage/readme/USAGE.md
  stock_valuation_layer_usage/security/ir.model.access.csv
  stock_valuation_layer_usage/static/description/icon.png
  stock_valuation_layer_usage/static/description/index.html
  stock_valuation_layer_usage/tests/__init__.py
  stock_valuation_layer_usage/tests/test_stock_valuation_layer_usage.py
  stock_valuation_layer_usage/views/stock_move_views.xml
  stock_valuation_layer_usage/views/stock_valuation_layer_usage_views.xml
  stock_valuation_layer_usage/views/stock_valuation_layer_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1711 [17.0][MIG] purchase_stock_picking_invoice_link
  purchase_stock_picking_invoice_link/README.rst
  purchase_stock_picking_invoice_link/__init__.py
  purchase_stock_picking_invoice_link/__manifest__.py
  purchase_stock_picking_invoice_link/i18n/es.po
  purchase_stock_picking_invoice_link/i18n/fr.po
  purchase_stock_picking_invoice_link/i18n/hr.po
  purchase_stock_picking_invoice_link/i18n/it.po
  purchase_stock_picking_invoice_link/i18n/pt_BR.po
  purchase_stock_picking_invoice_link/i18n/purchase_stock_picking_invoice_link.pot
  purchase_stock_picking_invoice_link/models/__init__.py
  purchase_stock_picking_invoice_link/models/purchase_order.py
  purchase_stock_picking_invoice_link/models/stock_move.py
  purchase_stock_picking_invoice_link/pyproject.toml
  purchase_stock_picking_invoice_link/readme/CONTRIBUTORS.md
  purchase_stock_picking_invoice_link/readme/DESCRIPTION.md
  purchase_stock_picking_invoice_link/readme/USAGE.md
  purchase_stock_picking_invoice_link/static/description/icon.png
  purchase_stock_picking_invoice_link/static/description/index.html
  purchase_stock_picking_invoice_link/tests/__init__.py
  purchase_stock_picking_invoice_link/tests/test_purchase_stock_picking_invoice_link.py
Labels: needs review, approved, migration, bot is merging ⏳

#1718 [16.0][MIG] procurement_auto_create_group_carrier
  procurement_auto_create_group_carrier/README.rst
  procurement_auto_create_group_carrier/__init__.py
  procurement_auto_create_group_carrier/__manifest__.py
  procurement_auto_create_group_carrier/i18n/procurement_auto_create_group_carrier.pot
  procurement_auto_create_group_carrier/models/__init__.py
  procurement_auto_create_group_carrier/models/stock_rule.py
  procurement_auto_create_group_carrier/readme/CONTRIBUTORS.rst
  procurement_auto_create_group_carrier/readme/CREDITS.rst
  procurement_auto_create_group_carrier/readme/DESCRIPTION.rst
  procurement_auto_create_group_carrier/static/description/icon.png
  procurement_auto_create_group_carrier/static/description/index.html
  procurement_auto_create_group_carrier/tests/__init__.py
  procurement_auto_create_group_carrier/tests/test_procurement_auto_create_group_carrier.py
  setup/procurement_auto_create_group_carrier/odoo/addons/procurement_auto_create_group_carrier
  setup/procurement_auto_create_group_carrier/setup.py
Labels: migration, bot is merging ⏳
