Repository OCA/stock-logistics-workflow, pull requests merged in 2024-06, with the labels that each got.

#1599 [15.0][IMP] stock_picking_mass_action: allow to configure `check_assign_all` domain
  stock_picking_mass_action/models/stock_picking.py
Labels: approved, bot is merging ⏳

#1612 [16.0][FW][IMP] stock_picking_auto_create_lot: Use Odoo core mechanism to create lots in pickings filling lot_name field instead of create all lots
  stock_picking_auto_create_lot/models/__init__.py
  stock_picking_auto_create_lot/models/stock_move_line.py
  stock_picking_auto_create_lot/models/stock_picking.py
  stock_picking_auto_create_lot/tests/test_stock_picking_auto_create_lot.py
Labels: enhancement, approved, bot is merging ⏳

#1429 [15.0][IMP] stock_return_request: Improve performance and simplicity.
  stock_return_request/README.rst
  stock_return_request/__init__.py
  stock_return_request/__manifest__.py
  stock_return_request/hooks.py
  stock_return_request/models/stock_move.py
  stock_return_request/models/stock_return_request.py
  stock_return_request/static/description/index.html
Labels: approved, bot is merging ⏳, stale

#1615 [IMP] [16.0] stock_picking_batch_validate_confirm: Add confirmation group
  stock_picking_batch_validate_confirm/README.rst
  stock_picking_batch_validate_confirm/__manifest__.py
  stock_picking_batch_validate_confirm/i18n/es.po
  stock_picking_batch_validate_confirm/i18n/stock_picking_batch_validate_confirm.pot
  stock_picking_batch_validate_confirm/readme/CONFIGURE.md
  stock_picking_batch_validate_confirm/readme/DESCRIPTION.md
  stock_picking_batch_validate_confirm/security/stock_picking_batch_validate_confirm_groups.xml
  stock_picking_batch_validate_confirm/static/description/index.html
  stock_picking_batch_validate_confirm/tests/test_batch_confirm.py
  stock_picking_batch_validate_confirm/wizards/stock_picking_batch_confirm.xml
Labels: approved, bot is merging ⏳

#1617 [15.0][FIX] stock_picking_invoice_link: don't store auxiliar fields
  stock_picking_invoice_link/models/account_move.py
  stock_picking_invoice_link/views/account_invoice_view.xml
Labels: approved, bot is merging ⏳

#1620 [16.0][FIX] stock_picking_invoice_link: don't store auxiliar fields
  stock_picking_invoice_link/models/account_move.py
  stock_picking_invoice_link/views/account_invoice_view.xml
Labels: approved, bot is merging ⏳

#1624 [17.0][FIX] stock_picking_invoice_link: don't store auxiliar fields
  stock_picking_invoice_link/models/account_move.py
  stock_picking_invoice_link/views/account_invoice_view.xml
Labels: approved, bot is merging ⏳

#1625 [16.0][FIX] stock_picking_invoice_link: Avoid inconsistent computes
  stock_picking_invoice_link/models/account_move.py
Labels: approved, bot is merging ⏳

#1631 [17.0][FIX] stock_picking_invoice_link: Avoid inconsistent computes
  stock_picking_invoice_link/models/account_move.py
Labels: bot is merging ⏳

#1630 [15.0][FIX] stock_picking_invoice_link: Avoid inconsistent computes
  stock_picking_invoice_link/models/account_move.py
Labels: approved, bot is merging ⏳

#1611 [ADD] [16.0] stock_picking_date_deadline_syncs_scheduled_date
  setup/stock_picking_date_deadline_syncs_scheduled_date/odoo/addons/stock_picking_date_deadline_syncs_scheduled_date
  setup/stock_picking_date_deadline_syncs_scheduled_date/setup.py
  stock_picking_date_deadline_syncs_scheduled_date/README.rst
  stock_picking_date_deadline_syncs_scheduled_date/__init__.py
  stock_picking_date_deadline_syncs_scheduled_date/__manifest__.py
  stock_picking_date_deadline_syncs_scheduled_date/models/__init__.py
  stock_picking_date_deadline_syncs_scheduled_date/models/stock_move.py
  stock_picking_date_deadline_syncs_scheduled_date/readme/CONTEXT.md
  stock_picking_date_deadline_syncs_scheduled_date/readme/CONTRIBUTORS.md
  stock_picking_date_deadline_syncs_scheduled_date/readme/DESCRIPTION.md
  stock_picking_date_deadline_syncs_scheduled_date/readme/ROADMAP.md
  stock_picking_date_deadline_syncs_scheduled_date/readme/USAGE.md
  stock_picking_date_deadline_syncs_scheduled_date/static/description/icon.png
  stock_picking_date_deadline_syncs_scheduled_date/static/description/index.html
  stock_picking_date_deadline_syncs_scheduled_date/tests/__init__.py
  stock_picking_date_deadline_syncs_scheduled_date/tests/test_date_deadline_sync.py
Labels: approved, ready to merge, bot is merging ⏳

#1636 [16.0][FIX] stock_picking_invoice_link: Avoid doble compute picking_count
  stock_picking_invoice_link/models/account_move.py
Labels: approved, bot is merging ⏳

#1635 [FIX] stock_picking_partner_note: Fix tests from unexistent variable / procurement_auto_create_group_carrier: Update function signature
  procurement_auto_create_group_carrier/models/stock_rule.py
  stock_picking_partner_note/tests/test_stock_picking_partner_note.py
Labels: enhancement, approved, bot is merging ⏳

#1634 [14.0] [MIG] stock_picking_return_lot
  setup/stock_picking_return_lot/odoo/addons/stock_picking_return_lot
  setup/stock_picking_return_lot/setup.py
  stock_picking_return_lot/README.rst
  stock_picking_return_lot/__init__.py
  stock_picking_return_lot/__manifest__.py
  stock_picking_return_lot/i18n/stock_picking_return_lot.pot
  stock_picking_return_lot/readme/CONTRIBUTORS.rst
  stock_picking_return_lot/readme/DESCRIPTION.rst
  stock_picking_return_lot/static/description/icon.png
  stock_picking_return_lot/static/description/index.html
  stock_picking_return_lot/tests/__init__.py
  stock_picking_return_lot/tests/test_stock_picking_return_lot.py
  stock_picking_return_lot/wizard/__init__.py
  stock_picking_return_lot/wizard/stock_picking_return.py
Labels: approved

#1616 [16.0][IMP] stock_picking_auto_create_lot
  stock_picking_auto_create_lot/models/__init__.py
  stock_picking_auto_create_lot/models/stock_move_line.py
  stock_picking_auto_create_lot/models/stock_picking.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1621 [16.0][FIX] stock_move_line_change_lot: fix tests
  stock_move_line_change_lot/tests/test_change_lot.py
Labels: approved, ready to merge, bot is merging ⏳
