Repository OCA/stock-logistics-workflow, pull requests merged in 2024-07, with the labels that each got.

#1656 [16.0][FIX] stock_picking_group_by_partner_by_carrier: add the same class style as in the base report
  stock_picking_group_by_partner_by_carrier/report/report_delivery_slip.xml
Labels: bot is merging ⏳

#1657 [MIG] stock_picking_auto_create_lot: Migration to 17.0
  stock_picking_auto_create_lot/README.rst
  stock_picking_auto_create_lot/__init__.py
  stock_picking_auto_create_lot/__manifest__.py
  stock_picking_auto_create_lot/i18n/es.po
  stock_picking_auto_create_lot/i18n/it.po
  stock_picking_auto_create_lot/i18n/nl.po
  stock_picking_auto_create_lot/i18n/stock_picking_auto_create_lot.pot
  stock_picking_auto_create_lot/i18n/zh_CN.po
  stock_picking_auto_create_lot/models/__init__.py
  stock_picking_auto_create_lot/models/product.py
  stock_picking_auto_create_lot/models/stock_move.py
  stock_picking_auto_create_lot/models/stock_move_line.py
  stock_picking_auto_create_lot/models/stock_picking.py
  stock_picking_auto_create_lot/models/stock_picking_type.py
  stock_picking_auto_create_lot/pyproject.toml
  stock_picking_auto_create_lot/readme/CONFIGURE.md
  stock_picking_auto_create_lot/readme/CONTRIBUTORS.md
  stock_picking_auto_create_lot/readme/DESCRIPTION.md
  stock_picking_auto_create_lot/readme/USAGE.md
  stock_picking_auto_create_lot/static/description/icon.png
  stock_picking_auto_create_lot/static/description/index.html
  stock_picking_auto_create_lot/tests/__init__.py
  stock_picking_auto_create_lot/tests/common.py
  stock_picking_auto_create_lot/tests/test_stock_picking_auto_create_lot.py
  stock_picking_auto_create_lot/views/product_views.xml
  stock_picking_auto_create_lot/views/stock_picking_type_views.xml
Labels: approved, bot is merging ⏳

#1581 [16.0][MIG] stock_production_lot_active: Migration to 16.0
  setup/stock_production_lot_active/odoo/addons/stock_production_lot_active
  setup/stock_production_lot_active/setup.py
  stock_production_lot_active/README.rst
  stock_production_lot_active/__init__.py
  stock_production_lot_active/__manifest__.py
  stock_production_lot_active/i18n/it.po
  stock_production_lot_active/i18n/stock_production_lot_active.pot
  stock_production_lot_active/models/__init__.py
  stock_production_lot_active/models/stock_production_lot.py
  stock_production_lot_active/readme/CONTRIBUTORS.rst
  stock_production_lot_active/readme/DESCRIPTION.rst
  stock_production_lot_active/static/description/icon.png
  stock_production_lot_active/static/description/index.html
  stock_production_lot_active/tests/__init__.py
  stock_production_lot_active/tests/test_lot_active.py
  stock_production_lot_active/views/stock_production_lot.xml
Labels: approved, migration, bot is merging ⏳

#1598 [16.0][FIX] stock_picking_restrict_cancel_printed: move cancellation
  stock_picking_restrict_cancel_printed/__manifest__.py
  stock_picking_restrict_cancel_printed/models/__init__.py
  stock_picking_restrict_cancel_printed/models/stock_move.py
  stock_picking_restrict_cancel_printed/tests/test_stock_picking_restrict_cancel_printed.py
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#1619 [16.0][ADD] stock_picking_auto_create_lot_sequence
  setup/stock_picking_auto_create_lot_sequence/odoo/addons/stock_picking_auto_create_lot_sequence
  setup/stock_picking_auto_create_lot_sequence/setup.py
  stock_picking_auto_create_lot_sequence/README.rst
  stock_picking_auto_create_lot_sequence/__init__.py
  stock_picking_auto_create_lot_sequence/__manifest__.py
  stock_picking_auto_create_lot_sequence/models/__init__.py
  stock_picking_auto_create_lot_sequence/models/stock_move_line.py
  stock_picking_auto_create_lot_sequence/readme/DESCRIPTION.rst
  stock_picking_auto_create_lot_sequence/static/description/index.html
  stock_picking_auto_create_lot_sequence/tests/__init__.py
  stock_picking_auto_create_lot_sequence/tests/test_stock_picking_auto_create_lot_sequence.py
Labels: approved, bot is merging ⏳

#1661 [15.0][ADD] stock_picking_operation_manual_lot_selection
  setup/stock_picking_operation_manual_lot_selection/odoo/addons/stock_picking_operation_manual_lot_selection
  setup/stock_picking_operation_manual_lot_selection/setup.py
  stock_picking_operation_manual_lot_selection/README.rst
  stock_picking_operation_manual_lot_selection/__init__.py
  stock_picking_operation_manual_lot_selection/__manifest__.py
  stock_picking_operation_manual_lot_selection/i18n/en_US.po
  stock_picking_operation_manual_lot_selection/i18n/fr.po
  stock_picking_operation_manual_lot_selection/models/__init__.py
  stock_picking_operation_manual_lot_selection/models/stock_move_line.py
  stock_picking_operation_manual_lot_selection/models/stock_picking.py
  stock_picking_operation_manual_lot_selection/readme/AUTHORS.rst
  stock_picking_operation_manual_lot_selection/readme/CONFIGURE.rst
  stock_picking_operation_manual_lot_selection/readme/CONTRIBUTORS.rst
  stock_picking_operation_manual_lot_selection/readme/DESCRIPTION.rst
  stock_picking_operation_manual_lot_selection/readme/USAGE.rst
  stock_picking_operation_manual_lot_selection/static/description/index.html
  stock_picking_operation_manual_lot_selection/tests/__init__.py
  stock_picking_operation_manual_lot_selection/tests/test_stock_picking_lot.py
  stock_picking_operation_manual_lot_selection/views/stock_move_views.xml
  stock_picking_operation_manual_lot_selection/views/stock_picking_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1623 [17.0][MIG] stock_picking_filter_lot: Migration to 17.0
  stock_picking_filter_lot/README.rst
  stock_picking_filter_lot/__init__.py
  stock_picking_filter_lot/__manifest__.py
  stock_picking_filter_lot/i18n/es.po
  stock_picking_filter_lot/i18n/fr.po
  stock_picking_filter_lot/i18n/it.po
  stock_picking_filter_lot/i18n/stock_picking_filter_lot.pot
  stock_picking_filter_lot/models/__init__.py
  stock_picking_filter_lot/models/stock_lot.py
  stock_picking_filter_lot/pyproject.toml
  stock_picking_filter_lot/readme/CONTRIBUTORS.md
  stock_picking_filter_lot/readme/DESCRIPTION.md
  stock_picking_filter_lot/readme/USAGE.md
  stock_picking_filter_lot/static/description/icon.png
  stock_picking_filter_lot/static/description/index.html
  stock_picking_filter_lot/views/stock_move_line_view.xml
  stock_picking_filter_lot/views/stock_scrap_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1646 [15.0][ADD] stock_move_original_date
  setup/stock_move_original_date/odoo/addons/stock_move_original_date
  setup/stock_move_original_date/setup.py
  stock_move_original_date/README.rst
  stock_move_original_date/__init__.py
  stock_move_original_date/__manifest__.py
  stock_move_original_date/models/__init__.py
  stock_move_original_date/models/stock_move.py
  stock_move_original_date/models/stock_picking.py
  stock_move_original_date/readme/CONTRIBUTORS.rst
  stock_move_original_date/readme/DESCRIPTION.rst
  stock_move_original_date/readme/USAGE.rst
  stock_move_original_date/static/description/icon.png
  stock_move_original_date/static/description/index.html
  stock_move_original_date/tests/__init__.py
  stock_move_original_date/tests/test_stock_move_original_date.py
  stock_move_original_date/views/stock_move_views.xml
  stock_move_original_date/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳
