Repository OCA/stock-logistics-workflow, pull requests merged in 2024-03, with the labels that each got.

#1525 [14.0][FIX] product_supplierinfo_for_customer_picking: use move's company
  product_supplierinfo_for_customer_picking/models/stock_move.py
  product_supplierinfo_for_customer_picking/tests/test_product_supplierinfo_for_customer_picking.py
Labels: enhancement, approved, bot is merging ⏳

#1500 [15.0][ADD] stock_force_assign_by_type: New Module
  setup/stock_force_assign_by_type/odoo/addons/stock_force_assign_by_type
  setup/stock_force_assign_by_type/setup.py
  stock_force_assign_by_type/README.rst
  stock_force_assign_by_type/__init__.py
  stock_force_assign_by_type/__manifest__.py
  stock_force_assign_by_type/models/__init__.py
  stock_force_assign_by_type/models/stock_move.py
  stock_force_assign_by_type/models/stock_picking.py
  stock_force_assign_by_type/models/stock_picking_type.py
  stock_force_assign_by_type/readme/CONFIGURE.rst
  stock_force_assign_by_type/readme/CONTEXT.rst
  stock_force_assign_by_type/readme/CONTRIBUTORS.rst
  stock_force_assign_by_type/readme/DESCRIPTION.rst
  stock_force_assign_by_type/readme/USAGE.rst
  stock_force_assign_by_type/static/description/icon.png
  stock_force_assign_by_type/static/description/index.html
  stock_force_assign_by_type/tests/__init__.py
  stock_force_assign_by_type/tests/test_stock_force_assign_by_type.py
  stock_force_assign_by_type/views/stock_picking_views.xml
Labels: needs review, approved, bot is merging ⏳

#1530 [15.0][IMP] stock_reception_discrepancy_distribution: Update initial demandto avoid an extra picking when use multi steps reception and MTO
  stock_reception_discrepancy_distribution/wizards/stock_reception_discrepancy_distribution_wiz.py
Labels: approved, bot is merging ⏳

#1466 [16.0] [MIG] stock_auto_move
  setup/stock_auto_move/odoo/addons/stock_auto_move
  setup/stock_auto_move/setup.py
  stock_auto_move/README.rst
  stock_auto_move/__init__.py
  stock_auto_move/__manifest__.py
  stock_auto_move/data/procurement_group.xml
  stock_auto_move/demo/stock_location.xml
  stock_auto_move/demo/stock_route.xml
  stock_auto_move/demo/stock_rule.xml
  stock_auto_move/i18n/ca.po
  stock_auto_move/i18n/de.po
  stock_auto_move/i18n/es.po
  stock_auto_move/i18n/es_MX.po
  stock_auto_move/i18n/fi.po
  stock_auto_move/i18n/fr.po
  stock_auto_move/i18n/hr.po
  stock_auto_move/i18n/it.po
  stock_auto_move/i18n/nl_NL.po
  stock_auto_move/i18n/pt.po
  stock_auto_move/i18n/pt_BR.po
  stock_auto_move/i18n/pt_PT.po
  stock_auto_move/i18n/sl.po
  stock_auto_move/i18n/stock_auto_move.pot
  stock_auto_move/i18n/tr.po
  stock_auto_move/i18n/tr_TR.po
  stock_auto_move/i18n/zh_CN.po
  stock_auto_move/models/__init__.py
  stock_auto_move/models/stock_move.py
  stock_auto_move/models/stock_rule.py
  stock_auto_move/readme/CONFIGURE.rst
  stock_auto_move/readme/CONTRIBUTORS.rst
  stock_auto_move/readme/DESCRIPTION.rst
  stock_auto_move/readme/INSTALL.rst
  stock_auto_move/readme/USAGE.rst
  stock_auto_move/static/description/icon.png
  stock_auto_move/static/description/index.html
  stock_auto_move/tests/__init__.py
  stock_auto_move/tests/test_stock_auto_move.py
  stock_auto_move/views/stock_move.xml
  stock_auto_move/views/stock_rule.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1483 [16.0][ADD] stock_move_priority_picking_assign
  setup/stock_move_priority_picking_assign/odoo/addons/stock_move_priority_picking_assign
  setup/stock_move_priority_picking_assign/setup.py
  stock_move_priority_picking_assign/README.rst
  stock_move_priority_picking_assign/__init__.py
  stock_move_priority_picking_assign/__manifest__.py
  stock_move_priority_picking_assign/models/__init__.py
  stock_move_priority_picking_assign/models/stock_move.py
  stock_move_priority_picking_assign/models/stock_picking_type.py
  stock_move_priority_picking_assign/readme/CONFIGURE.md
  stock_move_priority_picking_assign/readme/CONTEXT.md
  stock_move_priority_picking_assign/readme/CONTRIBUTORS.md
  stock_move_priority_picking_assign/readme/DESCRIPTION.md
  stock_move_priority_picking_assign/readme/INSTALL.md
  stock_move_priority_picking_assign/static/description/icon.png
  stock_move_priority_picking_assign/static/description/index.html
  stock_move_priority_picking_assign/tests/__init__.py
  stock_move_priority_picking_assign/tests/test_move_priority.py
  stock_move_priority_picking_assign/views/stock_picking_type.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1467 [15.0][MIG] stock_auto_move to v15
  setup/stock_auto_move/odoo/addons/stock_auto_move
  setup/stock_auto_move/setup.py
  stock_auto_move/README.rst
  stock_auto_move/__init__.py
  stock_auto_move/__manifest__.py
  stock_auto_move/data/procurement_group.xml
  stock_auto_move/demo/stock_location.xml
  stock_auto_move/demo/stock_location_route.xml
  stock_auto_move/demo/stock_rule.xml
  stock_auto_move/i18n/ca.po
  stock_auto_move/i18n/de.po
  stock_auto_move/i18n/es.po
  stock_auto_move/i18n/es_MX.po
  stock_auto_move/i18n/fi.po
  stock_auto_move/i18n/fr.po
  stock_auto_move/i18n/hr.po
  stock_auto_move/i18n/it.po
  stock_auto_move/i18n/nl_NL.po
  stock_auto_move/i18n/pt.po
  stock_auto_move/i18n/pt_BR.po
  stock_auto_move/i18n/pt_PT.po
  stock_auto_move/i18n/sl.po
  stock_auto_move/i18n/stock_auto_move.pot
  stock_auto_move/i18n/tr.po
  stock_auto_move/i18n/tr_TR.po
  stock_auto_move/i18n/zh_CN.po
  stock_auto_move/models/__init__.py
  stock_auto_move/models/stock_move.py
  stock_auto_move/models/stock_rule.py
  stock_auto_move/readme/CONFIGURE.rst
  stock_auto_move/readme/CONTRIBUTORS.rst
  stock_auto_move/readme/DESCRIPTION.rst
  stock_auto_move/readme/INSTALL.rst
  stock_auto_move/readme/USAGE.rst
  stock_auto_move/static/description/icon.png
  stock_auto_move/static/description/index.html
  stock_auto_move/tests/__init__.py
  stock_auto_move/tests/test_stock_auto_move.py
  stock_auto_move/views/stock_move.xml
  stock_auto_move/views/stock_rule.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1437 [17.0][MIG]stock_no_negative: Migrated to v17
  stock_no_negative/README.rst
  stock_no_negative/__init__.py
  stock_no_negative/__manifest__.py
  stock_no_negative/i18n/ar.po
  stock_no_negative/i18n/de.po
  stock_no_negative/i18n/es.po
  stock_no_negative/i18n/fr.po
  stock_no_negative/i18n/hr.po
  stock_no_negative/i18n/it.po
  stock_no_negative/i18n/pt.po
  stock_no_negative/i18n/stock_no_negative.pot
  stock_no_negative/models/__init__.py
  stock_no_negative/models/product.py
  stock_no_negative/models/stock_location.py
  stock_no_negative/models/stock_quant.py
  stock_no_negative/pyproject.toml
  stock_no_negative/readme/CONFIGURE.md
  stock_no_negative/readme/CONTRIBUTORS.md
  stock_no_negative/readme/DESCRIPTION.md
  stock_no_negative/readme/HISTORY.md
  stock_no_negative/readme/USAGE.md
  stock_no_negative/static/description/icon.png
  stock_no_negative/static/description/index.html
  stock_no_negative/tests/__init__.py
  stock_no_negative/tests/test_stock_no_negative.py
  stock_no_negative/views/product_product_views.xml
  stock_no_negative/views/stock_location_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1537 [15.0][FIX] stock_picking_auto_create_lot: Lots repeated for different stock move lines with the same product
  stock_picking_auto_create_lot/models/stock_move_line.py
  stock_picking_auto_create_lot/tests/test_stock_picking_auto_create_lot.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1330 [16.0][MIG] - stock_picking_progress
  requirements.txt
  setup/stock_picking_progress/odoo/addons/stock_picking_progress
  setup/stock_picking_progress/setup.py
  stock_picking_progress/README.rst
  stock_picking_progress/__init__.py
  stock_picking_progress/__manifest__.py
  stock_picking_progress/hooks.py
  stock_picking_progress/i18n/stock_picking_progress.pot
  stock_picking_progress/models/__init__.py
  stock_picking_progress/models/stock_move.py
  stock_picking_progress/models/stock_move_line.py
  stock_picking_progress/models/stock_picking.py
  stock_picking_progress/readme/CONTRIBUTORS.rst
  stock_picking_progress/readme/DESCRIPTION.rst
  stock_picking_progress/static/description/icon.png
  stock_picking_progress/static/description/index.html
  stock_picking_progress/tests/__init__.py
  stock_picking_progress/tests/test_progress.py
  stock_picking_progress/views/stock_picking.xml
Labels: needs review, approved, migration, bot is merging ⏳, stale

#1469 [16.0][ADD] stock_move_line_change_lot : switch lot reservations between pickings
  setup/stock_move_line_change_lot/odoo/addons/stock_move_line_change_lot
  setup/stock_move_line_change_lot/setup.py
  stock_move_line_change_lot/README.rst
  stock_move_line_change_lot/__init__.py
  stock_move_line_change_lot/__manifest__.py
  stock_move_line_change_lot/models/__init__.py
  stock_move_line_change_lot/models/stock_move_line.py
  stock_move_line_change_lot/readme/CONTRIBUTORS.rst
  stock_move_line_change_lot/readme/DESCRIPTION.rst
  stock_move_line_change_lot/static/description/index.html
  stock_move_line_change_lot/tests/__init__.py
  stock_move_line_change_lot/tests/test_change_lot.py
Labels: approved, ready to merge, bot is merging ⏳

#1538 [16.0][MIG] stock_product_set: Migration to version 16.0
  setup/stock_product_set/odoo/addons/stock_product_set
  setup/stock_product_set/setup.py
  stock_product_set/README.rst
  stock_product_set/__init__.py
  stock_product_set/__manifest__.py
  stock_product_set/i18n/es.po
  stock_product_set/i18n/stock_product_set.pot
  stock_product_set/models/__init__.py
  stock_product_set/models/product_set_line.py
  stock_product_set/readme/CONTRIBUTORS.rst
  stock_product_set/readme/DESCRIPTION.rst
  stock_product_set/readme/ROADMAP.rst
  stock_product_set/readme/USAGE.rst
  stock_product_set/security/ir.model.access.csv
  stock_product_set/static/description/icon.png
  stock_product_set/static/description/index.html
  stock_product_set/tests/__init__.py
  stock_product_set/tests/test_stock_product_set.py
  stock_product_set/views/stock_picking_views.xml
  stock_product_set/wizard/__init__.py
  stock_product_set/wizard/stock_product_set_wizard.py
  stock_product_set/wizard/stock_product_set_wizard_view.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1504 [14.0][MIG] stock_picking_partner_note: Migration from 16 to 14.0
  setup/stock_picking_partner_note/odoo/addons/stock_picking_partner_note
  setup/stock_picking_partner_note/setup.py
  stock_picking_partner_note/README.rst
  stock_picking_partner_note/__init__.py
  stock_picking_partner_note/__manifest__.py
  stock_picking_partner_note/i18n/fr.po
  stock_picking_partner_note/i18n/stock_picking_partner_note.pot
  stock_picking_partner_note/models/__init__.py
  stock_picking_partner_note/models/res_partner.py
  stock_picking_partner_note/models/stock_picking.py
  stock_picking_partner_note/models/stock_picking_note.py
  stock_picking_partner_note/models/stock_picking_note_type.py
  stock_picking_partner_note/models/stock_picking_type.py
  stock_picking_partner_note/readme/CONFIGURE.rst
  stock_picking_partner_note/readme/CONTRIBUTORS.rst
  stock_picking_partner_note/readme/DESCRIPTION.rst
  stock_picking_partner_note/security/ir.model.access.csv
  stock_picking_partner_note/static/description/icon.png
  stock_picking_partner_note/static/description/index.html
  stock_picking_partner_note/tests/__init__.py
  stock_picking_partner_note/tests/test_stock_picking_partner_note.py
  stock_picking_partner_note/views/res_partner.xml
  stock_picking_partner_note/views/stock_picking_note.xml
  stock_picking_partner_note/views/stock_picking_note_type.xml
  stock_picking_partner_note/views/stock_picking_partner_note_menus.xml
  stock_picking_partner_note/views/stock_picking_type.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1546 [15.0][IMP] stock_picking_batch_extended: batch relation in stock move
  stock_picking_batch_extended/models/__init__.py
  stock_picking_batch_extended/models/stock_move.py
Labels: approved, bot is merging ⏳

#1542 [17.0][MIG] stock_picking_show_return: Migration to 17.0
  stock_picking_show_return/README.rst
  stock_picking_show_return/__init__.py
  stock_picking_show_return/__manifest__.py
  stock_picking_show_return/i18n/de.po
  stock_picking_show_return/i18n/es.po
  stock_picking_show_return/i18n/fr.po
  stock_picking_show_return/i18n/it.po
  stock_picking_show_return/i18n/nl_NL.po
  stock_picking_show_return/i18n/pt.po
  stock_picking_show_return/i18n/pt_BR.po
  stock_picking_show_return/i18n/sl.po
  stock_picking_show_return/i18n/stock_picking_show_return.pot
  stock_picking_show_return/i18n/zh_CN.po
  stock_picking_show_return/models/__init__.py
  stock_picking_show_return/models/stock_picking.py
  stock_picking_show_return/pyproject.toml
  stock_picking_show_return/readme/CONTRIBUTORS.md
  stock_picking_show_return/readme/DESCRIPTION.md
  stock_picking_show_return/readme/HISTORY.md
  stock_picking_show_return/readme/USAGE.md
  stock_picking_show_return/static/description/icon.png
  stock_picking_show_return/static/description/index.html
  stock_picking_show_return/tests/__init__.py
  stock_picking_show_return/tests/test_stock_picking_show_return.py
  stock_picking_show_return/views/stock_picking_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1513 [ADD] [16.0] stock_rule_reserve_max_quantity
  setup/stock_rule_reserve_max_quantity/odoo/addons/stock_rule_reserve_max_quantity
  setup/stock_rule_reserve_max_quantity/setup.py
  stock_rule_reserve_max_quantity/README.rst
  stock_rule_reserve_max_quantity/__init__.py
  stock_rule_reserve_max_quantity/__manifest__.py
  stock_rule_reserve_max_quantity/i18n/es.po
  stock_rule_reserve_max_quantity/i18n/stock_rule_reserve_max_quantity.pot
  stock_rule_reserve_max_quantity/models/__init__.py
  stock_rule_reserve_max_quantity/models/stock_move.py
  stock_rule_reserve_max_quantity/models/stock_rule.py
  stock_rule_reserve_max_quantity/readme/CONTEXT.md
  stock_rule_reserve_max_quantity/readme/CONTRIBUTORS.md
  stock_rule_reserve_max_quantity/readme/CREDITS.md
  stock_rule_reserve_max_quantity/readme/DESCRIPTION.md
  stock_rule_reserve_max_quantity/readme/USAGE.md
  stock_rule_reserve_max_quantity/static/description/icon.png
  stock_rule_reserve_max_quantity/static/description/index.html
  stock_rule_reserve_max_quantity/tests/__init__.py
  stock_rule_reserve_max_quantity/tests/test_stock_rule_reservation.py
  stock_rule_reserve_max_quantity/views/stock_rule_views.xml
Labels: needs review, bot is merging ⏳

#1522 [15.0][ADD] backport stock_move_propagate_first_move
  setup/stock_move_propagate_first_move/odoo/addons/stock_move_propagate_first_move
  setup/stock_move_propagate_first_move/setup.py
  stock_move_propagate_first_move/README.rst
  stock_move_propagate_first_move/__init__.py
  stock_move_propagate_first_move/__manifest__.py
  stock_move_propagate_first_move/i18n/es.po
  stock_move_propagate_first_move/i18n/it.po
  stock_move_propagate_first_move/i18n/stock_move_propagate_first_move.pot
  stock_move_propagate_first_move/models/__init__.py
  stock_move_propagate_first_move/models/stock_move.py
  stock_move_propagate_first_move/models/stock_rule.py
  stock_move_propagate_first_move/readme/CONTRIBUTORS.rst
  stock_move_propagate_first_move/readme/DESCRIPTION.rst
  stock_move_propagate_first_move/static/description/icon.png
  stock_move_propagate_first_move/static/description/index.html
  stock_move_propagate_first_move/tests/__init__.py
  stock_move_propagate_first_move/tests/common.py
  stock_move_propagate_first_move/tests/test_stock_move_picking_type_origin_pull.py
  stock_move_propagate_first_move/tests/test_stock_move_picking_type_origin_pull_push.py
  stock_move_propagate_first_move/tests/test_stock_move_picking_type_origin_push.py
  stock_move_propagate_first_move/views/stock_move.xml
Labels: approved, ready to merge, bot is merging ⏳

#1541 [IMP] stock_picking_partner_note check note already in use
  stock_picking_partner_note/__manifest__.py
  stock_picking_partner_note/i18n/fr.po
  stock_picking_partner_note/i18n/stock_picking_partner_note.pot
  stock_picking_partner_note/models/__init__.py
  stock_picking_partner_note/models/res_company.py
  stock_picking_partner_note/models/res_config_settings.py
  stock_picking_partner_note/models/stock_picking_note.py
  stock_picking_partner_note/readme/CONFIGURE.rst
  stock_picking_partner_note/tests/test_stock_picking_partner_note.py
  stock_picking_partner_note/views/res_config_settings.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#1400 [16.0][MIG] stock_picking_quick : Migration to 16.0
  setup/stock_picking_quick/odoo/addons/stock_picking_quick
  setup/stock_picking_quick/setup.py
  stock_picking_quick/README.rst
  stock_picking_quick/__init__.py
  stock_picking_quick/__manifest__.py
  stock_picking_quick/i18n/pt_BR.po
  stock_picking_quick/i18n/sl.po
  stock_picking_quick/i18n/stock_picking_quick.pot
  stock_picking_quick/models/__init__.py
  stock_picking_quick/models/product_product.py
  stock_picking_quick/models/stock_picking.py
  stock_picking_quick/readme/CONTRIBUTORS.rst
  stock_picking_quick/readme/DESCRIPTION.rst
  stock_picking_quick/readme/USAGE.rst
  stock_picking_quick/static/description/filter.png
  stock_picking_quick/static/description/icon.png
  stock_picking_quick/static/description/index.html
  stock_picking_quick/static/description/po-product.png
  stock_picking_quick/static/description/po.png
  stock_picking_quick/tests/__init__.py
  stock_picking_quick/tests/test_stock_picking_quick.py
  stock_picking_quick/views/picking_view.xml
  stock_picking_quick/views/product_view.xml
Labels: needs review, approved, migration, bot is merging ⏳
