Repository OCA/stock-logistics-workflow, pull requests merged in 2024-04, with the labels that each got.

#1494 [14.0][MIG] stock_move_backdating
  setup/stock_move_backdating/odoo/addons/stock_move_backdating
  setup/stock_move_backdating/setup.py
  stock_move_backdating/README.rst
  stock_move_backdating/__init__.py
  stock_move_backdating/__manifest__.py
  stock_move_backdating/i18n/am.po
  stock_move_backdating/i18n/ca.po
  stock_move_backdating/i18n/de.po
  stock_move_backdating/i18n/es.po
  stock_move_backdating/i18n/es_AR.po
  stock_move_backdating/i18n/es_MX.po
  stock_move_backdating/i18n/fi.po
  stock_move_backdating/i18n/fr.po
  stock_move_backdating/i18n/gl.po
  stock_move_backdating/i18n/hr.po
  stock_move_backdating/i18n/hr_HR.po
  stock_move_backdating/i18n/it.po
  stock_move_backdating/i18n/nl.po
  stock_move_backdating/i18n/pt.po
  stock_move_backdating/i18n/pt_BR.po
  stock_move_backdating/i18n/pt_PT.po
  stock_move_backdating/i18n/ro.po
  stock_move_backdating/i18n/sl.po
  stock_move_backdating/i18n/stock_move_backdating.pot
  stock_move_backdating/i18n/tr.po
  stock_move_backdating/i18n/tr_TR.po
  stock_move_backdating/models/__init__.py
  stock_move_backdating/models/stock_inventory.py
  stock_move_backdating/models/stock_inventory_line.py
  stock_move_backdating/models/stock_move.py
  stock_move_backdating/models/stock_move_line.py
  stock_move_backdating/models/stock_picking.py
  stock_move_backdating/models/stock_quant.py
  stock_move_backdating/readme/CONTRIBUTORS.rst
  stock_move_backdating/readme/DESCRIPTION.rst
  stock_move_backdating/security/ir.model.access.csv
  stock_move_backdating/static/description/icon.png
  stock_move_backdating/static/description/index.html
  stock_move_backdating/tests/__init__.py
  stock_move_backdating/tests/common.py
  stock_move_backdating/tests/test_inventory.py
  stock_move_backdating/tests/test_picking.py
  stock_move_backdating/utils.py
  stock_move_backdating/views/stock_inventory_views.xml
  stock_move_backdating/views/stock_move_line_views.xml
  stock_move_backdating/views/stock_picking.xml
  stock_move_backdating/wizards/__init__.py
  stock_move_backdating/wizards/fill_date_backdating.py
  stock_move_backdating/wizards/fill_date_backdating.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1563 [FIX] stock_picking_group_by_partner_by_carrier: Don't get the assigned picking group
  stock_picking_group_by_partner_by_carrier/models/stock_move.py
  stock_picking_group_by_partner_by_carrier/tests/__init__.py
  stock_picking_group_by_partner_by_carrier/tests/test_grouping.py
  stock_picking_group_by_partner_by_carrier/tests/test_merge_wizard.py
Labels: enhancement, approved, bot is merging ⏳

#1503 [16.0][ADD] stock_customer_deposit
  .copier-answers.yml
  .github/workflows/test.yml
  setup/stock_customer_deposit/odoo/addons/stock_customer_deposit
  setup/stock_customer_deposit/setup.py
  stock_customer_deposit/README.rst
  stock_customer_deposit/__init__.py
  stock_customer_deposit/__manifest__.py
  stock_customer_deposit/i18n/es.po
  stock_customer_deposit/i18n/stock_customer_deposit.pot
  stock_customer_deposit/models/__init__.py
  stock_customer_deposit/models/product.py
  stock_customer_deposit/models/res_partner.py
  stock_customer_deposit/models/sale_order.py
  stock_customer_deposit/models/sale_order_line.py
  stock_customer_deposit/models/stock_move.py
  stock_customer_deposit/models/stock_picking.py
  stock_customer_deposit/models/stock_picking_type.py
  stock_customer_deposit/models/stock_quant.py
  stock_customer_deposit/models/stock_rule.py
  stock_customer_deposit/models/stock_warehouse.py
  stock_customer_deposit/readme/CONFIGURE.md
  stock_customer_deposit/readme/CONTEXT.md
  stock_customer_deposit/readme/CONTRIBUTORS.md
  stock_customer_deposit/readme/DESCRIPTION.md
  stock_customer_deposit/readme/ROADMAP.md
  stock_customer_deposit/readme/USAGE.md
  stock_customer_deposit/static/description/icon.png
  stock_customer_deposit/static/description/index.html
  stock_customer_deposit/tests/__init__.py
  stock_customer_deposit/tests/common.py
  stock_customer_deposit/tests/test_deliver_customer_deposit.py
  stock_customer_deposit/tests/test_sale_customer_deposit.py
  stock_customer_deposit/tests/test_stock_warehouse.py
  stock_customer_deposit/views/res_partner_views.xml
  stock_customer_deposit/views/sale_order_views.xml
  stock_customer_deposit/views/stock_picking_type_views.xml
  stock_customer_deposit/views/stock_warehouse_views.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1549 [ADD][16.0] stock_picking_restrict_cancel_printed
  setup/stock_picking_restrict_cancel_printed/odoo/addons/stock_picking_restrict_cancel_printed
  setup/stock_picking_restrict_cancel_printed/setup.py
  stock_picking_restrict_cancel_printed/README.rst
  stock_picking_restrict_cancel_printed/__init__.py
  stock_picking_restrict_cancel_printed/__manifest__.py
  stock_picking_restrict_cancel_printed/models/__init__.py
  stock_picking_restrict_cancel_printed/models/stock_picking.py
  stock_picking_restrict_cancel_printed/models/stock_picking_type.py
  stock_picking_restrict_cancel_printed/readme/CONTRIBUTORS.rst
  stock_picking_restrict_cancel_printed/readme/DESCRIPTION.rst
  stock_picking_restrict_cancel_printed/static/description/index.html
  stock_picking_restrict_cancel_printed/tests/__init__.py
  stock_picking_restrict_cancel_printed/tests/test_stock_picking_restrict_cancel_printed.py
  stock_picking_restrict_cancel_printed/views/stock_picking_type_views.xml
  stock_picking_restrict_cancel_printed/views/stock_picking_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1251 [16.0][ADD] sale_stock_restocking_fee_invoicing
  sale_stock_restocking_fee_invoicing/README.rst
  sale_stock_restocking_fee_invoicing/__init__.py
  sale_stock_restocking_fee_invoicing/__manifest__.py
  sale_stock_restocking_fee_invoicing/data/product_product.xml
  sale_stock_restocking_fee_invoicing/hooks.py
  sale_stock_restocking_fee_invoicing/i18n/fr.po
  sale_stock_restocking_fee_invoicing/i18n/sale_stock_restocking_fee_invoicing.pot
  sale_stock_restocking_fee_invoicing/models/__init__.py
  sale_stock_restocking_fee_invoicing/models/res_company.py
  sale_stock_restocking_fee_invoicing/models/res_config_settings.py
  sale_stock_restocking_fee_invoicing/models/res_partner.py
  sale_stock_restocking_fee_invoicing/models/sale_order.py
  sale_stock_restocking_fee_invoicing/models/sale_order_line.py
  sale_stock_restocking_fee_invoicing/models/stock_move.py
  sale_stock_restocking_fee_invoicing/readme/CONFIGURE.rst
  sale_stock_restocking_fee_invoicing/readme/CONTRIBUTORS.rst
  sale_stock_restocking_fee_invoicing/readme/DESCRIPTION.rst
  sale_stock_restocking_fee_invoicing/readme/ROADMAP.rst
  sale_stock_restocking_fee_invoicing/readme/USAGE.rst
  sale_stock_restocking_fee_invoicing/static/description/icon.png
  sale_stock_restocking_fee_invoicing/static/description/index.html
  sale_stock_restocking_fee_invoicing/tests/__init__.py
  sale_stock_restocking_fee_invoicing/tests/test_stock_return_picking.py
  sale_stock_restocking_fee_invoicing/views/res_company_views.xml
  sale_stock_restocking_fee_invoicing/views/res_config_settings_views.xml
  sale_stock_restocking_fee_invoicing/views/res_partner_views.xml
  sale_stock_restocking_fee_invoicing/views/stock_move_views.xml
  sale_stock_restocking_fee_invoicing/wizards/__init__.py
  sale_stock_restocking_fee_invoicing/wizards/stock_return_picking.py
  sale_stock_restocking_fee_invoicing/wizards/stock_return_picking_line.py
  sale_stock_restocking_fee_invoicing/wizards/stock_return_picking_views.xml
  setup/sale_stock_restocking_fee_invoicing/odoo/addons/sale_stock_restocking_fee_invoicing
  setup/sale_stock_restocking_fee_invoicing/setup.py
Labels: needs review, approved, bot is merging ⏳, stale

#1569 [15.0][ADD] stock_picking_show_lot: New module
  setup/stock_picking_show_lot/odoo/addons/stock_picking_show_lot
  setup/stock_picking_show_lot/setup.py
  stock_picking_show_lot/README.rst
  stock_picking_show_lot/__init__.py
  stock_picking_show_lot/__manifest__.py
  stock_picking_show_lot/i18n/es_ES.po
  stock_picking_show_lot/i18n/stock_picking_show_lot .pot
  stock_picking_show_lot/models/__init__.py
  stock_picking_show_lot/models/stock_picking.py
  stock_picking_show_lot/readme/CONTRIBUTORS.rst
  stock_picking_show_lot/readme/DESCRIPTION.rst
  stock_picking_show_lot/static/description/icon.png
  stock_picking_show_lot/static/description/index.html
  stock_picking_show_lot/views/stock_picking_views.xml
Labels: needs review, approved, bot is merging ⏳

#1568 [14.0][ADD] stock_picking_restrict_cancel_printed (backport)
  setup/stock_picking_restrict_cancel_printed/odoo/addons/stock_picking_restrict_cancel_printed
  setup/stock_picking_restrict_cancel_printed/setup.py
  stock_picking_restrict_cancel_printed/README.rst
  stock_picking_restrict_cancel_printed/__init__.py
  stock_picking_restrict_cancel_printed/__manifest__.py
  stock_picking_restrict_cancel_printed/models/__init__.py
  stock_picking_restrict_cancel_printed/models/stock_picking.py
  stock_picking_restrict_cancel_printed/models/stock_picking_type.py
  stock_picking_restrict_cancel_printed/readme/CONTRIBUTORS.rst
  stock_picking_restrict_cancel_printed/readme/DESCRIPTION.rst
  stock_picking_restrict_cancel_printed/static/description/index.html
  stock_picking_restrict_cancel_printed/tests/__init__.py
  stock_picking_restrict_cancel_printed/tests/test_stock_picking_restrict_cancel_printed.py
  stock_picking_restrict_cancel_printed/views/stock_picking_type_views.xml
  stock_picking_restrict_cancel_printed/views/stock_picking_views.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1539 [IMP] stock_grn: Don't use deprecated method _company_default_get anymore
  stock_grn/models/stock_grn.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1547 [16.0][ADD] stock_customer_deposit_elaboration
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  setup/stock_customer_deposit_elaboration/odoo/addons/stock_customer_deposit_elaboration
  setup/stock_customer_deposit_elaboration/setup.py
  stock_customer_deposit_elaboration/README.rst
  stock_customer_deposit_elaboration/__init__.py
  stock_customer_deposit_elaboration/__manifest__.py
  stock_customer_deposit_elaboration/i18n/es.po
  stock_customer_deposit_elaboration/i18n/stock_customer_deposit_elaboration.pot
  stock_customer_deposit_elaboration/models/__init__.py
  stock_customer_deposit_elaboration/models/sale_order_line.py
  stock_customer_deposit_elaboration/readme/CONFIGURE.md
  stock_customer_deposit_elaboration/readme/CONTEXT.md
  stock_customer_deposit_elaboration/readme/CONTRIBUTORS.md
  stock_customer_deposit_elaboration/readme/DESCRIPTION.md
  stock_customer_deposit_elaboration/readme/USAGE.md
  stock_customer_deposit_elaboration/static/description/icon.png
  stock_customer_deposit_elaboration/static/description/index.html
  stock_customer_deposit_elaboration/tests/__init__.py
  stock_customer_deposit_elaboration/tests/test_stock_customer_deposit_elaboration.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1556 [17.0][MIG] sale_order_global_stock_route: Migration to 17.0
  sale_order_global_stock_route/README.rst
  sale_order_global_stock_route/__init__.py
  sale_order_global_stock_route/__manifest__.py
  sale_order_global_stock_route/i18n/es.po
  sale_order_global_stock_route/i18n/it.po
  sale_order_global_stock_route/i18n/pt_BR.po
  sale_order_global_stock_route/i18n/sale_order_global_stock_route.pot
  sale_order_global_stock_route/models/__init__.py
  sale_order_global_stock_route/models/sale_order.py
  sale_order_global_stock_route/pyproject.toml
  sale_order_global_stock_route/readme/CONFIGURE.md
  sale_order_global_stock_route/readme/CONTRIBUTORS.md
  sale_order_global_stock_route/readme/DESCRIPTION.md
  sale_order_global_stock_route/readme/USAGE.md
  sale_order_global_stock_route/static/description/icon.png
  sale_order_global_stock_route/static/description/index.html
  sale_order_global_stock_route/tests/__init__.py
  sale_order_global_stock_route/tests/test_sale_order_global_stock_route.py
  sale_order_global_stock_route/views/sale_order_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1578 [14.0][FIX] stock_picking_putinpack_restriction: Restriction check after action_done
  stock_picking_putinpack_restriction/models/stock_move_line.py
  stock_picking_putinpack_restriction/readme/CONTRIBUTORS.rst
  stock_picking_putinpack_restriction/tests/test_stock_picking_putinpack_restriction.py
Labels: enhancement, approved, bot is merging ⏳

#1566 [14.0][FIX] stock_picking_auto_create_lot: create new serial number for lots
  stock_picking_auto_create_lot/models/stock_move_line.py
  stock_picking_auto_create_lot/tests/test_stock_picking_auto_create_lot.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1571 [ADD] [15.0] stock_warn_option
  setup/stock_warn_option/odoo/addons/stock_warn_option
  setup/stock_warn_option/setup.py
  stock_warn_option/README.rst
  stock_warn_option/__init__.py
  stock_warn_option/__manifest__.py
  stock_warn_option/i18n/es.po
  stock_warn_option/i18n/stock_warn_option.pot
  stock_warn_option/models/__init__.py
  stock_warn_option/models/res_partner.py
  stock_warn_option/models/warn_option.py
  stock_warn_option/readme/CONTEXT.md
  stock_warn_option/readme/CONTRIBUTORS.md
  stock_warn_option/readme/DESCRIPTION.md
  stock_warn_option/readme/USAGE.md
  stock_warn_option/static/description/icon.png
  stock_warn_option/static/description/index.html
  stock_warn_option/tests/__init__.py
  stock_warn_option/tests/test_warn_options.py
  stock_warn_option/views/res_partner_views.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1551 [17.0][MIG] stock_picking_purchase_order_link: Migration to 17.0
  stock_picking_purchase_order_link/README.rst
  stock_picking_purchase_order_link/__init__.py
  stock_picking_purchase_order_link/__manifest__.py
  stock_picking_purchase_order_link/i18n/es.po
  stock_picking_purchase_order_link/i18n/fr.po
  stock_picking_purchase_order_link/i18n/it.po
  stock_picking_purchase_order_link/i18n/pt_BR.po
  stock_picking_purchase_order_link/i18n/stock_picking_purchase_order_link.pot
  stock_picking_purchase_order_link/models/__init__.py
  stock_picking_purchase_order_link/models/stock_picking.py
  stock_picking_purchase_order_link/pyproject.toml
  stock_picking_purchase_order_link/readme/CONTRIBUTORS.md
  stock_picking_purchase_order_link/readme/DESCRIPTION.md
  stock_picking_purchase_order_link/readme/USAGE.md
  stock_picking_purchase_order_link/static/description/icon.png
  stock_picking_purchase_order_link/static/description/index.html
  stock_picking_purchase_order_link/tests/__init__.py
  stock_picking_purchase_order_link/tests/test_stock_picking_purchase_order_link.py
  stock_picking_purchase_order_link/views/stock_picking_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1554 [15.0][ADD] stock_picking_start: Backport from 16.0
  setup/stock_picking_start/odoo/addons/stock_picking_start
  setup/stock_picking_start/setup.py
  stock_picking_start/README.rst
  stock_picking_start/__init__.py
  stock_picking_start/__manifest__.py
  stock_picking_start/hooks.py
  stock_picking_start/i18n/es.po
  stock_picking_start/i18n/fr.po
  stock_picking_start/i18n/it.po
  stock_picking_start/i18n/stock_picking_start.pot
  stock_picking_start/models/__init__.py
  stock_picking_start/models/res_company.py
  stock_picking_start/models/res_config_settings.py
  stock_picking_start/models/stock_picking.py
  stock_picking_start/readme/CONTRIBUTORS.rst
  stock_picking_start/readme/DESCRIPTION.rst
  stock_picking_start/static/description/icon.png
  stock_picking_start/static/description/index.html
  stock_picking_start/tests/__init__.py
  stock_picking_start/tests/test_stock_picking_start.py
  stock_picking_start/views/res_config_settings.xml
  stock_picking_start/views/stock_picking.xml
Labels: approved, ready to merge, bot is merging ⏳
