Repository OCA/stock-logistics-workflow, pull requests merged in 2024-12, with the labels that each got.

#1775 [IMP] [16.0] stock_customer_deposit: Allow to add more deposits of the same product
  stock_customer_deposit/README.rst
  stock_customer_deposit/__manifest__.py
  stock_customer_deposit/i18n/es.po
  stock_customer_deposit/i18n/stock_customer_deposit.pot
  stock_customer_deposit/models/sale_order.py
  stock_customer_deposit/models/sale_order_line.py
  stock_customer_deposit/models/stock_move.py
  stock_customer_deposit/models/stock_quant.py
  stock_customer_deposit/readme/DESCRIPTION.md
  stock_customer_deposit/readme/USAGE.md
  stock_customer_deposit/static/description/index.html
  stock_customer_deposit/tests/test_sale_customer_deposit.py
  stock_customer_deposit/views/sale_order_views.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1760 [16.0][IMP] stock_move_line_lock_qty_done: prevent test cases from other modules from failing
  stock_move_line_lock_qty_done/README.rst
  stock_move_line_lock_qty_done/__manifest__.py
  stock_move_line_lock_qty_done/models/__init__.py
  stock_move_line_lock_qty_done/models/res_company.py
  stock_move_line_lock_qty_done/models/res_config_settings.py
  stock_move_line_lock_qty_done/models/stock_move_line.py
  stock_move_line_lock_qty_done/readme/CONFIGURE.rst
  stock_move_line_lock_qty_done/readme/CONTRIBUTORS.rst
  stock_move_line_lock_qty_done/readme/DESCRIPTION.rst
  stock_move_line_lock_qty_done/static/description/index.html
  stock_move_line_lock_qty_done/tests/test_stock_move_line_lock_qty_done.py
  stock_move_line_lock_qty_done/views/res_config_settings_views.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1784 [16.0][FIX] stock_customer_deposit: Filter out section and notes
  stock_customer_deposit/models/sale_order.py
Labels: needs review, approved, bot is merging ⏳

#1754 [16.0][IMP] product_expiry_simple: track expiry_date on stock.lot
  product_expiry_simple/models/stock_lot.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1622 [17.0][MIG] stock_quant_package_dimension
  stock_quant_package_dimension/README.rst
  stock_quant_package_dimension/__init__.py
  stock_quant_package_dimension/__manifest__.py
  stock_quant_package_dimension/i18n/es.po
  stock_quant_package_dimension/i18n/it.po
  stock_quant_package_dimension/i18n/stock_quant_package_dimension.pot
  stock_quant_package_dimension/models/__init__.py
  stock_quant_package_dimension/models/stock_quant_package.py
  stock_quant_package_dimension/pyproject.toml
  stock_quant_package_dimension/readme/CONTRIBUTORS.md
  stock_quant_package_dimension/readme/DESCRIPTION.md
  stock_quant_package_dimension/static/description/icon.png
  stock_quant_package_dimension/static/description/index.html
  stock_quant_package_dimension/tests/__init__.py
  stock_quant_package_dimension/tests/common.py
  stock_quant_package_dimension/tests/test_package_dimension.py
  stock_quant_package_dimension/views/stock_quant_package.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1683 [17.0][MIG] stock_lot_production_date: Migration to 17.0
  stock_lot_production_date/README.rst
  stock_lot_production_date/__init__.py
  stock_lot_production_date/__manifest__.py
  stock_lot_production_date/i18n/ca.po
  stock_lot_production_date/i18n/es.po
  stock_lot_production_date/i18n/it.po
  stock_lot_production_date/i18n/stock_lot_production_date.pot
  stock_lot_production_date/models/__init__.py
  stock_lot_production_date/models/stock_lot.py
  stock_lot_production_date/pyproject.toml
  stock_lot_production_date/readme/CONTRIBUTORS.md
  stock_lot_production_date/readme/CREDITS.md
  stock_lot_production_date/readme/DESCRIPTION.md
  stock_lot_production_date/readme/USAGE.md
  stock_lot_production_date/static/description/icon.png
  stock_lot_production_date/static/description/index.html
  stock_lot_production_date/static/description/lot.png
  stock_lot_production_date/views/stock_lot.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1798 [14.0][IMP] product_expiry_simple: backport small usability improvements
  product_expiry_simple/models/stock_production_lot.py
Labels: bot is merging ⏳
