Repository OCA/stock-logistics-workflow, pull requests merged in 2025-08, with the labels that each got.

#2055 [IMP] stock_move_line_qty_picked: sync `picked` and `qty_picked` fields
  stock_move_line_qty_picked/models/stock_move_line.py
  stock_move_line_qty_picked/tests/test_stock_move_line_qty_picked.py
Labels: approved, bot is merging ⏳

#1741 [16.0][ADD] stock_split_picking_dimension: Split picking based on dimension
  setup/stock_split_picking_dimension/odoo/addons/stock_split_picking_dimension
  setup/stock_split_picking_dimension/setup.py
  stock_split_picking_dimension/README.rst
  stock_split_picking_dimension/__init__.py
  stock_split_picking_dimension/__manifest__.py
  stock_split_picking_dimension/exceptions.py
  stock_split_picking_dimension/readme/CONTEXT.md
  stock_split_picking_dimension/readme/CONTRIBUTORS.md
  stock_split_picking_dimension/readme/CREDITS.md
  stock_split_picking_dimension/readme/DESCRIPTION.md
  stock_split_picking_dimension/readme/HISTORY.md
  stock_split_picking_dimension/readme/ROADMAP.md
  stock_split_picking_dimension/readme/USAGE.md
  stock_split_picking_dimension/static/description/icon.png
  stock_split_picking_dimension/static/description/index.html
  stock_split_picking_dimension/tests/__init__.py
  stock_split_picking_dimension/tests/test_stock_split_picking_dimension.py
  stock_split_picking_dimension/wizards/__init__.py
  stock_split_picking_dimension/wizards/stock_split_picking.py
  stock_split_picking_dimension/wizards/stock_split_picking.xml
Labels: bot is merging ⏳, no stale

#1829 [14.0][ADD] Add stock_split_picking_kit
  setup/stock_split_picking_kit/odoo/addons/stock_split_picking_kit
  setup/stock_split_picking_kit/setup.py
  stock_picking_restrict_cancel_printed/tests/test_stock_picking_restrict_cancel_printed.py
  stock_split_picking_kit/README.rst
  stock_split_picking_kit/__init__.py
  stock_split_picking_kit/__manifest__.py
  stock_split_picking_kit/readme/CONTRIBUTORS.rst
  stock_split_picking_kit/readme/DESCRIPTION.rst
  stock_split_picking_kit/static/description/index.html
  stock_split_picking_kit/tests/__init__.py
  stock_split_picking_kit/tests/test_stock_split_picking_kit.py
  stock_split_picking_kit/wizards/__init__.py
  stock_split_picking_kit/wizards/stock_split_picking.py
  stock_split_picking_kit/wizards/stock_split_picking.xml
Labels: approved, ready to merge, bot is merging ⏳

#2059 [14.0][FIX] delivery_procurement_group_carrier: Use new proc group for returns
  delivery_procurement_group_carrier/__init__.py
  delivery_procurement_group_carrier/tests/__init__.py
  delivery_procurement_group_carrier/tests/common.py
  delivery_procurement_group_carrier/tests/test_carrier.py
  delivery_procurement_group_carrier/tests/test_return.py
  delivery_procurement_group_carrier/wizards/__init__.py
  delivery_procurement_group_carrier/wizards/stock_return_picking.py
Labels: approved, ready to merge, bot is merging ⏳

#2066 [18.0][FIX] stock_picking_group_by_partner_by_carrier: properly drop group from domain
  stock_picking_group_by_partner_by_carrier/models/stock_move.py
Labels: bot is merging ⏳

#2068 [18.0][FWP][FIX] delivery_procurement_group_carrier: Use new proc group for returns
  delivery_procurement_group_carrier/__init__.py
  delivery_procurement_group_carrier/tests/__init__.py
  delivery_procurement_group_carrier/tests/common.py
  delivery_procurement_group_carrier/tests/test_carrier.py
  delivery_procurement_group_carrier/tests/test_return.py
  delivery_procurement_group_carrier/wizards/__init__.py
  delivery_procurement_group_carrier/wizards/stock_return_picking.py
Labels: bot is merging ⏳

#2062 [18.0] [REF] `stock_split_picking`: Split off moves in a new picking
  stock_split_picking/models/stock_picking.py
  stock_split_picking/tests/common.py
  stock_split_picking/tests/test_stock_split_picking.py
  stock_split_picking/wizards/stock_split_picking.py
  stock_split_picking/wizards/stock_split_picking.xml
Labels: bot is merging ⏳

#2076 [18.0][FIX] stock_move_line_qty_picked: Align move quantity with reserved
  stock_move_line_qty_picked/models/stock_move.py
  stock_move_line_qty_picked/models/stock_move_line.py
  stock_move_line_qty_picked/tests/test_stock_move_line_qty_picked.py
Labels: approved, bot is merging ⏳

#2069 [17.0][MIG] stock_receipt_lot_info: Migration to 17.0
  stock_receipt_lot_info/README.rst
  stock_receipt_lot_info/__init__.py
  stock_receipt_lot_info/__manifest__.py
  stock_receipt_lot_info/i18n/es.po
  stock_receipt_lot_info/i18n/it.po
  stock_receipt_lot_info/i18n/stock_account_product_run_fifo_hook.pot
  stock_receipt_lot_info/i18n/stock_receipt_lot_info.pot
  stock_receipt_lot_info/migrations/16.0.1.1.0/pre-migration.py
  stock_receipt_lot_info/model/__init__.py
  stock_receipt_lot_info/model/stock_move_line.py
  stock_receipt_lot_info/pyproject.toml
  stock_receipt_lot_info/readme/CONTRIBUTORS.md
  stock_receipt_lot_info/readme/DESCRIPTION.md
  stock_receipt_lot_info/readme/USAGE.md
  stock_receipt_lot_info/static/description/icon.png
  stock_receipt_lot_info/static/description/index.html
  stock_receipt_lot_info/tests/__init__.py
  stock_receipt_lot_info/tests/test_receipt_lot_info.py
  stock_receipt_lot_info/views/stock_move_line_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2014 [16.0][ADD] stock_move_not_merge_by_dest_moves
  setup/stock_move_not_merge_by_dest_moves/odoo/addons/stock_move_not_merge_by_dest_moves
  setup/stock_move_not_merge_by_dest_moves/setup.py
  stock_move_not_merge_by_dest_moves/README.rst
  stock_move_not_merge_by_dest_moves/__init__.py
  stock_move_not_merge_by_dest_moves/__manifest__.py
  stock_move_not_merge_by_dest_moves/models/__init__.py
  stock_move_not_merge_by_dest_moves/models/stock_move.py
  stock_move_not_merge_by_dest_moves/readme/CONTEXT.md
  stock_move_not_merge_by_dest_moves/readme/CONTRIBUTORS.md
  stock_move_not_merge_by_dest_moves/readme/CREDITS.md
  stock_move_not_merge_by_dest_moves/readme/DESCRIPTION.md
  stock_move_not_merge_by_dest_moves/readme/ROADMAP.md
  stock_move_not_merge_by_dest_moves/readme/USAGE.md
  stock_move_not_merge_by_dest_moves/static/description/icon.png
  stock_move_not_merge_by_dest_moves/static/description/index.html
  stock_move_not_merge_by_dest_moves/tests/__init__.py
  stock_move_not_merge_by_dest_moves/tests/test_stock_move.py
Labels: needs review, bot is merging ⏳

#1979 [18.0][MIG] stock_checkout_sync
  stock_checkout_sync/README.rst
  stock_checkout_sync/__init__.py
  stock_checkout_sync/__manifest__.py
  stock_checkout_sync/i18n/es_AR.po
  stock_checkout_sync/i18n/it.po
  stock_checkout_sync/i18n/stock_checkout_sync.pot
  stock_checkout_sync/models/__init__.py
  stock_checkout_sync/models/stock_move.py
  stock_checkout_sync/models/stock_picking.py
  stock_checkout_sync/models/stock_picking_type.py
  stock_checkout_sync/pyproject.toml
  stock_checkout_sync/readme/CONFIGURE.md
  stock_checkout_sync/readme/CONTRIBUTORS.md
  stock_checkout_sync/readme/CREDITS.md
  stock_checkout_sync/readme/DESCRIPTION.md
  stock_checkout_sync/security/ir.model.access.csv
  stock_checkout_sync/static/description/icon.png
  stock_checkout_sync/static/description/index.html
  stock_checkout_sync/static/description/sync-assistant.png
  stock_checkout_sync/tests/__init__.py
  stock_checkout_sync/tests/common.py
  stock_checkout_sync/tests/test_checkout_sync.py
  stock_checkout_sync/views/stock_picking_type_views.xml
  stock_checkout_sync/views/stock_picking_views.xml
  stock_checkout_sync/wizards/__init__.py
  stock_checkout_sync/wizards/stock_move_checkout_sync.py
  stock_checkout_sync/wizards/stock_move_checkout_sync_views.xml
Labels: approved, migration, ready to merge, bot is merging ⏳

#2087 [18.0][MIG] stock_move_original_date: Migration to 18.0
  stock_move_original_date/README.rst
  stock_move_original_date/__init__.py
  stock_move_original_date/__manifest__.py
  stock_move_original_date/i18n/stock_move_original_date.pot
  stock_move_original_date/models/__init__.py
  stock_move_original_date/models/stock_move.py
  stock_move_original_date/models/stock_picking.py
  stock_move_original_date/pyproject.toml
  stock_move_original_date/readme/CONTRIBUTORS.md
  stock_move_original_date/readme/DESCRIPTION.md
  stock_move_original_date/readme/USAGE.md
  stock_move_original_date/static/description/icon.png
  stock_move_original_date/static/description/index.html
  stock_move_original_date/tests/__init__.py
  stock_move_original_date/tests/test_stock_move_original_date.py
  stock_move_original_date/views/stock_move_views.xml
  stock_move_original_date/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳
