Repository OCA/stock-logistics-workflow, pull requests merged in 2025-02, with the labels that each got.

#1851 [17.0] [MIG] stock_restrict_by_planned_consumed_date: Migration to 17.0
  stock_restrict_by_planned_consumed_date/README.rst
  stock_restrict_by_planned_consumed_date/__init__.py
  stock_restrict_by_planned_consumed_date/__manifest__.py
  stock_restrict_by_planned_consumed_date/i18n/fr.po
  stock_restrict_by_planned_consumed_date/i18n/stock_restrict_by_planned_consumed_date.pot
  stock_restrict_by_planned_consumed_date/models/__init__.py
  stock_restrict_by_planned_consumed_date/models/stock_move.py
  stock_restrict_by_planned_consumed_date/models/stock_quant.py
  stock_restrict_by_planned_consumed_date/pyproject.toml
  stock_restrict_by_planned_consumed_date/readme/CONTRIBUTORS.md
  stock_restrict_by_planned_consumed_date/readme/DESCRIPTION.md
  stock_restrict_by_planned_consumed_date/readme/ROADMAP.md
  stock_restrict_by_planned_consumed_date/static/description/index.html
  stock_restrict_by_planned_consumed_date/tests/__init__.py
  stock_restrict_by_planned_consumed_date/tests/test_stock_restrict_by_planned_consumed_date.py
Labels: approved, ready to merge, bot is merging ⏳

#1786 [18.0][MIG] stock_dangerous_goods: Migration to 18.0
  stock_dangerous_goods/README.rst
  stock_dangerous_goods/__init__.py
  stock_dangerous_goods/__manifest__.py
  stock_dangerous_goods/i18n/it.po
  stock_dangerous_goods/i18n/stock_dangerous_goods.pot
  stock_dangerous_goods/models/__init__.py
  stock_dangerous_goods/models/product_product.py
  stock_dangerous_goods/models/stock_move_line.py
  stock_dangerous_goods/models/stock_quant_package.py
  stock_dangerous_goods/pyproject.toml
  stock_dangerous_goods/readme/CONTRIBUTORS.md
  stock_dangerous_goods/readme/CREDITS.md
  stock_dangerous_goods/readme/DESCRIPTION.md
  stock_dangerous_goods/static/description/icon.png
  stock_dangerous_goods/static/description/index.html
  stock_dangerous_goods/tests/__init__.py
  stock_dangerous_goods/tests/test_has_lq_products.py
Labels: approved, bot is merging ⏳

#1810 [18.0][MIG] stock_picking_show_backorder: Migration to 18.0
  stock_picking_show_backorder/README.rst
  stock_picking_show_backorder/__init__.py
  stock_picking_show_backorder/__manifest__.py
  stock_picking_show_backorder/i18n/cs_CZ.po
  stock_picking_show_backorder/i18n/de.po
  stock_picking_show_backorder/i18n/es.po
  stock_picking_show_backorder/i18n/fr.po
  stock_picking_show_backorder/i18n/hr.po
  stock_picking_show_backorder/i18n/it.po
  stock_picking_show_backorder/i18n/nl_NL.po
  stock_picking_show_backorder/i18n/pt.po
  stock_picking_show_backorder/i18n/pt_BR.po
  stock_picking_show_backorder/i18n/sl.po
  stock_picking_show_backorder/i18n/stock_picking_show_backorder.pot
  stock_picking_show_backorder/models/__init__.py
  stock_picking_show_backorder/models/stock.py
  stock_picking_show_backorder/pyproject.toml
  stock_picking_show_backorder/readme/CONTRIBUTORS.md
  stock_picking_show_backorder/readme/DESCRIPTION.md
  stock_picking_show_backorder/readme/USAGE.md
  stock_picking_show_backorder/static/description/icon.png
  stock_picking_show_backorder/static/description/index.html
  stock_picking_show_backorder/tests/__init__.py
  stock_picking_show_backorder/tests/test_stock_picking_show_backorder.py
  stock_picking_show_backorder/views/stock_view.xml
Labels: approved, bot is merging ⏳

#1688 [16.0][FIX] stock_picking_invoice_link, ensure field product_uom_qty value was changed to raise exception
  stock_picking_invoice_link/models/stock_move.py
Labels: approved, bot is merging ⏳, stale

#1857 [MIG] stock_split_picking: Migration to version 18.0
  stock_split_picking/README.rst
  stock_split_picking/__init__.py
  stock_split_picking/__manifest__.py
  stock_split_picking/exceptions.py
  stock_split_picking/i18n/ar.po
  stock_split_picking/i18n/ca_ES.po
  stock_split_picking/i18n/de.po
  stock_split_picking/i18n/es.po
  stock_split_picking/i18n/es_MX.po
  stock_split_picking/i18n/fi.po
  stock_split_picking/i18n/fr.po
  stock_split_picking/i18n/hr.po
  stock_split_picking/i18n/it.po
  stock_split_picking/i18n/nl_NL.po
  stock_split_picking/i18n/pt.po
  stock_split_picking/i18n/pt_BR.po
  stock_split_picking/i18n/sl.po
  stock_split_picking/i18n/stock_split_picking.pot
  stock_split_picking/i18n/tr.po
  stock_split_picking/i18n/tr_TR.po
  stock_split_picking/i18n/zh_CN.po
  stock_split_picking/models/__init__.py
  stock_split_picking/models/stock_picking.py
  stock_split_picking/pyproject.toml
  stock_split_picking/readme/CONTRIBUTORS.md
  stock_split_picking/readme/DESCRIPTION.md
  stock_split_picking/readme/USAGE.md
  stock_split_picking/security/ir.model.access.csv
  stock_split_picking/static/description/icon.png
  stock_split_picking/static/description/index.html
  stock_split_picking/tests/__init__.py
  stock_split_picking/tests/common.py
  stock_split_picking/tests/test_stock_split_picking.py
  stock_split_picking/views/stock_partial_picking.xml
  stock_split_picking/wizards/__init__.py
  stock_split_picking/wizards/stock_split_picking.py
  stock_split_picking/wizards/stock_split_picking.xml
Labels: approved, ready to merge, bot is merging ⏳

#1865 [17.0][MIG] stock_picking_auto_create_lot_sequence
  stock_picking_auto_create_lot_sequence/README.rst
  stock_picking_auto_create_lot_sequence/__init__.py
  stock_picking_auto_create_lot_sequence/__manifest__.py
  stock_picking_auto_create_lot_sequence/i18n/it.po
  stock_picking_auto_create_lot_sequence/i18n/stock_picking_auto_create_lot_sequence.pot
  stock_picking_auto_create_lot_sequence/models/__init__.py
  stock_picking_auto_create_lot_sequence/models/stock_move_line.py
  stock_picking_auto_create_lot_sequence/pyproject.toml
  stock_picking_auto_create_lot_sequence/readme/DESCRIPTION.md
  stock_picking_auto_create_lot_sequence/static/description/icon.png
  stock_picking_auto_create_lot_sequence/static/description/index.html
  stock_picking_auto_create_lot_sequence/tests/__init__.py
  stock_picking_auto_create_lot_sequence/tests/test_stock_picking_auto_create_lot_sequence.py
Labels: needs review, migration, bot is merging ⏳

#1862 [FIX] stock_no_negative: use display_name instead of name_get because it is deprecated
  stock_no_negative/models/stock_quant.py
  stock_no_negative/tests/test_stock_no_negative.py
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#1809 [18.0][MIG] stock_picking_purchase_order_link: Migration to 18.0
  stock_picking_purchase_order_link/README.rst
  stock_picking_purchase_order_link/__init__.py
  stock_picking_purchase_order_link/__manifest__.py
  stock_picking_purchase_order_link/i18n/es.po
  stock_picking_purchase_order_link/i18n/fr.po
  stock_picking_purchase_order_link/i18n/it.po
  stock_picking_purchase_order_link/i18n/pt_BR.po
  stock_picking_purchase_order_link/i18n/stock_picking_purchase_order_link.pot
  stock_picking_purchase_order_link/pyproject.toml
  stock_picking_purchase_order_link/readme/CONTRIBUTORS.md
  stock_picking_purchase_order_link/readme/DESCRIPTION.md
  stock_picking_purchase_order_link/readme/USAGE.md
  stock_picking_purchase_order_link/static/description/icon.png
  stock_picking_purchase_order_link/static/description/index.html
  stock_picking_purchase_order_link/views/stock_picking_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1870 [FIX] stock_picking_batch_validate_confirm: avoid propagating context with defaults
  stock_picking_batch_validate_confirm/models/stock_picking_batch.py
  stock_picking_batch_validate_confirm/tests/test_batch_confirm.py
  stock_picking_batch_validate_confirm/wizards/stock_picking_batch_confirm.py
Labels: needs review, approved, bot is merging ⏳

#1805 [18.0][MIG] stock_picking_back2draft: Migration to 18.0
  stock_picking_back2draft/README.rst
  stock_picking_back2draft/__init__.py
  stock_picking_back2draft/__manifest__.py
  stock_picking_back2draft/i18n/ca.po
  stock_picking_back2draft/i18n/de.po
  stock_picking_back2draft/i18n/es.po
  stock_picking_back2draft/i18n/es_AR.po
  stock_picking_back2draft/i18n/es_MX.po
  stock_picking_back2draft/i18n/fi.po
  stock_picking_back2draft/i18n/fr.po
  stock_picking_back2draft/i18n/hr.po
  stock_picking_back2draft/i18n/it.po
  stock_picking_back2draft/i18n/pt.po
  stock_picking_back2draft/i18n/pt_BR.po
  stock_picking_back2draft/i18n/sl.po
  stock_picking_back2draft/i18n/stock_picking_back2draft.pot
  stock_picking_back2draft/i18n/tr.po
  stock_picking_back2draft/i18n/tr_TR.po
  stock_picking_back2draft/i18n/zh_CN.po
  stock_picking_back2draft/models/__init__.py
  stock_picking_back2draft/models/stock_move.py
  stock_picking_back2draft/models/stock_picking.py
  stock_picking_back2draft/pyproject.toml
  stock_picking_back2draft/readme/CONTRIBUTORS.md
  stock_picking_back2draft/readme/DESCRIPTION.md
  stock_picking_back2draft/readme/USAGE.md
  stock_picking_back2draft/static/description/icon.png
  stock_picking_back2draft/static/description/index.html
  stock_picking_back2draft/tests/__init__.py
  stock_picking_back2draft/tests/test_picking.py
  stock_picking_back2draft/views/picking_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1839 [18.0][MIG] stock_picking_partner_note: Migration to 18.0
  stock_picking_partner_note/README.rst
  stock_picking_partner_note/__init__.py
  stock_picking_partner_note/__manifest__.py
  stock_picking_partner_note/i18n/fr.po
  stock_picking_partner_note/i18n/it.po
  stock_picking_partner_note/i18n/stock_picking_partner_note.pot
  stock_picking_partner_note/models/__init__.py
  stock_picking_partner_note/models/res_company.py
  stock_picking_partner_note/models/res_config_settings.py
  stock_picking_partner_note/models/res_partner.py
  stock_picking_partner_note/models/stock_picking.py
  stock_picking_partner_note/models/stock_picking_note.py
  stock_picking_partner_note/models/stock_picking_note_type.py
  stock_picking_partner_note/models/stock_picking_type.py
  stock_picking_partner_note/pyproject.toml
  stock_picking_partner_note/readme/CONFIGURE.md
  stock_picking_partner_note/readme/CONTRIBUTORS.md
  stock_picking_partner_note/readme/DESCRIPTION.md
  stock_picking_partner_note/security/ir.model.access.csv
  stock_picking_partner_note/static/description/icon.png
  stock_picking_partner_note/static/description/index.html
  stock_picking_partner_note/tests/__init__.py
  stock_picking_partner_note/tests/test_stock_picking_partner_note.py
  stock_picking_partner_note/views/res_config_settings.xml
  stock_picking_partner_note/views/res_partner.xml
  stock_picking_partner_note/views/stock_picking_note.xml
  stock_picking_partner_note/views/stock_picking_note_type.xml
  stock_picking_partner_note/views/stock_picking_partner_note_menus.xml
  stock_picking_partner_note/views/stock_picking_type.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1880 [18.0][MIG] stock_restrict_lot
  stock_restrict_lot/README.rst
  stock_restrict_lot/__init__.py
  stock_restrict_lot/__manifest__.py
  stock_restrict_lot/i18n/es.po
  stock_restrict_lot/i18n/hr.po
  stock_restrict_lot/i18n/it.po
  stock_restrict_lot/i18n/stock_restrict_lot.pot
  stock_restrict_lot/models/__init__.py
  stock_restrict_lot/models/product_product.py
  stock_restrict_lot/models/stock_move.py
  stock_restrict_lot/models/stock_picking.py
  stock_restrict_lot/models/stock_rule.py
  stock_restrict_lot/pyproject.toml
  stock_restrict_lot/readme/CONTRIBUTORS.md
  stock_restrict_lot/readme/DESCRIPTION.md
  stock_restrict_lot/static/description/icon.png
  stock_restrict_lot/static/description/index.html
  stock_restrict_lot/tests/__init__.py
  stock_restrict_lot/tests/test_restrict_lot.py
  stock_restrict_lot/views/stock_move_views.xml
  stock_restrict_lot/views/stock_picking.xml
Labels: approved, ready to merge, bot is merging ⏳

#1887 [16.0][FIX] purchase_stock_picking_invoice_link: Fallback to load CoA
  purchase_stock_picking_invoice_link/tests/test_purchase_stock_picking_invoice_link.py
Labels: bot is merging ⏳
