Repository OCA/stock-logistics-workflow, pull requests merged in 2025-06, with the labels that each got.

#1509 [14.0][ADD] stock_restrict_by_planned_consumed_date
  setup/stock_restrict_by_planned_consumed_date/odoo/addons/stock_restrict_by_planned_consumed_date
  setup/stock_restrict_by_planned_consumed_date/setup.py
  stock_restrict_by_planned_consumed_date/README.rst
  stock_restrict_by_planned_consumed_date/__init__.py
  stock_restrict_by_planned_consumed_date/__manifest__.py
  stock_restrict_by_planned_consumed_date/i18n/fr.po
  stock_restrict_by_planned_consumed_date/i18n/stock_restrict_by_planned_consumed_date.pot
  stock_restrict_by_planned_consumed_date/models/__init__.py
  stock_restrict_by_planned_consumed_date/models/stock_move.py
  stock_restrict_by_planned_consumed_date/models/stock_quant.py
  stock_restrict_by_planned_consumed_date/readme/CONTRIBUTORS.rst
  stock_restrict_by_planned_consumed_date/readme/DESCRIPTION.rst
  stock_restrict_by_planned_consumed_date/readme/ROADMAP.rst
  stock_restrict_by_planned_consumed_date/static/description/index.html
  stock_restrict_by_planned_consumed_date/tests/__init__.py
  stock_restrict_by_planned_consumed_date/tests/test_stock_restrict_by_planned_consumed_date.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1965 [18.0] [MIG] procurement_auto_create_group_carrier: Migration to 18.0
  procurement_auto_create_group_carrier/README.rst
  procurement_auto_create_group_carrier/__init__.py
  procurement_auto_create_group_carrier/__manifest__.py
  procurement_auto_create_group_carrier/i18n/it.po
  procurement_auto_create_group_carrier/i18n/procurement_auto_create_group_carrier.pot
  procurement_auto_create_group_carrier/models/__init__.py
  procurement_auto_create_group_carrier/models/stock_rule.py
  procurement_auto_create_group_carrier/pyproject.toml
  procurement_auto_create_group_carrier/readme/CONTRIBUTORS.md
  procurement_auto_create_group_carrier/readme/CREDITS.md
  procurement_auto_create_group_carrier/readme/DESCRIPTION.md
  procurement_auto_create_group_carrier/static/description/icon.png
  procurement_auto_create_group_carrier/static/description/index.html
  procurement_auto_create_group_carrier/tests/__init__.py
  procurement_auto_create_group_carrier/tests/test_procurement_auto_create_group_carrier.py
Labels: approved, ready to merge, bot is merging ⏳

#1966 [18.0] [MIG] stock_move_source_relocate: Migration to 18.0
  stock_move_source_relocate/README.rst
  stock_move_source_relocate/__init__.py
  stock_move_source_relocate/__manifest__.py
  stock_move_source_relocate/i18n/es_AR.po
  stock_move_source_relocate/i18n/it.po
  stock_move_source_relocate/i18n/stock_move_source_relocate.pot
  stock_move_source_relocate/models/__init__.py
  stock_move_source_relocate/models/stock_move.py
  stock_move_source_relocate/models/stock_source_relocate.py
  stock_move_source_relocate/pyproject.toml
  stock_move_source_relocate/readme/CONFIGURE.md
  stock_move_source_relocate/readme/CONTRIBUTORS.md
  stock_move_source_relocate/readme/CREDITS.md
  stock_move_source_relocate/readme/DESCRIPTION.md
  stock_move_source_relocate/security/ir.model.access.csv
  stock_move_source_relocate/static/description/icon.png
  stock_move_source_relocate/static/description/index.html
  stock_move_source_relocate/tests/__init__.py
  stock_move_source_relocate/tests/common.py
  stock_move_source_relocate/tests/test_source_relocate.py
  stock_move_source_relocate/views/stock_source_relocate_views.xml
Labels: approved, bot is merging ⏳

#1590 [16.0][ADD] stock_picking_portal: add module
  setup/stock_picking_portal/odoo/addons/stock_picking_portal
  setup/stock_picking_portal/setup.py
  stock_picking_portal/README.rst
  stock_picking_portal/__init__.py
  stock_picking_portal/__manifest__.py
  stock_picking_portal/controllers/__init__.py
  stock_picking_portal/controllers/portal.py
  stock_picking_portal/data/demo.xml
  stock_picking_portal/models/__init__.py
  stock_picking_portal/models/res_config_settings.py
  stock_picking_portal/models/stock_picking.py
  stock_picking_portal/models/stock_picking_type.py
  stock_picking_portal/readme/CONFIGURE.rst
  stock_picking_portal/readme/CONTEXT.rst
  stock_picking_portal/readme/CONTRIBUTORS.rst
  stock_picking_portal/readme/DESCRIPTION.rst
  stock_picking_portal/readme/USAGE.rst
  stock_picking_portal/security/ir.model.access.csv
  stock_picking_portal/security/stock_picking_portal_rule.xml
  stock_picking_portal/static/description/icon.png
  stock_picking_portal/static/description/index.html
  stock_picking_portal/tests/__init__.py
  stock_picking_portal/tests/test_res_config_settings.py
  stock_picking_portal/tests/test_stock_picking_portal.py
  stock_picking_portal/tests/test_wizard.py
  stock_picking_portal/views/res_config_settings_view.xml
  stock_picking_portal/views/stock_picking_template.xml
  stock_picking_portal/wizards/__init__.py
  stock_picking_portal/wizards/picking_link_wizard.py
  stock_picking_portal/wizards/picking_link_wizard.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1947 [18.0][MIG] stock_picking_group_by_partner_by_carrier
  stock_picking_group_by_partner_by_carrier/README.rst
  stock_picking_group_by_partner_by_carrier/__init__.py
  stock_picking_group_by_partner_by_carrier/__manifest__.py
  stock_picking_group_by_partner_by_carrier/i18n/de.po
  stock_picking_group_by_partner_by_carrier/i18n/es.po
  stock_picking_group_by_partner_by_carrier/i18n/fr.po
  stock_picking_group_by_partner_by_carrier/i18n/it.po
  stock_picking_group_by_partner_by_carrier/i18n/stock_picking_group_by_partner_by_carrier.pot
  stock_picking_group_by_partner_by_carrier/models/__init__.py
  stock_picking_group_by_partner_by_carrier/models/procurement_group.py
  stock_picking_group_by_partner_by_carrier/models/res_partner.py
  stock_picking_group_by_partner_by_carrier/models/sale_order.py
  stock_picking_group_by_partner_by_carrier/models/sale_order_line.py
  stock_picking_group_by_partner_by_carrier/models/stock_move.py
  stock_picking_group_by_partner_by_carrier/models/stock_picking.py
  stock_picking_group_by_partner_by_carrier/models/stock_picking_type.py
  stock_picking_group_by_partner_by_carrier/models/stock_rule.py
  stock_picking_group_by_partner_by_carrier/models/stock_warehouse.py
  stock_picking_group_by_partner_by_carrier/pyproject.toml
  stock_picking_group_by_partner_by_carrier/readme/CONFIGURE.md
  stock_picking_group_by_partner_by_carrier/readme/CONTRIBUTORS.md
  stock_picking_group_by_partner_by_carrier/readme/CREDITS.md
  stock_picking_group_by_partner_by_carrier/readme/DESCRIPTION.md
  stock_picking_group_by_partner_by_carrier/readme/USAGE.md
  stock_picking_group_by_partner_by_carrier/report/__init__.py
  stock_picking_group_by_partner_by_carrier/report/report_delivery_slip.py
  stock_picking_group_by_partner_by_carrier/report/report_delivery_slip.xml
  stock_picking_group_by_partner_by_carrier/security/ir.model.access.csv
  stock_picking_group_by_partner_by_carrier/static/description/icon.png
  stock_picking_group_by_partner_by_carrier/static/description/index.html
  stock_picking_group_by_partner_by_carrier/static/src/scss/report_delivery_slip.scss
  stock_picking_group_by_partner_by_carrier/tests/__init__.py
  stock_picking_group_by_partner_by_carrier/tests/common.py
  stock_picking_group_by_partner_by_carrier/tests/test_grouping_disable_on_partner.py
  stock_picking_group_by_partner_by_carrier/tests/test_grouping_pull_rules.py
  stock_picking_group_by_partner_by_carrier/tests/test_grouping_push_rules.py
  stock_picking_group_by_partner_by_carrier/tests/test_merge_wizard.py
  stock_picking_group_by_partner_by_carrier/tests/test_report.py
  stock_picking_group_by_partner_by_carrier/views/res_partner.xml
  stock_picking_group_by_partner_by_carrier/views/stock_picking_type.xml
  stock_picking_group_by_partner_by_carrier/views/stock_warehouse.xml
  stock_picking_group_by_partner_by_carrier/wizards/__init__.py
  stock_picking_group_by_partner_by_carrier/wizards/stock_picking_merge_wiz.py
  stock_picking_group_by_partner_by_carrier/wizards/stock_picking_merge_wiz.xml
  stock_picking_group_by_partner_by_carrier/wizards/stock_picking_merge_wiz_info_template.xml
Labels: approved, ready to merge, bot is merging ⏳

#1552 [17.0] [MIG] stock_picking_line_sequence: Migration to V17
  stock_picking_line_sequence/README.rst
  stock_picking_line_sequence/__init__.py
  stock_picking_line_sequence/__manifest__.py
  stock_picking_line_sequence/i18n/ca.po
  stock_picking_line_sequence/i18n/de.po
  stock_picking_line_sequence/i18n/es.po
  stock_picking_line_sequence/i18n/es_MX.po
  stock_picking_line_sequence/i18n/fi.po
  stock_picking_line_sequence/i18n/fr.po
  stock_picking_line_sequence/i18n/hr.po
  stock_picking_line_sequence/i18n/it.po
  stock_picking_line_sequence/i18n/nl_NL.po
  stock_picking_line_sequence/i18n/pt.po
  stock_picking_line_sequence/i18n/pt_BR.po
  stock_picking_line_sequence/i18n/sl.po
  stock_picking_line_sequence/i18n/stock_picking_line_sequence.pot
  stock_picking_line_sequence/i18n/tr.po
  stock_picking_line_sequence/i18n/tr_TR.po
  stock_picking_line_sequence/init_hooks.py
  stock_picking_line_sequence/models/__init__.py
  stock_picking_line_sequence/models/stock.py
  stock_picking_line_sequence/pyproject.toml
  stock_picking_line_sequence/readme/CONTRIBUTORS.md
  stock_picking_line_sequence/readme/DESCRIPTION.md
  stock_picking_line_sequence/readme/USAGE.md
  stock_picking_line_sequence/report/report_deliveryslip.xml
  stock_picking_line_sequence/static/description/icon.png
  stock_picking_line_sequence/static/description/index.html
  stock_picking_line_sequence/tests/__init__.py
  stock_picking_line_sequence/tests/test_move_lines_sequence.py
  stock_picking_line_sequence/views/stock_view.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1959 [18.0] [MIG] stock_picking_group_by_partner_by_carrier_by_date: Migration to 18.0
  stock_picking_group_by_partner_by_carrier_by_date/README.rst
  stock_picking_group_by_partner_by_carrier_by_date/__init__.py
  stock_picking_group_by_partner_by_carrier_by_date/__manifest__.py
  stock_picking_group_by_partner_by_carrier_by_date/i18n/fr.po
  stock_picking_group_by_partner_by_carrier_by_date/i18n/it.po
  stock_picking_group_by_partner_by_carrier_by_date/i18n/stock_picking_group_by_partner_by_carrier_by_date.pot
  stock_picking_group_by_partner_by_carrier_by_date/models/__init__.py
  stock_picking_group_by_partner_by_carrier_by_date/models/stock_move.py
  stock_picking_group_by_partner_by_carrier_by_date/models/stock_picking_type.py
  stock_picking_group_by_partner_by_carrier_by_date/pyproject.toml
  stock_picking_group_by_partner_by_carrier_by_date/readme/CONTRIBUTORS.md
  stock_picking_group_by_partner_by_carrier_by_date/readme/CREDITS.md
  stock_picking_group_by_partner_by_carrier_by_date/readme/DESCRIPTION.md
  stock_picking_group_by_partner_by_carrier_by_date/readme/USAGE.md
  stock_picking_group_by_partner_by_carrier_by_date/static/description/icon.png
  stock_picking_group_by_partner_by_carrier_by_date/static/description/index.html
  stock_picking_group_by_partner_by_carrier_by_date/tests/__init__.py
  stock_picking_group_by_partner_by_carrier_by_date/tests/test_grouping_by_date.py
  stock_picking_group_by_partner_by_carrier_by_date/views/stock_picking_type.xml
Labels: approved, ready to merge, bot is merging ⏳

#1985 [18.0][FWD-PORT] delivery_procurement_group_carrier: Carrier update
  delivery_procurement_group_carrier/__manifest__.py
  delivery_procurement_group_carrier/models/__init__.py
  delivery_procurement_group_carrier/models/stock_picking.py
  delivery_procurement_group_carrier/tests/test_carrier.py
Labels: approved, bot is merging ⏳

#1990 [IMP] stock_picking_start: Avoid rewriting started if not modified
  stock_picking_start/models/stock_picking.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1992 [18.0][FIX] stock_picking_group_by_partner_by_carrier: improperly ported method _create_backorder on stock.picking
  stock_picking_group_by_partner_by_carrier/models/stock_picking.py
Labels: bot is merging ⏳

#1987 [18.0][IMP] stock_picking_group_by_partner_by_carrier: allow to group when policy is one
  stock_picking_group_by_partner_by_carrier/models/stock_move.py
  stock_picking_group_by_partner_by_carrier/models/stock_picking.py
  stock_picking_group_by_partner_by_carrier/models/stock_picking_type.py
  stock_picking_group_by_partner_by_carrier/models/stock_warehouse.py
  stock_picking_group_by_partner_by_carrier/tests/test_grouping_pull_rules.py
  stock_picking_group_by_partner_by_carrier/tests/test_grouping_push_rules.py
  stock_picking_group_by_partner_by_carrier/views/stock_picking_type.xml
  stock_picking_group_by_partner_by_carrier/views/stock_warehouse.xml
Labels: approved, bot is merging ⏳

#1952 [18.0][MIG] stock_dynamic_routing: Migration to 18.0
  .oca/oca-port/blacklist/stock_dynamic_routing.json
  stock_dynamic_routing/README.rst
  stock_dynamic_routing/__init__.py
  stock_dynamic_routing/__manifest__.py
  stock_dynamic_routing/demo/stock_location_demo.xml
  stock_dynamic_routing/demo/stock_picking_type_demo.xml
  stock_dynamic_routing/demo/stock_routing_demo.xml
  stock_dynamic_routing/i18n/es.po
  stock_dynamic_routing/i18n/es_AR.po
  stock_dynamic_routing/i18n/it.po
  stock_dynamic_routing/i18n/stock_dynamic_routing.pot
  stock_dynamic_routing/models/__init__.py
  stock_dynamic_routing/models/stock_location.py
  stock_dynamic_routing/models/stock_move.py
  stock_dynamic_routing/models/stock_picking.py
  stock_dynamic_routing/models/stock_routing.py
  stock_dynamic_routing/models/stock_routing_rule.py
  stock_dynamic_routing/pyproject.toml
  stock_dynamic_routing/readme/CONFIGURE.rst
  stock_dynamic_routing/readme/CONTRIBUTORS.rst
  stock_dynamic_routing/readme/DESCRIPTION.rst
  stock_dynamic_routing/readme/USAGE.rst
  stock_dynamic_routing/security/ir.model.access.csv
  stock_dynamic_routing/static/description/icon.png
  stock_dynamic_routing/static/description/index.html
  stock_dynamic_routing/tests/__init__.py
  stock_dynamic_routing/tests/test_routing_pull.py
  stock_dynamic_routing/tests/test_routing_push.py
  stock_dynamic_routing/tests/test_routing_rule.py
  stock_dynamic_routing/views/stock_routing_views.xml
Labels: approved, migration, ready to merge, bot is merging ⏳

#1978 [18.0][MIG] stock_picking_batch_print_invoices
  stock_picking_batch_print_invoices/README.rst
  stock_picking_batch_print_invoices/__init__.py
  stock_picking_batch_print_invoices/__manifest__.py
  stock_picking_batch_print_invoices/i18n/es.po
  stock_picking_batch_print_invoices/i18n/it.po
  stock_picking_batch_print_invoices/i18n/stock_picking_batch_print_invoices.pot
  stock_picking_batch_print_invoices/models/__init__.py
  stock_picking_batch_print_invoices/models/stock_picking_batch.py
  stock_picking_batch_print_invoices/models/stock_picking_type.py
  stock_picking_batch_print_invoices/pyproject.toml
  stock_picking_batch_print_invoices/readme/CONFIGURE.md
  stock_picking_batch_print_invoices/readme/CONTEXT.md
  stock_picking_batch_print_invoices/readme/CONTRIBUTORS.md
  stock_picking_batch_print_invoices/readme/DESCRIPTION.md
  stock_picking_batch_print_invoices/readme/USAGE.md
  stock_picking_batch_print_invoices/static/description/icon.png
  stock_picking_batch_print_invoices/static/description/index.html
  stock_picking_batch_print_invoices/tests/__init__.py
  stock_picking_batch_print_invoices/tests/test_batch_print_invoices.py
  stock_picking_batch_print_invoices/views/report_picking_batch_print_invoices.xml
  stock_picking_batch_print_invoices/views/stock_picking_batch_views.xml
  stock_picking_batch_print_invoices/views/stock_picking_type_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1989 [18.0][MIG] stock_move_source_relocate_dynamic_routing
  stock_move_source_relocate_dynamic_routing/README.rst
  stock_move_source_relocate_dynamic_routing/__init__.py
  stock_move_source_relocate_dynamic_routing/__manifest__.py
  stock_move_source_relocate_dynamic_routing/i18n/es_AR.po
  stock_move_source_relocate_dynamic_routing/i18n/it.po
  stock_move_source_relocate_dynamic_routing/i18n/stock_move_source_relocate_dynamic_routing.pot
  stock_move_source_relocate_dynamic_routing/models/__init__.py
  stock_move_source_relocate_dynamic_routing/models/stock_move.py
  stock_move_source_relocate_dynamic_routing/models/stock_routing.py
  stock_move_source_relocate_dynamic_routing/models/stock_source_relocate.py
  stock_move_source_relocate_dynamic_routing/pyproject.toml
  stock_move_source_relocate_dynamic_routing/readme/CONTRIBUTORS.rst
  stock_move_source_relocate_dynamic_routing/readme/DESCRIPTION.rst
  stock_move_source_relocate_dynamic_routing/static/description/icon.png
  stock_move_source_relocate_dynamic_routing/static/description/index.html
  stock_move_source_relocate_dynamic_routing/tests/__init__.py
  stock_move_source_relocate_dynamic_routing/tests/test_dynamic_destination.py
  stock_move_source_relocate_dynamic_routing/tests/test_dynamic_relocate.py
  stock_move_source_relocate_dynamic_routing/views/stock_routing_views.xml
  stock_move_source_relocate_dynamic_routing/views/stock_source_relocate_views.xml
Labels: approved, migration, bot is merging ⏳

#2002 [17.0][FIX] stock_picking_group_by_base: Uninstall hook
  stock_picking_group_by_base/__init__.py
  stock_picking_group_by_base/hooks.py
Labels: enhancement, approved, merged 🎉

#1843 [15.0][FIX] stock_return_request: Cache miss error when access to qty_returnable computed field on stock move
  stock_return_request/models/stock_move.py
Labels: approved, bot is merging ⏳, stale
