Repository OCA/stock-logistics-workflow, pull requests merged in 2025-04, with the labels that each got.

#1905 [ADD] [16.0] stock_move_line_dates
  setup/stock_move_line_dates/odoo/addons/stock_move_line_dates
  setup/stock_move_line_dates/setup.py
  stock_move_line_dates/README.rst
  stock_move_line_dates/__init__.py
  stock_move_line_dates/__manifest__.py
  stock_move_line_dates/i18n/es.po
  stock_move_line_dates/i18n/stock_move_line_dates.pot
  stock_move_line_dates/models/__init__.py
  stock_move_line_dates/models/stock_move_line.py
  stock_move_line_dates/readme/CONTEXT.md
  stock_move_line_dates/readme/CONTRIBUTORS.md
  stock_move_line_dates/readme/DESCRIPTION.md
  stock_move_line_dates/readme/USAGE.md
  stock_move_line_dates/static/description/icon.png
  stock_move_line_dates/static/description/index.html
  stock_move_line_dates/views/stock_move_line_view.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1903 [IMP] [16.0] stock_picking_auto_create_lot: Make it compatible with Stock Picking Batches
  stock_picking_auto_create_lot/README.rst
  stock_picking_auto_create_lot/__manifest__.py
  stock_picking_auto_create_lot/models/__init__.py
  stock_picking_auto_create_lot/models/product_category.py
  stock_picking_auto_create_lot/models/stock_move.py
  stock_picking_auto_create_lot/models/stock_picking.py
  stock_picking_auto_create_lot/readme/CONFIGURE.rst
  stock_picking_auto_create_lot/readme/CONTRIBUTORS.rst
  stock_picking_auto_create_lot/readme/DESCRIPTION.rst
  stock_picking_auto_create_lot/readme/USAGE.rst
  stock_picking_auto_create_lot/static/description/index.html
  stock_picking_auto_create_lot/tests/common.py
  stock_picking_auto_create_lot/tests/test_stock_picking_auto_create_lot.py
  stock_picking_auto_create_lot/views/product_category_views.xml
  stock_picking_auto_create_lot/views/product_views.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1818 [18.0][MIG] stock_picking_progress: Migration to 18.0
  requirements.txt
  stock_picking_progress/README.rst
  stock_picking_progress/__init__.py
  stock_picking_progress/__manifest__.py
  stock_picking_progress/hooks.py
  stock_picking_progress/i18n/it.po
  stock_picking_progress/i18n/stock_picking_progress.pot
  stock_picking_progress/models/__init__.py
  stock_picking_progress/models/stock_move.py
  stock_picking_progress/models/stock_picking.py
  stock_picking_progress/pyproject.toml
  stock_picking_progress/readme/CONTRIBUTORS.md
  stock_picking_progress/readme/CREDITS.md
  stock_picking_progress/readme/DESCRIPTION.md
  stock_picking_progress/static/description/icon.png
  stock_picking_progress/static/description/index.html
  stock_picking_progress/tests/__init__.py
  stock_picking_progress/tests/test_progress.py
  stock_picking_progress/views/stock_picking.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1917 [17.0][MIG] product_cost_price_avco_sync: Migration to 17.0
  product_cost_price_avco_sync/README.rst
  product_cost_price_avco_sync/__init__.py
  product_cost_price_avco_sync/__manifest__.py
  product_cost_price_avco_sync/i18n/es.po
  product_cost_price_avco_sync/i18n/it.po
  product_cost_price_avco_sync/i18n/product_cost_price_avco_sync.pot
  product_cost_price_avco_sync/i18n/pt_BR.po
  product_cost_price_avco_sync/models/__init__.py
  product_cost_price_avco_sync/models/product_product.py
  product_cost_price_avco_sync/models/stock_move_line.py
  product_cost_price_avco_sync/models/stock_picking.py
  product_cost_price_avco_sync/models/stock_valuation_layer.py
  product_cost_price_avco_sync/pyproject.toml
  product_cost_price_avco_sync/readme/CONTRIBUTORS.md
  product_cost_price_avco_sync/readme/DESCRIPTION.md
  product_cost_price_avco_sync/static/description/icon.png
  product_cost_price_avco_sync/static/description/index.html
  product_cost_price_avco_sync/tests/__init__.py
  product_cost_price_avco_sync/tests/test_product_cost_price_avco_sync.py
Labels: approved, bot is merging ⏳

#1918 [18.0][MIG] product_cost_price_avco_sync: Migration to 18.0
  product_cost_price_avco_sync/README.rst
  product_cost_price_avco_sync/__init__.py
  product_cost_price_avco_sync/__manifest__.py
  product_cost_price_avco_sync/i18n/es.po
  product_cost_price_avco_sync/i18n/it.po
  product_cost_price_avco_sync/i18n/product_cost_price_avco_sync.pot
  product_cost_price_avco_sync/i18n/pt_BR.po
  product_cost_price_avco_sync/models/__init__.py
  product_cost_price_avco_sync/models/product_product.py
  product_cost_price_avco_sync/models/stock_move_line.py
  product_cost_price_avco_sync/models/stock_picking.py
  product_cost_price_avco_sync/models/stock_valuation_layer.py
  product_cost_price_avco_sync/pyproject.toml
  product_cost_price_avco_sync/readme/CONTRIBUTORS.md
  product_cost_price_avco_sync/readme/DESCRIPTION.md
  product_cost_price_avco_sync/static/description/icon.png
  product_cost_price_avco_sync/static/description/index.html
  product_cost_price_avco_sync/tests/__init__.py
  product_cost_price_avco_sync/tests/test_product_cost_price_avco_sync.py
Labels: approved, bot is merging ⏳

#1915 [18.0][ADD] stock_move_quantity_product_uom
  stock_move_quantity_product_uom/README.rst
  stock_move_quantity_product_uom/__init__.py
  stock_move_quantity_product_uom/__manifest__.py
  stock_move_quantity_product_uom/models/__init__.py
  stock_move_quantity_product_uom/models/stock_move.py
  stock_move_quantity_product_uom/pyproject.toml
  stock_move_quantity_product_uom/readme/CONTRIBUTORS.md
  stock_move_quantity_product_uom/readme/DESCRIPTION.md
  stock_move_quantity_product_uom/static/description/icon.png
  stock_move_quantity_product_uom/static/description/index.html
  stock_move_quantity_product_uom/tests/__init__.py
  stock_move_quantity_product_uom/tests/test_stock_move_quantity_product_uom.py
Labels: bot is merging ⏳

#1925 [18.0][IMP] stock_move_quantity_product_uom: bump development_status
  stock_move_quantity_product_uom/__manifest__.py
Labels: approved, bot is merging ⏳

#1906 [14.0][IMP] delivery_procurement_group_carrier: Align Carrier once per group
  delivery_procurement_group_carrier/models/stock_picking.py
  delivery_procurement_group_carrier/tests/test_carrier.py
Labels: enhancement, bot is merging ⏳

#1914 [17.0][ADD] stock_product_security: New module stock_product_security
  stock_product_security/README.rst
  stock_product_security/__init__.py
  stock_product_security/__manifest__.py
  stock_product_security/i18n/ca.po
  stock_product_security/i18n/es.po
  stock_product_security/pyproject.toml
  stock_product_security/readme/CONFIGURE.md
  stock_product_security/readme/CONTRIBUTORS.md
  stock_product_security/readme/DESCRIPTION.md
  stock_product_security/security/ir.model.access.csv
  stock_product_security/security/stock_security.xml
  stock_product_security/static/description/icon.png
  stock_product_security/static/description/icon.svg
  stock_product_security/static/description/index.html
Labels: needs review, approved, bot is merging ⏳

#1929 [16.0][FIX] stock_move_line_change_lot: Use id with browse
  stock_move_line_change_lot/models/stock_move_line.py
Labels: approved, bot is merging ⏳

#1924 [16.0][FW PORT]delivery_procurement_group_carrier: Fix carrier update
  delivery_procurement_group_carrier/models/__init__.py
  delivery_procurement_group_carrier/models/stock_picking.py
  delivery_procurement_group_carrier/tests/test_carrier.py
Labels: bot is merging ⏳

#1842 [17.0] [MIG] stock_putaway_hook: Migration to 17.0
  stock_putaway_hook/README.rst
  stock_putaway_hook/__init__.py
  stock_putaway_hook/__manifest__.py
  stock_putaway_hook/i18n/it.po
  stock_putaway_hook/i18n/stock_putaway_hook.pot
  stock_putaway_hook/models/__init__.py
  stock_putaway_hook/models/stock_location.py
  stock_putaway_hook/pyproject.toml
  stock_putaway_hook/readme/CONTRIBUTORS.md
  stock_putaway_hook/readme/DESCRIPTION.md
  stock_putaway_hook/readme/USAGE.md
  stock_putaway_hook/static/description/icon.png
  stock_putaway_hook/static/description/index.html
  stock_putaway_hook/tests/__init__.py
  stock_putaway_hook/tests/common.py
  stock_putaway_hook/tests/model.py
  stock_putaway_hook/tests/test_putaway_hook.py
  test-requirements.txt
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳
