Repository OCA/stock-logistics-workflow, pull requests merged in 2025-07, with the labels that each got.

#1808 [18.0][MIG] stock_picking_origin_reference_purchase: Migration to 18.0
  stock_picking_origin_reference_purchase/README.rst
  stock_picking_origin_reference_purchase/__init__.py
  stock_picking_origin_reference_purchase/__manifest__.py
  stock_picking_origin_reference_purchase/i18n/it.po
  stock_picking_origin_reference_purchase/i18n/stock_picking_origin_reference_purchase.pot
  stock_picking_origin_reference_purchase/models/__init__.py
  stock_picking_origin_reference_purchase/models/stock_picking.py
  stock_picking_origin_reference_purchase/pyproject.toml
  stock_picking_origin_reference_purchase/readme/CONTRIBUTORS.md
  stock_picking_origin_reference_purchase/readme/DESCRIPTION.md
  stock_picking_origin_reference_purchase/static/description/icon.png
  stock_picking_origin_reference_purchase/static/description/index.html
  stock_picking_origin_reference_purchase/tests/__init__.py
  stock_picking_origin_reference_purchase/tests/test_stock_picking_origin_reference_purchase.py
Labels: approved, ready to merge, bot is merging ⏳

#1923 [16.0][IMP] stock_picking_auto_create_lot: lot on print
  stock_picking_auto_create_lot/README.rst
  stock_picking_auto_create_lot/models/__init__.py
  stock_picking_auto_create_lot/models/ir_actions_report.py
  stock_picking_auto_create_lot/readme/CONFIGURE.rst
  stock_picking_auto_create_lot/static/description/index.html
  stock_picking_auto_create_lot/tests/test_stock_picking_auto_create_lot.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1964 [18.0][MIG] stock_move_actual_date: Migration to 18.0
  stock_move_actual_date/README.rst
  stock_move_actual_date/__init__.py
  stock_move_actual_date/__manifest__.py
  stock_move_actual_date/hooks.py
  stock_move_actual_date/i18n/it.po
  stock_move_actual_date/i18n/ja.po
  stock_move_actual_date/i18n/stock_move_actual_date.pot
  stock_move_actual_date/models/__init__.py
  stock_move_actual_date/models/account_move.py
  stock_move_actual_date/models/res_currency.py
  stock_move_actual_date/models/stock_actual_date_mixin.py
  stock_move_actual_date/models/stock_move.py
  stock_move_actual_date/models/stock_move_line.py
  stock_move_actual_date/models/stock_picking.py
  stock_move_actual_date/models/stock_scrap.py
  stock_move_actual_date/models/stock_valuation_layer.py
  stock_move_actual_date/pyproject.toml
  stock_move_actual_date/readme/CONFIGURE.md
  stock_move_actual_date/readme/CONTRIBUTORS.md
  stock_move_actual_date/readme/DESCRIPTION.md
  stock_move_actual_date/readme/ROADMAP.md
  stock_move_actual_date/readme/USAGE.md
  stock_move_actual_date/security/stock_move_actual_date_security.xml
  stock_move_actual_date/static/description/icon.png
  stock_move_actual_date/static/description/index.html
  stock_move_actual_date/tests/__init__.py
  stock_move_actual_date/tests/test_stock_move_actual_date.py
  stock_move_actual_date/views/stock_move_line_views.xml
  stock_move_actual_date/views/stock_move_views.xml
  stock_move_actual_date/views/stock_picking_views.xml
  stock_move_actual_date/views/stock_scrap_views.xml
  stock_move_actual_date/views/stock_valuation_layer_views.xml
  stock_move_actual_date/wizard/__init__.py
  stock_move_actual_date/wizard/stock_quantity_history.py
  stock_move_actual_date/wizard/stock_quantity_history.xml
Labels: approved, ready to merge, bot is merging ⏳

#1984 [18.0][MIG] product_customerinfo_picking: Migration to 18.0
  product_customerinfo_picking/README.rst
  product_customerinfo_picking/__init__.py
  product_customerinfo_picking/__manifest__.py
  product_customerinfo_picking/i18n/de.po
  product_customerinfo_picking/i18n/it.po
  product_customerinfo_picking/i18n/product_supplierinfo_for_customer_picking.pot
  product_customerinfo_picking/i18n/pt_BR.po
  product_customerinfo_picking/models/__init__.py
  product_customerinfo_picking/models/stock_move.py
  product_customerinfo_picking/pyproject.toml
  product_customerinfo_picking/readme/CONTRIBUTORS.md
  product_customerinfo_picking/readme/DESCRIPTION.md
  product_customerinfo_picking/static/description/icon.png
  product_customerinfo_picking/static/description/index.html
  product_customerinfo_picking/tests/__init__.py
  product_customerinfo_picking/tests/test_product_customerinfo_picking.py
  product_customerinfo_picking/views/stock_picking_view.xml
Labels: approved, ready to merge, bot is merging ⏳, wrong repository

#2011 [17.0] [FW] [FIX] stock_picking_invoice_link: remove duplicated element in stock.move form view
  stock_picking_invoice_link/views/stock_view.xml
Labels: approved, bot is merging ⏳

#1983 [16.0][FIX] stock_move_actual_date: fix button invisible is not working
  stock_move_actual_date/wizard/stock_quantity_history.xml
Labels: approved, ready to merge, bot is merging ⏳

#2017 [17.0] [FIX] stock_picking_invoice_link: add colspan attribute to invoice_line_ids field in stock.move form
  stock_picking_invoice_link/views/stock_view.xml
Labels: bot is merging ⏳

#2018 [18.0] [FW] [FIX] stock_picking_invoice_link: fix stock.move form view invoice_line_ids field rendering
  stock_picking_invoice_link/views/stock_view.xml
Labels: approved, bot is merging ⏳

#2013 [FIX] stock_picking_invoice_link: correct invoice_line_ids field in stock.move form view
  stock_picking_invoice_link/views/stock_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2019 [18.0][FIX] picking_group_by_carrier_by_date: Use UTC as default tz
  stock_picking_group_by_partner_by_carrier_by_date/models/stock_move.py
Labels: approved, merged 🎉

#2025 [18.0][FIX] stock_picking_group_by_partner_by_carrier: report
  stock_picking_group_by_partner_by_carrier/report/report_delivery_slip.py
  stock_picking_group_by_partner_by_carrier/tests/test_report.py
Labels: bug, approved, bot is merging ⏳

#2012 [18.0][MIG] stock_dynamic_routing_reserve_rule
  stock_dynamic_routing_reserve_rule/README.rst
  stock_dynamic_routing_reserve_rule/__init__.py
  stock_dynamic_routing_reserve_rule/__manifest__.py
  stock_dynamic_routing_reserve_rule/i18n/es_AR.po
  stock_dynamic_routing_reserve_rule/i18n/it.po
  stock_dynamic_routing_reserve_rule/i18n/stock_dynamic_routing_reserve_rule.pot
  stock_dynamic_routing_reserve_rule/models/__init__.py
  stock_dynamic_routing_reserve_rule/models/stock_routing.py
  stock_dynamic_routing_reserve_rule/pyproject.toml
  stock_dynamic_routing_reserve_rule/readme/DESCRIPTION.md
  stock_dynamic_routing_reserve_rule/static/description/icon.png
  stock_dynamic_routing_reserve_rule/static/description/index.html
  stock_dynamic_routing_reserve_rule/templates/stock_routing_templates.xml
  stock_dynamic_routing_reserve_rule/views/stock_routing_views.xml
Labels: approved, migration, bot is merging ⏳

#2028 [18.0][MIG] sale_line_returned_qty: Migration to 18.0
  sale_line_returned_qty/README.rst
  sale_line_returned_qty/__init__.py
  sale_line_returned_qty/__manifest__.py
  sale_line_returned_qty/i18n/es.po
  sale_line_returned_qty/i18n/it.po
  sale_line_returned_qty/i18n/sale_line_returned_qty.pot
  sale_line_returned_qty/models/__init__.py
  sale_line_returned_qty/models/sale_order_line.py
  sale_line_returned_qty/pyproject.toml
  sale_line_returned_qty/readme/CONTRIBUTORS.md
  sale_line_returned_qty/readme/DESCRIPTION.md
  sale_line_returned_qty/static/description/icon.png
  sale_line_returned_qty/static/description/index.html
  sale_line_returned_qty/tests/__init__.py
  sale_line_returned_qty/tests/test_sale_line_returned_qty.py
  sale_line_returned_qty/views/sale_order_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2051 [18.0] stock_move_line_qty_picked: set dev status to Beta
  stock_move_line_qty_picked/__manifest__.py
Labels: bot is merging ⏳
