Repository OCA/stock-logistics-workflow, pull requests merged in 2025-09, with the labels that each got.

#1389 [ADD] stock_picking_batch_start
  setup/stock_picking_batch_start/odoo/addons/stock_picking_batch_start
  setup/stock_picking_batch_start/setup.py
  stock_picking_batch_start/README.rst
  stock_picking_batch_start/__init__.py
  stock_picking_batch_start/__manifest__.py
  stock_picking_batch_start/models/__init__.py
  stock_picking_batch_start/models/stock_picking.py
  stock_picking_batch_start/models/stock_picking_batch.py
  stock_picking_batch_start/readme/CONTRIBUTORS.rst
  stock_picking_batch_start/readme/DESCRIPTION.rst
  stock_picking_batch_start/static/description/index.html
  stock_picking_batch_start/tests/__init__.py
  stock_picking_batch_start/tests/test_stock_picking_batch_start.py
  stock_picking_batch_start/views/stock_picking_batch.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#2098 [ADD] stock_picking_batch_planner
  stock_picking_batch_planner/README.rst
  stock_picking_batch_planner/__init__.py
  stock_picking_batch_planner/__manifest__.py
  stock_picking_batch_planner/hooks.py
  stock_picking_batch_planner/i18n/es.po
  stock_picking_batch_planner/i18n/stock_picking_batch_planner.pot
  stock_picking_batch_planner/models/__init__.py
  stock_picking_batch_planner/models/stock_picking_batch.py
  stock_picking_batch_planner/models/stock_picking_type.py
  stock_picking_batch_planner/pyproject.toml
  stock_picking_batch_planner/readme/CONFIGURE.md
  stock_picking_batch_planner/readme/CONTEXT.md
  stock_picking_batch_planner/readme/CONTRIBUTORS.md
  stock_picking_batch_planner/readme/DESCRIPTION.md
  stock_picking_batch_planner/readme/USAGE.md
  stock_picking_batch_planner/static/description/icon.png
  stock_picking_batch_planner/static/description/index.html
  stock_picking_batch_planner/tests/__init__.py
  stock_picking_batch_planner/tests/test_stock_picking_batch_planner.py
  stock_picking_batch_planner/views/stock_picking_batch_views.xml
  stock_picking_batch_planner/views/stock_picking_type_views.xml
Labels: needs review, approved, bot is merging ⏳

#2112 [18.0][FIX] stock_picking_group_by_partner_by_carrier: assets not loaded
  stock_picking_group_by_partner_by_carrier/README.rst
  stock_picking_group_by_partner_by_carrier/__manifest__.py
  stock_picking_group_by_partner_by_carrier/static/description/index.html
Labels: approved, bot is merging ⏳
