Repository OCA/stock-logistics-workflow, pull requests merged in 2025-05, with the labels that each got.

#1823 [18.0][MIG] stock_landed_costs_priority: Migration to 18.0
  stock_landed_costs_priority/README.rst
  stock_landed_costs_priority/__init__.py
  stock_landed_costs_priority/__manifest__.py
  stock_landed_costs_priority/i18n/es.po
  stock_landed_costs_priority/i18n/stock_landed_costs_priority.pot
  stock_landed_costs_priority/models/__init__.py
  stock_landed_costs_priority/models/stock_landed_cost.py
  stock_landed_costs_priority/pyproject.toml
  stock_landed_costs_priority/readme/CONTRIBUTORS.md
  stock_landed_costs_priority/readme/DESCRIPTION.md
  stock_landed_costs_priority/static/description/icon.png
  stock_landed_costs_priority/static/description/index.html
  stock_landed_costs_priority/views/stock_landed_cost_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1772 [18.0][MIG] stock_picking_send_by_mail
  stock_picking_send_by_mail/README.rst
  stock_picking_send_by_mail/__init__.py
  stock_picking_send_by_mail/__manifest__.py
  stock_picking_send_by_mail/i18n/de.po
  stock_picking_send_by_mail/i18n/es.po
  stock_picking_send_by_mail/i18n/fr.po
  stock_picking_send_by_mail/i18n/it.po
  stock_picking_send_by_mail/i18n/pt.po
  stock_picking_send_by_mail/i18n/pt_BR.po
  stock_picking_send_by_mail/i18n/stock_picking_send_by_mail.pot
  stock_picking_send_by_mail/models/__init__.py
  stock_picking_send_by_mail/models/stock_picking.py
  stock_picking_send_by_mail/pyproject.toml
  stock_picking_send_by_mail/readme/CONTRIBUTORS.md
  stock_picking_send_by_mail/readme/DESCRIPTION.md
  stock_picking_send_by_mail/readme/USAGE.md
  stock_picking_send_by_mail/static/description/icon.png
  stock_picking_send_by_mail/static/description/index.html
  stock_picking_send_by_mail/tests/__init__.py
  stock_picking_send_by_mail/tests/test_stock_picking_send_by_mail.py
  stock_picking_send_by_mail/views/stock_picking_view.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1938 [17.0][IMP] stock_push_delay: update development_status to P/S
  stock_push_delay/README.rst
  stock_push_delay/__manifest__.py
  stock_push_delay/static/description/index.html
Labels: approved, bot is merging ⏳

#1812 [18.0][MIG] stock_picking_warn_message: Migration to 18.0
  stock_picking_warn_message/README.rst
  stock_picking_warn_message/__init__.py
  stock_picking_warn_message/__manifest__.py
  stock_picking_warn_message/i18n/es.po
  stock_picking_warn_message/i18n/it.po
  stock_picking_warn_message/i18n/stock_picking_warn_message.pot
  stock_picking_warn_message/models/__init__.py
  stock_picking_warn_message/models/stock_picking.py
  stock_picking_warn_message/pyproject.toml
  stock_picking_warn_message/readme/CONFIGURE.md
  stock_picking_warn_message/readme/CONTRIBUTORS.md
  stock_picking_warn_message/readme/DESCRIPTION.md
  stock_picking_warn_message/readme/USAGE.md
  stock_picking_warn_message/static/description/icon.png
  stock_picking_warn_message/static/description/index.html
  stock_picking_warn_message/tests/__init__.py
  stock_picking_warn_message/tests/test_stock_picking_warn_message.py
  stock_picking_warn_message/views/stock_picking_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1940 [IMP][16.0] stock_partner_delivery_window: add weekdays
  stock_partner_delivery_window/models/res_partner.py
  stock_partner_delivery_window/readme/CONTRIBUTORS.rst
  stock_partner_delivery_window/static/description/index.html
  stock_partner_delivery_window/tests/test_delivery_window.py
Labels: approved, bot is merging ⏳

#1920 [16.0][ADD] stock_picking_return_empty_package
  setup/stock_picking_return_empty_package/odoo/addons/stock_picking_return_empty_package
  setup/stock_picking_return_empty_package/setup.py
  stock_picking_return_empty_package/README.rst
  stock_picking_return_empty_package/__init__.py
  stock_picking_return_empty_package/__manifest__.py
  stock_picking_return_empty_package/models/__init__.py
  stock_picking_return_empty_package/models/stock_picking_type.py
  stock_picking_return_empty_package/readme/CONFIGURE.rst
  stock_picking_return_empty_package/readme/CONTRIBUTORS.rst
  stock_picking_return_empty_package/readme/DESCRIPTION.rst
  stock_picking_return_empty_package/static/description/index.html
  stock_picking_return_empty_package/tests/__init__.py
  stock_picking_return_empty_package/tests/test_empty_package_at_picking_return.py
  stock_picking_return_empty_package/views/stock_picking_type.xml
  stock_picking_return_empty_package/wizards/__init__.py
  stock_picking_return_empty_package/wizards/stock_return_picking.py
Labels: needs review, bot is merging ⏳

#1949 [18.0][IMP] stock_move_quantity_product_uom: add init hook and migration roadmap
  stock_move_quantity_product_uom/README.rst
  stock_move_quantity_product_uom/__init__.py
  stock_move_quantity_product_uom/__manifest__.py
  stock_move_quantity_product_uom/hook.py
  stock_move_quantity_product_uom/readme/ROADMAP.md
  stock_move_quantity_product_uom/static/description/index.html
Labels: approved, bot is merging ⏳

#1876 [16.0][MIG] stock_move_quick_lot: Migration to 16.0
  setup/stock_move_quick_lot/odoo/addons/stock_move_quick_lot
  setup/stock_move_quick_lot/setup.py
  stock_move_quick_lot/README.rst
  stock_move_quick_lot/__init__.py
  stock_move_quick_lot/__manifest__.py
  stock_move_quick_lot/i18n/es.po
  stock_move_quick_lot/i18n/it.po
  stock_move_quick_lot/i18n/stock_move_quick_lot.pot
  stock_move_quick_lot/i18n/stock_pack_operation_quick_lot.pot
  stock_move_quick_lot/models/__init__.py
  stock_move_quick_lot/models/stock_move.py
  stock_move_quick_lot/readme/CONFIGURE.rst
  stock_move_quick_lot/readme/CONTRIBUTORS.rst
  stock_move_quick_lot/readme/DESCRIPTION.rst
  stock_move_quick_lot/readme/USAGE.rst
  stock_move_quick_lot/static/description/icon.png
  stock_move_quick_lot/static/description/icon.svg
  stock_move_quick_lot/static/description/index.html
  stock_move_quick_lot/tests/__init__.py
  stock_move_quick_lot/tests/test_stock_move_quick_lot.py
  stock_move_quick_lot/views/stock_view.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1954 [16.0][FW Port][FIX] delivery_procurement_group_carrier: Do not align carrier again, allow to set carrier to False
  delivery_procurement_group_carrier/models/stock_picking.py
  delivery_procurement_group_carrier/tests/test_carrier.py
Labels: merged 🎉

#1963 [MIG] [18.0] stock_picking_batch_invoice_frequency
  stock_picking_batch_invoice_frequency/README.rst
  stock_picking_batch_invoice_frequency/__init__.py
  stock_picking_batch_invoice_frequency/__manifest__.py
  stock_picking_batch_invoice_frequency/i18n/es.po
  stock_picking_batch_invoice_frequency/i18n/it.po
  stock_picking_batch_invoice_frequency/i18n/stock_picking_batch_invoice_frequency.pot
  stock_picking_batch_invoice_frequency/models/__init__.py
  stock_picking_batch_invoice_frequency/models/sale_invoice_frequency.py
  stock_picking_batch_invoice_frequency/models/stock_picking.py
  stock_picking_batch_invoice_frequency/models/stock_picking_batch.py
  stock_picking_batch_invoice_frequency/pyproject.toml
  stock_picking_batch_invoice_frequency/readme/CONFIGURE.md
  stock_picking_batch_invoice_frequency/readme/CONTRIBUTORS.md
  stock_picking_batch_invoice_frequency/readme/DESCRIPTION.md
  stock_picking_batch_invoice_frequency/readme/USAGE.md
  stock_picking_batch_invoice_frequency/static/description/icon.png
  stock_picking_batch_invoice_frequency/static/description/index.html
  stock_picking_batch_invoice_frequency/tests/__init__.py
  stock_picking_batch_invoice_frequency/tests/test_batch_invoice.py
  stock_picking_batch_invoice_frequency/views/sale_invoice_frequency.xml
Labels: approved, bot is merging ⏳
