Repository OCA/stock-logistics-workflow, pull requests merged in 2025-03, with the labels that each got.

#1891 [15.0][FIX] stock_picking_invoice_link, ensure field product_uom_qty …
  stock_picking_invoice_link/models/stock_move.py
Labels: approved, bot is merging ⏳

#1881 [17.0][MIG] stock_push_delay
  stock_push_delay/README.rst
  stock_push_delay/__init__.py
  stock_push_delay/__manifest__.py
  stock_push_delay/i18n/it.po
  stock_push_delay/i18n/stock_push_delay.pot
  stock_push_delay/models/__init__.py
  stock_push_delay/models/stock_move.py
  stock_push_delay/models/stock_picking.py
  stock_push_delay/models/stock_rule.py
  stock_push_delay/pyproject.toml
  stock_push_delay/readme/CONTRIBUTORS.md
  stock_push_delay/readme/DESCRIPTION.md
  stock_push_delay/readme/USAGE.md
  stock_push_delay/static/description/icon.png
  stock_push_delay/static/description/index.html
  stock_push_delay/tests/__init__.py
  stock_push_delay/tests/test_stock_push_delay.py
  stock_push_delay/views/stock_move_views.xml
  stock_push_delay/views/stock_rule_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1889 [17.0][MIG] stock_production_lot_active: Migration to 17.0
  stock_production_lot_active/README.rst
  stock_production_lot_active/__init__.py
  stock_production_lot_active/__manifest__.py
  stock_production_lot_active/i18n/es.po
  stock_production_lot_active/i18n/it.po
  stock_production_lot_active/i18n/stock_production_lot_active.pot
  stock_production_lot_active/models/__init__.py
  stock_production_lot_active/models/stock_production_lot.py
  stock_production_lot_active/pyproject.toml
  stock_production_lot_active/readme/CONTRIBUTORS.md
  stock_production_lot_active/readme/DESCRIPTION.md
  stock_production_lot_active/static/description/icon.png
  stock_production_lot_active/static/description/index.html
  stock_production_lot_active/tests/__init__.py
  stock_production_lot_active/tests/test_lot_active.py
  stock_production_lot_active/views/stock_production_lot.xml
Labels: approved, bot is merging ⏳

#1888 [18.0][MIG] stock_picking_type_force_move_type (was `stock_picking_type_shipping policy`)
  stock_picking_type_force_move_type/README.rst
  stock_picking_type_force_move_type/__init__.py
  stock_picking_type_force_move_type/__manifest__.py
  stock_picking_type_force_move_type/hooks.py
  stock_picking_type_force_move_type/i18n/es_AR.po
  stock_picking_type_force_move_type/i18n/es_MX.po
  stock_picking_type_force_move_type/i18n/it.po
  stock_picking_type_force_move_type/i18n/stock_picking_type_shipping_policy.pot
  stock_picking_type_force_move_type/models/__init__.py
  stock_picking_type_force_move_type/models/stock_picking.py
  stock_picking_type_force_move_type/models/stock_picking_type.py
  stock_picking_type_force_move_type/pyproject.toml
  stock_picking_type_force_move_type/readme/CONTRIBUTORS.md
  stock_picking_type_force_move_type/readme/CREDITS.md
  stock_picking_type_force_move_type/readme/DESCRIPTION.md
  stock_picking_type_force_move_type/static/description/icon.png
  stock_picking_type_force_move_type/static/description/index.html
  stock_picking_type_force_move_type/tests/__init__.py
  stock_picking_type_force_move_type/tests/test_stock_picking_type_force_move_type.py
  stock_picking_type_force_move_type/views/stock_picking_type.xml
Labels: approved, migration, ready to merge, bot is merging ⏳

#1890 [18.0][MIG] stock_picking_restrict_cancel_printed
  stock_picking_restrict_cancel_printed/README.rst
  stock_picking_restrict_cancel_printed/__init__.py
  stock_picking_restrict_cancel_printed/__manifest__.py
  stock_picking_restrict_cancel_printed/i18n/it.po
  stock_picking_restrict_cancel_printed/i18n/stock_picking_restrict_cancel_printed.pot
  stock_picking_restrict_cancel_printed/models/__init__.py
  stock_picking_restrict_cancel_printed/models/stock_move.py
  stock_picking_restrict_cancel_printed/models/stock_picking.py
  stock_picking_restrict_cancel_printed/models/stock_picking_type.py
  stock_picking_restrict_cancel_printed/pyproject.toml
  stock_picking_restrict_cancel_printed/readme/CONTRIBUTORS.rst
  stock_picking_restrict_cancel_printed/readme/DESCRIPTION.rst
  stock_picking_restrict_cancel_printed/static/description/icon.png
  stock_picking_restrict_cancel_printed/static/description/index.html
  stock_picking_restrict_cancel_printed/tests/__init__.py
  stock_picking_restrict_cancel_printed/tests/test_stock_picking_restrict_cancel_printed.py
  stock_picking_restrict_cancel_printed/views/stock_picking_type_views.xml
  stock_picking_restrict_cancel_printed/views/stock_picking_views.xml
Labels: approved, migration, bot is merging ⏳

#1883 [18.0][MIG] stock_picking_filter_lot: Migration to 18.0
  stock_picking_filter_lot/README.rst
  stock_picking_filter_lot/__init__.py
  stock_picking_filter_lot/__manifest__.py
  stock_picking_filter_lot/i18n/es.po
  stock_picking_filter_lot/i18n/fr.po
  stock_picking_filter_lot/i18n/it.po
  stock_picking_filter_lot/i18n/stock_picking_filter_lot.pot
  stock_picking_filter_lot/models/__init__.py
  stock_picking_filter_lot/models/stock_lot.py
  stock_picking_filter_lot/pyproject.toml
  stock_picking_filter_lot/readme/CONTRIBUTORS.md
  stock_picking_filter_lot/readme/DESCRIPTION.md
  stock_picking_filter_lot/readme/USAGE.md
  stock_picking_filter_lot/static/description/icon.png
  stock_picking_filter_lot/static/description/index.html
  stock_picking_filter_lot/tests/__init__.py
  stock_picking_filter_lot/tests/test_stock_picking_filter_lot.py
  stock_picking_filter_lot/views/stock_move_line_view.xml
  stock_picking_filter_lot/views/stock_scrap_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1860 [17.0] [MIG] sale_planned_consumed_date: Migration to 17.0
  sale_planned_consumed_date/README.rst
  sale_planned_consumed_date/__init__.py
  sale_planned_consumed_date/__manifest__.py
  sale_planned_consumed_date/i18n/fr.po
  sale_planned_consumed_date/i18n/sale_planned_consumed_date.pot
  sale_planned_consumed_date/models/__init__.py
  sale_planned_consumed_date/models/sale_order_line.py
  sale_planned_consumed_date/pyproject.toml
  sale_planned_consumed_date/readme/CONTRIBUTORS.md
  sale_planned_consumed_date/readme/DESCRIPTION.md
  sale_planned_consumed_date/static/description/index.html
  sale_planned_consumed_date/tests/__init__.py
  sale_planned_consumed_date/tests/test_sale_planned_consumed_date.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1826 [15.0][FIX] stock_valuation_layer_usage: company security rule
  stock_valuation_layer_usage/__manifest__.py
  stock_valuation_layer_usage/security/ir_rule.xml
Labels: approved, ready to merge, bot is merging ⏳

#1900 [17.0][FIX] stock_valuation_layer_usage: company security rule
  stock_valuation_layer_usage/__manifest__.py
  stock_valuation_layer_usage/security/ir_rule.xml
Labels: approved, bot is merging ⏳

#1899 [16.0][FIX] stock_valuation_layer_usage: company security rule
  stock_valuation_layer_usage/__manifest__.py
  stock_valuation_layer_usage/security/ir_rule.xml
Labels: approved, bot is merging ⏳

#1830 [18.0][FIX] stock_no_negative: fix field not visible in view
  stock_no_negative/views/product_product_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1793 [18.0][MIG] purchase_stock_picking_invoice_link
  purchase_stock_picking_invoice_link/README.rst
  purchase_stock_picking_invoice_link/__init__.py
  purchase_stock_picking_invoice_link/__manifest__.py
  purchase_stock_picking_invoice_link/i18n/es.po
  purchase_stock_picking_invoice_link/i18n/fr.po
  purchase_stock_picking_invoice_link/i18n/hr.po
  purchase_stock_picking_invoice_link/i18n/it.po
  purchase_stock_picking_invoice_link/i18n/pt_BR.po
  purchase_stock_picking_invoice_link/i18n/purchase_stock_picking_invoice_link.pot
  purchase_stock_picking_invoice_link/models/__init__.py
  purchase_stock_picking_invoice_link/models/purchase_order.py
  purchase_stock_picking_invoice_link/models/stock_move.py
  purchase_stock_picking_invoice_link/pyproject.toml
  purchase_stock_picking_invoice_link/readme/CONTRIBUTORS.md
  purchase_stock_picking_invoice_link/readme/DESCRIPTION.md
  purchase_stock_picking_invoice_link/readme/USAGE.md
  purchase_stock_picking_invoice_link/static/description/icon.png
  purchase_stock_picking_invoice_link/static/description/index.html
  purchase_stock_picking_invoice_link/tests/__init__.py
  purchase_stock_picking_invoice_link/tests/test_purchase_stock_picking_invoice_link.py
Labels: needs review, approved, migration, bot is merging ⏳

#1895 [14.0][FIX] delivery_procurement_group_carrier: Fix carrier update
  delivery_procurement_group_carrier/models/__init__.py
  delivery_procurement_group_carrier/models/stock_picking.py
  delivery_procurement_group_carrier/tests/test_carrier.py
Labels: approved, bot is merging ⏳

#1907 [14.0][FIX] stock_putaway_by_route: Return empty stock.location.route recordset instead of stock.location
  stock_putaway_by_route/models/stock_move.py
Labels: approved, bot is merging ⏳
